### ISSUE TITLE
Globe.pick for intersect ray and scene return undefined 

### ISSUE THREAD

**Issue by moreba1** [CesiumGS/cesium#10004]
Hi

 I will calculate position of intersection of a ray with earth terrain . i use this command but it return undefined. 
'''
var terrainIntersect = viewer.scene.globe.pick(ray, viewer.scene); 

'''

related to : 
https://github.com/CesiumGS/cesium/issues/6312

https://sandcastle.cesium.com/#c=pVXbbhoxEP0Vl4d0kbYm5KaGQFolzUPUSEFNlKrSvhjvAFaMjWwvlEb59473CrtLE6k8Yc+cM2c8x94VM2QlYA2GjIiCNbkGK5IFfUr3gqjD0/W1Vo4JBSbqdC8iFalejzzOgdww4+YkUiukmUk9AWTJ6KjloICmmxd5BkgpllaLGLPSAC13fErKOpaMA4k6ljkfdBB1crTlhjk+39V5jQLwH1PHQbco88yUZRbzGjl0avTiG8wMgA0+9Q/79Oj8qH94ehKS43N60j87O/t8WvKwiV7B9/1ki0Q6sZSbq80DZ5KZICsckj49DQu5GVt2JKCccAIsZXEcvOA+wZ+IB7vthnlAsQXsCS21RSKtBtsaq6BQbkBeluI3yAfxB0n6hyHhWmozKNvwK/rr5u7u/ucrAl/Lrsty1ShL3TNwV5vbONgRtY0ca39UZZAWQj3yickEgpySS82fKU+MQfJHsYBuzQGGbYhWNSOkrQk1I7Feq7yqT9yxxA+2ybyAEaqNmAmVaUJxxXYsDHAvrHWwCmZYNMggu5NMFd4qB8bmBGuBN6Byds3pZWpVaBv9CNZZiopuCkCAi7DCp0XFlARBC+WH0YgkKoYp3sy4Sw4OyL4slUjZ7ZLCc9jDdk1iwCVGWcIUER63YjIk6zkY8DNw82wcwqZ/i4wvOZnvVxTVxvnAq3ZxHH76Yz+6WnOlRmodnn7aq2fkWlktgUo9Q6s104siuffqkIaYNOsV61pUP209pNHuUb68U0mFyR7Gt4ukk3g/v08vqPe6D9cGX+fce/lq23nNJ5kuBX/OxpGuK5814C0ua81peqyqVDmMVPcMb5Ymwn20xFMTfGWF8yZrO5p6xTcsUE+vO6B5Ru3z/08ZUWe/P1ol/MsdDcC2NzphZ2jdRsJlIfyrWCy1QYcaGVDac7BYSnzVbG+S8GdwlFvroT512NuGDmOxwq/SqOXbT7hk1mJkiqX9pyXqXA57mN+ASs1ifKjvV2Ak2/i0ef/yLtuklA57uGxHOq3lhJka818

**Comment by zero406-CC** [comment]
Probably because there is no tiles to render at that time and there is another problem the second param should be scene not global. You can try this way:
var handler = new Cesium.ScreenSpaceEventHandler(viewer.canvas);
// When a feature is left clicked, print its class name and properties
handler.setInputAction(function(movement) {
    // Intersection with terrain 
var terrainIntersect = viewer.scene.globe.pick(ray, viewer.scene); 
if ((terrainIntersect !== undefined) && (terrainIntersect !== null)) { 
    // globe.pick returns a Cartesian3, so it's fine as it is 
    console.log("terrainIntersectPosition"); 
    console.log(terrainIntersect); 
} else if (terrainIntersect === undefined) { 
      console.log("terrainIntersectPosition"); 
    console.log("undefined");
} else if (terrainIntersect === null) { 
    console.log("terrainIntersect null");
} 
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);

**Comment by zero406-CC** [comment]
No matter you use mouse movement or timeinterval function,you need to wait quadtile rendered. You can check with this code :
var tilesToRender = viewer.scene.globe._surface._tilesToRender;
  if(tilesToRender.length !== 0){}
Or you can check is there other better way.

**Comment by ggetz** [comment]
Thanks for the question! Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. I would ask if you have any further questions that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help.
