### ISSUE TITLE
infoBox dependency

### ISSUE THREAD

**Issue by srothst1** [CesiumGS/cesium#10039]
This issue stems from the following support thread:
- https://community.cesium.com/t/how-to-update-instanced-features-metadata/16738/11

Please note that this thread may only be visible to Cesium employees.

It seems like there may be an issue with the dependencies for `infoBox`. It’s possible that a dependency used for the infoBox is not included in the published version of CesiumJS.

I created this issue to help facilitate an investigation on this matter.

**Comment by ggetz** [comment]
@srothst1 So I found out why the user was having issues loading the infoBox. Since they were loading an HTML in Chrome and not serving the file in anyway, the `load` event does not fire. That's why their code snippet is working in Sandcastle. The `load` event in the infobox widget injects some html into the frame which is critical for rendering the content. 

Since cesiums is not designed to work in this way, I would say this is not actually an issue on our side, and that the user should be serving their app for it to work as expected.

**Comment by srothst1** [comment]
Hi @ggetz. Thanks for looking into this and posting an update.
