### ISSUE TITLE
how can i add texCoord to 3dtiles?

### ISSUE THREAD

**Issue by h2936817294** [CesiumGS/cesium#10053]
in CustomShader ，I can get texCoord_0 from some models. but, under normal conditions,I can only get vec(0,0). The other is，Can I add custom attributes? be similar to featureId_0.

**Comment by ggetz** [comment]
Hi @h2936817294 !

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. I would ask that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by ptrgags** [comment]
@h2936817294, indeed, the forum is a better place for support questions, but I'll point out a couple of non-obvious things since Custom Shaders:

- there is documentation for Custom Shaders, currently in `Source/Scene/ModelExperimental/CustomShaderGuide/`, though I hope to move this to an easier-to-find location soon (see #10054)
- Indeed, if you add glTF custom accessors (with an underscore prefix like `_TEMPERATURE` it will show up in custom shaders as `fsInput.attributes.temperature`. See the custom shader guide mentioned above.
- `texCoord_0` will only have a well-defined value if the glTF primitive has a `TEXCOORD_0` attribute defined. Otherwise it will default to a hard-coded `vec2(0.0)`. This is to prevent the shader from crashing if applied to a tileset/glTF where not every primitive satisfies the shader, albeit it does produce unexpected results. We are considering adding a variable so you can check if the texture coordinates are valid within the shader, see #10037
