### ISSUE TITLE
Custom shaders don't work on instanced models

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10113]
While reviewing #10110, I discovered that custom shaders won't apply to instanced models, even if they're simple. I tested this with the [sandcastle here](https://sandcastle.cesium.com/#c=tVZtb9s2EP4rhD/Zg0NLsWMnXhqsddosw4IVtdcBm4aWpmiLMEUKJOU4LfLfdyQlWXnbuhQxEokvx7vnHj3kkSppLNpyds00eoUku0YzZniZ449+rJt0qO/PlLSES6aTTu/HRCYyrMFUKLrBtNSaSbvgOQMvlYdfSsGJPCeW4ZVW+aVRx+Mo7iYSoaRzGB3GB3F8EJ0sDqPp4WQ6nOAoHkfj0WhyNBwdj49HJ8PJn0knkSHeYIBmSiiNBN8wRBDNGN0wvVREp2hZWpQTGLcZ/GsiTUEAEL1BW6Jv0DW3mffgplNO1koSkUjqk6elsSqfZyS9T8GsNdP96nCvNFnnkGgYW7CdnaLPbgKhreJpM38FVHXfVZ1LWQC8lfHvPuJSQZd+yT/lKmXiCvjRnAjAHxq94O9reLlfPYNTvlqVxlG8ZXTYjXHUR/4R4cix5Ixvw+tzP5G3DXNXLpKpM/ZxDXj5y9lWgaxPJumE3NEbIoRSMun0wzQsZIJRMFmVklquJOr29iDDpA/T3QNPOhgP4G9O8kIwUAIZhNiDEKUKcreH12LZhHW/+KhuNzn62fC8B3++4VKyFM0yogm1Tq8vmcEVqdF/guYD6NH/QH4OeBVoPC80MwZS8FheCr6Ptg9Wp8PFZqFL2NFrYVfPTuV3KbhFb9TuWeifxAwOveemUaNE0TfxqyR7WTX4EO3292n5QqtSpugjyzgVLwY9RKmC3O19l54v4aghkoKQnyuEbwAPrps4dzoPBfxv1P/tD8pwOmbFvTLwMyMpl+v33NLsgxIBWDUHp3eGrfoAFlB0uvFx1PNOo/AMxSv4XfEdS6Em5GzhCtRK6XxfK5shg6GgEhHs1LtmzQWD2kus0lX9lEpDTQv5JZ1rZuy+VDbMttksteijjPF1Ziu+A6xCGe6NGywzoi20iBz6un3O1poxU32Og/hwiKPJaDSOTypyRyMcHUXDSTSuBkIU1w54UHXBwIZCFrjQPIeQW2awZrnastfAafgmrfrkitwTq0iaVmjqr+AWvN0VUCVdwYVK6YBfgAK6jbKcHqbIsVCP1OVX8930ke+Q3fvs7a/R0mbNX0tpoKBWr/L8VgheGLgk4D8u5sejlsEjwmiU2pi1bynTO73K5LbXJtznBvSS9OY9UMENw3D3kd39pvMWzc6rb3MAQhOQoNq8tk2SD1J8anMQuW5T8/geGR31+v9lcxDfMQrZLN3JBLHmRcY0wxpsS4N+QPt9HRpBSv7yc+vYmBOZUmIsnGegnIVSYkn0FZNl4MAEzjr9zqmxN4Kd1e5+4nkBu8xppguHj2Vw+MBNzAyWUCCZxdSY+iQ5HbSXnqZ8i3j66pG7M6KCGAMzq1KIOf8Cp/rZ6QDsHywVyhP725ZpQW6cWRaf/RoGMcanA+g+vtKGDO95/gc).

What the custom shader is doing is applying a solid yellow color to the model:
![image](https://user-images.githubusercontent.com/32226860/154521326-56433c24-2170-4e6e-937c-46784094dea5.png)

However, this doesn't work for `BoxInstanced.gltf`:
![image](https://user-images.githubusercontent.com/32226860/154521470-534124b5-5d65-49a3-b430-7e4e2133a341.png)

**Comment by ptrgags** [comment]
I did some digging today and found that the model _is_ rendering correctly based on PBR works.

If the specular value is high, then the reflections tend to overwhelm the diffuse color. By default, the glTF spec requires `baseColor`, `metallic`, and `roughness` to all be 1.0 (which corresponds to `diffuse = 0.0, specular = vec3(1.0), roughness = 1.0`. Since the Sandcastle in the description only changes the diffuse value, it is overwhelmed by the specular reflections.

However, if you reduce the specular value like in [this sandcastle](https://sandcastle.cesium.com/#c=tVdtb9s2EP4rhD8pg0NLtmMnXhqscV6WoUGL2OuATkNLU7RFhCIFknKSFvnvO4qSrMTutnSIYUt8Od499/B4R1MljUVrzu6YRm+QZHdoygwvMvyxHAviDi37UyUt4ZLpuLP3cyxj6ddgKhS9xbTQmkk75xkDLZWG3wrBiTwjluGlVtmVUYejMApiiVDc6Yf9aD+K9sOjeT+c9MeTwRiH0SgcDYfjg8HwcHQ4PBqMP8WdWHp7vR6aKqE0EvyWIYJoyugt0wtFdIIWhUUZgXGbwk8TaXICgOgDWhP9gO64TUsNbjrhZKUkEbGkpfO0MFZls5QkzymYtmaCbw73UpNVBo76sTm7txP0xU0gtFY8aeavgargoupcyRzgLU357iIuFXTp1+xzphImroEfzYkA/L6x5/V98y/3qWdwwpfLwjiK14wOggiHXVQ+Qhw6lrYWaFWsUsmMgSUguEvE5IwWguhaaUvVo3996cbysdmEawfa1OSVLjjtfzrZCrMteYk7VyBBJGUJOlX3cafrZ2EdE4yCxLKQ1HIlUbC3cddPllaCDdy4g3EPvjOS5YJBTJGeN90D1Y2dJx28EnbZWHWf6KBuNx6Ws/75DLyPAXRKhFBKvhZ6b6Uy8rQH+Bc/Dn92y6UE5qcp0YRad25f04NrUqP/DM0t6OELkJ8BXgVnPcs1BC64UGJ5LfiltY2x2h0ubue6gMy2FUQvceV3Kbj94eD/p5AvNTeNGiUK/xO/SrLXjYbSRLv9/2L5EtKYTNBHlnIqXg26t1IZedp7WTzH8q8yWfoMmebPqsqvjCRcrj5wS9MbJTy4ag6KQYqtugEJqGFBdBjulSpD//S10Otd8nuWQInJ2NzVu6XS2ab0NkMGQ30mwsupi2bNJYNSTqzSVTmWSkOJ9C7GnTtm7KbyNuy2GS206KKU8VVqK849rFwZXgo3WKZEW2gROSivAWdspRkz1ZbsR/0BDsfD4Sg6qvgdDnF4EA7G4aga8FZc2+NB1X0FGwpe4FzzDEyumcGaZWrN3gKnfl9aNcqVt++sIklSoal3wS04v8+hQLr6DUXSAb+EMxY00eVO3AQ5FuqRupprfj/ZsQ/ps21v70YrPmv+WsEGEdTqVZrPheC5gTsH/uNydjhsCewIjCZaG7H2pWfypNeI8Iys2CmBpPjO8Q/YJ+0wvtqaDlpXlu3FF1CFlJ5sRUUffzq/eV+vfKxuP/5d73dJLewuSR4+wE5wwzDc5GSwOfelRHP467spcKAJnAB1+9Y2HG8x/L2zSeSqvTO7j+jwYK/7bzL70RMh783C5RewNctTphnWIFsY9BPaJEbf8JFc3r8eHRszIhNKjIWsBIE7V0osiL5msvAcGM9Zp9s5NvZBsJNa3S88y+GQu5ANIP9ZBvkP7oCmt4AyxyymxtTJ7LjXXnqc8DXiyZsd/wQQFcQYmFkWQsz4V8jNJ8c9kN9aKlRJ7Ps104I8OLE0OnnnBzHGxz3o7l5pvYfPNP8N) it does render yellow!

![image](https://user-images.githubusercontent.com/8422414/177602510-a43a1bcc-cb76-4fed-aaef-9af801f6289d.png)

There's nothing actionable here so I'm closing this issue.
