### ISSUE TITLE
Update and consolidate jasmine usage

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#10134]
We are currently using two separate versions of jasmine-- One older version in `ThirdParty/jasmine-2.2.0` which is being used for running tests in the browser, and a newer version of `jasmine-core` via the `karma-jasmine` module which is being used for running tests on the command line and in CI.

- Is there anything preventing us from updating to the newest version of `jasmine-core`?
- Remove the existing copy of jasmine in `ThirdParty` and set up standalone jasmine consistant with the version of `jasmine-core` in `package.json`
- Audit our custom matchers,`customizejasmine`, and `spec-main` files for functionality redundant with an up-to-date copy of jasmine (namely that after we completely remove when.js and replace with promises, we won't need to do anything special to account for returned promises).

**Comment by ggetz** [comment]
One thing to consider is whether we can drop support for standalone jasmine entirely. I was under the impression that some developers use this for debugging unit tests, but we should discern if that is still the case. We should also take a look at what similar projects do.

**Comment by ebogo1** [comment]
From informal discussions offline, it looks like dropping the standalone SpecRunner files could be the way to go since we don't need the browser debugger for most of our use cases.

I mostly got the [4.0.1 standalone release](https://github.com/jasmine/jasmine/releases/tag/v4.0.1) working with minimal work. The main thing that I couldn't get right was filtering specs that are focused with `fit` or `fdescribe` - the spec runner showed all the skipped tests and took a while to get through them before displaying the tests I intended to run. Steps to reproduce:

- Download 4.0.1 release zip from the link above.
- Copy `jasmine-standalone-4.0.1/lib/jasmine-4.0.1/` folder into `ThirdParty/`.
- Point all the URLs in SpecRunner.html to the new 4.0.1 folder.
- Modify boot1.js to work with Cesium.js similar to the current spec-main.js file. I used the built-in `jasmine.QueryString` instead of `Cesium.queryToObject` for simplicity but I believe either way should work. Once we switch away from `Cesium.when` this step will get simpler too. 

Modified boot1.js file for future reference in case it's helpful: [spec-main.js.txt](https://github.com/CesiumGS/cesium/files/8157296/spec-main.js.txt)

**Comment by ggetz** [comment]
@ebogo1 If we do drop standalone jasmine, we'll need an easily accessable way to debug the tests. You can debug with the Chrome Debugger via the command line and karma now, but will need to edit the `karma.conf.cjs` file then open up a separate debug window manually by clicking that "Debug" button in the karma window. And none of that is documented. 

We'll probably want to add a new task like `test-debug` or add an optional `debug` parameter to the existing `test` task which runs karma with the configuration options for debugging (I think this is only setting `singleRun` to `false`). Additionally, we should be able to add a task to `launch.json` which can attach VS code for debugging purposes.

**Comment by ptrgags** [comment]
A couple of us had some feedback on the new command line interface now that #10184 removed SpecRunner, see https://github.com/CesiumGS/cesium/issues/10200

**Comment by IanLilleyT** [comment]
Posting this since I don't see it mentioned in the thread, but it looks like maybe the jasmine html has moved here: https://www.npmjs.com/package/karma-jasmine-html-reporter. No idea how well this fits in with the new changes.
