### ISSUE TITLE
Loop NONE is stopping animation without let it complete it's duration.

### ISSUE THREAD

**Issue by jackbr0gm** [CesiumGS/cesium#10161]
https://github.com/CesiumGS/cesium/blob/999ee4e6b82438996c30955cc47103bcfce4a35f/Source/Scene/ModelAnimationLoop.js#L10

As per the [documentation](https://cesium.com/learn/cesiumjs/ref-doc/ModelAnimation.html#loop), `ModelAnimationLoop.NONE` will `Play the animation once; do not loop it`. But it doesn't seems working like that way.
It's immediately stopping running animation on setting loop value to 0. Also there is no setter to set animation loop, then how to set animation loop.

Please check this sandcastle [example](https://sandcastle.cesium.com/index.html#c=fVNRb9sgEP4ryA+Vo2a4VR8qJXa0Ld1bq0nr1CdLEYGzg4bBApwqm/LfdxgndpZqWBZwfN/dx93BjXae7CW8gyUF0fBO1uBk19C33paWCe/3a6M9kxpsmczJn1IT4namU+KLlg3zsCDedjAv9XG2LHX49sySDWgv/QEdxwi030twlAmR9l5a49Bi9OIUd82sxxXTD7SypnmC2gK49NPj45w84H9/F8ZsHsiNEaAWUU4YnZULUiaUZq+saRU8Mc+yHuSy6P6F6WG1wSWt1RbvE+jHs/RBqreM/wLx7XSD4S49pOo0D6LJpgYfM4A7l0bI7CQopKC1ssEL7sGNWXAcNNDxZDnCFeja7xA6ntJoG0CVsSQNSImguyVO+UDC9e3tbEzGP/EvfaLuVM6WI1ZWJD2fUylIURRkKN/NzcSNxIZhmoOpThV7CQm+CByGBd9ZPRIp42EaszUJfozLYRqYnRZQYccJBB5D1l+ZFpw5ryC0z09j1JbZr533RmOb/oDGoLxnY9rQoucSpYOyST+OGkJdL0s4QGJqOFoMhlOmTq+4EXJlphvHdyA6BWJibFibsmJFGN0oVBhqF/jn1/K/L5knufMHBatTxj7LpjXWY7+rFJvdAzY7PkKXbTvsWU+5c6fa5tmUmgu5J1IUH7xqwhVzDk+qTqlX+RvKZJVniL+iKsOE1PX3PVjFDgG2u189RyOlNM9w+zHTx5pNPEfEXw).

If you press **Remove Loop** button, animation stops without completing its cycle (duration). In my project I don't want to play animations in loop. I just want to play it once and then stops.

It seems like a bug. If it's not please tell me how can I achieve the requirement.

- Thanks

**Comment by jackbr0gm** [comment]
I request to Cesium Team, Please response to this thread.
- Regards

**Comment by ggetz** [comment]
I don't think this is a bug since you're setting private members.

You can use [`ModelAnimationCollection`](https://cesium.com/learn/cesiumjs/ref-doc/ModelAnimationCollection.html) to remove the animation, then create a new animation which has the correct `loop` value and add it back to the collection/

Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. I would ask that you take questions like this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help.
