### ISSUE TITLE
Factor out "defer" usage for better error handling

### ISSUE THREAD

**Issue by ggetz** [CesiumGS/cesium#10178]
Cesium uses `defer` throughout the codebase as a remnant from when we were using `when.js`. However, the recommended best practice is to use `new Promise` constructor directly because it makes it much harder to let an exception escape. Functions passed to the construct should only reject the promise, never throw.

https://github.com/CesiumGS/cesium/pull/10149 excluded several specs in `Cesium3DTilesetSpec`, `GltfLoaderSpec`, `TimeDynamicPointCloudSpec`, and `ModelExperimentalSpec` which can be re-enabled once errors are better handled as a result of this change.

**Comment by ggetz** [comment]
@lilleyse @ptrgags Is there a particular reason why the loaders, like [`BufferLoader.js`](https://github.com/CesiumGS/cesium/blame/main/Source/Scene/BufferLoader.js) have a `promise` rather than having the `load` function return a promise? As far as I'm aware, the later is a much more common pattern and would make removing `defer` much more streamlined.

**Comment by lilleyse** [comment]
Separate promises + a new state could be ok. Would this move some of the burden to the caller to load and then process the loader?

`Model.js` seems like it will have a similar problem and I'm curious how we'll approach that.

**Comment by ggetz** [comment]
I'm not entirely sure yet, but I don't think so. So far it seems it can be handled internally and we just need to move around where the caller is actually handling the promises.

I agree `Model.js` will have similar problems. What do you think the timeline is for removing it? Maybe we can leave defer there until its replaced by `ModelExperimental`. It's not causing issues in the specs like the loaders are currently.

**Comment by lilleyse** [comment]
> I'm not entirely sure yet, but I don't think so. So far it seems it can be handled internally and we just need to move around where the caller is actually handling the promises.

Ok that doesn't sound too bad. I was imagining that a larger restructuring would be needed.

> I agree `Model.js` will have similar problems. What do you think the timeline is for removing it? Maybe we can leave defer there until its replaced by `ModelExperimental`. It's not causing issues in the specs like the loaders are currently.

We're aiming to remove it in June. Holding off until `ModelExperimental` replaces it sounds good.

**Comment by mramato** [comment]
FYI, we ran into issues in unit testing a Cesium-based app related to this behavior and had to insert `model.readyPromise.catch(() => {});` into some spots in the tests in order to ensure it doesn't break the entire testing suite when it resolves (simply awaiting doesn't work).

What's weird here is the model is never actually added to the scene, and my current understanding of how this works means that the promise should never reject or resolve.

Ultimately, I think there is more going on here than we realize. For example, `destroy` doesn't seem to actually be aware that anything async could be happening and I don't see checks in Model after async operations, such as `fetchArrayBuffer`, to verify the model hasn't been destroyed and turn it into a no-op.

@lilleyse I don't know anything about the `ModelExperimental` implementation, but hopefully it properly tracks async operations and accounts for things like the user destroying the object while it has an async operation pending and gracefully cancels or ignores the no longer needed operation when it completes.,

> We're aiming to remove it in June. Holding off until `ModelExperimental` replaces it sounds good.

Does that mean the July 1st release, or the June 1st release? It's only April 10th and I think we've introduced or magnifies several promise-related issues in CesiumJS with the last release. Just waiting around and hoping ModelExperimental fixes them seems like a bad call.

**Comment by lilleyse** [comment]
> @lilleyse I don't know anything about the `ModelExperimental` implementation, but hopefully it properly tracks async operations and accounts for things like the user destroying the object while it has an async operation pending and gracefully cancels or ignores the no longer needed operation when it completes.

The new implementation should be handling destroy + async operations more gracefully. All the loaders follow the pattern of checking `isDestroyed` after the promise resolves or rejects (for example see [GltfTextureLoader.js](https://github.com/CesiumGS/cesium/blob/dcf2adb016c8cdbb7939c9c9910e43a9c9308404/Source/Scene/GltfTextureLoader.js#L151-L170)). `ModelExperimental` itself doesn't have async operations. It all happens through the loader.

> Does that mean the July 1st release, or the June 1st release? It's only April 10th and I think we've introduced or magnifies several promise-related issues in CesiumJS with the last release. Just waiting around and hoping ModelExperimental fixes them seems like a bad call.

It would be the July 1st release. Since this is starting to impact development we should fix `Model` sooner, assuming it's not a huge effort.

**Comment by sanjeetsuhag** [comment]
@ggetz 3 areas remain:

- `Resource.js` and everything related to that.
- `TaskProcessor.js` - being addressed here: https://github.com/CesiumGS/cesium/pull/10545#pullrequestreview-1037388266
- `DeferredLoading` in `KmlDataSource` - not sure if worth doing right now, that entire system could probably be reworked. I'll open a separate issue for that too.
