### ISSUE TITLE
I am getting an error trying to use PINCH to rotate the map using Resium

### ISSUE THREAD

**Issue by erikhansenmujica** [CesiumGS/cesium#10239]
![IMG_0608](https://user-images.githubusercontent.com/47824513/160394547-9dedfebe-af5a-4dc1-9a56-8a8ff166eedd.PNG)
<img width="585" alt="Captura de pantalla 2022-03-28 a las 14 08 30" src="https://user-images.githubusercontent.com/47824513/160394619-62bcded2-0658-4d77-8f30-f60a79d675f8.png">

**Comment by ggetz** [comment]
Hi @erikhansenmujica. Resium is not an official cesium component. I would suggest opening a report with the Resium maintainers to get to the bottom of the issue. If it turns out to be a possible bug in CesiumJS, then please post back here with instructions to duplicate using the CesiumJS API. [Sandcastle](https://sandcastle.cesium.com/) is a good way to share examples. Thanks!
