### ISSUE TITLE
Add mipmaps to textures in `ModelExperimental`

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium#10231]
Currently, `ModelExperimental`'s `TextureManager` doesn't handle mipmapping like `GltfTextureLoader` does. This was started in #10158, but there turned out to be more work involved and the PR has gone inactive. A thorough implementation would do the following:

- [x] Put the `resizeImageToNextPowerOfTwo` function into its own file under `Source/Core/resizeImageToNextPowerOfTwo.js`. That way, it can be used in both `GltfTextureLoader` and `TextureManager` (and potentially be reused in the future).
- [x] Implement mipmapping in `TextureManager` in a similar manner to [`GltfTextureLoader`](https://github.com/CesiumGS/cesium/blob/999ee4e6b82438996c30955cc47103bcfce4a35f/Source/Scene/GltfTextureLoader.js#L223-L313), with some differences:
  - [x] Whereas `GltfTextureLoader` handles KTX2 compression with `internalFormat`, `TextureManager` handles `typedArray`, which is an array of numbers that represents the colors of the pixels. We can actually take these pixels and turn them into an image, then resize them, as long as the `PixelDataType` is of `UNSIGNED_BYTE`. So let's create a new file `Source/Core/getImageFromTypedArray.js` containing `function getImageFromTypedArray(typedArray, width, height)`. Then, inside,
    - [x] Create a new canvas and get the context
    - [ ] Call [`createImageData`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createImageData) on the context, with the original image width and height (don't convert to power of two yet)
    - [ ] Modify the `ImageData`'s data field directly. This only requires making a for loop that sets `imageData.data[i] = typedArray[i]`.
    - [x] Call [`putImageData`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData) with the image data we just created, with coordinates (0, 0)
    - [x]  Return the canvas. This gives us an `HTMLCanvasElement`
  - [x] `GltfTextureLoader` calls `console.warn` for KTX2 compression, and in the same location in `TextureManager`, we want to `console.warn` for typed arrays. But before that, check if `textureUniform.pixelDatatype === PixelDatatype.UNSIGNED_BYTE`. If so, call `getImageFromTypedArray` and put the resulting image into `resizeImageToNextPowerOfTwo`. Then create a `Texture` from that and proceed as normal.
- [ ] Add unit tests for `resizeImageToNextPowerOfTwo` , `getImageFromTypedArray`, and `TextureManager`

**Comment by jjhembd** [comment]
Hi @j9liu, I started a [draft PR](https://github.com/CesiumGS/cesium/pull/10482) addressing most of this issue. It follows your proposed strategy, with a few slight changes:
- `getImageFromTypedArray` directly uses the [ImageData constructor](https://developer.mozilla.org/en-US/docs/Web/API/ImageData/ImageData), rather than the context's [createImageData](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createImageData) method
- The logic for resizing is rearranged compared to `GltfTextureLoader`, to more clearly separate WebGL1 vs WebGL2 functionality

Handling the WebGL1 limitation (power-of-two dimension requirements) adds a lot of complexity. I wanted to separate out that complexity so that it can be easily removed whenever we drop WebGL1 support. The main createTexture function now looks like this:
```javascript
  const texture = context.webgl2
    ? getTextureAndMips(textureUniform, image, context)
    : getWebGL1Texture(textureUniform, image, context);
```
and all the dimension checks and resizing are handled inside `getWebGL1Texture`.

I wrote unit tests for the helper functions (`resizeImageToNextPowerOfTwo` and `getImageFromTypedArray`), but I'm still working on the tests for the main `TextureManager`.

I'd appreciate your feedback on 2 things:
- Does the strategy in `TextureManager` makes sense to you?
- How can I test both WebGL1 and WebGL2 contexts? The current `TextureManagerSpec` doesn't do this, and I'm not familiar with how to set up a context for the tests

Thanks!
