### ISSUE TITLE
Can cesium edit a specific component of a 3dtile model？

### ISSUE THREAD

**Issue by yoyomule** [CesiumGS/cesium#10287]
Can cesium edit a specific component of a 3dtile model, not the entire model. For example, edit the position, scale, and material of a column in the model.

**Comment by ggetz** [comment]
It depends on the 3D tileset. I don't believe we have an interface for changing position or scale, but its possible to embed [classification data, which can have custom styles applied](https://sandcastle.cesium.com/?src=3D%20Tiles%20Next%20Photogrammetry%20Classification.html).

Since this is more of a question, I would ask that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. We use GitHub for buck track exclusively. Thanks!
