### ISSUE TITLE
New version has broken map tiles

### ISSUE THREAD

**Issue by h11a** [CesiumGS/cesium#10307]
Hi

We are currently loading in webp map tiles from a third party provider. 

This is done like so
```
  this.observedImageLayerUpperGround = new Cesium.UrlTemplateImageryProvider({
            url: '[THE URL]',
            rectangle: Cesium.Rectangle.fromDegrees(west, south, east, north),
            ImagerySplitDirection: Cesium.ImagerySplitDirection.RIGHT,
            alpha: 0.5
        });
        this.observedImageLayerUpperGround.defaultAlpha = 1;
        layers.addImageryProvider(this.observedImageLayerUpperGround);
```

This was working great up until 1.92.0

However now we receive the following error. 

![image](https://user-images.githubusercontent.com/52792193/163979318-a241db33-7ba9-45d5-aa8b-9a62d7cd5799.png)

![image](https://user-images.githubusercontent.com/52792193/163979706-2047bb9c-0d5c-4a62-a163-5681bbe829c5.png)

I have rolled version back to 1.91.0 and it works again. Anyone have an idea what could have broken it in 1.92.0

**Comment by ggetz** [comment]
Hi there, we [updated to native promises](https://community.cesium.com/t/cesiumjs-is-switching-from-when-js-to-native-promises-which-will-be-a-breaking-change-in-1-92/17213) in 1.92 which changed a few small things with how Promises work in Cesium. The issue you ran into may have been fixed in https://github.com/CesiumGS/cesium/pull/10268. Would you be able to check out main and five it a try?
