### ISSUE TITLE
ModelExperimentalSpec - "projectTo2D works for CV" fails 

### ISSUE THREAD

**Issue by sanjeetsuhag** [CesiumGS/cesium#10403]
The [`Scene/ModelExperimental/ModelExperimental > projectTo2D works for CV`](http://localhost:8080/Specs/SpecRunner.html?category=none&spec=Scene%2FModelExperimental%2FModelExperimental%20projectTo2D%20works%20for%20CV) spec is currently failing on `main` on Chrome 101.0.4951.67 / Windows 10.

![image](https://user-images.githubusercontent.com/5172619/170346481-97a25f1b-17d1-445d-ad8d-8d35492c89de.png)

**Comment by lilleyse** [comment]
I don't think this is OS specific. Setting`this._logDepthBuffer = false;` in `Scene.js` results in the same test failure on Linux.

* We should check that `ModelExperimental` works property in CV when log depth is disabled in Sandcastle
* If sandcastle looks fine then it might be a problem with the test. When log depth is disabled the camera's near plane is `1.0` instead of `0.1`, and depending on how close the camera is to the model it might be seeing through the model.
