### ISSUE TITLE
Webworker cannot reas baseUrl 

### ISSUE THREAD

**Issue by dabuchera** [CesiumGS/cesium#10422]
Hi
Got the following error when deploying to gh-pages. The project is set up with the craco-resium package, but the error should not coming from there. On localhost everything is working fine. Only the deployment not working

![image](https://user-images.githubusercontent.com/53481997/171702274-04b7433f-7b55-4e62-9819-b1a71001c8a1.png)

Thanks for the help

**Comment by ggetz** [comment]
Hi @dabuchera, would you be able to check the network tab of the debugger? My guess is `Workers/createVerticesFromQuantizedTerrainMesh.js` is 404ing, leading to the error. 

I'm not sure about the details of `craco-resium`, but CesiumJS has some static asset files, including web workers, that need to be served alongside the library in order to work as intended. `window.CESIUM_BASE_URL` needs to be set so that cesium can request these files.

**Comment by dabuchera** [comment]
Nope. createVerticesFromQuantizedTerrainMesh is okay
I think the error is coming from the cesiumWorkerBootstrapper

![image](https://user-images.githubusercontent.com/53481997/171724689-510c38f6-2950-4f13-a005-23b8111b4530.png)

**Comment by dabuchera** [comment]
It also looks like that some js scripts in the web worker are missing in comparison to the localhost version

**Comment by ggetz** [comment]
Thanks. I think this is specific to the deployment process here, and not a bug, as I can't reproduce on sandcastle.cesium.com or other applications.

It will be difficult to track down exactly what's going on without more details. Perhaps try the [community forum](https://community.cesium.com/) with a description of the steps of your build and deployment. There should be developers there who are more familiar with craco-resium.
