### ISSUE TITLE
Enable SharedArrayBuffer in Cesium TaskProcessorWorker Evironment

### ISSUE THREAD

**Issue by jiangheng90** [CesiumGS/cesium#10502]
In Cesium TaskProcessorWorker Evironment，```SharedArrayBuffer``` is undefined in ```DedicatedWorkerGlobalScope```. but it works fine in original web worker. so how can I use it in TaskProcessor's Worker? 
My Cesium version is 1.92 I checked cesiumWorkerBootstrapper,and did not find a way to use  ```SharedArrayBuffer```

**Comment by ggetz** [comment]
HI @jiangheng90, there are [some additional security requirements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) that need to be met in order to use shared memory. Could you provide some additional context around what you're running using the TaskPorcessorWorker? Maybe a code example?

Also, Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, I would ask that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by jiangheng90** [comment]
> HI @jiangheng90, there are [some additional security requirements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) that need to be met in order to use shared memory. Could you provide some additional context around what you're running using the TaskPorcessorWorker? Maybe a code example?
> 
> Also, Cesium is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, I would ask that you take this to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

@ggetz  thanks！I found I have igonred set to cross-origin isolate in my  context. When I finish this I will make a code sample in sandcastle to share it to Cesium Forum

**Comment by jiangheng90** [comment]
@ggetz there are little changes in Cesium Source when I put cesium to cross-origin isolate environment，Do I need to make a pull request to show you？
