### ISSUE TITLE
tighter dependency versions or package lockfile?

### ISSUE THREAD

**Issue by chris-cooper** [CesiumGS/cesium#10585]
The loose versioning in `package.json` combined with a lack of lockfile can cause tricky to track down issues.  We recently had some specs start to fail in CI due to `zip.js` updating itself causing a failure due to the inclusion of `TransformStream`.

Have you considered either tightening the versions of dependencies or including a lockfile?

Our workaround: https://github.com/PropellerAero/cesium/commit/d951fe303f7b8bfe19a2b489284abe79e4121005

**Comment by ggetz** [comment]
Hi @chris-cooper, thanks for bringing this up.

We [moved to looser versioning](https://github.com/CesiumGS/cesium/issues/4697) a few years ago in order to prevent conflicts. However, given that we've just changed our strategy around third party modules and have moved several `devDependencies` to `dependencies`, it may be time to consider a lockfile to ensure consistency.

**Comment by ggetz** [comment]
Looking into this a bit more, while they work well for application development, [lockfiles are not a recommended best practice for libraries](https://www.twilio.com/blog/lockfiles-nodejs). So we're unlikely to go with a full lockfile approach. However, there was [another issue related to the zip library](https://github.com/CesiumGS/cesium/issues/10684) which we fixed by pinning a specific version. In the future, we'll likely stick with the pinning approach where needed. As of part of that fix, we are introducing more tests to our CI to catch such issues as they arise.
