### ISSUE TITLE
when i use cesium customshader in tileset,the tileset can not show all

### ISSUE THREAD

**Issue by engineerhe** [CesiumGS/cesium#10592]
when i use cesium customshader in tileset,the tileset can not show all.
The normal situation as shown below,
![image](https://user-images.githubusercontent.com/39166385/180760648-e1f0e332-03a7-4537-ab87-58b198e6fe1f.png)
but when i  enable ModelExperimental ,the result become that shown bellow,
![image](https://user-images.githubusercontent.com/39166385/180761351-ba7f6af8-570e-412e-a603-40405140e1ae.png)

the code as following shows:
    new CustomShader({

        fragmentShaderText : `void fragmentMain(FragmentInput fsInput, inout czm_modelMaterial material) {

        material.diffuse = vec3(1.0, 1.0, 0.0);

        material.alpha = 1.0;
    }`

**Comment by j9liu** [comment]
Hi @engineerhe,

I tried your Custom Shader on one of our tilesets and [it seems to work fine](https://sandcastle.cesium.com/#c=bVRrb9owFP0rFvuSSmDyogmMVpvaTkNa16pFkyZFWk1yoVYdO7IdSlvx33eTkDYUkMD2fZ3rc4+5AMPLnF5tCtA8B2mZ+AHMlhoMBckWAq5VBqLrJ2fE6hK+JjKRqZLGkjWHZ9Bol/BMLpqKf2qbk/TS+nyhMJVL0EnvpJNpuQADdj+1WYLLeeN03hJJSKnFpA2YKXkHRpU6BbrUKv9uMGyWOdEoCIOTfhWelsaq/P6RZaAne8U7jqYyIUvNVtXdGuscNnZCHhoXIWvFs/eIa7yD82N3mMmitGRp6rVPuFR4TF/zf3lF2TWzSBnSle82J23Ft3ZTfVovzfhyWRpAKtaQBo5H3T6pf1zqVpQdSWGieGSYgGHvAdt281DzsK3o2Fb5zZCoSUECLXCY3PI1TpllmbMbQxXWzIVL9DJxqwyuSiJGSx/TFndMBjXzl7DSAMapoAZRSF0vjr3A9WPX9cO47iB06enY88IgCCIvjH2vtuKoEnmAd6N5JbEdZGdqP4FlXK5uuU0f75QQB+C+R/0ojsZxFPvjIA5GNcoAzSiJsTsauXHkh6cNODIaeafjkTfGdsdx6I2aXvYoSlkOmlGkpZJyI5UMjOWy7m/ymaO6svq4wOTIpeoYkNlcM2mWSufvkka1aL4J6ezy6vd8Nv/bTi2RvX5vauyLgPN2st94XihtqyfhUDq0kBcCJWGGizJ9AktTYz4E88UqJRZMd1W3YOnTSqtSZhOiVwvmhH6ftF+Xxl25FagPZH5CwmLTMS+Uxqcy0DiW0uw7twfQvH4onQbWoC1PmRgwwVfIVM6zTMAh6sCqYkL8PeTWtVAWH/K+dwc9HXYJm2Z8TXh2duSviKSCGYOeZSnEPX+FpHc+HWL8QapQtQBvsHPBXqqwR+/8V2OklE6HeDyeuSPhU+X/). Is it possible to recreate this bug in a [Sandcastle](https://sandcastle.cesium.com/)? If not, are you able to share the tileset you're using so that we can debug further?

**Comment by engineerhe** [comment]
@j9liu thanks !
the tileset' url is "http://202.96.98.106:9627/ygkj/tileset.json"

**Comment by ptrgags** [comment]
@engineerhe Thank you for providing the tileset, I tried this locally and I think I see the problem. The good news is this is already fixed on the `main` branch (to be released next week in the 1.96 release)!

We had a bug in `ModelExperimental` where `.cmpt` tiles were not cached correctly. The first inner content will load correctly (which I think is what's happening in your second screenshot), but all the remaining contents end up using information from the first, which can lead to unpredictable results (sometimes duplicating the model several times, other times not rendering at all)

Fortunately, this has already been fixed in https://github.com/CesiumGS/cesium/pull/10524

Here's a [local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=bVJda9swFP0rFz85ECQnhWxJ3TDINhgs7KGhT4ZNka4Ttfowkuw2Gf3vk2VTTNcXSffj3HvOQdwaH6CT+IwO7sDgM+zQy1aTh5TLq4yneGdNYNKgq7LZbWUqwxOStz5YfX9m4j1+N6nkfysDUDt20mjCkDvgS4AN/OkrnZXirbyPa/LvY/DDNG2A2qd7DtLYGPKr/q2tQLVnAZ1kCvT4mEHaBG8JImRdtx4jtw75Tb4gxRzSUZCiFwLwGim8TjUFqdBj6CHJA+I5GiSNk1oG2aEnTIh8KjVdN18PA3BQ2zq1gSo7h9BsKF0WS7JekfVnsihWm/Vq+YleTk+PdNxFHr01VTbvgWjYUeG+1/ftpYkqeh9YHBZci6ljanrPfSA/kr1aqw82HwfPbrN5VvpwUbgdnAH4InVjXegZ5oTQgLpR0S5Pjy1/ily494MzACWdQkshO5Di7oM/AVwx72OlbpW6l1essm1JY/9/UGWZkOb0q0On2KVvOy+2P4ckIaSkMfwYGaxVR+beTf4H) that works on the `main` branch

![image](https://user-images.githubusercontent.com/8422414/181040776-ad825687-b512-4084-8672-f427ea1a673f.png)

One side note about transparency in `CustomShader`: By default, the shader renders opaque, and `material.alpha` is ignored. I wasn't sure if you intended to make the model translucent, but if you ever need that, remember to set `isTranslucent: true`, then `material.alpha` will adjust the translucency. See [a translucent version of the above Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=bVJdb5swFP0rVzwRKTIk1bKF0mhStkmTFu2h0Z6QVse+JG79gWxDm0z97zOGVbTrC+aec8/1uQeY0c5DJ/ARLdyAxkfYohOtIr8illYJi/XWaE+FRlsls+tKV5pFJWudN+r2RPlb/XbCpH8qDSDc3lLtZMtQ+wK8bXHe47WlRxWgoXePTx4KuOuZzgj+Qu/C9em3sfium9ZD7eI5B6FNKNlF/VaGo9xRj1ZQCWp8mUF0AC8A4aKuW4fBc4fsKl2QfA7xkZO8X/BVM5XNiYbWnHyI1HNw9zyNwQuJDn0/LcZGXNgRSWOFEl506AjlPJ2mE4+rL/tBOATUWllAlZy8b4osW+ZLsl6R9SeyyFfFerX8mJ2PD/fZeBe5d0ZXSUwQNT1I3PWrf31qguc+IionGU+/U+99MD+avRij9iYdB8+uk3lSOn+WuBlyAPgsVGOs7x2mhGQeVSNDOC47tOwheGHO/QutzKbSkosOBL955zcCJqlzgalbKW/FBatkU2ah/z+pNJQLffzZoZX03LedFpsfA0gIKbNQvq/0xsgDtW8m/wU).

![image](https://user-images.githubusercontent.com/8422414/181041733-d65d731a-8ddd-41c8-8dc7-9881a35078c3.png)

Since the underlying issue was already fixed, I'm closing this issue

**Comment by engineerhe** [comment]
@ptrgags It's wonderful.Thanks for your help
