### ISSUE TITLE
Inaccurate milliseconds value in JulianDate.toGregorianDate

### ISSUE THREAD

**Issue by kurdupovk** [CesiumGS/cesium#10602]
Hello!
First, I would like to thank you for such a great library and service!

**The issue**

I found that converting some ISO date strings into JulianDate and back to ISO string or Javascript Date causes different value of milliseconds, actually the difference is 1 millisecond.
Digging deeper I found that the problem is in **JulianDate.toGregorianDate** function which converts seconds with fractional part into milliseconds and during this conversion milliseconds differs from fractional part, this is because of math with floating point  numbers.
Check the sandcastle example below to understand the problem. Check sandcastle **Console** tab

Sandcastle example: https://sandcastle.cesium.com/#c=nVRdT9swFP0rVl6SaMVpOvYBDdWkom1Mm/rQDokpLya5DdYcG9lOEfx67DShzkdhWtWHxvecc8+5vk0muNJoR+EBJLpAHB7QEhStSnxdnwWpl9XPS8E1oRxk6oXzlKc8q5lUiQ0twVD92XQ2O5nOTuIPm/j9+enp+fQTPovP/vjzFpwTDU2TS/MzaMjhC6CQUAhJCb88IBs739xSYJVwAfr3Zvm1YuwGiAzCCXKOfxm/d0GI3qF4knLklmqFsH/6XVRS9UUorzT0T9dg3OZDLGNUHUpbwpQTbStFeaXE54/T2ARrQv2oWJMIO/XhXLRoBjLk7UuBQz9cj2CAmSgCfyVpQTlh9rqQ0pLyIk318OubcfWav2j4I7odH6378Kj0mPuW5QYY9B7mDS11vVrXWQYtbbM9sAt7Xbi7YiEuDzf6L0m6dDePq/TWFGtyby96xkazW1d2o49uyPjKdaU7/79+n9eH197jG9Y7Uzzmt9X6D8vh3Jt4idKPDBZW3n6+0PJeSI0qyQKMIw3lPTNgFd1W2V/QOFPKZrPQJHKpSU53iOYXI+9AlDGilKlszetnTZ8g9RZJZPADKhMkN/Nb7UAy8mhhd/Hi5/4QY5xE5nGcqYVgt0T2lJ8B

The problem is in [this line](https://github.com/CesiumGS/cesium/blob/a8c27a25fc4d810788a8c30f3e8ea8ba0b773fc7/Source/Core/JulianDate.js#L669).

During calculation of remainingSeconds the fractional parts changes. Here is the exact example based on date from sandcastle example:

```
// secondsOfDay = 6247.919;
let hour = (secondsOfDay / TimeConstants.SECONDS_PER_HOUR) | 0;  // Result: 1
let remainingSeconds = secondsOfDay - hour * TimeConstants.SECONDS_PER_HOUR; // Result: 2647.919
const minute = (remainingSeconds / TimeConstants.SECONDS_PER_MINUTE) | 0; // Result: 44
remainingSeconds =
  remainingSeconds - minute * TimeConstants.SECONDS_PER_MINUTE; // Result: 7.918999999999869
```

So as you can see the fractional part **.919** changes to **.918999999999869**.  So, the output date comes with **918** millseconds, which is not correct.

So, this is the issue.

Note: the issue appears not for all ISO date strings, some of them display correct milliseconds value although the floating point math always changes fractional part.

**Idea to fix**
As a quick fix I could suggest calculating milliseconds this way:

`const millisecond = (remainingSeconds / TimeConstants.SECONDS_PER_MILLISECOND) - (remainingSeconds | 0)  / TimeConstants.SECONDS_PER_MILLISECOND;
`

I searched through the forum and github issues, but I did not find any mention about this issue. I was really surprised that no one encountered this before.

**Comment by ggetz** [comment]
Thanks for the report @kurdupovk! Calculating milliseconds in a sperate operation should work. Would you be willing to open a pull request with this fix?

**Comment by javagl** [comment]
I might have misunderstood something here, but I wonder how the proposed fix could be applied. I tried changing the line for computing the `millisecond` as suggested, and compared the result to the 'old' implementation, and the result was the same.

In fact, I think that the problem is that of trying to compute the milliseconds from the seconds in the first place. Even though the value for `secondsOfDay` is printed as `6284.919`, that's not the actual value. This value cannot be represented as a floating-point value, and JavaScript just chooses to print a "shorter" value.

Some details in this sandcastle: 

https://sandcastle.cesium.com/#c=7VVdb9owFP0rV7yQdMUhrN1WkqJJgDQmSqpC9zBFqtLEUGuOjWwHxD7++5yYMNJAxfq0h4WX5Pqec8+1D9cxZ1LBiuA1FnANDK+hjyXJUvSliFlhIy6++5ypiDAswobthSxkcYEkks9IijW02Wl3Oq12p+Vezty33YuLbvs9unKvvja9MjmJFN4WGehXawu2dwlzwdOR5B/etV2dtxXyOaMkYjkA7a3vgw2cU4woX1jNQJAFYRHNxYFUgrBFF5rwBp7V2wGahmSesVgRziDm6TJT+IZQSmRAE0tinZ/IYD6INjb8CBkAxQqeeJZvWmUZnFJ3XqqftxUxJdF02A8mg+nD7fDu4VNwf2fDT2h7JZPAqd5cLXRqqDRrhbRlap2dxl3Qmh1NCcuKTbdqJU4QejOa3M+Gf6TWZebRA/FWWfjs1CK7rTB9a8U10lJF2Vl+OttkI8M6oMNk2Kd1Ox6PTMCD4jE9q0yw/XJaxK/jfpng9X+//Ot+eW17O4PYWvIx0+m6f+23l51WmVaVg87H2t5URBXnea9FIsVvBY6J1O62Oq5dY+I0MSO1NiqPiqlx6GvgAEf+93mRw/wa5w1fqg3FPXMKAB9JuuRCQSaohZCjcLqk+s6QzmMWf8MKxVLankn2nX2on5AVkOT6wE0HMY2k1CvzjNIp+Y7DRs93dH4NSnmUaAsEKyxotMnTntze2AQRQr6jPw8jFef0MRLPmH8D

The output is
```
Original iso string: 2022-02-15T13:44:07.919Z

secondsOfDay 6284.919
secondsOfDay 6284.91899999999986903
old: 918.999999999869
new: 918.999999999869
```

**Comment by kurdupovk** [comment]
> Thanks for the report @kurdupovk! Calculating milliseconds in a sperate operation should work. Would you be willing to open a pull request with this fix?

I am sorry, but I would leave it to people who is better familiar with the ecosystem and how to do it.

@javagl 
> In fact, I think that the problem is that of trying to compute the milliseconds from the seconds in the first place. Even though the value for secondsOfDay is printed as 6284.919, that's not the actual value. This value cannot be represented as a floating-point value, and JavaScript just chooses to print a "shorter" value.

I agree. The original floating-point value in memory is different than it s value printed in console. But still JS prints some numbers with long fractional part and other with short.
I experimented a little and found that at least in Google Chrome 103, JS prints number with long fractional part if number is < 2048.
Anyway, you are correct and my fix does not work.

I've come up with another fix, although I am not sure it is correct:
`
const millisecond = Math.round(remainingSeconds * 1000) % 1000;
`

Here is the sandcastle with [this fix](https://sandcastle.cesium.com/#c=7VZdb9owFP0rV0gTCRsmYd1HCUWToNOYgFSF7mFCqtLEgDXHRrYDZR//fU4MDJowAdKkPRQeINf3nHuuc5LrkDOpYEHwEgu4AoaX0MaSJDH6ksWscSnMrtucqYAwLMYl2xuzMQszJJF8RGKsoeW6U69XnXrVfTNyXzcuLhrOO3TpXn4te5vkKFB4XaSj/1prsL1NmAgedyV//9Zxdd5ayOeEkoClALSzvgs2cE4xonxqlX1BpoQFNBUHUgnCpg0ow0t4Um8LKBuSScJCRTiDkMfzROE+oZRIn0aWxDo/kv6kE6xs+DFmABQrmPEk3bS9ZahtdKel2mlbAVMSDa/b/qAzvL+5vr3/5N/d2vATHG/DJHCsN1cLHRoqzbpHWjW1KsdxZ7RmR2PCkmzTrVyJI4T2u4O70fUfqXmZabQgXt0UrhxbZLsVpm+tOEe6UbHpLL0762QjwyrQYTLs47rt9bom4EH2MT2rRLDdclrEr8N+GeDls1/+d7+c297WILaWfMh0uu7JfjvTab6aYfGRPBY57tlz/8RzRW7qB2qGBE9YlG+hAq7jaEO8yH5PsO1hO+wNr717kE65nSGJ9mzhnYtEit8IHBKpLWjVXTvHxGlkJmxuch4Uk+PQp4ICjvRtehIH8PSRgAl5LGbbPjF/ZTXf0qtSU6oVxS1jIYAPJJ5zoSAR1EKopnA8p/pgImsPSfgNKxRKaXsmuVnbhTYjsgASXRUcpyCkgZR6ZZJQOiTf8bjUatZ0fg5KeRBpo/gLLGiwStNmbqtnggihZk1fFiMV5/QhEE+YfwM) based on your example

Also, I have created a [testing sandcastle](https://sandcastle.cesium.com/#c=xVVrb9owFP0rt6gtSYEkMK2aykOrWqYxjVIV+mVjatNgipmxke20ZR3/fdd5QAJ049siRBLb9557jo9vAsGVBqrEgM4INKFY82q1ilerVN8PPO8s+jme530r1oc8iBaPpZh1lPhw6lUx4IIoGs6cLyGjPr/0NXEy81aS2MbgIR+HPNBUcAjEbB5q0qWMUXVFnnt6QuQn+mIpghAj1Rtf+gsbXocc8GJEw0SEEsFyC8BNwQ3EhanN51o5/fZF7+qyf3fdvrn73Lu9seE3eHWTy2SSZOZTTvljP06FWXNJKzHWyX65o7SxLDPKkZMpcgtij0K7navbQXtd6naZsRhb45UU+GRfkFzNZgeiTFh419cTR4qQj7YpnEAVXWDDUXRfqbmK3QpYE9Gh5FkkHF4aO2RL6HCjfRPenXpeglUH162avRhyg0Rx1mQ0z0RKYeww9pkieWvJkJ8zhsm6a0A1IEpjaVZiKUW00UiE2sKhZis1Gh1bCHPQRCCA42N8PgKsBy9omsGVI2P5BCMOE4/W/ffDV06ewZjfsh0tOv1eX8sIcPkDN+geSmBRNxawhK9iDIevWeJuxHiZOhE0FkxG93Y9xlvGt7GQlqE/jaTA8hpZ9XCgVCrDtFTK1ImUpgkjJDRNtm+bD8CDJP7Pevq+zBLVMPIjZ69Yrh7S8+08xppahiDdEKGeT0b37B0GdDM26RzGcW82kSS/k2smG3nIy5wEmKebOwA0a+9EvhWiUXFHWE5EY9LslqxnUstqGZLMcNZHxfTooD1GaIpiCXZRQW2vJQmoQrtbtaptv5WuHUEaWc+giNsSbWIJimVoJzTi8V1aRMvOAx367MysSVXIgu10THKL/5PvBfYFNSGxwK1NgVZHL132305ZVMVBtFF2XknTPxTMfaWQhQqDgCg1DhlbFFcnFAi2onXlf29D2WO9LJuq7LQp/iOwUC40lF4w0kqRPtLZXEgNoWSW47iazOYMJVLuQxj8JNoJlErxGm42tDGiT0BHzWEhiI4hfjI0tnAihwUIGHLFGUOyT3+RYaHVcHH9VigT/ggr6z0RyfyFWTaptr7Gg47jNFx83R2phWAPvtzI/Ac) to test it for multiple different timestamps, it just takes initial timestamp and add 1 millisecond to it each iteration, so it checks timestamps sequantially, I set only 1 hour.
I am sorry, it is a bit difficult to understand because I've developed it so you can run with big numbers and do not let browser freeze.
I ran it for 24 hours(86400000 milliseconds) and took about 30 minutes, and it did not fail. For example, when I used my first fix it failed immediately on the first millisecond.

Again, I am not sure if it is correct fix, but it passed tests for every timestamp within 24 hours. I am not sure whether there are others quick fixes for this issue.

**Comment by javagl** [comment]
After looking more closely at the test and the source code, and doing further tests, I'm no longer sure about the actual problem here. Looking at your original sandcastle, the last line is
```
JulianDate.toIso8601(JulianDate.fromGregorianDate())			2022-02-15T13:44:07.918999999999869Z
```
This shows that the original value of `919` is preserved as `9189999...`, which is as accurate as this number can be represented via the `secondsOfDay` variable. In doubt, you could change the last line to
```
console.log('JulianDate.toIso8601(JulianDate.fromGregorianDate())\t\t\t' + 
  Cesium.JulianDate.toIso8601(Cesium.JulianDate.fromGregorianDate(gregorianDate), 3));
//--------------------------------------------------------------------------------^ add this  
```
causing it to print
```
JulianDate.toIso8601(JulianDate.fromGregorianDate())			2022-02-15T13:44:07.919Z
```
which may be what you'd expect here. 

---

One could still argue about the `secondsOfDay` variable: It obviously _does_ cause a precision loss, and may lead to unexpected results. In addition to the unexpected output of "918999999999869", it actually _does_ lose one millisecond when looking at the line
```
JulianDate.toDate(JulianDate.fromGregorianDate()).toISOString()		2022-02-15T13:44:07.918Z
```
But after diving into a few [rabbit holes of specifications](https://262.ecma-international.org/7.0/#sec-date.prototype.setmilliseconds), I noticed that this is not a limitation of the Cesium classes, but rather one of the built-in `Date` class: This class simply cannot handle fractional parts for milliseconds.

Beyond that, there might not be an easy way to get around the `secondsOfDay` in general, because it is part of the `JulianDate` API. One approach could be to change this and have `wholeSecondsOfDay`+`nanosecondsInSecond`, which are both _integral_ values, but this may require a few more modifications of the internals of `JulianDate`...

**Comment by kurdupovk** [comment]
> This shows that the original value of 919 is preserved as 9189999..., which is as accurate as this number can be represented via the secondsOfDay variable. In doubt, you could change the last line to

Somehow I overlooked the **presiion** parameter of **JulianDate.toIso8601** function.
After testing my cases I concluded that this is sufficient for my project. So I am closing the issue.

> But after diving into a few [rabbit holes of specifications](https://262.ecma-international.org/7.0/#sec-date.prototype.setmilliseconds), I noticed that this is not a limitation of the Cesium classes, but rather one of the built-in Date class: This class simply cannot handle fractional parts for milliseconds.

I believe it is because usually it is recommended to use fractional part as an integer number.

Anyway, thank you for your help and researching.
