### ISSUE TITLE
How to load a model with both KHR_draco_mesh_compression and CESIUM_primitive_outline extensions?

### ISSUE THREAD

**Issue by SunnyBily** [CesiumGS/cesium#10662]
Hi,

I'm trying to use Cesium to load a 3dTiles model with outlines, and the geometry of this model is compressed by draco.

I stored the compressed geometry as a bufferView, and the outlines data as a separate bufferView (outline indices are not compressed). The primitives extension part in the mesh includes both two fields: KHR_draco_mesh_compression and CESIUM_primitive_outline, like this:
![image](https://user-images.githubusercontent.com/36740211/183818146-f061616f-c25f-4c47-a7e9-556b20a20c54.png)

The model generated by the above method does not load properly in Cesium.
![image](https://user-images.githubusercontent.com/36740211/183818538-09d5ea48-60ed-40f3-99bc-042bd950462b.png)

Here is the 3dTiles model generate by my method.
[3dTiles_draco_outlines.zip](https://github.com/CesiumGS/cesium/files/9296880/3dTiles_draco_outlines.zip)

The Cesium version is 1.96

What I want to know is how to properly generate the draco-compressed model with outlines?

Thanks.

**Comment by SunnyBily** [comment]
This issue is migrated to community forum: https://community.cesium.com/t/how-to-load-a-model-with-both-khr-draco-mesh-compression-and-cesium-primitive-outline-extensions/19918

**Comment by lilleyse** [comment]
@SunnyBily looks like this is a bug in CesiumJS. I opened a PR to fix it: https://github.com/CesiumGS/cesium/pull/10686

**Comment by SunnyBily** [comment]
@lilleyse , I modified my local code according to your submission, and the problem was solved, Thanks a lot!

**Comment by lilleyse** [comment]
@SunnyBily great to hear!

**Comment by lilleyse** [comment]
I'll just keep this open until the PR is merged.

**Comment by ptrgags** [comment]
@SunnyBily I merged the PR to fix the outline loading crash. That said, I noticed that the glTF file (inside the `.i3dm` inside the tileset) seems to be missing some details which makes it not render correctly, even with the fix. The accessors do not reference any buffer views, so most of the data in the model is ignored (including the outline indices)

```jsonc
"accessors": [
    // ...
    {
      "componentType": 5126,
      "count": 78,
      "type": "VEC2"
      
      // Missing bufferView, and possibly byteOffset.
      // Without a bufferView, the accessor values will default to all 0s!
    },
    // ...
```

This is because of the following line from the [glTF spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#sparse-accessors)

>When `accessor.bufferView`is undefined, the sparse accessor is initialized as an array of zeros

Some relevant parts of the glTF specification:

* [Accessors](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#accessors)
* [Accessor property reference](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#reference-accessor)

**Comment by lilleyse** [comment]
It's ok that the draco compressed attributes are missing buffer views since the data comes from the draco blob.

The problem might be that `CESIUM_primitive_outline` references the same index buffer as `indices` which doesn't have a buffer view.
