### ISSUE TITLE
Error LegacyInstanceing without normal

### ISSUE THREAD

**Issue by progsung** [CesiumGS/cesium#10764]
# Error legacyInstancing i3dm without normal vertex attribute. (in main branch, 1.97)

https://github.com/CesiumGS/cesium/blob/85535fbedc196ef872f989d9a81ef22161f16193/Source/Shaders/Model/LegacyInstancingStageVS.glsl#L7

# My Fix 
```
//(original) vec3 normalMC = attributes.normalMC;
=>
//(fix)
#ifdef HAS_NORMAL
    vec3 normalMC = attributes.normalMC;
#endif
```

**Comment by progsung** [comment]
Maybe..., This case also need testing.
* InstancingStageVS  ( _new instancing_ )
https://github.com/CesiumGS/cesium/blob/85535fbedc196ef872f989d9a81ef22161f16193/Source/Shaders/Model/InstancingStageVS.glsl#L1

**Comment by ptrgags** [comment]
@progsung thanks for catching this! You had the right idea for the fix, there was indeed a missing define, though only in `InstancingStageVS.glsl`. The problematic line in the legacy (i3dm) version was actually dead code, so the fix was to remove the line.

I opened https://github.com/CesiumGS/cesium/pull/10765 to fix this.
