### ISSUE TITLE
When the camera gets closer to the terrain, some terrain shadows disappear

### ISSUE THREAD

**Issue by JiaoJianing** [CesiumGS/cesium#10793]
Sandcastle example: [Link](https://sandcastle.cesium.com/#c=bZLRbtsgFIZfBfkqkTyCjcF2kkbbkt6126RW241vqH3SoGGIACfLpr77sJ1E0VYkJM7h+/k5B2qjnUcHCUew6A5pOKI1ONm1+PuQm1RRPcRro72QGmwVxehPpRFyO9GYo5sjbzuI+4wHawPzdNk4nzTGj6YBfP/l0+eH+80t/c2ag2zAXvHagvDww1jVPI/IZBoEb9NFpSs9XhWP5o9ij1vxS7Zdu5HOC11DKCIhYdzCtWjBCrxVp2czGe7egPNSCy+NvvquhfVhJTTFW2vaDbxaADdJCMec0zLNaJIlJWdpjNISs4JSQgkjjDHKY5SXCS6zgrE0z/OATYcajZUQ+jb6DM4I7UA0Ur/OEceEU1LkeUmDActZPAJ76evdHH0gOCt4zngRbFPKi7zIzoQ1Ss0RwX2hpCB5mRHKKQ9AQdMeebv2Cw0jiqMqWvTRZSK0dP6kYHVBPsp2b6xHnVUTjGce2r0K7+BmL139EzyunZsuzsrZrXTZyAOSzd07PwXVSjgXdradUk/yN1TRajkL/H9SZYamfD2AVeLUY7tk9TAmMcbLWQjfV3pj1Iuw/5z8Fw)

Browser:Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)

Operating System: Windows 10

When the camera moves closer to the terrain, some shadows disappear.
![shadow-not correct](https://user-images.githubusercontent.com/12868409/190351090-e8ba23d3-8838-47d6-bd42-1b8e0a9e3945.gif)

**Comment by ggetz** [comment]
Hi @JiaoJianing. I believe this is due to higher resolution terrain tiles loading in as you zoom closer. To see this demonstrated, [this sandcastle enables wireframe debug mode](https://sandcastle.cesium.com/#c=bZJhb9owEIb/ipVPIGXGiRMnAYq2Qb+126RW65dIlUkOsObYyHZgdOp/n5NAhdpaiuQ7P3ev73UqraxDBwFHMOgGKTiiJVjRNvh3nxuVQdXHS60cFwpMGYToX6kQsjte66OdImdaCLuMA2M883A5OHca4ntdA7798e373e3qmv5l9EHUYN7wygB38KSNrB8HZDT2Ba/jWalKNVwVD+L3fI8b/lc0bbMS1nFVgR8iIn5dwxVvwHC8kadHPervXoN1QnEntHrTXXLj/I4rijdGNyvYGgA7igjDjNEiTmiURAVL4xDFBU5zSgklKUnTlLIQZUWEiyRP0zjLMo+N+xm1EeB9G3R6ZYR2wGuhtlPEMGGU5FlWUC+QZmk4AHvhqt0UfSE4yVmWstzLxpTlWZ6cCaOlnCKCu0FJTrIiIZRR5oGcxh3y+sGvChTgrdRrwM+2NRte+Y0TEi7+4+ca1u0WH4WBjfGOeSe7l+27oH4FYVAGsy66fAjNrTtJWFyQr6LZa+NQa+QI44mDZi/9a9rJuq3+gMOVtePZuXJyXTqvxQGJ+uaT/w1VklvrTzatlA/iBcpgMZ94/kOp1L21Pw9gJD912C5a3A1JjPF84sPPK53Wcs3Nu87/AQ) and shows more geometry loading in as the camera gets closer.

**Comment by JiaoJianing** [comment]
Hi @ggetz Thanks for your response! I understand your meaning, I prepared a new gif:
![WPS动图制作(2)](https://user-images.githubusercontent.com/12868409/190941865-adc64758-60c7-47dc-9942-579f515d3e0f.gif)
When I change the camera's angle slightly, terrain's geometry barely change, but some shadows disappear.

**Comment by ggetz** [comment]
@JiaoJianing I think this may be due to culled terrain tiles. We [don't render terrain tiles which are out of view of the camera](https://cesium.com/blog/2015/06/24/oriented-bounding-boxes/). If they are not rendered, then there is no object in the scene to cast a shadow.

To see this, here's [your sandcastle example with the Cesium Inspector Widget added](https://sandcastle.cesium.com/#c=bZJdb9sgFIb/CvJVInkYGxvbSRqtS3oxqdkmtdpufEPtkwYNQwQ4H53630fsJIq2IiH5HJ73vJyDa62sQzsBezDoDinYowVY0bX4Z58bVUHdxwutHBcKTBWE6E+lELIb3ui9nSBnOghPGQfGeObpcnCuNMQr3QB++Hb/5fFheUv/MHonGjBXvDbAHfzSRjbPAzIae8H7eFqpSg1XxYP5im9xyw+i7dqlsI6rGnwTMfHrFq55C4bjtTw+61F/9wasE4o7odXVd8GN819cUbw2ul3CqwGwo5gwzBgtk5TGaVyyLAlRUuKsoJRQkpEsyygLUV7GuEyLLEvyPPfYuO9RGwF+boNP74zQBngj1OsEMUwYJUWel9QbZHkWDsBWuHozQZ8ITguWZ6zwtgllRV6kZ8JoKSeI4FOjpCB5mRLKKPNAQZMT8n6dVxTdN825RfRV2S3UTpvraODgQDWj8wiG5BBc2ZU4CDUUQ/0KwqAKpqfoshGaWXeUML8gn0W71cahzsgRxpGDdiv9o9ropat/g8O1tePpWRndSmeN2CHR3H3w26Facmv9ybqT8km8QRXMZ5Hn/5NK3U/4+w6M5McTtonnj0MSYzyLfPix0mktX7j5p/Jf). Zoom into the point where the shadows disappear. Then, in the inspector, check "Suspend LOD Update" under the "Terrain" section. When you zoom out, you can see the culled area, and the shadows remain the same.

**Comment by malaretv** [comment]
Interesting! We're also running into this as we are seeking to provide our users with as accurate terrain shadows as possible. Is there any way to relax the aggressiveness of the culling?

**Comment by ggetz** [comment]
Not through the public API, I believe.

You could experiment with seting `globe._surface._debug.suspendLodUpdate` to stop any new culling from happening.
