### ISSUE TITLE
Cesium on terriajs

### ISSUE THREAD

**Issue by scrummish** [CesiumGS/cesium#10902]
When running gulp:watch I get the following error. Any information would be helpful. Thank you!    

WARNING in ./node_modules/terriajs-cesium/Source/Workers/Transforms-6a73174d.js 12935:27-34
    Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
     @ ./node_modules/terriajs-cesium/Source/Workers sync nonrecursive .*\.js
     @ ./node_modules/string-replace-webpack-plugin/loader.js?id=0ph6wzmv6klh!./node_modules/terriajs/buildprocess/removeCesiumDebugPragmas.js!./node_modules/terriajs-cesium/Source/Workers/cesiumWorkerBootstrapper.js

**Comment by kring** [comment]
The TerriaJS build process is... complicated. You should probably raise this in the TerriaJS discussion forum instead:
https://github.com/TerriaJS/terriajs/discussions

But I can say that that warning is normal and doesn't usually cause a problem.

I'm closing this because it's not a CesiumJS issue.
