### ISSUE TITLE
workspace.replaceAll is not a function

### ISSUE THREAD

**Issue by alanwhy** [CesiumGS/cesium#10948]
Hello, cesium developers.
I found a problem when studying your packaging method, as shown in the title
The reason is that my node version is 14.19.0 , but the `replaceAll` method was added in the node 15 version
I upgraded the version to stable 16.18.1, and the problem did not recur
So I suggest using `replace` to execute

```js
export const postversion = function () {
  const workspace = argv.workspace;
  if (!workspace) {
    return;
  }

  // After the workspace version is bumped by `npm version`,
  // update the root `package.json` file to depend on the new version
  const directory = workspace.replaceAll(`@${scope}/`, ``); // this line is wrong in node 14
  const workspacePackageJson = require(`./packages/${directory}/package.json`);
  const version = workspacePackageJson.version;

  packageJson.dependencies[workspace] = version;
  return writeFile("package.json", JSON.stringify(packageJson, undefined, 2));
};
```

For example, you can refer to

```js
//Taken from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
function replaceAll(str, match, replacement){
   return str.replace(new RegExp(escapeRegExp(match), 'g'), ()=>replacement);
}

console.log(replaceAll('a.b.c.d.e', '.', '__'));
console.log(replaceAll('a.b.c.d.e', '.', '$&'));
```

Reference link: https://stackoverflow.com/a/62825372/8086267

**Comment by ggetz** [comment]
Hi @alanwhy,

[npm workspackes](https://docs.npmjs.com/cli/v7/using-npm/workspaces) are only supported in Node 16 and above, which is why we've [documented a minimum Node version of 16 or above in the build guide](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/BuildGuide#build-the-code) to build the code or run development scripts.

However, workspaces are not required to run the packaged/shipped code, which is why the minimum supported Node version defined in `package.json` is >14.

Thanks!

**Comment by alanwhy** [comment]
Thank you very much for your reply. I learned
