### ISSUE TITLE
Polygon + property callback = dramatic performance drop

### ISSUE THREAD

**Issue by azurre** [CesiumGS/cesium#10946]
Hello,
Using property callback for the polygon hierarchy cause the dramatic performance drop

Sandcastle example: [Sandcastle](https://sandcastle.cesium.com/#c=bVLBitswEP2VwScHvOPuJqXb1gltU0oPhQay9FL3oMiTRKwshZGc4Ib995Utu6TZNQj8Zt7MezOStMZ5OCo6EcMcDJ1gSU41Nf7qY2mZyB4vrfFCGeIymXwsTaxAJ8kQVrRpduu9PX1jUZNbEa9JWlOFhp4bCnQIn+yl9opYsNy3ITkoLQX78CfMFLds66+0YyL3mVm06e+buxne32dwO8XZNIMR3txN8f2bDN7N8O1LeEXu4Z/OdvQghdYbIR//H3g5RFdsD8S+TdMJzBeXjJXV7c6a7+MI6b9hJhlshXbUaYwqZLzy3ZjDrnqsyKGoqvQMh9jsA5wvdvL0FDushamkcF5Tx36wNjjjL4331oQbuXZaJkG+MdIrayC4PncLj/I4yODl3sf5g9SgN1jc6vbBprGySyRZUib99Y0HoHC+1bSIAOCTqg+WPTSsU8TcU33QIlxnvmnkI3mUzk2GB1Dkl6VFpY6gqvkrDwykFs6FzLbReq3+UpksijzwX5RqKypldj+PxFq0HW1/u/gRg4hY5AG+XunjTq86PwM)

Browser: Chrome 108.0.5359.95

Operating System: Windows 10

**Comment by ggetz** [comment]
Thanks for the report @azurre!

I think the reason you're seeing such a performance drop with the dynamic positions are slow is because rendering a large polygon like this on the globe requires curving it along the surface. The geometry is being recreated every frame. The solution to this would be [using dynamic buffers](https://github.com/CesiumGS/cesium/issues/932).

I'll close this issue in favor of https://github.com/CesiumGS/cesium/issues/932, but note this specific report there.
