### ISSUE TITLE
Loading a Billboard image from an inline SVG doesn't allow Hex color codes

### ISSUE THREAD

**Issue by VsKatshuma** [CesiumGS/cesium#11055]
Greetings.

Current version of Cesium (1.101) has an oddity when adding a Billboard to a BillboardCollection. Here's my code:

`billboardCollection.add({
  position: Cartesian3.fromDegrees(longitude, latitude, height),
  image: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400"><path fill="#ffffff" d="M 200 400 l -75 -75 l -75 0 s -50 0 -50 -50 l 0 -225 s 0 -50 50 -50 l 300 0 s 50 0 50 50 l 0 225 s 0 50 -50 50 l -75 0 Z"/></svg>'
})`

Using an inline SVG like this results in an error. Chrome console reads `Error loading image for billboard: [object Event]`

But curiously, changing the #ffffff Hex color code to rgb(255,255,255) fixes the issue. The following method works as expected:

`billboardCollection.add({
  position: Cartesian3.fromDegrees(longitude, latitude, height),
  image: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400"><path fill="rgb(255,255,255)" d="M 200 400 l -75 -75 l -75 0 s -50 0 -50 -50 l 0 -225 s 0 -50 50 -50 l 300 0 s 50 0 50 50 l 0 225 s 0 50 -50 50 l -75 0 Z"/></svg>'
})`

The only change is `fill="#ffffff"` to `fill="rgb(255,255,255)"`

For some reason, Cesium doesn't allow Hex color codes to be used in this scenario, but inputting the same color as an RGB value functions just fine. `fill="#ffffff"` is accepted SVG syntax, so this feels like a bug to me.

**Comment by ggetz** [comment]
Hi there @VsKatshuma. The issue here is not with the SVG itself, but with the data URI. I added your first example to the W3C validator and selected "Validate by URI". [The result is an unexpected end of input](https://validator.w3.org/check?uri=data%3Aimage%2Fsvg%2Bxml%2C%3Csvg+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22+viewBox%3D%220+0+400+400%22%3E%3Cpath+fill%3D%22%23ffffff%22+d%3D%22M+200+400+l+-75+-75+l+-75+0+s+-50+0+-50+-50+l+0+-225+s+0+-50+50+-50+l+300+0+s+50+0+50+50+l+0+225+s+0+50+-50+50+l+-75+0+Z%22%2F%3E%3C%2Fsvg%3E&charset=%28detect+automatically%29&doctype=Inline&group=0) due to the `#` character. I would suggest escaping it.

**Comment by VsKatshuma** [comment]
Thank you so much for pointing me in the right direction. Indeed, replacing `#` with `%23` produces the expected behavior.
