### ISSUE TITLE
label background outline is fuzzy

### ISSUE THREAD

**Issue by ABoyCDog** [CesiumGS/cesium#11124]
I found that when i create a label in the ScreenSpaceEventHandler, it would be fuzzy background outline. Please help me to solve it.

![企业微信截图_16775741432595](https://user-images.githubusercontent.com/29125698/221802063-d6cd93a5-a466-4c5c-9153-b7475565f0b7.png)

example:
[example](https://sandcastle.cesium.com/#c=nZRdb9owFIb/yhE3DQg5S7uLiS+tREygMlEJ1N1EWo1xwcLYke2E0or/PtvhIwW6tZNy4fPxvs45TxQihTaQM7qmCtog6Bpiqlm2Qg8+FyQV4uNYCoOZoCqpVJuJIF6nCRXUygo98qEt7ssLLGb81HdMFKVinGJCezkVpl80BV6MCBY51tWSCcdTyrX1KBpSxVbMsJxqhGezoGQ8dI2x5JwSw6QIqs4lrNVKNtalsPPa10QApFIz194ov2OMlbEnLG6CqA7uqdZds6HPpgGP0aOP9EKuG2BURn34xLi7XqrGwcZFqDu8je8Ogi4my7mSmZiVpNND8pLBr/5g0iuusBAakFSir+kzrKSQ2q0xqfjiQir24ijxkWJzJg4u/ZMCGvZ+TLwkp8owciZ4eJNG3dFkMvppBVu30VotdHASsaOLNDUDkWbmtlh7QKvQ7oBfbrH6lJHl/W7NR46lZGDD3dHdAHDUvoftk+BO0Z3B+wi+vwD8OMJ/QCwb3dtpmZjD5Qmvg+ibne/LfsD/wP/pDwBgewTkkRzAWUZlpM1jh9u8rV5F1zfl56q5pyw5RVzOg2O1/sarXjJy12/r7/1LJpuU+vF+x8NBfOeaK/VKS5sNp51iYoDvbJVKZSBTPEAoNHSVcmx3Gk4zsqQGEa2LIQFaYVnamrEc2Kx94ZcIhGOtbeUp43zMXizOTiu0/WdSLrGDOrKb53jj2hZRZ1gkEUKt0IaXlUZKPsXqxPkP)

**Comment by UniquePanda** [comment]
I fixed a similar issue here: #11040  
For us this bug doesn't happen anymore. The difference seems to be how the labels are initialized. When added as an `Entity` the bug doesn't happen. When added via a `LabelCollection` it happens.
Unfortunately I currently don't have the capacity to look into this again, because it doesn't affect us directly.

@ABoyCDog: Maybe you can use the workaround of creating every label as an `Entity` until this bug is fixed?  
See this example: [Example Sandcastle](https://sandcastle.cesium.com/#c=dVNfb9owEP8qp7w0SJEZ0x6mLKCWiAnUTFQi6l4iTca5goWxI9sJpRPffU5CuhRoXuK735+73DlMSWOh4nhADWOQeIAYDS/35LnJ+ZnHmjhW0lIuUWfe4EcmWaMzDCU6WasnTejADt5SmYtL3xXTiHJVUIazCqWdtyS/ERNGZUXNoDE5y4lBu5BFaR+Y5Ur6Pg5gPIG/mQRo6xSc7Z6U4TXsirVO/aTvwvOxtoauYVfeJdEQmud+YwjQEcMPtkELCrpGEcKZWj8WX20Idym6PpIavQv+g2arDiFYXWIv+cKFiJVQOuxG0kRkmjzEjxfiKWW7jValzK9s1u/QLbPf80U66xd16wsh80bfilfYK6lMvYDMu2n45MbB5QbC/t5iqq07UfnVH30PYPRl0NNuleZv9Q0RS803XL53M78ASDL7mfaEFWrL2ZXs+UOaTJdpuvx1lp2a96le5Cn47FalxwKbWn/iZBE/1mQv8CJjjwInXfl7vi+UtlBq4RMytLgvBHUfOVyXbIeWMGPa6wIQDfvSKOcV8Hx84+cAJqgxDnkphVjxNzfjSTR0/CupULSe8tKNQNBjTduOJkmbJIREQxfeVlqlxJrqC+d/)

**Comment by ABoyCDog** [comment]
Copy that, thanks for that. @UniquePanda 
Acturely, I did solve it via creating the label as an Entity.
But keep watching, thanks again.

**Comment by ggetz** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/11293.
