### ISSUE TITLE
No way to detect if a Model has animations associated with it

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#11172]
Previously, `Model.gltf` could be used to determine if a model has animations associated with it, as well as a number of other bits of useful information. Since we removed these properties, it's now impossible to detect if a model has animations.

This is important for use cases where you may be writing a generic loader/viewer for model files. You may want to show additional information, such as the list of animations and enabling a user to play them.

**Comment by ggetz** [comment]
Thanks @mramato. Just confirm my understanding, you are looking for something like `model.gltf.animations` to return a list of animation indices so that they can be played with 

```
model.activeAnimations.add({
              index: 0,
             ....
            });
```

Is that correct?

**Comment by javagl** [comment]
A few cents:

> a list of animation indices

I think that list would only be the range `[0,numAnimations)`, with `numAnimations` being the information that is sufficient for running a particular one. But looking at the [examples for `add`](https://cesium.com/learn/cesiumjs/ref-doc/ModelAnimationCollection.html#add), there also seems to be the option to add an animation _by name_. 

In view of

>  show additional information, such as the list of animations and enabling a user to play them.

one could consider different options for the information that is supposed to be exposed here. Specifically: The animation name might not be known at compile-time, and it might be desirable to allow users to select animations (from a UI component) based on their _name_. 

(I don't know what `model.sceneGraph.components.animations` actually is. If these are just the glTF `animation` objects, then they may not have a name. Otherwise, one could consider to offer `getAnimationNames() { return model.sceneGraph.components.animations.map(a => a.name); }`, returing the names, and with that (implicitly) the `numAnimations` that determines the valid _indices_. Whether or not there is further information that is worth exposing (like `startTimeS` or `durationS`) has to be considered)

**Comment by j9liu** [comment]
`ModelAnimationCollection` assumes the user knows exactly what animations are in the model, and only contains the active animations (i.e. animations the user has actually added). We could expand the API so that it reports how many animations there actually are, e.g. `model.activeAnimations.totalAnimationsInGltf`, though that makes the name `activeAnimations` confusing.

But this issue raises a question of scalability. We removed `model.gltf` because the new `Model` implementation converts the glTF into the `ModelComponent` system. We didn't consider the importance of making the original glTF accessible to the user. So in the future, if it seems like we'll need more information from the glTF, we may require a way to expose or retrieve the original glTF contents.

**Comment by mramato** [comment]
> So in the future, if it seems like we'll need more information from the glTF, we may require a way to expose or retrieve the original glTF contents.

One possible short-term option here would be to have an option to the constructor that simply keeps the glTF after loading. Then the client can access the glTF just like it did previously. You could also augment this with a way to "clear" the glTF when the client is done with it to avoid keeping it in memory for the lifetime of the model.

Another option (that I think I like better) would be to have a callback/event that simply passes the glTF as part of the load process so the client can do whatever it wants with it.

I don't know enough about the refactored Model class to know how easy/hard the above is, but could be a great compromise.
