### ISSUE TITLE
viewer.zoomTo gltf model is not working

### ISSUE THREAD

**Issue by xrui94** [CesiumGS/cesium#11239]
OS: Windows 11,
Browser: Microsoft Edge 112.0.1722.4
Cesium version: 1.99.0

viewer.zoomTo( ) gltf model is not working when loading model by Cesium.Model.fromGltf( ) API, but viewer.entities.add( ) is working. This is my code bellow, there is no any runtime error.

```js
const model = Cesium.Model.fromGltf({ url: source.url });

// viewer.zoomTo(model);

// The code above is not working, so I try new code bellow according to the ref: https://community.cesium.com/t/zoom-to-model-added-as-primitive/8478
model.readyPromise.then(primitive => {
    this._viewer.zoomTo(
        primitive,
        new Cesium.HeadingPitchRange(
            heading,
            pitch,
            primitive.boundingSphere.radius * 2.0)
    );
});
```
By the way, it seems that all APIs related to camera (e.g. viewer.camera.lookAt( ), viewer.camera.viewBoundingSphere, ...) will be modified viewer.scene.screen.SpaceCameraController, however, I custom myself's viewer.scene.screen.SpaceCameraController

**Comment by ggetz** [comment]
Hi there @xrui94, 

This is not a bug. [`zoomTo`](https://cesium.com/learn/cesiumjs/ref-doc/Viewer.html?classFilter=Viewer#zoomTo) works with model entities, but not an instance of `Model` or a `primitive` itself. The code you provided work by accident rather than by design.

I would suggestion waiting fro the model to be ready, the using `Camera.viewBoundingSphere` on `model.boundingSphere`.

Thanks!
