### ISSUE TITLE
Geocoder input conversion weirdness

### ISSUE THREAD

**Issue by tdriver** [CesiumGS/cesium#11376]
Sandcastle example: not necessary

Browser: Edge

Operating System: Win 10
When I paste in the coordinates (from a search) for the Titanic, I found: 41°43′32″N 49°56′49″W, into the geocoder window, it automatically converts this to a lat/lon pair in decimal degrees. (nice!)
![image](https://github.com/CesiumGS/cesium/assets/3452278/ac9652f3-094f-4ada-8f84-8fe74a382686)
When I press enter it goes to that correct lat lon.
If I press enter again on those coordinates (without pasting them again), it goes to the location represented by lat =lon and lon = lat.
This seems like a bug to me.

**Comment by ggetz** [comment]
Thanks for the report @tdriver!

For some context, the geocoding search and autocomplete results are driven by Cesium ion, which is currently a wrapper around [Bing Maps Geocoding](https://learn.microsoft.com/en-us/bingmaps/rest-services/locations/).

[Both lat,lon and lon,lat are accepted orders of coordinate pairs](https://observablehq.com/@clhenrick/lat-lon-or-lon-lat). What I think is happening is that the first result (since you've included the N and W specifiers) goes to the lat/lon location. However, the second time, without the additional context, the geocoding search assumes lon/lat.

Since CesiumJS is simply passing the query along to Bing Maps, I'm not sure this is something we could easily fix without intercepting and parsing the query ourselves. Since we're unlikely to do so, I'm going to close this issue for the time being.

**Comment by tdriver** [comment]
Good to know! Thanks for checking into it.
