### ISSUE TITLE
Geocoding gives different results with or without whitespace

### ISSUE THREAD

**Issue by anne-gropler** [CesiumGS/cesium#11433]
Sandcastle example: no code added to sandcastle, version 1.107.1

Browser: Chrome

Operating System: Windows

When using the geosearch, I noticed that using a whitespace after the comma creates different results. E.g., `52, 13` and `52,13`. It seems that the comma influences whether those values are interpreted as latitude-longitude or longitude-latitude. See gif below.

I'd expect that such a small detail wouldn't matter, or at least that it's documented, e.g., the suggestions list `52,13 (long, lat)` and `52, 13 (lat, long)`. Or instead maybe "N, E"./"E, N".

![castlelatlong](https://github.com/CesiumGS/cesium/assets/5690856/808637ce-e972-4b49-a099-e30588a44216)

**Comment by ggetz** [comment]
Hi @anne-gropler, thanks for the report. This is due to conflicting suggestions from Cesium ion's geocoder service and CesiumJS's internal `CartographicGeocoderService`. Since Cesium ion's geocoder service supports latitude and longitude pairs directly, we'll remove the redundant `CartographicGeocoderService` by default in https://github.com/CesiumGS/cesium/pull/11435.
