### ISSUE TITLE
cesium error

### ISSUE THREAD

**Issue by Darktranquility** [CesiumGS/cesium#11461]
Hi, I have a question : 
 
<img width="1299" alt="dfc3f1c2a7a547178bfb863a38a2244" src="https://github.com/CesiumGS/cesium/assets/53104681/eb2ecfb4-23ec-4138-bcd4-a6f933ca5bcb">

In Google Browser encountered this problem, what is the cause of this problem, how to solve

**Comment by ggetz** [comment]
Hi @Darktranquility, you'll need to enable WebGL in order to use CesiumJS.

[get.webgl.org](https://get.webgl.org/troubleshooting/) is a good resource to try. 

I'm going to close this issue since it's not specific to CesiumJS, but feel free to ask further questions on the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
