### ISSUE TITLE
Calculation method of UV direction of polygon material

### ISSUE THREAD

**Issue by yangvictor** [CesiumGS/cesium#11491]
When I draw a polygon, the texture map direction is sometimes wrong, how can I confirm the UV coordinate direction so that I can calculate the correct material repeat value.
      I drew two polygons with the same parameters, but their texture direction is different:

https://sandcastle.cesium.com/index.html#c=3VVda9swFP0rwk8JpIr1LbtpGYTBBh0rbOxlHsW1tcSbbQVZaZuW/vddx85IO3vkdSMQZOncc6Src+zM1o1Hd4W5Nw5doNrco6Vpim2Fv+znJkmQ7Z+XtvZpURuXBNPzpO5+2b7amwe/dSa/tuVuZWug6fiwqX3hC9PgNM8nT0mNUJ1WJm4HCCXB2wfvtrnJfxOgTc9wX/g12hh3trENMMDM2hSrtW9QWuco2zbeVocqlFnr8qJOvWmSYNaS9zQxeuqk1oVxqcvWuxh97Wb6hW4fD0kQozNCJOVcYxYJRgTVRM+OQbsWxKWgRLWYSCslKHsBedxDaCi4irAQggOYdoDn2d90WchDHCmiJacyFIO6sCWGiWYRD4mQg7qypWFMSCp1dJIwjXSENRBSLhgb0WUa9sZoyOBgw7qEUKw51UxGnIqXwqPSLFKYUi7hNJqIkV5HHM4MF6KoosO9FoLiENjgXpQ8aPcOq7/NDqP2Hwx13fvp3d5OMQIDmh5TgYFckZbxcQjeV+nKfOhXrp0FCr+b9Ccq2sU4CTCe74fNvKu6ubIre7O0pXX4x2bVmxIhZzYm9fER/TJ14NoiremEz0g4fZ7uoW3vnruUDSaM/sMRY5pjKWEgtGJjEWtdqSKlacjFyLVLsHpISZvU05yuwG5MSU5kKNWY1du9cc4gwSNOpwSHGl4BgsjTZEOFNWNMK8nk8HEJh61BAqmMNCdjugpLzgghENRTA0YEphJeLjSC98pIpxnFCnrDCfRmrNMSLgOuhIP4f5evpO6D9Ght9dlOXsVqeo6CWbBo/K40l4f2vCmqjXUebV05gb15U23KNhrz223203icNU1L3kIX8+PSRV7coSK/GPimoqxMmwZWvm/L8lPxaJLgcjEH/B+lpU0hiquPd8aV6a6FrcnlVTeJMV7M4XG40ltb3qbuFfMv

**Comment by ggetz** [comment]
I believe this is because the rotation is defined relative to the normal for polygons with `perPositionHeight`. You can set the [`stRotation`](https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html?classFilter=polygonGra#stRotation).property on one to ensure the texture repeat matches, as in [this example](https://sandcastle.cesium.com/index.html#c=1VVdb9MwFP0rVp46qbjxt511E9I0CSTQJkDwQNCUJaYNpHHluNu6af+d6zaFMZpp4glUqXLsc8+xb85xStd2AV3V9tp6dIRae41ObFevFvjjZm6UJ+Xm+cS1oahb6/Pk4DBv46/c1AZ7E1beVueuWc9cCyRbNmzbUIfadrioqtFd3iLUFgubxQFCeXJ6E/yqstVPArTsGa7rMEdL618sXQcMMDO39WweOlS0FSpXXXCLXRUqnfNV3RbBdnkyjuQ9TYbutlLz2vrCl/N1hj5vZ/qF7T5u8iRDLwiRlHONmRGMCKqJHj8ErSOIS0GJihijlRKU/Qa53UBoKrgyWAjBAUy3gPvxU7os5Sk2imjJqUzFXl3YEsNEM8NTIuReXRlpGBOSSm2eJUyNNlgDIeWCsQFdpmFvjKYMDrZflxCKNaeaScOp+F14UJoZhSnlEk6jiRjoteFwZnghiiq6v9dCUJwCG7wXJXfavcPaL+PdKP6Doc57P73a2ClDYEDbYxZgIF8XTfYwAq8Xxcy+7VfOvQOKsB71J6rjYpYnGE82w26yrbp442bu4sQ1zuNvy1lvSoS8XdoiZA/oTwoPrq2Llo74mKQH9wcbaOzd/TZjexNG/4eIPfnyTaqwZoxpJZncHzTClcJgTCqN5mTAeFRhyRkhBPz7XN8RgamEzFEDcRvwHaNYUaM4oUwN+E5KrCGyhoP4s7LGNMdSwkBoxYYul5hHZZSmKRdDwhDylJJ4Rz0v49BHOIbkRKZSDYU87o1zBnfXUKsJTjVcfoLIX7J/E7QuvHOhiIvZLgeQsDk+f31x9vH03cWHT2f/dCTzts/erXOLD270KIkHhygZJ9MurBt7vGvly3qxdD6glW9GsLdgF8smpmlyuSq/24DLrovkETqdPCydVvUVqqujPR9hVDZF18HK11XTvK9vbZ4cTyeA/6O0cQWkd3Z2ZX1TrCNsTo7fbCcxxtMJPO6vDM41l4V/xPwD).

**Comment by yangvictor** [comment]
> I believe this is because the rotation is defined relative to the normal for polygons with `perPositionHeight`. You can set the [`stRotation`](https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html?classFilter=polygonGra#stRotation).property on one to ensure the texture repeat matches, as in [this example](https://sandcastle.cesium.com/index.html#c=1VVdb9MwFP0rVp46qbjxt511E9I0CSTQJkDwQNCUJaYNpHHluNu6af+d6zaFMZpp4glUqXLsc8+xb85xStd2AV3V9tp6dIRae41ObFevFvjjZm6UJ+Xm+cS1oahb6/Pk4DBv46/c1AZ7E1beVueuWc9cCyRbNmzbUIfadrioqtFd3iLUFgubxQFCeXJ6E/yqstVPArTsGa7rMEdL618sXQcMMDO39WweOlS0FSpXXXCLXRUqnfNV3RbBdnkyjuQ9TYbutlLz2vrCl/N1hj5vZ/qF7T5u8iRDLwiRlHONmRGMCKqJHj8ErSOIS0GJihijlRKU/Qa53UBoKrgyWAjBAUy3gPvxU7os5Sk2imjJqUzFXl3YEsNEM8NTIuReXRlpGBOSSm2eJUyNNlgDIeWCsQFdpmFvjKYMDrZflxCKNaeaScOp+F14UJoZhSnlEk6jiRjoteFwZnghiiq6v9dCUJwCG7wXJXfavcPaL+PdKP6Doc57P73a2ClDYEDbYxZgIF8XTfYwAq8Xxcy+7VfOvQOKsB71J6rjYpYnGE82w26yrbp442bu4sQ1zuNvy1lvSoS8XdoiZA/oTwoPrq2Llo74mKQH9wcbaOzd/TZjexNG/4eIPfnyTaqwZoxpJZncHzTClcJgTCqN5mTAeFRhyRkhBPz7XN8RgamEzFEDcRvwHaNYUaM4oUwN+E5KrCGyhoP4s7LGNMdSwkBoxYYul5hHZZSmKRdDwhDylJJ4Rz0v49BHOIbkRKZSDYU87o1zBnfXUKsJTjVcfoLIX7J/E7QuvHOhiIvZLgeQsDk+f31x9vH03cWHT2f/dCTzts/erXOLD270KIkHhygZJ9MurBt7vGvly3qxdD6glW9GsLdgF8smpmlyuSq/24DLrovkETqdPCydVvUVqqujPR9hVDZF18HK11XTvK9vbZ4cTyeA/6O0cQWkd3Z2ZX1TrCNsTo7fbCcxxtMJPO6vDM41l4V/xPwD).

Thank you for your response. How do I know when to rotate, or how can I calculate the normal for polygons with perPositionHeight.

**Comment by ggetz** [comment]
You may not need to use `perPositionHeight`, unless it is necessary for another reason.

The normal is calculated internally when creating the geometry. It's possible to access, but will require some knowledge of the rendering pipeline.
