### ISSUE TITLE
When I import DrawCommand, TypeScript prompts that Cesium does not export this method, but I checked the Cesium package, and it does indeed export DrawCommand

### ISSUE THREAD

**Issue by MyDataHouse** [CesiumGS/cesium#11521]
Exporting everything else works fine; if possible, please let me know the solution.
![image](https://github.com/CesiumGS/cesium/assets/105039275/20ab3aa4-d035-474d-a571-5939daf0750f)
![image](https://github.com/CesiumGS/cesium/assets/105039275/99a9c3f7-195a-44bf-bac9-c032b7d4c2f6)
cesium:1.109.0
pnpm:8.7.4
Typescript: 5.1.6

**Comment by ggetz** [comment]
Thanks for the report @MyDataHouse. 

This is because [`DrawCommand` is a private API](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Renderer/DrawCommand.js#L19), and therefore not typescript definitions are not generated for this class. 

Since this is not a supported use of the library, you'll need to ignore the error or write your own definition.
