### ISSUE TITLE
There are doubts about the document description

### ISSUE THREAD

**Issue by danchaotaiyang** [CesiumGS/cesium#11578]
I don't quite understand a paragraph in the following document
下面文档中的一段话，不是很理解
https://cesium.com/learn/cesiumjs-learn/cesiumjs-particle-systems/

_Some of these properties are dynamic. Notice that instead of using the available single color property scale, there is a startScale and endScale. These allow you to specify that the particle size transitions between the start and end scale over the course of the particle’s life. startColor and endColor work similarly._

what dose 'using the available single color property scale' mean?

**Comment by ggetz** [comment]
Instead of using `color` and interpreting it as a constant value over the particle's lifetime, the properties `startColor` and `endColor` are used. In this case, the color of the particle changes linearly over it's lifetime.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!

**Comment by danchaotaiyang** [comment]
> 不是将`color`其使用和解释为粒子生命周期内的常数值，而是使用属性`startColor`和。`endColor`在这种情况下，粒子的颜色在其生命周期内呈线性变化。

![image](https://github.com/CesiumGS/cesium/assets/13347321/ef22c6b6-e235-4331-aa5b-874d21966ba4)

I understand the meaning expressed in the documentation, but based on my understanding, I feel that the word "color" in this context may be redundant. In my opinion, the properties "color" and "scale" are separate.

我理解文档中表达的含义，但根据我的理解，我觉得在这个上下文中，“color”这个词可能是多余的。我认为，“color”和“scale”属性是独立的。

I really love Cesium, it has brought me a lot of expectations. I feel that the word 'big' doesn't accurately describe Cesium, it should be described as 'infinite'. I will continue to follow and learn about Cesium in the long term, and if I discover any issues, I will report them promptly. This is my way of giving back, and I'm more than happy to do so.

我非常喜欢Cesium，它给我带来了很多期许。我觉得“big”这个词描述Cesium不够准确，应该用“infinite”来形容。我会长期关注并学习Cesium，如果我发现任何问题，我会及时上报。这是我回报的方式，我非常乐意这样做。
