### ISSUE TITLE
Performance issues with model loading in multiple tilesets

### ISSUE THREAD

**Issue by tom0907** [CesiumGS/cesium#11622]
Hello everyone,
I am having issue with models in my tileset. This might be issue with my implementation or code, however I haven't found direct solution yet, so I assume this approach is either not commonly used, not implemented or I just overlooked something. 
When loading tileset with large amount objects (which all have same .glb model), every single model is requested from server individually, which creates large amount of network traffic and slows whole page down.
I tried to reference same model in multiple ways, eg. using browser cache to store model or embedding model directly into tileset JSON, but it still loads multiple instances of same model to memory. 
Most solutions online suggest using one big tile for every model, however I want to avoid this approach. I am attaching an example files which demonstrate my issue, it contains around 3k trees.

Example tileset, models and HTML page:
[example.zip](https://github.com/CesiumGS/cesium/files/13329570/example.zip)

Screenshot:
![image](https://github.com/CesiumGS/cesium/assets/57686247/d671a516-d242-4eba-a36b-f292f96cd01f)

Does this library have/ will have implementation for solving this issue ? It is possible my code is badly designed, and if so, I would love to get some recommendations on how to fix this behaviour.
Thank you for any answers or suggestions!

Browser: Chromium 116.0.5845.188 / Firefox 118.0.2
Operating System: Windows 10 22H2 / Ubuntu 22.04.3

**Comment by ggetz** [comment]
Hi there,

You'll likely want to using instancing in your tileset. Here's a [community forum discussion thread](https://community.cesium.com/t/most-basic-example-of-instanced-3d-model-using-glb/27549/3) on the topic.

Since this issue has more to do with the 3D Tiles data rather than CesiumJS, I'm going to close it.
CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. 

Thanks!
