### ISSUE TITLE
"An error occurred while rendering. Rendering has stopped." occurs when it's loading specific 3D Tiles

### ISSUE THREAD

**Issue by HideBa** [CesiumGS/cesium#11771]
### What happened?

I am working on the projet to visualize City Facility data in 3D Tiles data format.

Data conversion has been done with FME from CityGML to 3D Tiles data. 

I got this error.
![image](https://github.com/CesiumGS/cesium/assets/49897538/0bf5ddd3-8ba0-4ec2-ae1d-8fb83c2fcedd)

### Reproduction steps

1. Open the sandcastle
2. Load the 3D Tiles data
3. It cause this error
...

### Sandcastle example

https://sandcastle.cesium.com/#c=bVJdj9MwEPwrq4qHVmrtftJr6VWIguChFYgCT5F6W3ubGBw7sp2Wcrr/jpO04oBGUSLv7ExmZ8M5bNHARqUlacitjE/hCANJ2J/hfam0Jpdb2DBYE2pYa0xLYxmsNKGJXWUBaCRk1l84G+vSSlJEsqM5ZCEUc85Th0WmhGfxPkVVhblnJEsuMSDPyWfk2c9cJ0ZY4wMcFZ3IwT0YOsGKvCpz9q2utZOWqM8rawIqQy5pdV4lJjHBneExMQCNRFCaPIWogSdU4arSvEZvvzQwOzibf3U6ylZWffSKPtaj0+iw0DELLJkjQhcypuwF5WLKZ4PZZD/tHaY0643FRPTuhBz3cDSWh7F4ub87DPhgMuj3d0apNI7Z85naDfvD4W4ka3O7wc4Wu4Mz/OKVfffWNOPAJQLmBRlihVO5CuoYU0Ip25f+G40Cc3LIqtobWxqpTLotMnJ05bD9X+Xu84Q/EFbIJxVE9hlNSu1+F3p9NulCv1N97AkERgza5Jx1nT9xW01M27T98K4CQNta6LqDObx4rBlPD7VKYlrd1sKHs6ZlpVBdr1VeWBegjLtgjAfK6/A935fiR7QtvG/GBVjw59SFVEdQ8v7GfwFCx3VF5FBqvVW/KGktFzz2/0e9GP54JKfxXLVlg+W6KTLGFjwebzODtXqP7h/l3w

### Environment

Browser:
CesiumJS Version: 1.112
Operating System: MacOS Ventura

**Comment by ggetz** [comment]
Hi there @HideBa.

To confirm your 3D Tiles data is valid, please run it through the [3d-tiles-validator](https://github.com/CesiumGS/3d-tiles-validator) and let us know the results. Thanks!

**Comment by javagl** [comment]
Unfortunately, the validator might not provide sooo much helpful information here. It will report _many_ errors, because the batch table binary in the B3DMs is not properly aligned. This error in the B3DM header causes it to not even attempt the validation of the GLB payload. It should probably be more gracious here, and at least _try_ to validate the GLB - I opened https://github.com/CesiumGS/3d-tiles-validator/issues/299 to track this.

Apparently, CesiumJS does not care about the invalid alignment. But what it _does_ care about is the validity of the GLB payload. And this is the crux here: The file `data/data77.b3dm` contains a GLB that is invalid. 

The glTF validator reports for this one:

> MESH_PRIMITIVE_TOO_FEW_TEXCOORDS	
> Material is incompatible with mesh primitive: Texture binding '/materials/8/pbrMetallicRoughness/baseColorTexture' needs 'TEXCOORD_0' attribute.	
> /meshes/0/primitives/8/material

So `data/data77.b3dm` contains a GLB where one primitive is missing texture coordinates.

(This could be fixed in various ways, and if necessary, I can provide further infos/support here, but ... it is not a CesiumJS issue)

**Comment by ggetz** [comment]
Thanks @javagl! I'm going to close this since it's not an issue, but please feel free to continue discussion.
