### ISSUE TITLE
Two node_modules directories need to be added to.gitignore

### ISSUE THREAD

**Issue by Hiwen** [CesiumGS/cesium#11947]
### What happened?

When I installed the dependency using 'npm install', I found that git changes have added a number of new entries in the node_modules directorys(packages/engine/node_modules and packages/widgets/node_modules). Obviously, these files don't need to be managed by git.
<img width="381" alt="gitignore error" src="https://github.com/CesiumGS/cesium/assets/13505993/dae237bd-10fa-4cdc-be35-6c74aba50c84">

I found a way to fix, just like this:
<img width="959" alt="gitigonre fix" src="https://github.com/CesiumGS/cesium/assets/13505993/a8c47e48-a178-4568-8266-cf6481c648e0">

Is there any one can fix this? Or by other ways to fix?

### Reproduction steps

1.npm install
2.check the git changes

### Environment

Browser: none
CesiumJS Version: 1.116
Operating System: windows 11

**Comment by ggetz** [comment]
Hi @Hiwen! Thanks for reporting this!

The way npm handles [workspaces](https://docs.npmjs.com/cli/v10/using-npm/workspaces) usually means that that all dependencies are installed at the root level `node_modules` directory, unless there are conflicting dependency versions.

Did you make any changes before installing? If you delete all `node_modules` directory and re-run `npm install` does it happen again?

I'm hesitant to make this change, as it usually is a signifier that something else went wrong. Making the suggested change would hide the issue instead of making it aparent.

**Comment by Hiwen** [comment]
@ggetz Thanks for your suggestion. When I delete all `node_modules`  and re-run `npm install,` I found git changes works very well. I used `cnpm install` cause the Original problem。

I think this Issue can be closed! And I'm really sorry for wasting time.
