### ISSUE TITLE
Cesium Install Fails on Gentoo @Playwright

### ISSUE THREAD

**Issue by jlpoolen** [CesiumGS/cesium#11941]
### What happened?

I'm trying to install Cesium on a Gentoo Linux system.  The install fails at Playwright.  

**I am able to install Playwright outside of the Cesium** install paradigm, see lines 7-9 of this Pastebin:  https://pastebin.com/EjEREg01

### Reproduction steps

1. git clone https://github.com/CesiumGS/cesium.git
2. cd cesium
3. npm install

### Sandcastle example

NA

### Environment

Browser: 
``` 
Firefox: 124.0.2 (64-bit)  
Chrome: Version 123.0.6312.122 (Official Build) (64-bit)
```
CesiumJS Version: 
```
(cesium) eos /home/jlpoole/cesium/cesium # git --no-pager log -1
commit 58bc5ac46d1884656973496942aef15fc08070c4 (HEAD -> main, origin/main, origin/HEAD)
Merge: a9765758a2 1b6f3cdd42
Author: Gabby Getz <gabby@cesium.com>
Date:   Wed Apr 17 13:38:54 2024 -0400

    Merge pull request #11939 from CesiumGS/remove-source-check-types
    
    Don't copy `.d.ts` files with other assets in build
(cesium) eos /home/jlpoole/cesium/cesium # 
```
Operating System:  **Gentoo Linux**  
```
Linux eos 6.6.13-gentoo-dist #1 SMP PREEMPT_DYNAMIC Fri Jan 26 12:14:04 PST 2024 x86_64 AMD Ryzen 7 5700U with Radeon Graphics AuthenticAMD GNU/Linux
```

**Comment by jjspace** [comment]
Thanks for the report @jlpoolen. As it says in your output it looks like this is a Playwright issue as you're system is not supported

> BEWARE: your OS is not officially supported by Playwright; installing dependencies for ubuntu20.04-x64 as a fallback.

This means it falls back to `apt-get` which you do not seem to have.
Their own [system requirements](https://playwright.dev/docs/intro#system-requirements) list Debian only for linux

> Debian 11, Debian 12, Ubuntu 20.04 or Ubuntu 22.04, with x86-64 or arm64 architecture

If you can confirm playwright works correctly on your system in another project we can look into why it might not in CesiumJS but otherwise I would recommend opening an issue in the [playwright repo](https://github.com/microsoft/playwright) for Gentoo support.

All of that said, if you just wish to _use_ CesiumJS you don't need to clone the repo and can just [install from npm](https://github.com/CesiumGS/cesium#npm--yarn). If you're cloning the repo to contribute that's awesome! We are always happy to review community PRs if you find a fix for this and would like to improve our code for a wider range of developers feel free to [open an PR](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#opening-a-pull-request).

**Comment by jlpoolen** [comment]
I ended up using a Debian VM and successfully installed cesium.  If you know of a project that uses Playwright, I could try and see if my installation of Playwright works.  Playwright is a new project to me.  The problem is that if Playwright does not install, then the cesium install script halts.  Maybe a work-around would be like a configuration test and if Playwright is found on the system, then the install step is bypassed and cesium's install proceeds?

As far as I am concerned, I've logged the issue here to alert other potential Gentoo users (I may be the first to try Cesium on Gentoo in the last 5 years) and my work-around was to switch over to a Debian machine.  You can close this issue unless you have test for Playwright that doesn't require me to do much except install something which depends on Playwright and is stable.

Thank you for your considered response.

**Comment by ggetz** [comment]
Thanks @jlpoolen. Feel free to continue conversation in this thread, but I'm going to go ahead and close the issue.
