### ISSUE TITLE
When using polygon to draw an arch, it will collapse.

### ISSUE THREAD

**Issue by sunqlPeanut** [CesiumGS/cesium#11981]
### What happened?

1.I want to draw an arch that doesn't collapse.

### Reproduction steps

1.
2.
3.
...

### Sandcastle example

https://sandcastle.cesium.com/#c=jZNRa9swEMe/yuEnBxI5bbouSd2wzHsYrHSFjUGp96DK11hMlowkJ7il372yrbAkTYptMLq73/90h++YksbCmuMGNVyDxA0kaHhVkD+tL0wD1tqJkpZyiToNBlepTCVrlaym8k6JeqWkk3d5CErLLUdDaJaFL6kEkLTAOaRB4nBYo7acUQGlF264zaFEPSqVcULnyZGvcmuAygxUZYW7OA2GTSavmUObFyDnqKlmeT3fFp5Qbd2Jygl50qr4hiuNaJZa0/p7lzZ86LQAo9mYjIdb6+Jsx9gNjKazU9j52D176PQUevEO/dwfvexfwKc+LR1yk5OtX57Czj/uZ/JhP9P+6Kx3Aft/83hLfwf+4Abuzs9bNxdzsLpCHy2oRc2p+D9WSihNkvvlrSf8XO6pvK9lD5Rfb5bJjxZ7dd/Xboma1y/Ns1LFbxUerNDgCoJhEBtbC1xsm/nCi1JpC5UWISGRxaIUrlwTPVbsH1rCjGnSN2gc7UrjjK+BZ9dHlhqYoMa4yFMlxC/+7PZtEUeOfycVimZcrn66NRa0brD8bHHTOQkhceTM40qrlHik+iDzGw

### Environment

Browser:
CesiumJS Version:
Operating System:

**Comment by sunqlPeanut** [comment]
![polygon](https://github.com/CesiumGS/cesium/assets/119641376/b19c1844-097d-4a8b-9f29-e31f5efe2392)

**Comment by ggetz** [comment]
Hi @sunqlPeanut,

The reason for this is detailed [in this comment](https://github.com/CesiumGS/cesium/issues/5203#issuecomment-293661265). I would recommend either revising the list of position such the arch is constructed of 3 coplanar polygons instead of one. Or perhaps using a glTF model if that suits your workflow.

Thanks!
