### ISSUE TITLE
 Support For PBF

### ISSUE THREAD

**Issue by cavencj** [CesiumGS/cesium#11980]
### Feature

Any plans to support pbf vector tile data?

**Comment by ggetz** [comment]
Hi @cavencj, are you referring to [protobuf](https://github.com/protocolbuffers/protobuf) specifically, or mapbox vector tiles more generally?

**Comment by cavencj** [comment]
@ggetz Yes, it's mapbox vector tiles.

**Comment by syzdev** [comment]
This feature depends on `maplibre-gl`, which may be a burden for Cesium.

**Comment by syzdev** [comment]
CC https://github.com/CesiumGS/cesium/issues/2132

**Comment by ggetz** [comment]
There is a community implementation of MVT in CesiumJS in the issue @syzdev linked. (Thanks @syzdev!) At least in the near future, we don't have plans to bring this into the main branch of CesiumJS since, as @syzdev mentioned, there's a sizable dependency.

I'm going to close this for now given there are no near-term plans. But support is not completely out of the question.

**Comment by markchagers** [comment]
We would really like to see support for PBF tiles in cesiumjs.
