### ISSUE TITLE
protobufjs new version 7.3.1 delete dist dir, cesium run error.

### ISSUE THREAD

**Issue by FrozenJun** [CesiumGS/cesium#12034]
### What happened?

I installed Cesium in the new Vite project,
when pnpm dev send an error: 
Could not resolve "protobufjs/dist/minimal/protobuf.js"
  ../../node_modules/.pnpm/@cesium+engine@9.2.0/node_modules/@cesium/engine/Source/Core/GoogleEarthEnterpriseMetadata.js:1:26:
      1 │ ...rt * as protobuf from "protobufjs/dist/minimal/protobuf.js";

I found that @cesium/engine depends on protobufjs: ^7.1.0. There is a dist directory in this version, and there was also one until version 7.3.0, but the latest protobufjs 7.3.1 deleted the dist directory. I solved this problem by configuring
"resolutions": {
    "protobufjs": "7.3.0"
} 
in package.json, but it would be better to lock the protobufjs version to solve this problem.

### Reproduction steps

1. pnpm i cesium
2. pnpm dev
3. show error
...

### Environment

Browser: chrome@latest
CesiumJS Version: 1.118.1
Operating System: Windows11

**Comment by s3xysteak** [comment]
It also happened in `v1.118.2` 😭 .

**Comment by claustres** [comment]
The error can appear as well in previous version of Cesium, e.g. 115. As far as I can see the problem is not related to the Cesium version but the fact that it does not use a `.lock` file for dependencies so that this [specification](https://github.com/CesiumGS/cesium/blob/main/packages/engine/package.json#L50) will allow to install a newer version of protobufjs if available. The trick provided by @FrozenJun is the way to go unless Cesium uses npm lock files.

**Comment by FrozenJun** [comment]
protobufjs7.3.2 version fixes this problem，it`s over now

**Comment by cfairbanks** [comment]
protobufjs 7.3.3 looks to have re-introduced this bug by removing the dist directory again.

https://cdn.jsdelivr.net/npm/protobufjs@7.3.3/

**Comment by stevethewright** [comment]
Can confirm this is now happening on Cesium Version v1.120 due to protobufjs removing the dist folder in v7.3.3.
