### ISSUE TITLE
I have a question about Polygon's textureCoordinates (Irregular vertical plane)

### ISSUE THREAD

**Issue by yjf-3** [CesiumGS/cesium#12039]
### What happened?

I noticed that flipping its positions sometimes yields the correct result, but I don't know when it's necessary to flip it(Irregular vertical plane)

### Reproduction steps

1.
2.
3.
...

### Environment

Browser:
CesiumJS Version:cesium@1.99
Operating System:any

**Comment by ggetz** [comment]
Hi there,

I think the root of this issue may be that polygons are design to be tangent to the ellipsoid surface rather than perpendicular. I would suggest a billboard or possibly a Wall Geometry for your use case.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
