### ISSUE TITLE
Bugs on the Polygon textureCoordinates attribute

### ISSUE THREAD

**Issue by yjf-3** [CesiumGS/cesium#12032]
### What happened?

I calculated the textureCoordinates property of Polygon, but the texture is incorrect. I reversed the positions array of textureCoordinates and the texture is normal. I want to know why this is because, in theory, The result obtained from an array without inversion is correct. But now it's the opposite.Is there a way to identify whether it is necessary to reverse t the positions array of textureCoordinates .thanks

### Reproduction steps

1.http://localhost:8088/Apps/Sandcastle/index.html#c=lZVbj+I2FMe/isUTVIzjaxyzMGpFK7VSVx2pVV/KPngTL7hNYuQYZtlqv/ueXIAMO7OXgIRjn9/f9rmR+7qJ6Ojsow1ohWr7iNa2cYcK/93NTTeTvHtf+zoaV9uwmcxeberSRmRCMKcV+mdTo+G5jsZKaxMijEzNpohgLSmhOtNUMqU0ncNUpjTJiOKE0JSpjM3mV6HndUiLaSIY01xIpVPBiRphL1BoTi5GL5jcng8QTATXLCNEKSkZIaPzPS/SXYoImeoMQMFSuBmjcnam3oADk6RzHw72aENjp7NXSRJ3rkH5ztRbi3xdnsD+aAKqTLTBmfJpfH6rzNa+HpYegt/bEE/T/6+eSxL0BXx9aKKvvirSPq41WqDNBOMEvq7aJvSO4n/3281k/sQUtgx2b01cvOxfwtAPg9Wh89PoffZ047PWC14mc0qeEB/Pmbn3ro5kdctw/C746me7DdY2U4TuKIf9QQXSYkzSbyBpS96C7Fu3HIGFa44r9DkH89HUuZ32l5n3G4yow9cp1lO0pfKu0qN9Hw/BFg++PG19DTnR1z62dXTR2QabougToDaVXfTu3Ux+eR/DobDFRQAu3Cs8urhDkDd3e9+AAszsrNvuYoNMXaC8S7MzhXLvQ+FqSLhmyJ1BZoGGpNs5G0zId6cF+qIvf2qr59d+pym0oE1NqcCMgH815xnUqUhhA8awIlpJDqXIOKFUwiSXGiuqoD7TLJOZVGJ+wSnUPOVSScKuOMkUgbVMtoY8hQhqKZiQkmSCp98FixRLokWmldCKsmz+XQcXCtNUg3yaKq0pH9E0hY4jUhiM6JRTyTlYn2GdUsJERlKeKtF7/M25nQ1BWl9jdIlKG6c+us2i61sD8nH4hfg/DAZ9TBYI8sX2q73JuQ0tLqNutVXo6rb9DLn4wfvqLz+9yczWaDKfLJt4Ku39+Vw/umrvQ0SHUE6hOUVb7cv26MnbQ/6fjThvOrA1XSZjdFm4I3LF6pk/OJSXpmlg5d2hLP90H+xmcr9MwP4ztPQGXLX9A3p4aU6t2Y7e/95PYoyXCbw+T0bvy7cm3Ch/Ag
2.Open comment code : array. reverse()

### Environment

Browser:
CesiumJS Version: cesium@1.99
Operating System:

**Comment by yjf-3** [comment]
//

**Comment by ggetz** [comment]
Hi there, 

I think the root of this issue may be that polygons are design to be tangent to the ellipsoid surface rather than perpendicular. I would suggest a billboard or possibly a Wall Geometry for your use case.

CesiumJS is a big project, so we use GitHub for feature requests and bug tracking exclusively. In the future, please take any questions to the [Cesium Forum](https://community.cesium.com/) where there are members of the community and developers from the team who can help. Thanks!
