### ISSUE TITLE
Add support for rotation data while creating an asset using ION API

### ISSUE THREAD

**Issue by oussamabonnor1** [CesiumGS/cesium#12135]
### Feature

It would be useful to be able to set the orientation offset of a 3D Capture model upon it's upload/creation using the API instead of doing it manually via the ION settings panel.

The position can already be added here https://cesium.com/learn/ion/rest-api/#operation/postAssets

![image](https://github.com/user-attachments/assets/9c50bcb2-e1fb-4a49-ba66-b66d8763cde9)

Adding rotation as well would be very helpful.

Thanks!

**Comment by ggetz** [comment]
Hi @oussamabonnor1, this repo is for tracking CesiumJS issues and requests only. Since your request has to do with the Cesium ion REST API, I would suggest adding the request to https://community.cesium.com/c/cesium-ion/9 instead. It will get better visibility from the Cesium ion devs there.

Thanks!
