### ISSUE TITLE
Mouse event function registered by ScreenSpaceEventHandler(cavasElement) won't properly fire when specific keys are being held

### ISSUE THREAD

**Issue by Ron025** [CesiumGS/cesium#12235]
### What happened?

As simple as the title tells.

This issue does not happer if you switch to `cavasElement.addEventListener('mousedown', function(e){ ... })` instead.

Or, suspension on these keys are on purpose ?

### Reproduction steps

1 Register mouse event such as _left_click_, _left_down_ or _left_up_ using `ScreenSpaceEventHandler(canvasElement).setInputAction()`

2 Press down and **hold** any key of _Ctrl_, _Shift_ or _Alt_

3 Click mouse's left button on map, the registered function won't be fired.

### Sandcastle example

https://sandcastle.cesium.com/#c=dY9Ba8MwDIX/ismlCRSbnpeGja5jg7IeUraLYbiOupk5crDllGzsv89JL2VrdZKe3veEtMNArDdwBM+WDOHIVhBMbPnLpOUy09O8ckjKIHiZFTcSJZ5Za+0BsO6UhnUPSI8KG5vYUywPGhC4VtirUPAA9IRdpDtNxmF+iDg1LIcRLdh3CieVcMpni1kh8Wd+7c5u6IBv1g+7t/vt63ORzbMy0GChksimujVt5zyx6G3OuSBoO6sIgthH/QnEdQjjM6O1FOdo2ZiemWZ54XumrQohbQ7R2tp8gcyqUiT/P9Q61Rh83/bgrRpG28ei2pxEznkp0niZJOfsXvk/yb8

### Environment

Browser: Chrome
CesiumJS Version: 1.121
Operating System: Windows 11

**Comment by jjspace** [comment]
This is by design. The event handlers require you to specify what modifiers need to be held down for an action and only trigger that handler when fired. When you hold `Ctrl`, `Shift` or `Alt` it's firing a different event handler. See this [sandcastle](https://sandcastle.cesium.com/#c=vVPRSsMwFP2V0Je1MFKmvtkVx9zYsDqwRV8KkqW3M5jdlCTtqOK/m3YgQ+eDMJan3HvPOfccQrhCY0kjYAeajAnCjkzBiHpLn/qen3u8r6cKLRMIOveC6xxzPICmXANgWjEOswbQLhgW0nH3stRwQKCcYcNMQA3YJVa1nXArFPpljf2F+NBRA/LhxC13tpQEKtXGH4wG3cbP4V/rsrYCmszm2cvt6vnh3O4u/uXuG3YH7VoxXfSYe1WIUjgz6WI5z86d4PKUCabZY3LuAFenDDBJ3AN4Qy8ytpUQ50j6cyO2ldKW1Fr6lIYWtpVkFky4rvkbWMqN6Ux00Cg8pEaFaIgoxkc+EuGSGeMmZS1lKt4h9+IodPhfVKlYIXCzakBL1naw11Gc7JuU0ih05XGmVUqumf6h/AU)

**Comment by Ron025** [comment]
> This is by design. The [event handlers](https://cesium.com/learn/cesiumjs/ref-doc/ScreenSpaceEventHandler.html#setInputAction) require you to specify what modifiers need to be held down for an action and only trigger that handler when fired. When you hold `Ctrl`, `Shift` or `Alt` it's firing a different event handler. See this [sandcastle](https://sandcastle.cesium.com/#c=vVPRSsMwFP2V0Je1MFKmvtkVx9zYsDqwRV8KkqW3M5jdlCTtqOK/m3YgQ+eDMJan3HvPOfccQrhCY0kjYAeajAnCjkzBiHpLn/qen3u8r6cKLRMIOveC6xxzPICmXANgWjEOswbQLhgW0nH3stRwQKCcYcNMQA3YJVa1nXArFPpljf2F+NBRA/LhxC13tpQEKtXGH4wG3cbP4V/rsrYCmszm2cvt6vnh3O4u/uXuG3YH7VoxXfSYe1WIUjgz6WI5z86d4PKUCabZY3LuAFenDDBJ3AN4Qy8ytpUQ50j6cyO2ldKW1Fr6lIYWtpVkFky4rvkbWMqN6Ux00Cg8pEaFaIgoxkc+EuGSGeMmZS1lKt4h9+IodPhfVKlYIXCzakBL1naw11Gc7JuU0ih05XGmVUqumf6h/AU)

Cool, thanks!
