### ISSUE TITLE
Gltf (compressed using Draco) loses material in cesium1.124, but works normally in cesium1.83

### ISSUE THREAD

**Issue by lvfeijian** [CesiumGS/cesium#12393]
`

      const viewer = new Cesium.Viewer("cesiumContainer");
      var position = Cesium.Cartesian3.fromDegrees(-75.152325, 39.94704, 500);
      var heading = Cesium.Math.toRadians(0);
      var pitch = Cesium.Math.toRadians(180);
      console.log(pitch, "pitch");
      var roll = Cesium.Math.toRadians(0);

      var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
      var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);
      const url = "./Draco/1-draco.glb";
      const entity = viewer.entities.add({
        position: position,
        orientation: orientation,
        model: {
          uri: url,
        },
      });
      viewer.trackedEntity = entity;
      // viewer.flyTo(entity)

`
Hello developer
Cesium loads Draco processed gltf in different versions, with lower versions functioning normally and higher versions having issues.

[1-draco.zip](https://github.com/user-attachments/files/18244975/1-draco.zip)

**Comment by javagl** [comment]
Trying to load the model will report
```
Failed to load glTF texture
Failed to load texture
Failed to load embedded image
Image format is not recognized
```

Examining the GLB will reveal that it contains a texture in BMP format (yeah, "Bitmap"). For some reason, older CesiumJS versions may have been more gracious here, and may have loaded that ~"because BMP can conveniently loaded by the browser anyhow". But this was never a valid glTF, and it's unlikely that this is considered to be an "issue" that will be "fixed".

Here's that GLB with the same texture as a PNG (1.5MB smaller, by the way)

[1-draco-fixed.zip](https://github.com/user-attachments/files/18246964/1-draco-fixed.zip)

(Bottom line: The issue is unrelated to Draco. The model is just invalid...)

**Comment by lvfeijian** [comment]
> Trying to load the model will report
> 
> ```
> Failed to load glTF texture
> Failed to load texture
> Failed to load embedded image
> Image format is not recognized
> ```
> 
> Examining the GLB will reveal that it contains a texture in BMP format (yeah, "Bitmap"). For some reason, older CesiumJS versions may have been more gracious here, and may have loaded that ~"because BMP can conveniently loaded by the browser anyhow". But this was never a valid glTF, and it's unlikely that this is considered to be an "issue" that will be "fixed".
> 
> Here's that GLB with the same texture as a PNG (1.5MB smaller, by the way)
> 
> [1-draco-fixed.zip](https://github.com/user-attachments/files/18246964/1-draco-fixed.zip)
> 
> (Bottom line: The issue is unrelated to Draco. The model is just invalid...)

Thank you for your reply
You are right, the texture of the original file is image/bpm,
I would like to ask a question, is it necessary for all gltf files to undergo verification by [gltf-validator](https://github.khronos.org/glTF-Validator/) before they can be previewed properly in cesium

**Comment by javagl** [comment]
> I would like to ask a question, is it necessary for all gltf files to undergo verification by [gltf-validator](https://github.khronos.org/glTF-Validator/) before they can be previewed properly in cesium

For CesiumJS (as well as all other glTF viewers), the _contract_ that is set up, based on the glTF specification and the validator, is the following:

1. When a glTF file complies to the specification - meaning that does not cause errors in the glTF-Validator - then CesiumJS (and any other glTF viewer) should be able to render it. If it can not render it, then this is a bug in the viewer, and should be brought up as an issue.
2. When a glTF file does not comply to the specification - meaning that it causes errors in the glTF-Validator - then no viewer is required to display it properly. The file simply **is not** a glTF file...

Both points come with disclaimers:

There may be corner cases when it comes to glTF extensions, or features that are currently not supported. One of the few examples in CesiumJS is that it currently does not support _sparse accessors_ - meaning that there can be cases where a _valid_ glTF can not be displayed properly in CesiumJS. But this specific example is already tracked in an issue.

Conversely, there may be glTF files that are "invalid" in one way or another. And in some cases, certain viewers (like CesiumJS) can still load and display such files. This depends on _what exactly_ is invalid about that file, and whether a certain viewer decides to "ignore" (or otherwise handle) invalid input data. But the point is: Nobody can _expect_ a viewer to display an invalid file.
