### ISSUE TITLE
z-fighting caused by overlapping polygons

### ISSUE THREAD

**Issue by aramk** [CesiumGS/cesium#1456]
I've been experiencing z-fighting:

![z-fighting](http://snag.gy/xorur.jpg)

I've been trying to resolve the issue like so:

```
var scene = this._widget.scene;
scene.farToNearRatio = 4; // Changed from 1000
```

This increases the number of frustums by a lot and this helps a bit, but doesn't eliminate the issue. It also results in less performance. Is there an easy solution to this that I'm missing? I've read up on other issues and pull requests, and even [this presentation](http://cesiumjs.org/massiveworlds/index.html#UsingMultipleFrustumsforMassiveWorlds) which helped understand the concepts.

My next attempt will be to create z offsets for the polygons and attempt to prevent them overlapping. This is somewhat naive though, so let me know if there's a better way :smiley:

**Comment by meenalpatil-2007** [comment]
![temp](https://cloud.githubusercontent.com/assets/4018123/19075309/fe382264-8a61-11e6-9737-65b27bac7338.png)

I am facing this issue when a click event listener is bound with the yellow polygon. And when tried with solution by @mramato, yellow polygon is completely immersed into blue polygon and no click event is triggered.

Can this issue be solved by adding a attribute like z-index? 
Looking forward for the solution :)

**Comment by pjcozzi** [comment]
@meenalpatil-2007 have you tried posting your question on the [Cesium forum](http://cesiumjs.org/forum.html)?  It will get more attention there, especially since this issue is closed.  Also, include an animation if possible to help diagnose.  A workaround may be to make the yellow mesh slightly smaller.

**Comment by meenalpatil-2007** [comment]
@pjcozzi, I have already posted a question in [cesium forum](https://groups.google.com/forum/embed/?place=forum/cesium-dev&showsearch=true&showpopout=true&hideforumtitle=true&fragments=true&parenturl=http%3A%2F%2Fcesiumjs.org%2Fforum.html#!searchin/cesium-dev/overlapping/cesium-dev/y1kPEhPUJ78/Ud-0yX1-BQAJ)
But no satisfying answer I got there. Could you please post answer there as you say this is closed issue?

Thanks :)

**Comment by burn123** [comment]
@mramato The sandcastle link doesn't have the .999 in there anymore, and if you do try to add it, you get a lot of intersecting parts of the polygons. Is there another way to fix this?

**Comment by hpinkos** [comment]
Hello @burn123,  you can disable order independent translucency by passing that option into the viewer:
```
var viewer = new Cesium.Viewer('cesiumContainer', {
    selectionIndicator : false,
    orderIndependentTranslucency: false,
    infoBox : false
}); 
```

That should make the polygons layer the way you want.

In the future, you should ask question like this on [the forum](https://groups.google.com/forum/#!forum/cesium-dev).
We use GitHub for tracking bugs and planning new features.  And since this issue is closed, I almost didn't see your question.
