### ISSUE TITLE
Official support for desktop Safari

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#1804]
Placeholder issue to track issues in Safari for consideration post 1.0.  WebGL will be on by default in Safari in OS X Yosemite (summer 2014).
- [ ]

**Comment by kring** [comment]
@mramato can you elaborate on the scoping bug?  I'm seeing some really weird behavior with Cesium's frustums in Safari 8.0.3 and I'm wondering if it might be a symptom of the same problem.  Details here if you're curious:
https://github.com/NICTA/nationalmap/pull/527

**Comment by mramato** [comment]
The place I've been able to reproduce it is in [createPropertyDescriptor.js](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/DataSources/createPropertyDescriptor.js#L12), basically `privateName` and `subscriptionName` from line 12 both end up pointing to the same value inside of the `set` method.  Safari seems to get confused or make a bad optimization and all of a sudden two totally different variables collapse into one.

I am able to reproduce it in a Jasmine spec (fails on Safari but no other browser), but any attempt at further simplification makes the problem go away.  Last I checked this specific problem was fixed in Safari nightly. (though I should check again to be sure).

I have no idea if it's related to your problem, but who knows.  I think Safari has a long way to go before it can run non-trivial WebGL apps.

**Comment by kring** [comment]
Thanks, Matt.  That's a pretty crazy bug.  I'm not sure if I'm seeing the same thing or not.  It's one of those awesome bugs where any attempt at debugging it makes the bug go away.  I'll try out the nightly build of Safari to see if that helps at all.

**Comment by speigg** [comment]
I'm seeing this bug too, and it seems to happen randomly. This happens on both desktop safari and mobile safari. I suggest modifying the changeProperty function to:

```javascript
    function createPropertyDescriptor(name, configurable, createPropertyCallback) {
        return createProperty(name, '_' + name, defaultValue(configurable, false), defaultValue(createPropertyCallback, createConstantProperty));
    }
```

And simply appending the 'Subscription' string inside the createProperty function...

**Comment by speigg** [comment]
So, I tried what I suggested above (moving all string concatenation into createProperty), and somehow Safari still managed to break it. I had to call `name.toString()` in order to make it work reliably:  

```javascript
function createProperty(name, configurable, createPropertyCallback) {
   var privateName =  '_' + name;
   var subscriptionName = '_' + name.toString() + 'Subscription';
   return {
       // ...
   }
}
```

**Comment by speigg** [comment]
In fact, using `name.toString` alone seems to be enough to make it work:
```javascript
    function createPropertyDescriptor(name, configurable, createPropertyCallback) {
        return createProperty(name, '_' + name, '_' + name.toString() + 'Subscription', defaultValue(configurable, false), defaultValue(createPropertyCallback, createConstantProperty));
    }
```
