### ISSUE TITLE
Make Entity API use custom ellipsoid

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#3543]
It looks like the Entity API only uses the default Ellipsoid.WGS84.  As a result, you can't really use it if you need a custom ellipsoid.  In this example, the polygon is hovering above the globe because the ellipsoid is smaller than earth:

``` javascript
var radius = 5e6;
var ellipsoid = new Cesium.Ellipsoid(radius, radius, radius);
var projection = new Cesium.GeographicProjection(ellipsoid);

var viewer = new Cesium.Viewer('cesiumContainer', {
    mapProjection: projection,
    baseLayerPicker: false,
    imageryProvider: new Cesium.BingMapsImageryProvider({
        url : '//dev.virtualearth.net',
        mapStyle : Cesium.BingMapsStyle.AERIAL,
        ellipsoid: ellipsoid
    })
});

var redPolygon = viewer.entities.add({
    name : 'Red polygon on surface',
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-115.0, 37.0,
                                                        -115.0, 32.0,
                                                        -107.0, 33.0,
                                                        -102.0, 31.0,
                                                        -102.0, 35.0]),
        material : Cesium.Color.RED
    }
});
```

**Comment by mramato** [comment]
The (simply by hacky) workaround for this is to actually modify `WGS84` at the start of your app so that it has the custom size, then just use the default everywhere.

It might actually be a decent real solution to have `Ellipsoid.default` in addition to `Ellipsoid.WGS84` and just have the former equal the latter by default.  Then we use `Ellipsoid.default` everywhere we currently use `Ellipsoid.WGS84`.

This seems way more elegant of a solution when you only have a single custom ellipsoid in an application.

**Comment by mramato** [comment]
The actual problem here is that all of the `XXXGeometryUpdater` objects use the default ellipsoid value rather than getting it from the scene.  Should be a straightforward fix, but I don't have the bandwidth to do it myself right now.

**Comment by ggetz** [comment]
Also brought up for CZML in https://github.com/CesiumGS/cesium/issues/11185.
