### ISSUE TITLE
Easy API to select a non-earth ellipsoid

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#4245]
Users on the forum want to use non-earth ellipsoids but it is unclear how they have to set it.

**Comment by emackey** [comment]
Oh, if only choosing an ellipsoid were so easy.  Unfortunately not so!  You must tell the `imageryProvider` and the `mapProjection` about your choice of ellipsoid.  The `CesiumWidget.globe` will automatically grab it from `scene.mapProjection` if it needs it.

In this demo, the hover text is Cartesian3 in meters, so you can see it's the Moon's radius and not the Earth.

```
// First, select your favorite ellipsoid.
var ellipsoid = Cesium.Ellipsoid.MOON;

var imagery = new Cesium.SingleTileImageryProvider({
    // Your imagery provider needs the ellipsoid.  Specify it here.
    ellipsoid: ellipsoid,
    url: Cesium.buildModuleUrl('Assets/Textures/moonSmall.jpg')
});

var viewer = new Cesium.Viewer('cesiumContainer', {
    // The CesiumWidget and the Globe get Ellipsoid from Scene.mapProjection.
    mapProjection: new Cesium.GeographicProjection(ellipsoid),
    // Don't forget your imagery provider that uses the ellipsoid.
    imageryProvider: imagery,
    // Set some other options too.
    selectionIndicator : false,
    infoBox : false,
    baseLayerPicker: false,
    geocoder: false,
    skyAtmosphere: false
});

var scene = viewer.scene;
var handler;

var entity = viewer.entities.add({
    label : {
        show : false
    }
});

handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
handler.setInputAction(function(movement) {
    var cartesian = viewer.camera.pickEllipsoid(movement.endPosition, scene.globe.ellipsoid);
    if (cartesian) {
        var cartographic = Cesium.Cartographic.fromCartesian(cartesian);
        var longitudeString = Cesium.Math.toDegrees(cartographic.longitude).toFixed(2);
        var latitudeString = Cesium.Math.toDegrees(cartographic.latitude).toFixed(2);

        entity.position = cartesian;
        entity.label.show = true;
        entity.label.text = '(' + cartesian.x.toFixed(0) + ', ' + cartesian.y.toFixed(0) +
            ', ' + cartesian.z.toFixed(0) + ')';
    } else {
        entity.label.show = false;
    }
}, Cesium.ScreenSpaceEventType.MOUSE_MOVE);
```

I vote to close this, or change it to a doc issue.

**Comment by hpinkos** [comment]
Thanks @emackey!  I updated this issue and labeled it `doc`

**Comment by mramato** [comment]
I think we could do a lot better codewise here.  My official recommendation for updating the ellipsoid is actually a hack'; simply set Ellipsoid.WGS84 to whatever ellipsoid values you want at the start of your app and then Cesium is guaranteed to use it everywhere.  For single-ellipsoid apps, this is by far the easiest way to do it.  Because of this, I think it might be worth introducing `Ellipsoid.Default` and just having that be WGS84 by default and use `Ellipsoid.Default` everywhere in Cesium.  Then my "hack" can become the official way to change the default ellipsoid and the only reason you would need t specify it otherwise is if you have multiple scenes with multiple ellipsoids in your app.

**Comment by mramato** [comment]
Of course there could be a flaw in my plan, but I'm not sure what it could be.

**Comment by emackey** [comment]
I find this hack tempting, but there are potential issues.  Cesium is already very reliant on the concept of a default ellipsoid, and uses WGS84 to initialize several scratch variables hidden in closures around the codebase (for example: [GeographicProjection](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.24/Source/Core/GeographicProjection.js#L34) is constructed and saved as scratch in [BoundingSphere](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.24/Source/Core/BoundingSphere.js#L219) and [RectangleGeometryLibrary](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.24/Source/Core/RectangleGeometryLibrary.js#L72).  Likewise, [EllipseGeometry](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.24/Source/Core/EllipseGeometry.js#L689) constructs one that gets saved in [CircleGeometry](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.24/Source/Core/CircleGeometry.js#L103-L107), even though the latter appears to be constructing a unit sphere and yet contains a hidden default reference to WGS84.  You can find these and more such examples by modifying WGS84 to be `null` in original source code, and then attempting to run the moon code above).

Resetting the default ellipsoid in user code, even if done before constructing a viewer, cannot happen in time to reset all of these pre-constructed scratch variables.  Specifying the ellipsoid manually, in each and every place it is needed, is currently the only way to have some hope that the factory default doesn't creep in anywhere... but I don't know of any way to enforce that with tests such that newly-added default ellipsoid references get detected somehow.  Perhaps we assign Ellipsoid.Default to be the unit sphere during startup, and then reset it to WGS84 just before handing off to user code?  That might force these issues to the surface, since any code holding onto a unit sphere would presumably be obviously wrong for the Earth.

I still have long-term hope of visualizing interplanetary missions in Cesium with multiple central bodies in one window.  We'll need to have a good way to avoid reliance on defaults for that.

**Comment by pjcozzi** [comment]
CC #4069

**Comment by OmarShehata** [comment]
Looks like the ground atmosphere has to be turned off for this to work now: `viewer.scene.globe.showGroundAtmosphere = false;` see https://github.com/AnalyticalGraphicsInc/cesium/issues/8000

**Comment by jumpjack** [comment]
news about multiple globes/ellipsoids for planets representation?
