### ISSUE TITLE
GroundPrimitives are broken in orthographic projection

### ISSUE THREAD

**Issue by bagnell** [CesiumGS/cesium#5110]
Most likely a clipping or depth clamping issue.

See https://github.com/AnalyticalGraphicsInc/cesium/pull/5021#issuecomment-281544461

**Comment by he-hesce** [comment]
Dear CesiumJS developers,

We think we are experiencing this issue. We have an in-house bespoke piece of software which is a tool developed in C++ and Qt5 for time-series analysis and visualization. We are working (slowly) since some years in enhancing this tool with state-of-the-art mapping. Due to Qt5’s very limited facility is this area (QtLocation is basically useless for interactivity), we have opted to develop a map widget using QtWebKit with CesiumJS as that would enable the interactivity with the map which the users require.

However, after some initial success in using our Natural Earth base layers and bespoke overlays, we ran into an issue when we try to plot primitives such as billboards (symbols), labels, and polylines (great-circle paths) on the flat surface (later on we will also plot ellipses, azimuths, and distance circles using ellipses and/or polylines primitives). Things look fine when we use the perspective projection but our users need to use the orthographic projection and that is when we run into an issue which looks like clipping at the horizon of the globe. For troubleshooting, we tried raising the height from zero meters to some thousand meters but the clipping issue is still there. We also tried both QtWebKit "5.5" shipping with EPEL-7 (for CentOS) and QtWebKit 5.212 shipping with EPEL-8 (for CentOS) and in Ubuntu 18.04 in case it was a WebGL issue but it appears in both the older and latest QtWebKit. We have tried CesiumJS from version 1.52 up to the latest 1.65 and they all experience the issue.

Two screenshots are attached showing both how it looks fine in perspective projection and how the billboards and polylines are not clipped when they are supposed to disappear behind the horizon in orthographic projection.

Is anyone looking at this issue and thinking of addressing it?

**Attachments:**

Perspective Projection:

![20200118-cesiumjs-perspective](https://user-images.githubusercontent.com/13648954/73591491-088fd700-44e7-11ea-8c55-20a852077bd7.png)

Orthographic Projection:

![20200118-cesiumjs-orthographic](https://user-images.githubusercontent.com/13648954/73591493-1180a880-44e7-11ea-98de-2ee84908b8b0.png)

**Comment by OmarShehata** [comment]
@he-hesce thanks for adding your debugging details to this issue. Would you be able to put together a [Sandcastle example](https://sandcastle.cesium.com/index.html?) showing this issue that you can share here?

**Comment by he-hesce** [comment]
Dear @OmarShehata,

I will take a look at it as soon as I find time and see what I can do in Sandcastle. Is it enough to attach the html file you get from Save As?

Cheers,

**Comment by he-hesce** [comment]
Dear @OmarShehata et al,

Please find attached a Sandcastle example. This can be pasted into the JavaScript code tab in the Hello World example. It only shows the issue with polylines but it also applies to other primitives as described above. Look for the non-clipping at the horizon.

Cheers,
HE

[sandcastle-orthographic-projection-horizon-clipping-issue.txt](https://github.com/CesiumGS/cesium/files/4239870/sandcastle-orthographic-projection-horizon-clipping-issue.txt)

**Comment by OmarShehata** [comment]
Thanks @he-hesce, I am able to reproduce this. Here's a [runnable Sandcastle of this issue](https://sandcastle.cesium.com/index.html#c=nVVtT9swEP4rVr8QUHFAY2LKClooFZpGaVfY+LBOyE2ujTfHjmwnVYb632c3LzQpRVvvi3PXe+58z925GZEoo7AEiS4QhyXqg6JpjL+vbc5BsFb7gmtCOciDLnqecmQkkeIXBJoKPqbBbwP3kJYpTPnq8OOUZyZsIljODKgvGCs9iY5UM894y8kpE8wY8HCUWJNXeV+92PBo7H/9NuhWCdf3xSoADjiRNKaaZqBwCEpLkY9ri0k/J0zBGxgJscjAZ8x5KzIJQ2dHiRZWA9tEYWsfihAYVkuqg+hBjKSOxEKSJKKBU4LXBCpqcfbOLbrGNAF74oW5lSQa+kRq40K4L4OKwRpf81d7vcNzKeJrWEgA5UtJcufH8fkJPukW0P+U47P3+0LP90banD/3gpZsDBijiRI0xI839x/ODstYrhsBXUTaQy98uK5pD08ZkVTnNZ1D02w88a8/+3f3T+PB5Ol6cDMZDEoMVOG9HQm7ryyLafV29+rPMvKShjry0GmpMiESr5jq0hKbiZCUMG9z1YalsRoPK2Y5aKCL1d2gUptiFUvNyOtmYCtzMjMgDz03qXePmrrOE/DauesBHqXaHg/GqdXClNO5kLHaSmAlEExIrzheab0oovYLr01tt/Njk8xKVi39yP2X8ta59iyq2lGr4atbv//ljStV3ys7tSszRDueosYzZYet0+30lM4ZXBYBPtE4EVKjVDIHY1dDnDBTjXJnqXmtNA7U+jnruRWoF9IM0fBi2mn9N0w7KGBEKfPLPGXsnv6Baeey5xr/BowJElK+GGUgGcmtS3R6eVsYMcY916jbKC0EmxG5EfEv) (you can press "share" at the top and get a sharable link).

**Comment by he-hesce** [comment]
Thanks @OmarShehata. I tried the share/copy button but I got nothing in my pastebuffer. I was using Safari so perhaps the page was blocked from writing to the pastebuffer/clipboard.

Fixing this in CesiumJS is beyond me so we would really appreciate the help from the Cesium community of developers as this is kind of a show stopper for us when (surface) primitives are not working properly with orthographic projection which is the one projection we need to use for scientific purposes.

**Comment by he-hesce** [comment]
Is there any company or self-employed developer out there who is able to fix this issue but is lacking time/compensation?

**Comment by sowo** [comment]
We're having the same problem and would highly appreciate this to be addressed.
Thank you

**Comment by he-hesce** [comment]
Is there nobody at the Cesium company using orthographic projection and/or interested in addressing this long-standing issue?

**Comment by OmarShehata** [comment]
@he-hesce as far as I am aware, orthographic projection in CesiumJS is less commonly used. We'd love to see this fixed but I don't have a timeline of when we'll be able to investigate.

If you or other WebGL developers from the community want to take a look and contribute a fix we'd be happy to review a PR.

**Comment by he-hesce** [comment]
@OmarShehata: Thanks for the update. My expertise is not in WebGL or the area of this bug :-/ so I am afraid I cannot help much resolving this clipping/frustum issue. Believe me, if I could fix it, there would already be a PR.

**Comment by IanLilleyT** [comment]
@he-hesce and @sowo Can you check if https://github.com/CesiumGS/cesium/pull/8854 fixes your problems? Thanks!

**Comment by he-hesce** [comment]
@IanLilleyT: Thanks for looking into this issue. I tried your patch but it doesn't seem to fix the issue we're having. I'm attaching a screenshot how it still looks when using your new code with Orthographic projection:

![20200515-cesiumjs-orthographic-1](https://user-images.githubusercontent.com/13648954/82023442-cea1a580-967d-11ea-989b-661672078590.png)

Here is the same "view" but with Perspective and you can see how the polylines (and billboards) are properly clipped behind the horizon:

![20200515-cesiumjs-perspective-1](https://user-images.githubusercontent.com/13648954/82023929-8636b780-967e-11ea-8b67-968c02e2afd2.png)

@OmarShehata helped me set up a Sandcastle example (see link in a comment above) which perhaps you can test with as well.

**Comment by OmarShehata** [comment]
@IanLilleyT Sandcastle [is here](https://sandcastle.cesium.com/index.html#c=nVVtT9swEP4rVr8QUHFAY2LKClooFZpGaVfY+LBOyE2ujTfHjmwnVYb632c3LzQpRVvvi3PXe+58z925GZEoo7AEiS4QhyXqg6JpjL+vbc5BsFb7gmtCOciDLnqecmQkkeIXBJoKPqbBbwP3kJYpTPnq8OOUZyZsIljODKgvGCs9iY5UM894y8kpE8wY8HCUWJNXeV+92PBo7H/9NuhWCdf3xSoADjiRNKaaZqBwCEpLkY9ri0k/J0zBGxgJscjAZ8x5KzIJQ2dHiRZWA9tEYWsfihAYVkuqg+hBjKSOxEKSJKKBU4LXBCpqcfbOLbrGNAF74oW5lSQa+kRq40K4L4OKwRpf81d7vcNzKeJrWEgA5UtJcufH8fkJPukW0P+U47P3+0LP90banD/3gpZsDBijiRI0xI839x/ODstYrhsBXUTaQy98uK5pD08ZkVTnNZ1D02w88a8/+3f3T+PB5Ol6cDMZDEoMVOG9HQm7ryyLafV29+rPMvKShjry0GmpMiESr5jq0hKbiZCUMG9z1YalsRoPK2Y5aKCL1d2gUptiFUvNyOtmYCtzMjMgDz03qXePmrrOE/DauesBHqXaHg/GqdXClNO5kLHaSmAlEExIrzheab0oovYLr01tt/Njk8xKVi39yP2X8ta59iyq2lGr4atbv//ljStV3ys7tSszRDueosYzZYet0+30lM4ZXBYBPtE4EVKjVDIHY1dDnDBTjXJnqXmtNA7U+jnruRWoF9IM0fBi2mn9N0w7KGBEKfPLPGXsnv6Baeey5xr/BowJElK+GGUgGcmtS3R6eVsYMcY916jbKC0EmxG5EfEv). Just rotate the globe a bit to get the line over the horizon as in the pictures.

**Comment by IanLilleyT** [comment]
Thanks! Looking into it now. It's looking like a depth plane issue.

**Comment by IanLilleyT** [comment]
It turns out the polyline issue we've been talking about is not related to ground primitives, which is why https://github.com/CesiumGS/cesium/pull/8854 didn't make a difference. Instead, it's related to a different recent PR: https://github.com/CesiumGS/cesium/pull/8850.

The problem was `View` was not updating correctly when switching to orthographic.

@he-hesce can you try https://github.com/CesiumGS/cesium/pull/8850 instead and see if it fixes the problem?

**Comment by he-hesce** [comment]
@IanLilleyT: Thanks for your continued effort on this plaguing issue. I tried Cesium-1.69.0-orthoCameraFixBounds34391.zip attached to #8850 but the horizon clipping issue is still there:

![20200515-cesiumjs-orthographic-2](https://user-images.githubusercontent.com/13648954/82073301-93789400-96c8-11ea-9e4c-37d8ee406bff.png)

**Comment by IanLilleyT** [comment]
hmm... does this [sandcastle](https://sandcastle.cesium.com/index.html#c=nVVtT9swEP4rVr8QUHFAY2LKClooFZpGaVfY+LBOyE2ujTfHjmwnVYb632c3LzQpRVvvi3PXe+58z925GZEoo7AEiS4QhyXqg6JpjL+vbc5BsFb7gmtCOciDLnqecmQkkeIXBJoKPqbBbwP3kJYpTPnq8OOUZyZsIljODKgvGCs9iY5UM894y8kpE8wY8HCUWJNXeV+92PBo7H/9NuhWCdf3xSoADjiRNKaaZqBwCEpLkY9ri0k/J0zBGxgJscjAZ8x5KzIJQ2dHiRZWA9tEYWsfihAYVkuqg+hBjKSOxEKSJKKBU4LXBCpqcfbOLbrGNAF74oW5lSQa+kRq40K4L4OKwRpf81d7vcNzKeJrWEgA5UtJcufH8fkJPukW0P+U47P3+0LP90banD/3gpZsDBijiRI0xI839x/ODstYrhsBXUTaQy98uK5pD08ZkVTnNZ1D02w88a8/+3f3T+PB5Ol6cDMZDEoMVOG9HQm7ryyLafV29+rPMvKShjry0GmpMiESr5jq0hKbiZCUMG9z1YalsRoPK2Y5aKCL1d2gUptiFUvNyOtmYCtzMjMgDz03qXePmrrOE/DauesBHqXaHg/GqdXClNO5kLHaSmAlEExIrzheab0oovYLr01tt/Njk8xKVi39yP2X8ta59iyq2lGr4atbv//ljStV3ys7tSszRDueosYzZYet0+30lM4ZXBYBPtE4EVKjVDIHY1dDnDBTjXJnqXmtNA7U+jnruRWoF9IM0fBi2mn9N0w7KGBEKfPLPGXsnv6Baeey5xr/BowJElK+GGUgGcmtS3R6eVsYMcY916jbKC0EmxG5EfEv) work for you? It works for me with #8850.

**Comment by he-hesce** [comment]
If I click that link I get a Sandcastle which doesn't work. Is it pointing to and using the CesiumJS from #8850? It is easier to see the issue turning off the atmosphere and horizon haze like we do in our bespoke application.

This is how sandcastle in previous comment looks for me in Safari 13.1:

<img width="505" alt="20200515-cesiumjs-sandcastle-safari-13 1" src="https://user-images.githubusercontent.com/13648954/82080512-37b40800-96d4-11ea-8f3f-51c30a046d4c.png">

Do note that in our bespoke application (previous screenshots with the Map window title) we are using QtWebKit 5.9.1 (the one shipping with CentOS 7.7). I cannot load the Sandcastle URL into our embedded QtWebKit browser so that is why I tested the Sandcastle link in Safari.

**Comment by IanLilleyT** [comment]
Thanks for the info. I think I was misunderstanding the problem this whole time! So the problem is the line dipping below the horizon? As seen [here](https://sandcastle.cesium.com/#c=lVJNj9MwEP0rVk6JVJxdAVqpzVaUrsQFtJW24kI4uPY0MTh2NJ4kKqj/HeeDKnR74WTPzHtv5o3dCmSthg6QPTILHduC103Fvw65OI/kEG+dJaEtYB4t2O/cMlaj+wGStLM7LX8CLhlhA4vcnpNVbnM7inIvwQIvjDsA96XrPqFrrNpQ5XxdAkLoehTGw+rCuBbmff6LU2C47zTJcu+ekUpXoKhLLeOx3YuwSgpPBrhQau+KwsDHhsjZuJ82j56gppIReAoW+tSNAVWP2QfIpghmPe0BMVwG+LGxw1AsliWEuVQy7uF/hILZibzqqefcTrsKj1A7czJhwz6A/lGsUVeadAu+dza4mb3TbqJtnTHj1uJklL0IDrTxzZzXPcQvr+k7XUN/8iK0REGwFRh2pYXdoIwno6/pF9RbfkRXPUGBAH4TzJ7ibyOJsTcPd/xucYnevZ9FD/NgVvmeDJfzeHRaUblk90N5+l/RIso8nQys/9I/6Kp2SKxBE3OeElS1CU58emjCyolL75PVCM7SOTVTumVaPd747Ewa4X2oHBtjXvQvyKN1lgb8K6pxQmlbPLeARpx6WHm//jwmOedZGsLbTHLOHAReKf8B).

Before:

<img width="987" alt="Screen Shot 2020-05-15 at 2 30 42 PM" src="https://user-images.githubusercontent.com/1328450/82084116-cfa3f880-96b8-11ea-9eb5-207d2106d8a3.png">

After:

<img width="986" alt="Screen Shot 2020-05-15 at 2 30 54 PM" src="https://user-images.githubusercontent.com/1328450/82084138-d6327000-96b8-11ea-9f56-5de1de444b34.png">


Is that correct?

The way I fixed it was by doing:
`viewer.scene.globe.depthTestAgainstTerrain = true` 

But I'm pretty sure there's a way to fix this without having to use that code. And it has to do with the depth plane most likely. I'll see where that takes me.

**Comment by he-hesce** [comment]
Yes, indeed. viewer.scene.globe.depthTestAgainstTerrain = true does indeed fix this issue in orthographic projection with polylines not clipping properly at/behind the horizon. It was never an issue in perspective projection. Even though this now makes me happy as it it fixes our issue with polylines, I still think this shouldn't happen at all as I think it is a plotting/rendering problem for these primitives in orthographic projection and should never happen. Who would want this to happen and be a "feature"?

However, switching on viewer.scene.globe.depthTestAgainstTerrain now makes our billboards look crap. And now both in perspective and orthographic projection. See screenshots below:

Perspective:

![20200516-cesiumjs-perspective-1](https://user-images.githubusercontent.com/13648954/82090271-cd579380-96e4-11ea-8798-3f780d53c999.png)

Orthographic:

![20200516-cesiumjs-orthographic-1](https://user-images.githubusercontent.com/13648954/82090280-d0528400-96e4-11ea-95fa-80cac7fc3937.png)

**Comment by he-hesce** [comment]
And with viewer.scene.globe.depthTestAgainstTerrain = true, when zooming in closer to the surface this following happens:

Orthographic:

![20200516-cesiumjs-orthographic-2](https://user-images.githubusercontent.com/13648954/82091469-f37e3300-96e6-11ea-8255-a2a2ec5226cb.png)

Perspective:

![20200516-cesiumjs-perspective-2](https://user-images.githubusercontent.com/13648954/82091499-fda03180-96e6-11ea-9a02-0f08b51273df.png)

**Comment by he-hesce** [comment]
With viewer.scene.globe.depthTestAgainstTerrain = false, when zooming in closer to the surface it looks fine.

Orthographic:

![20200516-cesiumjs-orthographic-3](https://user-images.githubusercontent.com/13648954/82091830-9df65600-96e7-11ea-88f5-008204d72b80.png)

**Comment by IanLilleyT** [comment]
`viewer.scene.globe.depthTestAgainstTerrain = true` is only a proof-of-concept fix. I wouldn't expect you to use it as the final solution due to all the drawbacks you pointed out. 

It's not a problem with primitives and projection, it's a problem with this invisible depth plane  plane that is supposed to block objects behind the horizon, but it in the wrong location for orthographic. So hopefully the fix isn't too complicated and you won't have to change your code.

**Comment by he-hesce** [comment]
@IanLilleyT: Sounds like you're onto a solution. 🥇 Thanks for all your effort in resolving this.

**Comment by IanLilleyT** [comment]
Third time's the charm? This PR might the real fix to the problem: https://github.com/CesiumGS/cesium/pull/8858

**Comment by he-hesce** [comment]
@IanLilleyT: You're a rockstar 👍 #8858 does indeed appear to resolve our sub-issue. This looks correct now, there is no clipping problem on the horizon and also looks fine zoomed in:

![20200516-cesiumjs-orthographic-fixed-1](https://user-images.githubusercontent.com/13648954/82111909-dc1b6600-9737-11ea-91d8-5fb938542d66.png)
![20200516-cesiumjs-orthographic-fixed-2](https://user-images.githubusercontent.com/13648954/82111911-dd4c9300-9737-11ea-9619-84ce1f0ae322.png)
![20200516-cesiumjs-orthographic-fixed-3](https://user-images.githubusercontent.com/13648954/82112135-babb7980-9739-11ea-93e1-018d7e490fd0.png)

Our users/scientists will be very happy with their new fancy orthographic projection view.

Hope this can make it officially into the next CesiumJS release.

Thank you!

**Comment by he-hesce** [comment]
Maybe we were yelling victory too early. If I tilt the globe (ctrl-click + move) then it seems the issue reappear.

![20200516-cesiumjs-tilted-not-fixed](https://user-images.githubusercontent.com/13648954/82112466-c52b4280-973c-11ea-9d76-0310184dd190.png)
![20200516-cesiumjs-tiled-not-fixed-2](https://user-images.githubusercontent.com/13648954/82112477-e9871f00-973c-11ea-8de0-95dd552a966e.png)

**Comment by IanLilleyT** [comment]
Oof.. I reproduced the issue and submitted some fixes for it. Could you try https://github.com/CesiumGS/cesium/pull/8858 again? Thanks!

**Comment by he-hesce** [comment]
@IanLilleyT: I have tried Cesium-1.69.0-orthoDepthPlaneFix34405.zip and will say (cautiously this time) that it does seem to work fine now, tilted or not tilted. I've been rotating, tilting, zooming, and trying to break it but it does seem to look fine in all circumstances and I cannot make it to look "unclipped". So this could be it!

![20200517-cesiumjs-orthographic-with-tilt-1](https://user-images.githubusercontent.com/13648954/82124887-a0ad8580-9791-11ea-8de9-183ca918d6c8.png)
![20200517-cesiumjs-orthographic-with-tilt-2](https://user-images.githubusercontent.com/13648954/82124888-a2774900-9791-11ea-882e-a30098da24af.png)
![20200517-cesiumjs-orthographic-with-tilt-3](https://user-images.githubusercontent.com/13648954/82124890-a4410c80-9791-11ea-9a8f-be8dabe580ed.png)
![20200517-cesiumjs-orthographic-with-tilt-4](https://user-images.githubusercontent.com/13648954/82124891-a5723980-9791-11ea-9294-f3223f71f5bd.png)

**Comment by he-hesce** [comment]
Hope to see this fix in 1.70! Cheers to all involved!

**Comment by sowo** [comment]
I've tested the fix as well and can confirm that it resolves my issue. Thanks to everybody involved in resolving this.
