### ISSUE TITLE
Cache bust for new Cesium releases

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium#5115]
On the forum, the absolute most frequent cause for problems is that users update to the newest Cesium release and everything is broken because something was cached from the old release and they need to clear their cookies/cache to make Cesium work.  Is there anything we could do to prevent this from happening?

In the release build, could we tack the version number onto the end of the Asssets/ThirdParty/Widgets/Workers folders?  Should we be tacking the version number onto the end of the `Cesium.js` file?

This is something users can do in their own applications (see https://groups.google.com/d/msg/cesium-dev/Hzq39xt1LVA/eLSjc35oDAAJ), but considering the frequency that this causes errors, I'm not sure if it's something most users are aware of.  

We can close this if it's outside the scope of what we want to handle, but I figured we should at least discuss it since it causes trouble for so many people.

**Comment by mramato** [comment]
Ultimately, the problem is an improperly configured server. Adding a query parameter to workers may fix a specific case where the worker is cached, but it doesn't fix the fact that other js/html/image files (like Cesium.js itself) may be cached.

So my vote is we do nothing and encourage developers to properly configure their servers.

Now if there is an edge case where worker caching is causing a problem for standard server configurations, then I'm okay with adding a query parameter, but I don't see it providing any benefit.

**Comment by pjcozzi** [comment]
Agree with @mramato.

What doc in particular would be useful?  Is there something very concise we could put on the downloads page?

**Comment by ggetz** [comment]
I don't believe this is reproducible anymore.
