### ISSUE TITLE
GeocoderService incompatibility between when.js Promise and browser native Promise

### ISSUE THREAD

**Issue by thw0rted** [CesiumGS/cesium#5442]
I have made two examples in Sandcastle, [one with browser-native Promise](http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=52ce4f0cb053317229ef805b6c7be1bd) and [one with when.js calls](http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=cb7391b40c2d494f1ad5e377a57ae14e).  Please load each example, search for anything, then hit Enter.  In the browser-native Promise example, the bar continues to show "Searching..." until you click the X button to clear it.  In the when.js example, the first (and only) result is selected as expected.

The docs say that `geocode()` should return a `Promise.<Array.<GeocoderResult>>` -- I would be very happy if native Promise were supported, but until y'all figure out what's broken maybe at least update the docs to specify `when()` instead?

Ubuntu 16.04, Chromium 58.0.3029.110 (latest stable)

**Comment by thw0rted** [comment]
Note that both examples do show suggestions, so it "partially" works -- you can even click a suggestion, but for some reason enter-to-search breaks things.  Weird!

**Comment by mramato** [comment]
This is an area Cesium needs to do a lot better.  Cesium was written long before Promises were standardized and so it relies on some non-standard functions in the old version of when we are using `otherwise` in this case.

The solution in this case if to make sure that we wrap any user-created promises in a `when.resolve` (in this case, the Geocoder should be wrapping the return result from `geocode`.

@thw0rted thanks for reporting this and we'd be happy to take a pull request to fix this specific issue.

As an aside for anyone curious, even when we switch to bluebird (which has been a long-standing goal), we'll still need to deal with wrapping externally generated promises like this.  The only other option would be to use native promises exclusively, but I think that will hurt performance and needlessly complicate a lot of our code.

**Comment by thw0rted** [comment]
Thanks for the response.  I'm not actually sure where in the callback chain this falls apart; my Promise debugging skills are middling at best, so I lose track of the resolution somewhere between my code and Cesium's.  Sorry!  For the time being, I'm going to try to be careful to only give `when` promises to Cesium.

**Comment by mramato** [comment]
It's in two places:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/Geocoder/GeocoderViewModel.js#L348

and

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/Geocoder/GeocoderViewModel.js#L446

I think that should fix the issue.
