### ISSUE TITLE
CallbackPositionProperty

### ISSUE THREAD

**Issue by nsorin** [CesiumGS/cesium#5534]
Hello Cesium community,

As mentionned in #2597 :

A CallbackPositionProperty with a `referenceFrame` would be a useful addition to cesium, not sure why it doesn't exist already. Since the position of an entity can be defined by a callback, it seems logical to have the possibility to combine the advantages of both classes.

I am using a polyline with a `PolylineDashMaterialProperty` as material to link 2 entities whose position is determined by a non constant `CallbackProperty`. To reference the 2 entities' positions in the polyline, I have to use a `PropertyArray `instead of a `PositionPropertyArray `(because the latter needs a `referenceFrame`, which does not exist in a standard `CallbackProperty`).
This somehow causes the dashes of the polyline to stretch in a strange way at some angles. This did not happen when I didn't need the callback and simply used a `PositionPropertyArray`.

Any chance this feature can be implemented in a future version ?

**Comment by emackey** [comment]
Beware that dashes currently don't work with callback properties:  #5450

**Comment by jfayot** [comment]
Hi @ggetz ! Why not close this one and other related issues, now that CallbackPositionProperty has been implemented ?

**Comment by ggetz** [comment]
Yes, thank you @jfayot for the reminder! 

Next time, [you can use the `fixes` keyword in your PR](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) so that GitHub automatically closes linked issues. 

This was resolved in https://github.com/CesiumGS/cesium/pull/12170.
