### ISSUE TITLE
Replace atan in polyline dash vertex shader with fast approximation

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#5545]
This line in the polyline vertex shader:

https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/PolylineCommon.glsl#L64

may get a nice performance benefit from the fast atan approximation @AnimatedRNG is working on for #5455

**Comment by pjcozzi** [comment]
Perhaps useful reading: [Inverse trigonometric functions GPU optimization for AMD GCN architecture](https://seblagarde.wordpress.com/2014/12/01/inverse-trigonometric-functions-gpu-optimization-for-amd-gcn-architecture/)

**Comment by ErixenCruz** [comment]
Seems the approximation introduces too much error. Here's what it looks like if we use `czm_fastApproximateAtan` instead of `atan` at https://github.com/CesiumGS/cesium/blob/adea020fd9b3b20de146ef16f09f1c65b785ab68/Source/Shaders/PolylineCommon.glsl#L88
![ezgif com-gif-maker](https://user-images.githubusercontent.com/45504062/168685045-0adce3ff-ad59-4ed7-b6e4-b8c3dff253e3.gif)

**Comment by ggetz** [comment]
Thanks for checking on this @ErixenCruz. We'll close this.
