### ISSUE TITLE
Drag and Drop success event

### ISSUE THREAD

**Issue by cguldner** [CesiumGS/cesium#5690]
There is a `dropError` event for the `viewerDragDropMixin`, it would also be nice to have a `dropSuccess` event so that custom data processing can occur once the file has loaded.

**Comment by hpinkos** [comment]
Thanks for the suggestion @burn123!  You should be able to achieve this by listening to the [viewer.dataSources.dataSourceAdded](http://cesiumjs.org/Cesium/Build/Documentation/DataSourceCollection.html?classFilter=datas#dataSourceAdded) event.  Will that solve what you're trying to do?

Otherwise, we'd be happy to look at another PR if you have time to make this change =)

**Comment by burn123** [comment]
The problem with that event is that it fires whenever there is a file added to the Cesium Viewer, it doesn't care where it is from.

**Comment by ggetz** [comment]
This is unlikely to become a priority anytime soon. We'd still happily accept a PR addressing this issue. But tracking this isn't particularly useful because of its low priority, so I will close it. Thanks!
