### ISSUE TITLE
Add "Typings" file to NPM package for Typescript consumers

### ISSUE THREAD

**Issue by thw0rted** [CesiumGS/cesium#5717]
I've been working on a Cesium-based project for a few months now, and picked Visual Studio Code as my primary editor.  I was a little irritated that other libraries I rely on (like Moment and jQuery) have good feedback from Intellisense, while Cesium doesn't give me anything (out of the box, at least).  I learned that this is because the more popular libraries have a "Typings" file (`.d.ts`) either available from an external source, or bundled into the Node module directly.

I found [this repo](https://github.com/excelulous/cesium-type-definitions/blob/master/index.d.ts) and placed the `index.d.ts` in my `node_modules/cesium/` and like magic, VSCode knew the types of all the Cesium classes and functions -- except that listing was last updated 4 months ago with version 1.26, so it was missing stuff that's changed in the last half-dozen or so releases.  I've added some things to it myself, though I wouldn't say it's definitely complete.  I can post my modified version if anybody would like that.

I recognize that this would be an ongoing requirement, either to maintain manually or to generate as part of your build workflow, but I think it would really help out both those that try to use Cesium from actual Typescript, and those that work with vanilla-JS Cesium from VSCode.

**Comment by ggetz** [comment]
Hi, thanks @thw0rted! There's been previous discussion about starting to use Typescript (see #4434) and it's included on our [BIM Roadmap](#4678) if you'd like to contribute to discussions there.

**Comment by hpinkos** [comment]
We've been talking about updating to es6 modules sometime soon, so we may be able to do this as part of that effort.

**Comment by mramato** [comment]
ES6 is orthogonal to this.

The best way to implement this would be to automatically generate it from the jsDoc comments, which is what some of our users have tried doing. (I believe jsDoc already outputs an interim json document that makes this straightforward).  Hopefully there is a standard tool available that we can use to validate the output so we can automatically detect when it's broken as well.  I imagine there are bugs in the jsDoc that would have to be cleaned up in the process as well.

It's doubtful that the core team will be able to do this anytime soon, but if someone would like to implement a gulp task that generates the definition file, we would be happy to take the contribution, it just needs to be auto-generated and cleanly written so that it's minimal work for us to maintain going forward.

**Comment by thw0rted** [comment]
I read #4434, and while moving *to* TS would be neat and all, I'm talking about "just" adding typings sooner rather than later.  As Matt points out I think this is reasonably straightforward if the JSDoc is already correct (and of course, if the JSDoc isn't correct, it should be updated).

In the past few days working with it, the biggest hangup has been dealing with `Property` types.  I don't know a lot of Typescript so if there's a way to say that you can assign any other type (or specific other types, declared as a generic like `Property<boolean>`) and implicitly convert, I haven't found it.  I updated a lot of type members that are listed as just `Property` in the docs to be `Property | Color` (or `boolean` or `number` or whatever), just so that assignments work.  I'll look into the toolchain to generate the typings file from a gulp task, but we need to figure out the Property thing before the output will really be useful.

**Comment by thw0rted** [comment]
Oh! And I forgot, while ES6 is kinda-sorta orthogonal, I believe that importing an ES6 module in VSCode will apply Typescript-style static checking to the JSDoc (if intact) which would mean you wouldn't strictly need a typings file to get Intellisense working.  (You might still need the file to actually include Cesium in a Typescript project without copping out and calling it `any`?)

**Comment by thw0rted** [comment]
I'm trying to rectify how Cesium handles `Property` with how Typescript wants this to work.

For example, in a simple Billboard Sandcastle, I can set `viewer.entities.billboard.show = false` and it *appears* to be setting a property of the `billboard`.  Under the hood, it looks like the setter is creating a `ConstantProperty` and saving that to a private member.  This is a common pattern across the sample code.

[Typescript has some strong opinions about this.](https://github.com/Microsoft/TypeScript/issues/2521)  From that issue:

> I truly object to the idea that this code `foo.bar = "hello"; console.log(foo.bar);` should ever print anything than "hello" in a language that attempts to have sane semantics.
>  Properties should have behavior that is indistinguishable from fields to external observers.

This is on an issue talking about why Typescript won't let type types of a getter/setter pair differ from each other.  So there's currently no way to declare typings such that `billboard.show = true;` works and so does `if(defined(billboard.show) && billboard.show.getValue()){ ... }`.  You can declare `show` as being of type `Property | boolean` (which is exactly what I did for the constructor options) but that means that you have to add a type guard any time you get the property, even though you know it will always be a `Property` and not a raw `boolean`.

**Comment by mramato** [comment]
While I don't have a good answer for you, what Cesium is inspired by another Microsoft language, C# and is normally referred to as implicit construction. You can read more about it here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/implicit  It's not that the setter/getter are different types, it's that the Property type is automatically instantiated during the assignment.  Conceptually, you are always setting a Property type, it's just created on the fly.

I don't know enough about TypeScript to know if it has any sort of implicit construction, but if there is any such concept, I think that could be used here.  Ideally, in the TS definition, it should always say Property{bool} (or whatever the generic notation is) is the type for the getter/setter, but it would know that Property can be implicitly cast from bool.

Of course this is me talking in the abstract and unlikely to have a good TS solution, but I just wanted to provide some context as to the idea behind the properties.

I also wonder if we can lie to TS for the sake of a good definition file, even if the actual implementation is slightly different.

**Comment by thw0rted** [comment]
I did a little research about implicit cast / implicit construction but didn't have time to really get into it.  I'm familiar with the idea, and the good news is that Anders Hejlsberg worked on both languages so there's probably support for getting the feature in there if it's not already.  I believe some primitive types can already be implicitly assigned / cast to one another, so hopefully there's some way to shoehorn in implicit construction too.

Maybe I should take this to the TypeScript tracker for more details...

**Comment by thw0rted** [comment]
If anybody is tracking, I went ahead and hand-jammed some 1.37.0 updates to the Typings file I found earlier: https://gist.github.com/thw0rted/c0c73335c9968d5e7b6dd18a43ef6c42

I'm sure it's still missing some information or wrong in places, and I don't have automated tooling in place to generate this, which is what's really needed.  Still no workaround as far as I know for the issue I raised back in August -- Typescript still *really* doesn't want you to use getter/setter pairs the way Cesium does, so you might have to do use type guards or casts in your consuming code that wouldn't otherwise be necessary.

**Comment by emackey** [comment]
I stumbled across another thing to consider here: [TypeScript without Transpiling](http://seg.phault.net/blog/2017/10/typescript-without-transpiling/).

> TypeScript 2.3, which arrived in April, introduced support for analyzing conventional JavaScript code that has type annotations in comments. You can use a JSDoc-inspired syntax to describe function signatures and add type information. TypeScript tools read the type annotations from the comments and use them in much the same way that they use TypeScript’s own type system.

> JavaScript with type annotations in comments is less succinct than writing actual TypeScript code, but it works everywhere, it eliminates the need for transpiling, and it makes the TypeScript tooling totally optional. It doesn’t cover all the same ground as the TypeScript language yet, but it is comprehensive enough to be useful.

**Comment by beginor** [comment]
@thw0rted I have move your [gist](https://gist.github.com/thw0rted/c0c73335c9968d5e7b6dd18a43ef6c42) to a public repo https://github.com/beginor/cesium-typings ,  this make it easy for others to contribute.

Any star or fork is welcome.

**Comment by pjcozzi** [comment]
Also see https://github.com/excelulous/cesium-type-definitions by via @excelulous https://groups.google.com/forum/#!topic/cesium-dev/25jPqr5ODg0

If the community wants to collaborate on a single TypeScript definition for Cesium - and even contribute it back in a way that is easy for the core team to maintain - please go for it!

**Comment by bampakoa** [comment]
Hi all,

I am currently experimenting with [tsd-jsdoc](https://www.npmjs.com/package/tsd-jsdoc) to produce a **typings** file for CesiumJS. I have finally managed to create an output file (not sure if it is ok, needs review) but I needed to make a bunch of modifications so that the tool can be aligned with CesiumJS. In detail:

- When I run the tool, I noticed some inconsistencies between the primitive types that are defined in Cesium and those that the library expects to parse. For example: the tool looks for string, number, boolean and not String, Number, Boolean.
- In some cases the error handling was not so good and the library was crashing if it could not find some properties. I added some code there also to handle exceptions.

The library does not seem to be stable yet. It had stuck for a year on 2.0.0-beta.1 version and suddenly there were some new pre-releases out in the last 15 days. I do not know if it is worth to make PRs to fix their current code. 

@pjcozzi what do you think about maintaining a tailored made fork of this tool, for the needs of CesiumJS? Alternatevily, I could try to make CesiumJS be aligned with their current codebase by submitting PRs for the current Cesium documentation. 

I really want to help on this so in case someone is interested, we can start collaboration and finally take something under review from the Cesium team.

> A thread was also started on the Cesium forum if you want to have a look. https://groups.google.com/forum/#!searchin/cesium-dev/Angular%7Csort:date/cesium-dev/Ztd5jNcKPdo/z1AHGEfKAAAJ

**Comment by thw0rted** [comment]
@szechyjs How did you generate these typings?  I saw in the NPM listing that you credit @zuzon so I assume you're starting from the same hand-massaged version I've been maintaining [in a gist](https://gist.github.com/thw0rted/c0c73335c9968d5e7b6dd18a43ef6c42).  I try to keep up with changes that are mentioned in the changelog but I'm sure there's plenty of stuff I've missed.  It's good to have *something* in DT but I think in the long run @bampakoa 's approach (generating typings from existing JSDoc) is really the only way the typings are going to stay accurate, given the significant rate of change this project sees.

**Comment by mramato** [comment]
@bampakoa First off, thanks for your interest in Cesium and desire to help the community!

> what do you think about maintaining a tailored made fork of this tool, for the needs of CesiumJS? 

Our usual preference is to submit patches to other tools upstream, that way we help improve them for everyone and play the role of good OSS citizen.  If customization is needed for Cesium, then having plug-in points for the `tsd-jsdoc` would be preferred over a fork.  That being said, I haven't looked at `tsd-jsdoc`, if it's in the realm of a single file, then just having a `generate-tsd` gulp task is a possibility, in which case we can just have the whole code base be in Cesium.

> Alternatevily, I could try to make CesiumJS be aligned with their current codebase by submitting PRs for the current Cesium documentation.

> For example: the tool looks for string, number, boolean and not String, Number, Boolean.

Since JSDoc is perfectly fine with String/Number/Boolean, I assume that any tool that claims jsdoc -> tsd  should also be okay with it.  So this is something I would fix in the tool, not in Cesium.  If you find invalid JSDoc in Cesium, then Cesium should definitely be fixed, but other than that, we would want to keep changes to Cesium to a minimal.

Ultimately, the Cesium team's preference would be to generate official bindings automatically as part of our release process (and travis builds).  I know there have been separate efforts from those in the community to generate tsds, but I don't think anyone has ever opened a Pull Request to make it a reality.

Given Cesium's scope, there's no way a PR is going to get merged without a lot of discussion and iteration.  @bampakoa since this seems like something that really interested you, I would suggest opening a PR, even if it's only 50% done in order to get feedback from the maintainers and community regarding the approach you're taking and quality of the output.  Sounds like @thw0rted and @szechyjs both may have some good insights and ideas here (as well as previous hurdles they have had to overcome in their own efforts).  Perhaps you can even rally others to open PRs to your PR to help further improve it.  I'm sure it will expose issues in Cesium's JSDoc code as well.

I personally would love to do more with TypeScript, but none of the libraries I work on currently use it (This is true for most (all?) of the Cesium maintainers.) and it's unlikely Cesium itself will ever switch to it.  However, we want to support our community of TS Cesium devs so I would love to see this happen.

**Comment by mramato** [comment]
> That is, number is the type of the primitive literal 42 and Number is the class that holds e.g. the toFixed function. If tsd-jsdoc is unhappy about function arguments that are defined as boxed-type, it might just be codifying this guidance from the TS handbook as a "rule".

Right, what I'm suggesting is that `tsd-jsdoc` should treat `Number` in JSDoc as `number` in TypeScript.

**Comment by thw0rted** [comment]
I don't know enough TS (or JS for that matter) to tell you if that's safe.  The primitive/object-box distinction is not unique to TS, it exists in JS as well -- see e.g. [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number).  Cesium functions almost definitely don't *require* a boxed object, so I *think* they should probably specify the unboxed primitive, but I'm not personally expert enough in why to argue about it here.

**Comment by mramato** [comment]
@thw0rted, that's actually a really good point and may be a good reason to update Cesium to `number` instead of `Number`.

**Comment by bampakoa** [comment]
@szechyjs I have used your typings in one of my past projects and looks awesome. Very nice effort!

@mramato thank you very much for your feedback, I really appreciate. I am currently in the process of fixing bugs and contribute back to the library. As soon as, I have a good working copy, I will get back with a PR so anyone can take a look and help.

**Comment by bampakoa** [comment]
In the latest releases, there are changes in the documentation of the source code that allow extraction of **typings** file using [tsd-jsdoc](https://www.npmjs.com/package/tsd-jsdoc).  I would ❤️  to give more details in case anyone is interested.

@hpinkos @pjcozzi @mramato do you think it would be useful to write a blog post for that?

**Comment by emackey** [comment]
Related, can there be / should there be a build step for generating typings?

**Comment by emackey** [comment]
@bampakoa Were you able to get to a state where the typings file came directly from tsd-jsdoc, with no manual edits?

**Comment by bampakoa** [comment]
@emackey yes, I was able to generate a typings definition file using **tsd-jsdoc** but I have not verified its correctness and quality yet. It would be great if anyone could review that.

**Comment by bampakoa** [comment]
Hey all! Today Microsoft [announced](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/) Typescript 3.7 Beta which contains a significant change as far as typings generation is concerned.

`--declaration` and `--allowJs` options will finally play nice together. That actually means that Typescript will do its best to extract type definitions from JSDoc statements by its own and the use of 3rd party tools such as **tsd-jsdoc** may not be needed in the future 🎉.

**Comment by puckey** [comment]
I have successfully generated typescript types for the source files using the latest Typescript 3.7 beta:  `tsc --declaration --allowJs --emitDeclarationOnly ./Source/Cesium.js`

**Comment by thw0rted** [comment]
Would you mind throwing those up e.g. in a gist somewhere? I'd like to try it on my project and see if it still compiles, vs. the hand-groomed ones I've been using so far.

**Comment by puckey** [comment]
Here you go: https://www.dropbox.com/s/wih9qtxn2e4x642/cesium-typescript-types.zip?dl=0

These are generated by downloading the Cesium repo as zip then, install and build (to create `/Source/Cesium.js` and afterwards:

```
yarn add typescript@beta
npx tsc --declaration --allowJs --emitDeclarationOnly --outDir ./types ./Source/Cesium.js
```

I am unable to generate them as a single `.d.ts` file, because some of the files are giving errors during building: https://gist.github.com/puckey/d333f8f7c51ef80ed962694f1e4f7517

I have also noticed that some of the types are missing. For example `Scene.camera` is missing and `FeatureDetection.d.ts` is empty..

**Comment by thw0rted** [comment]
Ah, OK.  Well, thanks for the upload and I might try to poke at it, but if it's not "drop in ready" yet then I'll set it aside until I have a little more time.  Ideally, I could make the typings, fix the JSDoc where stuff is missing / wrong, and iterate until at least my own code builds cleanly.  I'll try to get to it when I have the time, for sure.

**Comment by puckey** [comment]
Looking into some of the jsdocs annotations, I am noticing inconsistencies like the following in `Scene.prototype.mapProjection`, where the type is set as `MapProjection` (which does not exist) while the default references `GeographicProjection`:

```
        /**
         * Get the map projection to use in 2D and Columbus View modes.
         * @memberof Scene.prototype
         *
         * @type {MapProjection}
         * @readonly
         *
         * @default new GeographicProjection()
         */
```

Leads me to wonder if generating types from comments like this would ever lead to a correct set of typings.. Comments are notoriously hard to keep up to date.

**Comment by thw0rted** [comment]
The Typing generation step would need to be part of CI, if not maybe also the local build tooling (rollup etc).  We need to fix all the comments once, then instrument so that future failings break the build loudly and block PR merging.

**Comment by puckey** [comment]
(I will refrain from proposing Typescript as the solution) : )

**Comment by thw0rted** [comment]
[Too late](https://github.com/AnalyticalGraphicsInc/cesium/issues/4434)!  We can just insidiously make it easier and remove friction points until whoops, look at that, the code is basically TS already 😁

**Comment by thw0rted** [comment]
OK, I had a little time to look at this today.  My goal is to eventually stop having to hand-maintain one giant `cesium.d.ts` and have generated typings on a per-module level as well as a top level one that matches the (generated) `Source/Cesium.js`.

I'm walking out the door now, but if you want to play with [my first pass](https://github.com/thw0rted/cesium), it at least builds (`npm run build-typings`).  A number of tests fail in the Jasmine runner, but I didn't think to try running it beforehand so I'm not sure if they were my fault.  I'm re-testing now but I'm going to have to see what (if anything) failed when I get back on Monday.

**Comment by thw0rted** [comment]
I went back and re-ran the tests.  Three are still failing (c.f. #7892) but that's the same before and after my changes.  I'm looking to see if there are any alternatives to `@memberof` support because I don't see that showing up any time soon.  I think it *might* be possible to convert the legacy pattern to proper ES6 classes without breaking the API but that's a heck of a lot of work.

Will update the issue if I get any clever new ideas.

**Comment by mramato** [comment]
For anyone following this issue, check out #8878.  Your feedback is appreciated.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/25jPqr5ODg0
https://groups.google.com/forum/#!searchin/cesium-dev/Angular%7Csort

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/5717 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
