### ISSUE TITLE
Should Cesium.ExtrapolationType.HOLD consider last known orientation?

### ISSUE THREAD

**Issue by Mendanbar** [CesiumGS/cesium#6166]
I'm using a SampledPositionProperty for position, VelocityOrientationProperty for orientation, and a forwardExtrapolationType of Cesium.ExtrapolationType.HOLD to model the movement of a 3D entity. Once the time advances past the window of sample data, I would expect the HOLD to maintain not only position, but also last known orientation (with zero velocity and acceleration).  It seems to only hold the last position, while returning orientation to default.  

In my case, I'm calculating waypoints on the fly (which takes <1 second), but there is sometimes a gap where my entities reach the last sample before I can add a new future sample.  This results in the entity pausing at the last sample and waiting for the next sample to arrive (which is what I would expect), but the reset of orientation to default causes the motion to look less smooth as the entity briefly faces in the default heading.

Am I doing this incorrectly?  Or is there a way to specify that the HOLD applies not only to position but also last know orientation?

**Comment by zouyaoji** [comment]
Hello, is there a solution to this problem, I also encountered this problem. @Mendanbar

**Comment by mramato** [comment]
Orientation is independent of position but can be made to match.  Assuming you are using `SampledProperty` to defined orientation, set the `entity.orientation` property to use the same extrapolation settings as you are setting for `entity.position`.

Sorry the original post here never went answered, we recommend posting to our forum, https://community.cesium.com, for help like this because it will most likely get a faster response.
