### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#6167]
You can now make pull request templates as well as different templates for issues, e.g., bugs vs. features.

https://github.com/blog/2495-multiple-issue-and-pull-request-templates

For this repo and other repos in our organization.

**Comment by hpinkos** [comment]
We were talking about this a little bit today.  It might be helpful to have a small checklist like 
- [ ] Test coverage
- [ ] Runs in Firefox
- [ ] Runs in IE
- [ ] Runs in Edge

We've had some problems with big features we've merged lately breaking cross-browser compatibility and this would help us catch that before it gets merged instead of when we're putting together the release

**Comment by ggetz** [comment]
Maybe as part of this (or the concierge update that covers the checklist), prompt for a maintainer to be @ mentioned or assigned as a reviewer.

I see a lot of PRs sit there since no one is directly "responsible" for reviewing.
