### ISSUE TITLE
Expose an interface to ModelInstanceCollection

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#7062]
The best way to have hundreds of instances that all share the same model is to use the `ModelInstanceCollection` class. It's currently used internally when loading 3D Tiles but there's no public interface to it. 

I think it would be a good idea to allow users to create this directly. 

[Forum discussion](https://groups.google.com/d/msg/cesium-dev/IfXK7gh6pwI/05O5mWCZCQAJ).

**Comment by mramato** [comment]
I think a better approach (at least in the short term) would be to have entities take advantage of ModelInstanceCollection so that it gets used automatically if lots of models are specified (and this would help all users "for free" without having them manually manage them at the primitive layer).

**Comment by OmarShehata** [comment]
Came up again here: https://groups.google.com/d/msg/cesium-dev/XLTrotCj3IY/M6mtimhcAgAJ

In the context of rendering thousands of ships.

**Comment by wejrox** [comment]
This is a great idea, however it is implemented. I'm trying to do the same thing since I'm dynamically creating thousands of objects at the moment and running into memory limits. 

A solution that doesn't require user implementation sounds great if possible, as right now we can only specify the URI when creating a `ModelGraphics`, so it would require more interface changes.

In the mean time, @OmarShehata do you know of a method of using instances which would allow me to use them when creating an Entity?
