### ISSUE TITLE
Hide atmosphere until globe is ready to render

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#7189]
When Cesium first loads, we often see the white/red/yellow artifacts that are part of the sky atmosphere that are "under/behind" the globe while the globe loads.  It doesn't bother us, but I think it looks like a bug/artifact to a lot of users.  Let's not render it until the globe is "loaded."  This will couple things slightly more but should be easily implemented just in the `Scene` render loop.

@OmarShehata could you look at this one this week with help from @lilleyse or @bagnell?

---

Please close if this is a duplicate; I thought there was an issue but could not find it.

**Comment by OmarShehata** [comment]
Yes! I think there's a lot of small things like this we can do to improve perceived visual quality. It's almost a taboo to see anything loading in a game engine.

I'll give this a shot.

**Comment by OmarShehata** [comment]
Looks like the skyAtmosphere already waits for the root tile to load before rendering, see [Scene.js#L2675](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Scene.js#L2675). This is only a problem when `viewer.scene.logarithmicDepthBuffer` is true. The root tile does correctly load, but it doesn't cover the surface, because of https://github.com/AnalyticalGraphicsInc/cesium/issues/6573.

This is with log depth on:

![atmosphere_loading](https://user-images.githubusercontent.com/1711126/47519804-66516000-d85c-11e8-8307-b36d8215521a.gif)

And with log depth off:

![log_depth_off](https://user-images.githubusercontent.com/1711126/47519816-70735e80-d85c-11e8-8a63-4415becac34f.gif)

@bagnell looks like the fix was to not write log depth in the vertex shader? https://github.com/AnalyticalGraphicsInc/cesium/pull/6701 Do you know why this root tile is getting clipped like that?

**Comment by pjcozzi** [comment]
@OmarShehata @bagnell what is the plan here?

**Comment by OmarShehata** [comment]
I believe @bagnell is working on the underlying log depth issue.
