### ISSUE TITLE
`Cesium3DTileset` loads tileset recursively on empty content URL

### ISSUE THREAD

**Issue by vaclavblazek** [CesiumGS/cesium#7263]
While writing 3D Tiles generator I've found out that an empty URL in the Tile's content (i.e. `"content": { "url": "" }`) causes cycle in the tile tree structure in the Cesuim API.

The core cause is because content's full URL is then the original tileset's URL and fetched JSON is treated as an external tileset. If there is more than one tile with an empty URL it is an equivalent of a fork bomb: the browser slows down terribly, endlessly loading _external_ tilesets and actual tile data over and over again.

Propper handling should be to report invalid tile and maybe skip it.

**Comment by OmarShehata** [comment]
Thanks for reporting this @vaclavblazek . I do agree it sounds like it would be a good idea to have a check on load to prevent this from happening. 

I think it would be great to see a community contribution for this! I marked it good first issue since it could be a nice entry to how 3D Tiles are loaded in CesiumJS.

**Comment by j9liu** [comment]
@ebogo1 or @lilleyse - I'm working on this issue right now and just wanted to clarify some things before I started implementing a solution.

- If a `Cesium3DTile` is invalid (i.e. it contains `"content": { "url": "" }`), should it throw an error and stop the rest of the process?
- If not, then I'll make it print something to the console. Should it then be skipped over while the other `Cesium3DTile`s load? Or should it be treated as a valid empty tile?

**Comment by lilleyse** [comment]
Technically the tileset.json is invalid because it creates a circular dependency which is disallowed by the spec:

> When a tile points to an external tileset, the tile:
>
> * Cannot be used to create cycles, for example, by pointing to the same tileset file containing the tile or by pointing to another tileset file that then points back to the initial file containing the tile.

https://github.com/CesiumGS/3d-tiles/tree/main/specification#external-tilesets

Generally we try not to add workarounds for invalid data but in this case I think it's fine to print a warning to the console and treat it like a regular empty tile.
