### ISSUE TITLE
Refactor the Timeline to meet coding standards.

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#754]
The `Timeline` widget is awesome and people love it; however, it's some of the oldest UI code in Cesium and is radically different than the rest of the code base.  We need to bring it up to snuff so that it meets our coding standards.  There are also additional features we would like to add but cannot do so until we have a way to validate and
- [ ] - Refactor to use Knockout and view models and meet general coding standards.
- [ ] - Document the API (there is currently no entry at all in the built Documentation)
- [ ] - Add specs (we currently don't have any)]

Related issues: #773, #1768, #2066, #3555

**Comment by mramato** [comment]
Some discussion on the [fourm](https://groups.google.com/d/msg/cesium-dev/AMvvGRwCo_k/TBCPZHrh1YgJ)

**Comment by WarpDrive** [comment]
Thanks Matt. There's also an issue with mousewheel: when you can scroll the page Cesium is on, you can't mousewheel the timeline because the page scrolling moves the timeline away from the pointer, and the pointer needs to be hovering over the element to register mousewheel (for keyboard events only focus is needed, not hover over.) So when the timeline is hovered over page scrolling should be disabled (which seems to already be the case for the 3D canvas.)

**Comment by td-edge** [comment]
+1

A standalone application would be ideal...

**Comment by hpinkos** [comment]
idea from the forum: add a way to select the current date/time by typing it in or pick from a calendar instead of having to use the slider

**Comment by td-edge** [comment]
@hpinkos I had the same issue and used bootstrap's datepicker to create a solution:

    var start_julian = clock.startTime;
    var end_julian = clock.stopTime;

    $("#start-datepicker").datepicker({
        onSelect: function(dateText, inst) {
            var dateAsObject = $(this).datepicker( 'getDate' ); //the getDate method
            start_julian = new Cesium.JulianDate.fromDate(dateAsObject);
            clock.startTime = start_julian;
            clock.currentTime = start_julian;
            timeline.zoomTo(start_julian, end_julian);
        }
    });

    $("#end-datepicker").datepicker({
        onSelect: function(dateText, inst) {
            var dateAsObject = $(this).datepicker( 'getDate' ); //the getDate method
            end_julian = new Cesium.JulianDate.fromDate(dateAsObject);
            clock.stopTime = end_julian;
            timeline.zoomTo(start_julian, end_julian);
        }
    });

**Comment by jjhembd** [comment]
This is unlikely to be a priority anytime soon. If someone does want to address it, something along the lines of https://github.com/CesiumGS/cesium/issues/10876 would be more in line with current coding standards.
Tracking this isn't particularly useful because of its low priority, so I will close it. 
Thanks!
