### ISSUE TITLE
HDR does not work with WebGL 2

### ISSUE THREAD

**Issue by polluxll** [CesiumGS/cesium#7647]
Does cesium support webgl2?
when I set requestWebgl2 as true in my code,the globe cann't be rendered.

Chrome:72.0.3626.121

[.WebGL-09868378] GL_INVALID_FRAMEBUFFER_OPERATION: Draw framebuffer is incomplete
[.WebGL-09868378] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete

**Comment by verybigzhouhai** [comment]
I also encountered the same problem.

**Comment by hpinkos** [comment]
@lilleyse what's the status of webgl2 support?

**Comment by OmarShehata** [comment]
Cesium defaults to WebGL 1 because that's what's officially supported. With that said, it is on our roadmap to have WebGL 2 be the default. Looks like this broke in version 1.52. If you go to:

https://cesiumjs.org/releases/1.52/Apps/Sandcastle/index.html?src=Offline.html

And put `contextOptions: { requestWebgl2: true },` you'll get those warnings/nothing rendered, but it works with 1.51. 

It looks like it's the HDR that breaks it. Turning it off allows it to render just fine even in the latest CesiumJS:

```
viewer.scene.highDynamicRange = false;
```

If anyone in the community wants to dig further into this we'd be happy to review a PR!

**Comment by OmarShehata** [comment]
I'm closing this since CesiumJS does not officially support WebGL 2, but it is on the roadmap, so we can consolidate known bugs and discussion in this issue: https://github.com/CesiumGS/cesium/issues/797#issuecomment-617189407.
