### ISSUE TITLE
ClippingPlaneCollection as a concave polygon

### ISSUE THREAD

**Issue by xuncanzhe** [CesiumGS/cesium#7665]
I want to use the ClippingPlaneCollection to dig a polygon on 3dtiles, but only the convex polygon succeeds, and the concave shape has no effect. So I would like to ask if ClippingPlaneCollection can dig a concave polygon pit on a 3dtiles?

**Comment by hpinkos** [comment]
@xuncanzhe `ClippingPlaneCollection` uses the intersection of the tileset in front of the plane for every plane in the collection, so it does not currently support concave shapes.  I'll leave this issue open as a feature request, and we'll give you an update if we implement support for this.  Otherwise, if you have time to look into it, we would be happy to review a pull request!

**Comment by WangXiaoLun** [comment]
I have the same request too.Have you solved the problem yet?@xuncanzhe

**Comment by hemincan** [comment]
I need this  feature too.

**Comment by stevenjh** [comment]
I'll add a plus one to this.

**Comment by TuoLe** [comment]
@xuncanzhe @hpinkos 
Hello，I  have also met this question these two days. 

ClippingPlaneCollection doesn't clip terrain when the clip shape is a concave polygon, I'm trying to split the concave polygon into several convex polygons,but i find ClippingPlaneCollection only  can receive and clip a plane, i'm so troubled.

I would like to ask if you have solved this problem, can you provide some ideas and methods？
Thank you very much!

**Comment by ggetz** [comment]
This issue should be obsolete with the addition of `ClippingPolygonCollection`.
