### ISSUE TITLE
Polyline shifting artifact with logarithmic depth buffer

### ISSUE THREAD

**Issue by lyhkop** [CesiumGS/cesium#7852]
when i use this code to add  a line entity。

```
            var purpleArrow = viewer.entities.add({
                name : 'Purple straight arrow at height',
                polyline : {
                    positions : Cesium.Cartesian3.fromDegreesArrayHeights([start.longitude, start.latitude, start.height,
                    end.longitude, end.latitude, end.height]),
                    width : 10.0,
                    followSurface : false,
                    material : new Cesium.PolylineArrowMaterialProperty(Cesium.Color.PURPLE)
                }
            });
```

The point of intersection with b3dm data will change when camera move! I think  the causes of this problem is that we change the position in screenspace but depth is not change！

**Comment by OmarShehata** [comment]
@lyhkop can you post a full [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) example that we can run to replicate this issue? Screenshots/gifs help too to explain exactly what you mean.

**Comment by lyhkop** [comment]
![Snipaste_2019-05-21_08-19-29](https://user-images.githubusercontent.com/8472213/58060067-278d4980-7ba2-11e9-90bf-571090a4493c.png)
![Snipaste_2019-05-21_08-20-13](https://user-images.githubusercontent.com/8472213/58060068-2825e000-7ba2-11e9-8629-bb4fe3e52a06.png)
when i move the camera the point of intersection will change!
the code is:
` var viewer = new Cesium.Viewer('cesiumContainer', {
            shadows: false,
        });

        var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
           url : 'http://localhost:8080/Data/svsdata/blyx/tileset.json',
           show : true,
           shadows : Cesium.ShadowMode.CAST_ONLY,
        }));

        viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0, -1.57, 0.0));
        var projection = viewer.scene.mapProjection;
        var ellipsoid = projection.ellipsoid;

        // WGS84 转 地理坐标
        // pos is a Cesium.Cartesian3(x, y, z)
        function WGS84ToCartographic( pos )
        {
            var cartographic = Cesium.Cartographic.fromCartesian(pos);

            // 弧度转经纬度，Cesium中Cartographic为弧度表示（不易使用，我们自己定义一个经纬度对象）
            var lng = Cesium.Math.toDegrees(cartographic.longitude);
            var lat = Cesium.Math.toDegrees(cartographic.latitude);
            var height = cartographic.height;

            return {longitude : lng, latitude : lat, height : height};
        }

       // 输入地理坐标 pos 为 {longitude : longitude, latitude : latitude, height : height}
        function CartographicToWGS84( pos )
        {
            var car33 = Cesium.Cartesian3.fromDegrees(cartographic.longitude, cartographic.latitude, cartographic.height);
            var x = car33.x;
            var y = car33.y;
            var z = car33.z;
            return new Cesium.Cartesian3(x, y, z);
        }


        function  DrawLine( start, end )
        {
            var purpleArrow = viewer.entities.add({
                name : 'Purple straight arrow at height',
                polyline : {
                    positions : Cesium.Cartesian3.fromDegreesArrayHeights([start.longitude, start.latitude, start.height,
                    end.longitude, end.latitude, end.height]),
                    width : 10.0,
                    followSurface : false,
                    material : new Cesium.PolylineArrowMaterialProperty(Cesium.Color.PURPLE)
                }
            });
        }

        var p1, p2;
        // 鼠标左键，输入起点
        viewer.screenSpaceEventHandler.setInputAction(function onLeftClick(event) {

            var cartesian = viewer.scene.pickPosition(event.position);
            if (Cesium.defined(cartesian)) 
            {
                var pos = WGS84ToCartographic(cartesian);
                //{longitude : longitude, latitude : latitude, height : height}
                p1 = {longitude : pos.longitude, latitude : pos.latitude, height : pos.height};
            }
        }, Cesium.ScreenSpaceEventType.LEFT_CLICK);
		

        // 鼠标右键，输入终点
        viewer.screenSpaceEventHandler.setInputAction(function onRightClick(event) {

            var cartesian = viewer.scene.pickPosition(event.position);
            if (Cesium.defined(cartesian)) 
            {
                var pos = WGS84ToCartographic(cartesian);
                p2 = {longitude : pos.longitude, latitude : pos.latitude, height : pos.height};

                DrawLine(p1, p2);
            }
        }, Cesium.ScreenSpaceEventType.RIGHT_CLICK);

    }`

**Comment by OmarShehata** [comment]
If I'm reading this right, the intersection point is sliding several meters? (It goes from being on one side of the extruded part of the building that's closest to the street, to the other side).

I'm unable to recreate this in a Sandcastle example though. Here's [my Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=rVZbb9s2FP4rRPZguXVoybLiS9JgaZKhxdLWSNK91MVASbTNhSIFkrLjDv7vO9RdbtO+zHAc8lw/nhu5JQptGd1Rhd4gQXfommqWJfivnOb0onx7LYUhTFDVG6B/lwLBR29ILHcazZFRGV2KQ/98KZaisIV1RAXFay5DimOams0j1eZqDTa0eaRKwQL8Wc1Cq0TxQcaUA6P0saFsvTFz5IL5XK4E9yRk9CQzg40i0ZNTa/ZrY0ZKHhJ7plhGWUKFwWtqbjm1y7f797HTK0V6VunYLklTvn/LRMzEWjf2B5XdliPGqaamG7zin3/zWDCd8jiZ4nPUw3hYf6/SVA8fSJJyekMMGXYUh6V6vRiWzvA/WopeHfKKqiiJ9wslE6YpNhsqnFUmIsOkcEqRfhXYTpZSxRJm2JZqTOK4lj3viH6TMnmUFXPQPu078AtxWjATbe6JWFPHxe4Anbo4GFTxwaHM8mg+pBuqKFagkmn0Co2w27euDn0sAbPaAfgGN1SKVDXqSAotOcVcrkvOeR2E4wxCtj+FmqotCTltZ7BXFFWvj3UW6kixsOWv4PW79Qe5/ZglIXRDyS4jw1bIYfoj+VjRaz37UdRkSpSiBwsxjyaUTESUkWtF0g2LwHZVMy0qXkEWLQFYpM7ecQwheYaqOk9gWWdqRSLaNZrb8HOT9xB1IrTTRgDRFGtmspgOUJdOTEmGdLa9yNWqqPj/1Uk3tnlrKTBjBaT4oTPIn+1/4xSABtXxO8XZyDv9yngVz8RWxAdiFHtuHBT7cX6UxwaB00LTKrulGA7RgkVPKJWa5VDlCtnBsWVxRjiQmTAaFcNiQ0TMjyftQ6QoFQ8pIL/dQkrfFUJO2XgRAVVtvZXaGKC/F2lmroqabZrFajctDv5qTG+OOh4AL0peoYYr0SpGcKxae8c4RyFFUH10BbdAbEsfmhVl0GAo4mBNIy0TajZQnbY+cm4+/ZtWKY9bmnBqh52uabf4MaTWNALEwCoHVkvdfiq1eb0adAUo5yzVksVzdKSa9y2UL5u/UEIw0Oy331U7NNtDv+n4w+ClFD/uU4rvbv94/Pv67v31n81tUiHWkLEvhaEfA/FGXuC5Mzw7c93Jmee6Ixi444l/5s9GOPCD2Zl3NvUGaOxOvfFkgl137Af+aDLy+4Nf2XVHIzx1J8FsMvFdv7Q79oA4O5v6sC7MBhMfjyZjbzr1/ckvrY5nfoBn/ng0GwezaWnUG0+x5wUj3w38aWF16sG14QW+F8wACgT6axOcTME9eQWDf9cU9I8qQZCEwrukt8gVkIbWzec4yVWJKWdNr8ScSr7nUJOoUw9NKppC0q1K2rHYbIA3spddQ15JzuXuoRzEc7QiXNMWPyEwsxkMhk6JLUoI+eE+lCJwladUmX3VOdeSS4UXn+8Xd7f9psqK6oF+vYYHgIHj5reDtuekJNoUEwgEXq2kQo4NJIPwuecMXTQHw5yKtdmcI/b6db/7SHip177vM/2FfW0d9eU+q4IwR52j3d/eHLXqT5vRxVN7NxU/rZYs2zEPzOHV8GRwcqHNntPLgv47S1KpjH2NOfAEMxReX4BHD8MseoJbIdK6auLfqmdkC38IL861sjfxHKl1SJwxtF71Z4G0plUKIYOJOEfj9LlFDqWKqTot3kBt5uHILbNjvu18C/XAIsJPCWdriHzCYrgSvvd4amQKpdnxWrFCaYxM2lxwezGsQnQBVxdi8ZvlydHTf3kCo55oDZxVxvkD+0aXJ5cXQ5DvqHGZPwc/AVZO9lZk413eFUSM8cUQtt9rlUcG8QKT5Vy+y/u0Es7JRUgMDFBQUva1CbgSJmB3CmMQu3ZLnmFb7bShqd3CMoY39mkItzPst4RndF6OggHKt59TkABiL/fSa8B0vBr6bKxdCADsgp/ZzS1U+P8D).

![intersection](https://user-images.githubusercontent.com/1711126/58119623-64bd0000-7bd1-11e9-9274-ff5a03dd9e24.gif)

Another way to confirm this is to place a sphere at this point and compare it to the line:

![intersection_sphere](https://user-images.githubusercontent.com/1711126/58119648-6f779500-7bd1-11e9-9a8a-b9de8444a42f.gif)

Can you please try this and let me know the result? If you are able to recreate this issue using this tileset in Sandcastle this will help a lot in determining the issue and fixing it.

**Comment by lyhkop** [comment]
![2019_05_22_10_19_08_793](https://user-images.githubusercontent.com/8472213/58142890-64793f00-7c7b-11e9-9b8b-db5869e1829b.gif)

thank for your reply! i jsut delete the first point in your Sandcastle code，like this：
`var positions = [
    //new Cesium.Cartesian3(1215109.9600761002, -4736392.535961681, 4081477.0043532723),
    new Cesium.Cartesian3(1215022.8075977303, -4736412.89683736, 4081573.274188337),
    new Cesium.Cartesian3(1214935.934294598, -4736148.115230538, 4081810.5153159215)
];`

**Comment by wtfgecko** [comment]
I'm having a very similar issue with my polylines, although I can't provide a sandbox example as the terrain tiles are generated and served by my application in CesiumTerrainProvider format but the polyline is not testing correctly against the terrain.

```

viewer.scene.globe.depthTestAgainstTerrain = true;

var newEntity = connectionsCollection.entities.add({
                                id: connection.id,
                                name: connection.name,
                                polyline: {
                                    positions: Cesium.Cartesian3.fromDegreesArrayHeights([connection.siteALocation.x, connection.siteALocation.y, connection.siteALocation.z,
                                        connection.siteBLocation.x, connection.siteBLocation.y, connection.siteBLocation.z]),
                                    width: 5,
                                    material: new Cesium.PolylineDashMaterialProperty({
                                        color: Cesium.Color.PINK
                                    })
                                }
                            });
```

![polyline](https://user-images.githubusercontent.com/50911387/58169756-719d2a80-7c89-11e9-8ee6-10b9333d72fc.gif)

**Comment by OmarShehata** [comment]
Ok, I definitely see what you mean here.

![intersection_sphere](https://user-images.githubusercontent.com/1711126/58171346-d180da80-7c63-11e9-9219-edca21caa0c7.gif)

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=zVdbcxo3FP4rGveBpcFil2XNgp1MHZs2njoOYzt9CZmM2BWgWkg7khZMOvz3Hu19SZy89KGML9K56zsXiS1RaMvojir0Ggm6Q1dUs3SD/8poTifKtldSGMIEVZ0e+mcuEHz0msRyp9EEGZXSuTh0z+diLnJbWEdUULzickFxTBOzfqTaXK7AhjaPVClYgD+rmWsVUbyXMeXAKHysKVutzQS5YD6TK4J7EjJ6kqnBRpHoyak0u5UxIyVfEHumWEbphgqDV9RMObXLt/ub2OkUIh2rdGyXJAnfv2UiZmKla/u90m7DEeNUU9MGL//nXz/mTKc4Tqr4BHUw7lc/l0mi+w9kk3B6TQzptxT7hXq16BfO8N9aik4FeUlVlMT7mZIbpik2ayqcZSoiw6RwCpFuCWwrS4liG2bYlmpM4riSPW+JfpVy8yhLZq952nfgF3CaMROt74lYUcfFbg+dujjolfjghUwzNB+SNVUUK1BJNfoVDbDbta4OXSwhZrWD4Ou4oVKkqqKOpNCSU8zlquCcVyAcZxCy/WGhqdqSBafNDHbyoup0sU4XOlJs0fCX87rt+oPc3qWbBXRDwS6QYUvkMH1H7kp6pWc/ippUiUL0YEPM0ISSiYgycqVIsmYR2C5rpkHFS8iiJQCLVNk7xhCSZ6iq8gSWdaqWJKJto5kNPzN5D6gToZ1mBICmWDGTxrSH2nRiCjKks+lFLpd5xf+nTtrYZq2lwIwVkOK7ziB/tv+NkwfUK4/fKs5a3umWxks8N7Yi3hOj2HPtIN8Ps6M81hE4jWgaZTcX/T6asegJJVKzLFS5RHZwbFmcEg5kJoxG+bBYExHz40n7EClKxUMCkU+3kNJ3uZBTNF5EQFVbb4U2htBvRJKay7xm62ax2nWLg78qptdHHQ8BzwperoZL0RIjOFalvWOcowVFUH10CbdAbEsfmhWl0GAo4mBNIy031KyhOm19ZNxs+tetUhy3MOFUDltd02zx45Aa0wgiBlYxsBrq9lOqTapVry1AOWeJliyeoCPVrG+hfNnkhRKCgWZ/um21Q709dOuOP/ReSvHjPqH4dvr745er25urP+vbpIxYQ8Y+lYn4fijewAs8d4zHZ647OvNcdwAjdzjyz/zxAAd+MD7zzkKvh4Zu6A1HI+y6Qz/wB6OB3y3weNmuOxjg0B0F49HId/3C7tAD4vgs9GGdmw1GPh6Mhl4Y+v7op1aHYz/AY384GA+DcVgY9YYh9rxg4LuBH+ZWQw8uDi/wvWAMoQDUn2t4UgU35SWM/l1d0t+rBUE2FF4mnVmmgDQ0bzbJSaZKTDFtOkXMieR7DlWJWhVRJ6MuJd2opR2LzRp4A3vd1eSl5FzuHopRPEFLwjVt8DcEpjaD0dAqslkRQna494UIXOYJVWZf9s6V5FLh2cf72e202zAJ01SknChm9mC1HmRrfH95fXN59/BlNr3/cj394346rcszLzto9Ct4ORhAKbtWtIWHkmidj665WEqFHIs+A8zdc4YuajQwp2Jl1ueIvXrVbb8tXmrRb9tTf2KfG4d5uT1L5Koj5njcT6+POvyHPezi0F5p+Z9GJxddnMFyKJC5zEHIZzo41zQbtegGraRBi30+/OzQ21nsgK4J1JdoSVeP4p9D8oOW9EIMTR2Gg3EwDMpWHw0xNP8wCGFd9OQ4xKNB4IVn4Xjc/V/BetI7udBmz+mbnPQb2yRSGfssduAtbCg8gyEU3V+k0RNcz5HW5TT9pXzPN0JfwNN/peyTaILUakGcIUzA8tfG0Lg2EkAcsjRBw+S5QV5IFVN1mj9Gm8zDkVtm79um8y20JYsIPyWcrSBxGxbD3fytx1MjE5gQLa8layGNkZsmF9xe9EuILuANgVj8en5y9B1sfgJlR7QGzjLl/IF9pfOTNxd9kG+pcZm9yz9ArJzsrcjae3ObEzHGF33YfqtVHBnE85gs5827bFyWwhk5h8TATQZKyj77Ia4NE7A7hdsIu3ZLnmFb7rShid3CMoYvO6cLeCbBfkt4SifFRO6hbPsxAQkgdjIvnTqYlldDn421CwDALviR3cxCGf+/)

@wtfgecko thanks for providing the additional case. I think this can be worked around by doing a raycast to get the actual point of intersection and adding that point to the polyline, which is why it didn't happen in my first case. 

@likangning93 do you have any insight here? Is this expected behavior?

**Comment by likangning93** [comment]
This might be an artifact of linearly interpolating log depth, I can't seem to reproduce the effect with `viewer.scene.logarithmicDepthBuffer = false`.

**Comment by wtfgecko** [comment]
> This might be an artifact of linearly interpolating log depth, I can't seem to reproduce the effect with `viewer.scene.logarithmicDepthBuffer = false`.

That fixes it for my issue. I'm reading in to the consequences of turning this off at the moment, but I would assume this isn't an intended consequence of the feature.

As per https://cesium.com/blog/2018/05/24/logarithmic-depth/

**Comment by OmarShehata** [comment]
I believe this indeed a bug, and I've labelled it as such. 

> I'm reading in to the consequences of turning this off at the moment

I think you should be fine turning this off for now. You might see a slightly lower performance or you may need to adjust the near/far planes if you're seeing any Z-fighting (see https://cesiumjs.org/Cesium/Build/Documentation/Camera.html?classFilter=Camera).
