### ISSUE TITLE
GroundPrimitive Polygon visual artifacts at pole

### ISSUE THREAD

**Issue by shunter** [CesiumGS/cesium#8033]
[Sandcastle example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html#c=nVRNb6MwEP0riEtTCRyMP8DZNFope1xppa3US+nBYCe11tiRIemmq/73NSRpoB+raDkge+a9mfE8j3fcBdVzrYOb4P5PYQL/FaESRRjM/ELYaltL0xZhdPLtpGuUNUcABEkRFuYlCoIRe1aEFRMiq8oyZiUjMc5zFPMVlzGSUDIEs2yF8CCu4bXseWvXBXi1b6zq8s+O4XuT+i31rXru8Dg62yurrRtCO6Nbl9zb7s+2IIA0iQiKIERRSsjZ83BavhwWL4Mq9H7dnXpUh21U63vRvM1ZcdfateObR1X95ELxHjIqIUYAYkhYSgkiOcsYimIIEKMpRTjxDoIpolESjUgQkCzJGEUpzRjOGaUXsJILMP8V+NIzfNTggWw1b6VTXL/tYmO1Esv3mn4i9edy/0vyUVUD6UfLD67DQfnxfehkl41Xe1wAAgzmNE1YinOIcZbKGCa+lTFFhGYkBQjiFBOYsRPnWFCf1v8evhSmMDs/qTsln6Tzs2rkU7D0ubY1uOttk6uq3y6tabky0l1de9YBDwRv+a3dOg8BXIjJkbn0c//t1QW05WLSvQXXHTWMwnnT7rVcFOarqjfWtcHW6QkA01bWG+1Fa6bltvolW1A1TUeZT0+EuVC7QIkb35NxVf7ZqDRvGu9ZbfVxiBfzqcePaF0tyqx/+NdG830HeYSL7wcjAGA+9dv3rNZaXXI3iFiYvw)

This is a single polygon at the pole.  There are multiple visual artifacts:

![image](https://user-images.githubusercontent.com/32828/62320736-fe751900-b46e-11e9-9dc0-bf3e357dda45.png)

**Comment by ggetz** [comment]
I did some debugging here, and this artifact happens only with ground polygons. As a workaround, you can set `height: 0` to use a regular polygon.

This is caused by using [spherical texture coordinates for ground primitives](https://cesium.com/blog/2018/06/26/implementing-materials-on-ground-primitives/), particularly a `discard` that that clips any values computed outside of the [0, 1] range for UV coordinates.

The article mentions using altitude-azimuthal spherical coordinates, perhaps it makes sense to use polar-azimuthal coordinates for polygons which are local to the poles to avoid the artifacts.
