### ISSUE TITLE
Generate Source Maps

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8245]
Now that we have switched over to roll-up with #8224, it should be straightforward to generate sourcemaps for our code.  The only tricky part may be our use of pragmas which remove code from the "built" version.  But roll-up hasn't let me down yet so there's a good chance it will "just work"

**Comment by kring** [comment]
#8659 adds sourcemaps for the unminified build. I tried adding them for the minified too, but it didn't go well. The debugger ended up in totally wrong locations.

Removing uglify fixed it, but I'm not sure why uglify would be the problem because sourcemaps are supposed to work with rollup+uglify.

To try it, add this to the end of `rollup-plugin-strip-pragma`'s `transform` function:

```
            if (options.sourcemap !== false) {
                result.map = magicString.generateMap();
            }
```

And change the two places in `gulpfile.cjs` with `"sourcemap": debug` to `"sourcemap": true`.

**Comment by fredj** [comment]
I haven't tried but the latest version of magic-string fixes a bug related to the source map:
https://github.com/Rich-Harris/magic-string/blob/master/CHANGELOG.md
