### ISSUE TITLE
Fix jsDoc to allow @exception tag on ECMAScript 5 properties...

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#832]
Documenting an exception on an ES5 property changes the property type to the exception type.  In the below example, `aValue` shows up in the generated doc as type `DeveloperError`, instead of type `Element`.  Removing the exception doc makes the problem go away.

```
/**
 * Gets or sets a value
 * @memberof MyClass.prototype
 * @type {Element}
 * @exception {DeveloperError} an error!
 */
aValue : {
    get : function() {
        return this._value;
    },
    set : function(value) {
        if (typeof value === 'undefined') {
            throw new DeveloperError('an error!');
        }
        this._value = value;
    }
}
```

**Comment by pjcozzi** [comment]
Does anyone know if this is still an issue?

**Comment by pjcozzi** [comment]
Upgrading to the latest JSDoc should fix this, https://github.com/AnalyticalGraphicsInc/cesium/issues/1859#issuecomment-285692183

For a test case, check http://cesiumjs.org/releases/1.34/Build/Documentation/Model.html?classFilter=Model#boundingSphere

**Comment by andynines** [comment]
Can this issue be closed? I can reconfirm @bampakoa's comment on #1859 that the problem is no longer present; I generated a test doc page using JSDoc 3.6.11 (the version my NPM resolved to from the version requirements of the package.json in the `main` branch) and the configuration found in `Tools/jsdoc/conf.json`.
