### ISSUE TITLE
Toggling Orthorgraphic can break everything

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8346]
1. Run http://localhost:8080/Apps/Sandcastle/index.html?src=Projection.html&label=All
2. Without moving the camera, toggle to Perspective view
3. Without moving the camera, toggle back to Orthographic
4. Everything is terrible:

![image](https://user-images.githubusercontent.com/1495196/68047924-d6879280-fcb5-11e9-8ad3-e8914415975e.png)

Moving the camera doesn't fix anything at this point.  However if you do move the camera between steps 2/3 everything seems to be fine.

@lilleyse any ideas?  I don't think this is a showstopper, but seems like something we should fix soonish.

**Comment by lilleyse** [comment]
For me step 3.5 is to right-click and zoom outward. That's when the milk truck becomes visible again and starts to show the problems.

This doesn't seem to be a problem when log depth is disabled.

**Comment by OmarShehata** [comment]
This was [reported on the forum today](https://groups.google.com/d/msg/cesium-dev/8KFNqzbSc9I/RGixiWo9AgAJ), although a slightly different issue that I think is related. If you toggle orthographic -> perspective -> back to othrographic, you get this:

![image](https://user-images.githubusercontent.com/1711126/73367408-8486e680-427d-11ea-8c86-99d12a3fd427.png)

This almost looks like the camera has zoomed out into space and is rendering the globe incorrectly, but if you use the geocoder to fly anywhere, you'll see the camera actually hadn't moved from its original place, the view gets fixed when the camera starts to fly.

**Comment by UniquePanda** [comment]
Thanks for bumping from my forum post, Omar :)

Something I can add from my investigations on this:
My initial problem (before I encountered what Omar described above in the sandcastle) was, that a 3DTile (a point cloud) disappeared when the camera switched to orthographic frustum.
I found out that many times (although not always unfortunately) a call to "pick()" can make the point cloud appear again. E.g. a call like that:
`viewer.scene.pick(new Cartesian2(0, 0), 1, 1);`

From looking at the code my guess was that it had something to do with the clearing of the frame- or depthbuffer but I didn't manage to extract the correct code for making the point cloud appear again without all of the necessary picking ^^

But as I said this seems to now always help, because a colleague of mine managed to let the point cloud disappear again even with the added pick call.

And another addition..
Often I had the following case:
1. Switch to orthographic -> point cloud disappeared
2. Do the pick call/move the camera -> point cloud appeared again
3. Switch to perspective -> everything fine
4. Switch back to orthographic -> everything still fine

So it looks like something got "fixed" in step 2 so that even for consecutive switches to orthographic frustum everything worked again.

And sometimes I had no problem at all when switching to orthographic. I think it depended on the camera angle when the orthographic view got broken and when it didn't.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/d/msg/cesium-dev/8KFNqzbSc9I/RGixiWo9AgAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8346 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Comment by OmarShehata** [comment]
Posted an update that this issue has been fixed on the forum: https://community.cesium.com/t/switch-to-orthographic-camera-breaks-rendering/9036/2
