### ISSUE TITLE
To display rtmp live stream video in cesium

### ISSUE THREAD

**Issue by moonCai** [CesiumGS/cesium#8373]
I would like to display an rtmp stream video in Cesium. I created an entity and used the <video> element as its material. When I use video stored locally (in .mp4 format) it worked fine, but when I switched to an rtmp source and play it via videojs, it can play in <video> element, but it can't play on the entity. The rtmp uses flash to play, while ordinary video does not require flash, I wonder if its because of this.

Here's the <video> element

<video id="rtmpStream" class="video-js" controls preload="auto" width="640" height="300" data-setup="{}" autoplay>
        <source src="rtmp://202.69.69.180:443/webcast/bshdlive-pc" type="rtmp/flv">
</video>

Some people use video server such as VLC to receive stream and resend the stream as an http link.It works but it seems that VLC is not very good in terms of  latency and performance.

To display RTMP live stream video in cesium is very useful for the fusion of map and video. If you 
add this feature, We would be very grateful. 

My loyal Thanks!

**Comment by OmarShehata** [comment]
Thanks for bringing this up @moonCai . Since browsers do not support RTMP streams, I think it's unlikely CesiumJS will support it directly. It should be possible to do with videoJS since that looks like it'll convert the RTMP into a regular HTML5 video. 

Can you share a [Sandcastle example](https://sandcastle.cesium.com/index.html?) showing your attempt at using videojs to display this video on an entity?
