### ISSUE TITLE
Typo in wiki page on Fabrics

### ISSUE THREAD

**Issue by stacktracer** [CesiumGS/cesium#8386]
The [wiki page on Fabrics](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Fabric) has a GLSL example block that says:

> `czm_materialInput m = czm_getDefaultMaterial(materialInput);`

The type of `m` needs to be changed to `czm_material`, to match the return type of `czm_getDefaultMaterial()`.

**Comment by LuminousPath** [comment]
There's a large amount of other missing documentation on the fabric page, notably the list of built-in glsl functions seems to be a broken link.

**Comment by OmarShehata** [comment]
Thanks @LuminousPath . I think ideally we'd move these guides with the rest of our updated documentation, either in the repo or on cesium.com/docs. 

CC @IanLilleyT

**Comment by IanLilleyT** [comment]
[Fixed the wiki](https://github.com/CesiumGS/cesium/wiki/Fabric/_compare/3bc982b990388a4ace953f44db8c60f3e6be28cf...3ae47d380515c7592b32f71d30accb02b059b2b5)

I set it to point to [AutomaticUniforms.js](https://github.com/CesiumGS/cesium/blob/master/Source/Renderer/AutomaticUniforms.js) for the built-in uniforms. Not sure if this is the right change since it's a private class, but it's the only place that has documentation for all this.

**Comment by mramato** [comment]
Ian his on the gist of it, there is a large portion of this doc that is not part of the public API, which is why it doesn't have a higher profile.

In the beta days of Cesium we included the uniforms as part of the refdoc, but that was remove before the 1.0 release.
