### ISSUE TITLE
Adding and removing Cesium ImageryProvider synchronously

### ISSUE THREAD

**Issue by Dosmi** [CesiumGS/cesium#8601]
Making a smooth animation from Imagery Layers:

I want to have an animation made from ImageryLayers, and for each tick, it should remove the old imageryLayer and add a new one. However, in doing so, there is a time in between when no image is loaded - resulting in a flicker between images - ON - OFF - ON 

In my code, I keep a copy of the OLD layer, then add a new one and only AFTER I have added it, I call the remove function, but obviously it does the adding/removing asynchronously and thus it still removes the old layer without the new one added first.

**My goal is to have the old layer only removed when the new one is added, so there is no empty gap in between.**

I add the layer as:
_layers.addImageryProvider(new Cesium.SingleTileImageryProvider({
		url: png_url,
		rectangle: Cesium.Rectangle.fromDegrees(west, south, east, north),
		alpha: 1
	}))_

and then I remove the old top layer as:
_layers.remove(layer_to_remove, true);_

where _layer_to_remove_ is the old top layer before adding a new ImageryProvider

**Comment by OmarShehata** [comment]
If you haven't already, I'd recommend opening an issue on the Cesium forum: https://groups.google.com/forum/#!forum/cesium-dev. I think a better approach here might be to use a time dynamic imagery provider instead of adding/removing layers like here:

https://sandcastle.cesium.com/index.html?src=Web%20Map%20Tile%20Service%20with%20Time.html
