### ISSUE TITLE
Runtime error in styling language when comparing any feature that contains null value

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8615]
Let's say you have a building dataset where each building contains a `Year` that it was built. For some buildings this year information does not exist. Since the [styling language](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/Styling) allows for `null`, you may choose to set those buildings to have a `null` year. However, if you then try to style by year, you get the following crash:

```
RuntimeError: Operator "<=" requires number arguments. Arguments are null and 50.
```

[Sandcastle](https://sandcastle.cesium.com/#c=zVRRb9owGPwrFpqUICEDXaFrm1br6EaDGlghK4VmmhzHFINjM9sJDVX/+xxCu1DtYW+bHxI5391357Odeh10JeIadIiiSdwbAYQxUQpoATKRSEAFB0gpolXACwx0BYcRmaGE6Yst2BdLwsEZsEjWm4ddTAe0537buM0+dZXLhy3ccdvucnV32+kdQwP6GXWXBuQ+TsafW4PL+Xw6ajJvc3N47Q+pt8B6sujHk1GjOYn7S2/stfr+cDlduPS601tNTTPPn2RetqZo/KXhLsRj33db3sY78BY32ewGhndN95b+GJArdiTHx7TRbPBHiT9/8NqdHgoHadIdh18H0/XBoXUa8ICnSIKUkjWRZhmcrHdxwNvtN9vC22lHcI0oJ9KqvrI0ZcSkY2gFHypMOIErSWOqaUoURFFkBxyYUWpcvN5f+gXdfioQ+UgkOwG/ox4SZfYBEziTIr7Id8KN7KPDdrNdLTjP5r3zUzjYCBH7wt4526Gg0HMi11QRe5ZwrPN9tYmUQlZBSRwLrgQjkImHXfX0RWUrEfAR4hFGShuQWZkvBAuR/JRoLbhtdQQTEoQZuCL0Ya6tGngRs19ldr6g0hkj+3GXUxnlZXvPWt77pOx25ziiuYIytfv9Wj7urXdPhZtn4JyBVsOYsra97KCySuSKkaBSAw3Yqlrfa3/ia5mQMilkiaEY9D64NH0uZbZ9/F1oE2IOlI2LU6YATxgDKTJq1f8lyNzhP4wx4JVaxdmu97yofaTxSkidXxobwrom8YohTVQ9TPDSZIOVyolO/YXkRDQFNDoLKm/udFABmJk/nanMTPAjujHuzp26we/RmEAR5Q+DlEiGMgMpjDjz5vl1UYIQOnUzzWXfsnWx9aXOvwA). 

This is just a test tileset with a single b3dm:

[tileset.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/4216786/tileset.zip)

This is what the header for the file looks like:

```
{"BATCH_LENGTH":1,"RTC_CENTER":[3783162.5968943657,901779.6901006929,5038256.658626413]}    {"Height":[88.03899621963498],"Latitude":[52.52055470075144],"Longitude":[13.40721184415235],"RoofCoordinates":["391919.605750434 5820113.6189754 46.3596332160857 391923.820103177 5820113.88098915 41.0079400725952 391923.353383662 5820121.54678542 41.0079400725952 391919.414597783 5820117.11537646 46.3596332160857 391919.605750434 5820113.6189754 46.3596332160857"],"bldg:rooftype":["\n\t\t\t"],"Year":[null],"Majority_Ownership_Type":["Unknown"]}   
```

The only workaround I can think of is to set `Year` values that don't exist to some special numerical representation like `0` or `-1` and treat them differently in the style. 

Is this the expected behavior? Is `null` mainly just supposed to used for string/categorical data?

**Comment by mramato** [comment]
I'm not sure if this is expected behavior, but it definitely sounds like something we should fix ASAP.  @lilleyse any ideas?

**Comment by lilleyse** [comment]
It's expected behavior according to the styling spec:

> The styling language does not allow for implicit type conversions, unless stated above. Expressions like vec3(1.0) === vec4(1.0) and "5" < 6 are not valid.

Either the style should have a special condition for `null` or it could be casted to a number like `Number(${Year})` in [Type conversions](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/Styling#type-conversions).

From the data side it's probably best to use a binary batch table property if all the values are meant to be numbers.

**Comment by mramato** [comment]
> Either the style should have a special condition for `null` or it could be casted to a number like `Number(${Year})` in [Type conversions](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/Styling#type-conversions).

@lilleyse So are you saying this should work?

```
            conditions : [
                ['null', 'color("blue")'],
                ['undefined', 'color("blue")'],
                ['${Year} <= 50', 'color("purple", 0.5)'],
                ['true', 'color("blue")']
            ]
```

Because updating Omar's example still causes it to crash.

**Comment by mramato** [comment]
Nevermind, it looks like the below does work:

```js
                ['${Year} === null', 'color("blue")'],
                ['${Year} === undefined', 'color("blue")'],
                ['${Year} <= 50', 'color("purple", 0.5)'],
                ['true', 'color("blue")']
```

**Comment by mramato** [comment]
@lilleyse Actually, it looks like there's still a problem because I can't use `null` in Cesium for point clouds styling.  You get `Error generating style shader: null is not supported.`

**Comment by lilleyse** [comment]
@mramato that's one limitation of the GLSL styling backend since null is not a supported GLSL type:

See https://github.com/CesiumGS/3d-tiles/tree/master/specification/Styling#point-cloud

> Implementation Note: Point cloud styling engines may often use a shader (GLSL) implementation, however some features of the expression language are not possible in pure a GLSL implementation. Some of these features include:
> * Evaluation of isNan and isFinite (GLSL 2.0+ supports isnan and isinf for these functions respectively)
> * The types null and undefined
> * Strings, including accessing object properties (color()['r']) and batch table values
> * Regular expressions
> * Arrays of lengths other than 2, 3, or 4
> * Mismatched type comparisons (e.g. 1.0 === false)
> * Array index out of bounds

What about

```js
['Number(${Year}) === 0', 'color("blue")'],
['${Year} <= 50', 'color("purple", 0.5)'],
['true', 'color("blue")']
```

Not ideal since it doesn't know the difference between `${Year} === 0`, `${Year} === null`, `${Year} === undefined` but it should work for both JS and GLSL backends.

**Comment by lilleyse** [comment]
Edit: the above doesn't work when `${Year}` is `undefined` since `Number(undefined)` is NaN and the GLSL backend doesn't support `isNaN`.

**Comment by mramato** [comment]
> Not ideal

I would say it's not viable at all, since there are plenty of use cases where 0 is a valid value that would be treated differently than undefined. (plus as you just mentioned it doesn't work in all cases). I appreciate the limits of GLSL, but simply pushing the problem up to the developer isn't really the right option.

Obviously the spec or GLSL isn't changing anytime soon, so I think this is something that CesiumJS should mitigate internally.  Instead of using 0, can't we automatically convert null/undefined to some sentinel value (like Number.MIN_VALUE) and just use that?  It's extremely less likely that data will ever contain Number.MIN_VALUE compared to zero and since we do it at the CesiumJS level, developers don't have to special case their styles or data in order to make them generic for all tilesets.
