### ISSUE TITLE
fxaa's effect is worse then before

### ISSUE THREAD

**Issue by happyfeet1996** [CesiumGS/cesium#8626]
Sandcastle example:

Browser:

Operating System:

when i update cesium to 1.66，the fxaa's effect is worse then before

**Comment by lilleyse** [comment]
Which version are you upgrading from? FXAA is disable by default now, but you can enable it with `viewer.scene.postProcessStages.fxaa.enabled = true`

See https://sandcastle.cesium.com/?src=FXAA.html

**Comment by happyfeet1996** [comment]
> Which version are you upgrading from? FXAA is disable by default now, but you can enable it with `viewer.scene.postProcessStages.fxaa.enabled = true`
> 
> See https://sandcastle.cesium.com/?src=FXAA.html

thanks for your response,i update from version 1.64. I know to enable fxaa, i just feel the fxaa's effect is worse than version 1.64, it's effect likes the version before improving.

**Comment by mramato** [comment]
@happyfeet1996 comparing the latest release to 1.64 shows that are identical except for some minor lighting improvements (which were intentional). There does not seem to be any difference in FXAA. You can open them side by side in your browser and see for yourself.

If these are different on your machine, can you please explain how and also let us know what OS, GPU, browser you are using (and exact versions).  Thanks!

[Latest release](https://sandcastle.cesium.com/#c=lVJdb9owFP0rES8NEjN2PgxpKRqjm4a0j6qgfUh5MfYFrDk2sp203bT/PidAxda+LC+Jj++55+bc0zAbNRLuwUbXkYb7aA5O1hX60mHxBe+Oc6M9kxrsxSD6VeooPB6sDdCtNY0UYC9PRG6BefhqrBKrQ0ncL/Xv/lWpS31QQo6DBsRZBZYhB74Vi499BTgvNfPS6MvzgebM+vDFdBqTNCUZKVCKkyTFo1E+iF5lNKd0TFAeMJylaRLAjKQ0SRNEw2WBcYbz/uAgYqyE8EfPRN4DE1Jvb6XnuzujVEwRTpMsz/MsJzih4yJIYYRzOg5wQUmGCUlGNIhRlIyTlOIijFTghNCTFmixsky7jbFV9GTTR+atfMjQ4ubtp9Vi9f1li/ZWVtLLBhxiQsTndnSv9GYlFQQHT+7VVj1JLIy+A2dqywFtrKlmLhQuRJyPMtKt5CVB43xYadi6W3q2DbqbB8YQaLZWIEJEvK2hoy2ZFpw5r6AdbWW2WwVvau+Nji/efZvNQlLa2kG0qTVvjY75DvgPEP1Tgv5P+Mi+OhrVG/Qmzj8qmB6avZbV3ljfGhAjNPRQ7VXIoRuu60DziDvX0ibDE2kiZBNJcV32/ol42Yu4Ys6Fm02t1FL+hLI3nQxD/V80ZbqsfG7AKvbYluzI9MMBRAhNhuH4nOWNUWtmzzr+AQ)

[1.64](https://cesium.com/downloads/cesiumjs/releases/1.64/Apps/Sandcastle/#c=lVJdb9owFP0rES+kEjPOZ8vGqrGwbmGFDggtIKTJdS7g1rGZ7UBh2n+fgTJ1Hy/LS+zrc+65Pj4JaFYWKJUC5TAnJTctSkHrTD6CcN46Vdh2lvcfKbthnXS0S70eS3UqBhFN0jh9XI1vk04DWdC3/OOjBaXbSXFVdNvThynDwTRLd9fZoOi1J2ZSdMPu0FtOi9H2Juvx6V0/7Plddp10VlPbrPswiux6N/Ebm+m4y264ZpNxb5uyDZta3Hi4YeTuCqcP8qmXLTa9Xd/vtvu7eR+lOOrQQTZKRi1vcDf2t1j2yddVmF/dxmZBWp8/qWQUtR74Iq2+mYmZWBPlrBlsQNkrCtg4ydGG20PNrdLDNpHCECZAVWvO95lw7GdAKVv6ouSa5aBen4hUATFwJxXPsyPEPZuJH2dHtUNXpCkIQJQUoAjSYPZi7nPfHLRhghgmxeuXAyVEGbsiInC9IPBCr4EC7PsBPj+Pas6rMI7i+MJDka3hMAh8Wwy9IPYDH8X2sIFxiKOz2lFEKgb2Rn+JfAKSM7H4wgxdDiTnboxw4IdRFIWRh/34omGlMMJRfGHLjdgLsef557EVi5F/4QcxbtiRGtj34pMWiDxTROi5VIXzy6YuMYo9hShtf+hlaTb5t0UrxQpm2Bo0InnuvrTj8AvaGeNgHTy5Vyr+S8ImeQBalooCmitZtLQFprkbnYfe4Un+JSi1sU+6z/3QkIXVnT8RgkCQew65jYhRJRxoQyJySrThsB8tk4sFh/elMVK41atxq2WTssfWnHkp6N5oly6BPkJ+dkrQ/wk/s988G1WpVZrabDlcHpu9Y8VKKrM3wEWobqBYcZtDXb8vLc0gqvWe1qyfSM2crR2Wv51V/oj4rOJQTrS2J/OS8yHbwaxy2axb/G80Lg9ZuVmD4mS7hyy9y+tjESHUrNvt3ywjJb8n6kXHnw)

**Comment by lilleyse** [comment]
Ah maybe the difference is that `viewer.useBrowserRecommendedResolution` is `true` by default now.

@happyfeet1996 try this [Sandcastle](https://sandcastle.cesium.com/#c=lVPZbtswEPwVwS+RAZemLtpOnKA5WtRAjyAxegB6Yci1Q5QigyXlJC36711ZceCmfaleJA53OKvZ4UZisjFwD5gcJw7uk3MIpm3Y5y2WHqjt8ty7KI0DPBglP2uX0BMBkaBL9BujAQ93RIUgI3zxaPWyL0mHtfs1PKpd7Xol1gY4Q38fAK9A+aYBp0FfQfC2jcY76mQlbYB9SlDggCnZAEoWIHb9pU+taAjRONlRD/f/4VxipC/pijQriqzMZqzgeV7wyaQaJa9KUQkxzVhFGC+LIiewzAqRFzkTtDnjvOTVcNSLeDRAJvwl8g6kNm59aaK6vfLWpoLxIi+rqiqrjOdiOiMpznglpgTPRFbyLMsngsQEy6d5IfiMWprxPBM7LfJjidKFlccmeXb2g4xoHkq2uHjzcblYfnvpam/RHZrGRLOBwKTW6b4d21dxsTQWyMGdey3aZ4mFd90YWlTAVuib00CFC51WkzLbTvFfgj5ESgEFJVxHuSbd1YOUDJy8saBplhHbfpTX0mklQ7TQtbb067WFszZG79KDt19PTylcXe0oWbVOdUan6hbUd9DDXej+T/iJffRk1GA0mIf4aOGkP+y1ae48xs6AlLFxhObOUnTD+KYlWmQqhI42H+9Ic202idHH9eDFragHibIyBNpZtdZemx9QD07mY6r/g2b9NiufNoBWPnYlt9nJ+x5kjM3HtPybFb23NxL3TvwN). It should look closer to 1.64.

**Comment by mramato** [comment]
@lilleyse good catch.  That definitely changed and would have a big effect on high DPI displays (I really should switch to 4K so I can catch these things)

**Comment by happyfeet1996** [comment]
> @happyfeet1996 comparing the latest release to 1.64 shows that are identical except for some minor lighting improvements (which were intentional). There does not seem to be any difference in FXAA. You can open them side by side in your browser and see for yourself.
> 
> If these are different on your machine, can you please explain how and also let us know what OS, GPU, browser you are using (and exact versions). Thanks!
> 
> [Latest release](https://sandcastle.cesium.com/#c=lVJdb9owFP0rES8NEjN2PgxpKRqjm4a0j6qgfUh5MfYFrDk2sp203bT/PidAxda+LC+Jj++55+bc0zAbNRLuwUbXkYb7aA5O1hX60mHxBe+Oc6M9kxrsxSD6VeooPB6sDdCtNY0UYC9PRG6BefhqrBKrQ0ncL/Xv/lWpS31QQo6DBsRZBZYhB74Vi499BTgvNfPS6MvzgebM+vDFdBqTNCUZKVCKkyTFo1E+iF5lNKd0TFAeMJylaRLAjKQ0SRNEw2WBcYbz/uAgYqyE8EfPRN4DE1Jvb6XnuzujVEwRTpMsz/MsJzih4yJIYYRzOg5wQUmGCUlGNIhRlIyTlOIijFTghNCTFmixsky7jbFV9GTTR+atfMjQ4ubtp9Vi9f1li/ZWVtLLBhxiQsTndnSv9GYlFQQHT+7VVj1JLIy+A2dqywFtrKlmLhQuRJyPMtKt5CVB43xYadi6W3q2DbqbB8YQaLZWIEJEvK2hoy2ZFpw5r6AdbWW2WwVvau+Nji/efZvNQlLa2kG0qTVvjY75DvgPEP1Tgv5P+Mi+OhrVG/Qmzj8qmB6avZbV3ljfGhAjNPRQ7VXIoRuu60DziDvX0ibDE2kiZBNJcV32/ol42Yu4Ys6Fm02t1FL+hLI3nQxD/V80ZbqsfG7AKvbYluzI9MMBRAhNhuH4nOWNUWtmzzr+AQ)
> 
> [1.64](https://cesium.com/downloads/cesiumjs/releases/1.64/Apps/Sandcastle/#c=lVJdb9owFP0rES+kEjPOZ8vGqrGwbmGFDggtIKTJdS7g1rGZ7UBh2n+fgTJ1Hy/LS+zrc+65Pj4JaFYWKJUC5TAnJTctSkHrTD6CcN46Vdh2lvcfKbthnXS0S70eS3UqBhFN0jh9XI1vk04DWdC3/OOjBaXbSXFVdNvThynDwTRLd9fZoOi1J2ZSdMPu0FtOi9H2Juvx6V0/7Plddp10VlPbrPswiux6N/Ebm+m4y264ZpNxb5uyDZta3Hi4YeTuCqcP8qmXLTa9Xd/vtvu7eR+lOOrQQTZKRi1vcDf2t1j2yddVmF/dxmZBWp8/qWQUtR74Iq2+mYmZWBPlrBlsQNkrCtg4ydGG20PNrdLDNpHCECZAVWvO95lw7GdAKVv6ouSa5aBen4hUATFwJxXPsyPEPZuJH2dHtUNXpCkIQJQUoAjSYPZi7nPfHLRhghgmxeuXAyVEGbsiInC9IPBCr4EC7PsBPj+Pas6rMI7i+MJDka3hMAh8Wwy9IPYDH8X2sIFxiKOz2lFEKgb2Rn+JfAKSM7H4wgxdDiTnboxw4IdRFIWRh/34omGlMMJRfGHLjdgLsef557EVi5F/4QcxbtiRGtj34pMWiDxTROi5VIXzy6YuMYo9hShtf+hlaTb5t0UrxQpm2Bo0InnuvrTj8AvaGeNgHTy5Vyr+S8ImeQBalooCmitZtLQFprkbnYfe4Un+JSi1sU+6z/3QkIXVnT8RgkCQew65jYhRJRxoQyJySrThsB8tk4sFh/elMVK41atxq2WTssfWnHkp6N5oly6BPkJ+dkrQ/wk/s988G1WpVZrabDlcHpu9Y8VKKrM3wEWobqBYcZtDXb8vLc0gqvWe1qyfSM2crR2Wv51V/oj4rOJQTrS2J/OS8yHbwaxy2axb/G80Lg9ZuVmD4mS7hyy9y+tjESHUrNvt3ywjJb8n6kXHnw)


![image](https://user-images.githubusercontent.com/40989006/75260079-fc681280-5823-11ea-9b53-30ab7d2ff4ae.png)

**Comment by happyfeet1996** [comment]
> Ah maybe the difference is that `viewer.useBrowserRecommendedResolution` is `true` by default now.
> 
> @happyfeet1996 try this [Sandcastle](https://sandcastle.cesium.com/#c=lVPZbtswEPwVwS+RAZemLtpOnKA5WtRAjyAxegB6Yci1Q5QigyXlJC36711ZceCmfaleJA53OKvZ4UZisjFwD5gcJw7uk3MIpm3Y5y2WHqjt8ty7KI0DPBglP2uX0BMBkaBL9BujAQ93RIUgI3zxaPWyL0mHtfs1PKpd7Xol1gY4Q38fAK9A+aYBp0FfQfC2jcY76mQlbYB9SlDggCnZAEoWIHb9pU+taAjRONlRD/f/4VxipC/pijQriqzMZqzgeV7wyaQaJa9KUQkxzVhFGC+LIiewzAqRFzkTtDnjvOTVcNSLeDRAJvwl8g6kNm59aaK6vfLWpoLxIi+rqiqrjOdiOiMpznglpgTPRFbyLMsngsQEy6d5IfiMWprxPBM7LfJjidKFlccmeXb2g4xoHkq2uHjzcblYfnvpam/RHZrGRLOBwKTW6b4d21dxsTQWyMGdey3aZ4mFd90YWlTAVuib00CFC51WkzLbTvFfgj5ESgEFJVxHuSbd1YOUDJy8saBplhHbfpTX0mklQ7TQtbb067WFszZG79KDt19PTylcXe0oWbVOdUan6hbUd9DDXej+T/iJffRk1GA0mIf4aOGkP+y1ae48xs6AlLFxhObOUnTD+KYlWmQqhI42H+9Ic202idHH9eDFragHibIyBNpZtdZemx9QD07mY6r/g2b9NiufNoBWPnYlt9nJ+x5kjM3HtPybFb23NxL3TvwN). It should look closer to 1.64 (on high DPI displays where the difference is noticeable).

you are right, this example is closer to 1.64.In my application that use cesium 1.66,i used flashlight,but when i changed to sunLight,this difference still here.

**Comment by happyfeet1996** [comment]
> @lilleyse good catch. That definitely changed and would have a big effect on high DPI displays (I really should switch to 4K so I can catch these things)

![image](https://user-images.githubusercontent.com/40989006/75261710-6aadd480-5826-11ea-964e-71fb9351b32b.png)
![image](https://user-images.githubusercontent.com/40989006/75261749-7dc0a480-5826-11ea-9b75-a6ce8923f729.png)
the first photo from cesium 1.66;
the second photo from cesium 1.64;
i used the same screen and browser, i used window10 and my gpu is nvidia gtx1060, browser is google chrome

**Comment by mramato** [comment]
Sounds like the mystery has been solved.  I also switched to a 4K monitor so these difference happen for me now as well :smile: 

Thanks @happyfeet1996 and please let us know if you still have questions.

Thanks @lilleyse for realizing what the problem was.
