### ISSUE TITLE
Polyline regression in 1.67?

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8663]
Load simple.czml and zoom to GeoEye (after animating some so it's partially through the orbit)

![image](https://user-images.githubusercontent.com/1495196/75936622-a7925080-5e50-11ea-8895-5ed85270d27f.png)

In the above view, the polyline is clipped (the line moving towards the left should go all the way to the end of the screen) and there is also some weird break in the distance on the right (this should be one long continuous polyline)

Any ideas? @kring @lilleyse

**Comment by kring** [comment]
I haven't found a view where I can see that break on the right, but the clipping on the left could be a result of the log depth changes. When I turn off log depth it looks the same in 1.66 and 1.67 (though kinda dodgy in both), but with log depth enabled it's clipped sooner in 1.67. I'll take a look.

**Comment by allinempty** [comment]
I run into the same issue

![image](https://user-images.githubusercontent.com/38897850/77148499-a7d65100-6aca-11ea-9253-7fe2ee764d10.png)

**Comment by OmarShehata** [comment]
@allinempty what version of CesiumJS are you testing? Does this produce the expected behavior in 1.67?

I'm not sure this is a regression. It can reproduce in 1.66:

https://cesium.com/downloads/cesiumjs/releases/1.66/Apps/Sandcastle/index.html?src=CZML.html

Turning off log depth with `viewer.scene.logarithmicDepthBuffer = false;` does fix it though.

**Comment by allinempty** [comment]
@OmarShehata I can reproduce it in both 1.66 and 1.67.  Turning off log depth can fix it in both version. Thank you.
