### ISSUE TITLE
Not allowed to add more then 250 label

### ISSUE THREAD

**Issue by serviVeroulo** [CesiumGS/cesium#8681]
dear sir,

i want to add a large number of labels, the maximum number allowed is 250, and i want to add 1500,
when i add a number of labels more then 250 the application freezes, is there any way i can do it??
i tried suspendEvents and resumeEvents but still the same result appears..
i am adding labels with viewer.entities.add(label);
any help ?

**Comment by GatorScott** [comment]
There is no limit within Cesium related to the problem you're having.  I'm able to display over 10,000 on my laptop.  There's something about your specific situation that is causing the problem.

BTW, Github issues are used for bugs, that are ideally reproducible in Sandcastle, and features. 
 Please take your question over to the [Cesium-dev forum](https://groups.google.com/forum/#!forum/cesium-dev) and supply as much information as possible about your application, data, and environment so that someone there can help you.  That information should include your deployment environment (e.g. browser, operating system, and graphics card details).

**Comment by serviVeroulo** [comment]
Thank you.
this is the link on dev-forum, i asked how to add large number of labels, because it seems i am doing it in a wrong way.
[https://groups.google.com/forum/#!topic/cesium-dev/bsSL1tngOJ4](url)

**Comment by yankai12** [comment]
I also encountered the same problem
