### ISSUE TITLE
Pick/drillpick imagery layer

### ISSUE THREAD

**Issue by OmarShehata** [CesiumGS/cesium#8692]
This was [requested on the forum](https://groups.google.com/forum/#!topic/cesium-dev/r_yEsNdUwkc) to be able to use something like `scene.pick(mousePosition)` and get which imagery layer(s) are at that location:

> Most of our use cases are about picking local imagery and doing things with them. They often overlap, but can also stand on their own, and there's functionality associated with each, even a multitude (like a spreadsheet associated with several orthos spread out across a local area).

I think this should be fairly straightforward to compute in your application, given that you know the extents of the imagery ahead of time, can convert the mouse position to a location on the globe, and see which rectangles have that position inside, but perhaps this is something that can be built-in if it's a common use case?

**Comment by shelterit** [comment]
And just to add some additional .2$, as a developer I'd love to leave the Cesium map to Cesium, and so if I click on the map, Cesium should be able to tell me what I clicked on. That it only does this only for some things on the map seems a bit odd since Cesium put those things there.

Yes, I can write all sorts of code to simulate a click handler, and we already have a layers stack so I can work it out from there. But it would be great if, say, the drillPick(...) can return entities, imageProviders, tileSets, etc. so that my interaction point with Cesium is limited and focused. Makes for better code. :)

**Comment by OmarShehata** [comment]
This came up on the forum again here: https://community.cesium.com/t/imagery-layer-picking-in-viewer/9777

> I have a base map layer, then a number of drone imagery layers loaded via ION. These layers may stack or only slightly overlap each other.
>
> I need to catch which layer has been clicked on by the user. I do this with entities using screenSpaceEventHandler.setInputAction, but can’t get imagery layers to work in a similar fashion.

@lilleyse can you confirm it isn't possible to "pick" imagery layers in CesiumJS right now? My recommended alternative here is to collect the bounding rectangles and see which ones have the mouse position inside. Perhaps it wouldn't be so hard to extend our picking system to imagery layers so you get the same pixel perfect picking.

**Comment by kring** [comment]
Is https://cesium.com/docs/cesiumjs-ref-doc/ImageryLayerCollection.html?classFilter=imagerylayer#pickImageryLayerFeatures not what you're after?

**Comment by OmarShehata** [comment]
@kring no, the goal here is to find out which imagery layer was picked. As far as I understand the use case here is you have each drone flight's imagery layer, perhaps a small area, and they're all next to each other.

If you try this in the Imagery Layers example (https://sandcastle.cesium.com/index.html?src=Imagery%20Layers%20Manipulation.html) none of the layers actually have features, so they all return "no features picked".

**Comment by lilleyse** [comment]
Looking at how `pickImageryLayerFeatures` is implemented it doesn't seem too difficult to make a separate `pickImageryLayer` function.

**Comment by lilleyse** [comment]
There are some downside to the rectangle approach. Since it's not pixel perfect it will pick imagery in several situations where it shouldn't.

[Transparent imagery](http://localhost:8080/Apps/Sandcastle/index.html?src=Imagery%20Layers%20Manipulation.html)
<img src="https://user-images.githubusercontent.com/915398/124369378-54453380-dc39-11eb-9e29-502a6f0aa724.jpg" width="400" />

[Imagery Cutout](https://sandcastle.cesium.com/?src=Imagery%20Cutout.html)
<img src="https://user-images.githubusercontent.com/915398/124369405-a5552780-dc39-11eb-9c2d-11c0e9dc6331.jpg" width="400" />

[Imagery Layers Split](https://sandcastle.cesium.com/?src=Imagery%20Cutout.html)
<img src="https://user-images.githubusercontent.com/915398/124369504-5d82d000-dc3a-11eb-9efa-cc0f5c8c4d55.jpg" width="400" />

[Day/night split](https://sandcastle.cesium.com/?src=Earth%20at%20Night.html)
<img src="https://user-images.githubusercontent.com/915398/124369540-a8044c80-dc3a-11eb-8985-15721aa180ba.jpg" width="400" />

**Comment by lilleyse** [comment]
As I was reviewing https://github.com/CesiumGS/cesium/pull/9651 I started to think more about what it would take to implement per-pixel picking. I'm abstracting over a lot of details but the approach would be something like this.

Create a pick id for each imagery layer. I'm not sure if this would go in the globe or in the imagery layer itself, but the globe would eventually need access to the pick ids.

```js
var pickId = context.createPickId({
  // This is slightly awkward because imageryLayer isn't actually a primitive
  // But it does have a show property which is required for drill picking to work.
  primitive: imageryLayer
})
```

Each globe tile has a set of overlapping imagery textures called "day textures" that are sent to the GPU as a uniform array of samplers. There would need to be a corresponding uniform array of pick colors. The pick color is the 32-bit integer ID packed into an RGBA8.

Next is crafting the pick shader. The point of the pick shader is to render the pick color instead of the normal globe color so that the rendered imagery can be identified. The pick pass works by rendering the scene and then reading back the color and finding the pick object associated with the color.

Special care is needed so that the pick color is not modified in any way in the shader. Brightness, contrast, HDR, atmosphere, fog, and other effects need to be disabled. Alpha blending of imagery layers needs to be disabled. If a texture has any amount of alpha it should overwrite the pick color of the layer below it. The imagery alpha channel is important but the color is completely ignored, except when using the color-to-alpha effect. If the final color is completely transparent then the shader should call `discard` so that no pick color is written.

This may also require changes in `GlobeTranslucencyState`.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/r_yEsNdUwkc

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/CesiumGS/cesium/issues/8692 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.

**Comment by lilleyse** [comment]
Opened a separate issue for pixel perfect picking: https://github.com/CesiumGS/cesium/issues/9695
