### ISSUE TITLE
Direction of image on a wall is inconsistent

### ISSUE THREAD

**Issue by darkpaw** [CesiumGS/cesium#8708]
A wall with an image as material seems to usually apply the image as a texture in the direction of the path given for positions, but at other times it applies the image in the opposite direction.

https://sandcastle.cesium.com/index.html#c=3VdNb5wwEP0rFheItDX7RSptyartNlIPUXpI1T2EaOXAhLXqD2QbVpsq/70GE2WT7CkClXQ42B7PPMZ+TyOoiEIVhR0odIYE7NAKNC05/tX4Aj9tlispDKEClH/yKRH1U9m89fmaMGbzHAAGYaihoDHJsuBPIpA1QTigBfJ3dSQxaAs03xp/5HYb7wK1sbUVUlsMKbR1t6WsiDJ2RsQM3ynJv0GuAPQXpcj+e4Omg+vJfIzHI/RhNq2H6bg2O3vCfaNNomO4NycHyJwKykvelmLLvp64lyM33hzGEgOKkvrM/taYQi/CUBORpUQbBthdNk4lDyknOejQXcHmQuZys5JMqs2PChQje1yI3HfAD4l4cLTUpJyvh0PK0+VFnZIyP4Y7fFK+gsj01bComXVNTfSI+7Efzmdv5vwfce+6pON+OgjyuyNj3pN65l2rJzpW8HtQz0HnuBxW54h64j7C0346R/SOO8fl/9Y5TntSz2nX6omOFTx09bTf6E4v91LynzJ4oZ460Bt5sTZ7BksH8JnyQiqDSsUCjEMDvGC2UB3elulvMDjVTVocPibFGa0Qzc4S78V/QuKhlBGt7c5dydgVvYfEW8ahjX+WxiTJqMjbs9Qh28nywjkxxnFol6+zjJTslqgDxL8

**Comment by darkpaw** [comment]
This might sound trivial, but if you need to programmatically add 100s of features, it is impossible to know which direction they will be displayed in.

**Comment by OmarShehata** [comment]
[Here's a Sandcastle](https://sandcastle.cesium.com/index.html#c=3VZdT9swFP0rVl6SSp3TrzAJQjXWIe0BwQPT+kAQMs0ltfBHZTupCuK/c1OX0bE+VclWzS+Or+85vj5HN3LFDKk4LMGQU6JgSSZgeSnpz3UsCmfr5UQrx7gCE3ZOMlUhhssCASGlMZesABt73N2FLvSdrsAItqILVYSY7xHT8ykTAkH+OArKccfBUpbn0XOmCA7FJJBjEi7rTObIHHgxd2HX766jx2STW4+FtsihlcXwpvAJMw6/mBrSB6PlNygMgD0zhq2+r9lsdNMf9WivSz4NB/U06NUDv9559xz9ZBfvbWeLWXLFZSk3pWDZN31/OPHz7XYuc2A4q++Mcvv4S6ZeOr80PZ8ejqbvd08a1XS0i7d1Tb+Cyu31YSk7bFrZ5I33czuWDfe2bD/r/C/GWzc4CO+a03LUkvmjps1PdhX8F8zf6tvLw+rbpCXrEjpop2+Tf9e3l/9b3x61ZP5R0+Ynuwpu2Xy031v9pLX8oaMPxndOgm6QWrcSMPbQL1wutHGkNCLCt6cDuRB4go3vy9kjODqztmZO4zdQmvOK8Pw0Cz68ZLOAzASzFnceSiGu+RNkwTiNMf83mNAs56q48k/aOmXeH1/4IKU0jXH5J8ppLe6Z2WJ8BQ) that's easier to run locally for debugging since it uses the right local URL for the image. 

I can see from your examples, looking at the last two walls for example, that their coordinates are defined in reverse order but the texture is pointing the same way. It looks like the texture coordinates are computed here, but I'm not sure why it's consistent: https://github.com/CesiumGS/cesium/blob/4603fd33e40db78c0baf9531ad301f64d9d63049/Source/Core/WallGeometry.js#L431-L498

@hpinkos can you confirm this inconsistency is not intentional behavior?

**Comment by hpinkos** [comment]
Well, it looks like the code is doing this intentionally.  I can't for the life of me figure out why we would want it to work this way though.  If you remove this block of code it should fix the problem:

https://github.com/CesiumGS/cesium/blob/master/Source/Core/WallGeometryLibrary.js#L131-L147

**Comment by nmschulte** [comment]
Doesn't the winding order affect (back-face) culling, and isn't some GPU hardware optimized to support a particular winding order?

https://github.com/CesiumGS/cesium/blob/2fd0e8f7e4212bd1e7084299187f70597a6bbfd8/Source/Renderer/RenderState.js#L93
https://cesium.com/docs/cesiumjs-ref-doc/global.html#CullFace
https://www.cesium.com/docs/tutorials/geometry-and-appearances/

**Comment by hpinkos** [comment]
@nmschulte yes it does, but that doesn't come into play in this case.  Winding order determines the back-face culling of the triangles used to draw the wall, but this particular issue is related to the order of Cartesian3 positions the user passes in to define where the wall should be placed on the globe

**Comment by darkpaw** [comment]
Thanks all, I have more of these to add and it will be a lot easier now! 

(Select 3D on the right)

  https://minview.geoscience.nsw.gov.au/#/?lon=146.4093&lat=-33.48897&z=11.3&bm=bm2&l=ge68:n:100,ge69:n:100,ge66:n:100,ge61:n:100,ge62:n:100,ge63:n:100,ge612:y:100,gp7:n:100,gp1:n:100,gp3:n:100,gp2:n:100,gp6:n:100,gp5:n:100,wa1:n:100,ut8:n:100,ut7:n:100,ut1:n:100,so9:n:100,gp118:n:100,gp11:n:100,mt2:n:100,wa3:n:100,cl10:n:100,dr1:n:100,ad0:n:100,csa03:y:100,csa00:n:100,csa01:y:100
