### ISSUE TITLE
Documentation: duplicate PerInstanceColorAppearance

### ISSUE THREAD

**Issue by KhochkinNick** [CesiumGS/cesium#8721]
Look documentation by uri: "https://www.cesium.com/docs/cesiumjs-ref-doc/Appearance.html".
In section *See* have reference duplicate for **PerInstanceColorAppearance**.

*See:
MaterialAppearance
EllipsoidSurfaceAppearance
**PerInstanceColorAppearance**
DebugAppearance
PolylineColorAppearance
PolylineMaterialAppearance
**PerInstanceColorAppearance***

**Comment by OmarShehata** [comment]
Thanks for pointing this out @KhochkinNick ! This is because the code doc here has duplicate mentions of it: https://github.com/CesiumGS/cesium/blob/70478525bd196b7cb30bd3669dfc51082adca6ee/Source/Scene/Appearance.js#L24-L30. 

We're happy to take a pull request to fix this! See [contributing guide here](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#opening-a-pull-request).

**Comment by OmarShehata** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/8732.
