### ISSUE TITLE
Cesium viewer takes a long time to load the first time

### ISSUE THREAD

**Issue by boriskogan81** [CesiumGS/cesium#8723]
Hello,

The Cesium viewer doesn't load imagery on the first load. Subsequent loads seem faster.

You can see the screenshare video here:

https://youtu.be/AtCB0u0XYEE

I'm using Cesium in a Vue app, using the Vue Cesium library, version 2.0.0, which is using Cesium 1.63.1.

Implementing it like this:

```
        <vc-viewer :requestRenderMode="true"
                   :infoBox="false"
                   :geocoder="geocoder"
                   :terrainExaggeration="100"
                   @ready="ready"
                   :camera="camera"
                   @selectedEntityChanged="selectedEntityChanged"
                   @moveEnd="onMoveEnd">
            <!-- We loop through our community billboards and render each as a Vue-Cesium entity -->
            <vc-entity v-if="billboards.length > 0" v-for="billboard in billboards"
                       :ref="billboard.id"
                       :position="billboard.position"
                       :billboard="billboard"
                       :key="billboard.id"
                       :id="billboard.id.toString()"></vc-entity>
            <!-- Our Vue Cesium imagery layer. We use Bing Maps -->
            <vc-layer-imagery :alpha="alpha" :brightness="brightness" :contrast="contrast">
                <vc-provider-imagery-bingmaps url="https://dev.virtualearth.net" :bmKey="bmKey" :mapStyle="mapStyle"/>
            </vc-layer-imagery>
        </vc-viewer>
```

Browser:
Chrome 80.0.3987.149

Operating System:
Windows 10

**Comment by OmarShehata** [comment]
> The Cesium viewer doesn't load imagery on the first load. Subsequent loads seem faster.

This sounds like when you're loading data from your cache it's faster, which is expected. 

I did take a look at your video - it does seem unusually slow, but also the requests that are taking the most time seem to be requests your app is making that each take 2-4 seconds each? If you're able to reproduce this unusually high load time (and you're convinced the issue is not in your network) please submit a [Sandcastle example](https://sandcastle.cesium.com/index.html?) showing the issue.

Otherwise it may be something you can optimize in your app. Feel free to search through the community forum (https://community.cesium.com/) or post your question there to get some more idea on how you can optimize this.
