### ISSUE TITLE
WMS service will occupy 3dtiles network request resources

### ISSUE THREAD

**Issue by xianxuLi** [CesiumGS/cesium#8730]
WMS service will occupy 3dtiles network request resources, which leads to the slow loading of 3dtiles. How can I solve this problem?

**Comment by OmarShehata** [comment]
There was some discussion on this issue here: https://github.com/CesiumGS/cesium/issues/5954. 

If you are seeing a significant delay in 3D Tiles loading when having an imagery layer in the scene, please provide a minimal [Sandcastle](https://sandcastle.cesium.com/index.html?) example that demonstrates this issue.

**Comment by OmarShehata** [comment]
Closing since no reproducible example was provided.
