### ISSUE TITLE
Error: Missing or invalid spatial reference system

### ISSUE THREAD

**Issue by anaezes** [CesiumGS/cesium#8734]
Hi, 

I'm trying to upload the given ascii file to ION but I get the following error:

> 
> Error: Missing or invalid spatial reference system
> File: Area of interest.asc

The file contains bathymetry data downloaded as a esri ascii `.asc` from https://portal.emodnet-bathymetry.eu

Is there anything wrong with the file or is it not supported?

[attached file](https://pastebin.com/VEz07StC)

**Comment by OmarShehata** [comment]
That file doesn't seem to contain a spatial reference system, which Cesium ion needs in order to reproject if needed.

It looks like there's an option to download a GeoTIFF version of these assets from that portal. Have you tried that?

Note that there are some known issues with bathymetry rendering, see: https://github.com/CesiumGS/cesium-ion-community/issues/1

I'm going to close this issue as this is not specific to CesiumJS, but if you're still having trouble getting your data into Cesium ion, feel free to open a new issue on the the Cesium ion community repo (https://github.com/CesiumGS/cesium-ion-community) or on the Cesium forum (https://community.cesium.com/).

**Comment by GatorScott** [comment]
There's another option when you download to get a 32-bit GeoTIFF file.  I downloaded one of those and it had the necessary georeferencing information (though it isn't strictly clear what the vertical reference is, but I didn't look very hard).
