### ISSUE TITLE
camera.flyTo is choppy on Firefox

### ISSUE THREAD

**Issue by puckey** [CesiumGS/cesium#8745]
I noticed camera.flyTo performance on Firefox is choppy, while things like zooming and mouse interaction are smooth as usual. To reproduce, visit the sandcastle example below and select a destination in the dropdown to start a camera flight.

Sandcastle example:
https://sandcastle.cesium.com/index.html?src=Camera.html

Browser:
Firefox 76

Operating System:
MacOS Catalina 10.15.3

**Comment by OmarShehata** [comment]
@puckey do you still see choppiness if you switch to the Natural Earth base layer?

![image](https://user-images.githubusercontent.com/1711126/79047806-02a12b00-7be7-11ea-88e1-3e45b3668f23.png)

My best guess is that it's the imagery tiles loading on the main thread causing this stutter. In Chrome CesiumJS uses createImageBitmap to load the images off the main thread but the `Resource.supportsImageBitmapOptions` check fails for Firefox.

**Comment by mramato** [comment]
@OmarShehata Do we have an issue regarding the FireFox bug/limitations?  I couldn't find it.

Using the JS profiler here should also make it pretty obvious if it's easily reproducible.

**Comment by puckey** [comment]
I don't think this is related to imagery being loaded, since the choppiness does not occur when zooming in and out manually or dragging the globe around by hand... I noticed it on http://radio.garden and then double checked on the Cesium sandcastle to make sure it wasn't on our side. Haven't had the chance to do any JS profiling yet..

**Comment by puckey** [comment]
@OmarShehata Sorry, to answer your question: I do not see the slowdown when using switching to the Natural Earth base layer.

**Comment by puckey** [comment]
@OmarShehata oops - scratch that, I checked in Chrome by accident. Using the Natural Earth base layer, I am still seeing choppiness during flights.

**Comment by OmarShehata** [comment]
> @OmarShehata Do we have an issue regarding the FireFox bug/limitations? I couldn't find it.

We don't, because it isn't really specific to Firefox. We enable ImageBitmap loading on all browsers that support the full ImageBitmap API (loading and being able to flip the image on loading), which just happens to be only Chrome right now. Once Firefox supports the full API it'll work, so there's nothing actionable we need to do for it on our side.

> Using the Natural Earth base layer, I am still seeing choppiness during flights.

Ok, that (most likely) confirms it isn't the imagery then. 

### My profiler results

I used a version with no imagery, but with the tile coordinates layer: [sandcastle](https://sandcastle.cesium.com/index.html#c=7Vpbc9u6Ef4raM6DpEaGdacUJ5m6ijzRjC8ZWzmZtu5kaBKSeEwRKgnKcTv+711cSAK8SJSTvlUPiQQssN9ivwUWC+/sEO088kRC9AEF5AlNSeTFG/y7aGs2HPFzSgNmewEJG62z+2AHYyKHBASGyLFY/FRdjk+dx6xL/FRdIVmSkAQOuQjtDfkSehuPeTs+8D5YxoHDPBqgpf+8oHd28MkjK9psof/cBwg+0OI6dsR8gl3i+HZImoYkR8blErWgILSxEGmqKfjHJRHzAltoepdYO7VDBt/soI+XId18IquQkKh50u1auDtqo34PW9026g47nQ7utORsL1zjSxH6Z2K7XrD64jFnfUt9/7AJ+RH/E1N6PdzrtdFghLvwn7Kknc1GQ4+Al9Vsmhr+WUuEmZorm60xo7fQbAdRs5ebjH+23JzKESf9YXFICMbDCJgsa3/Zv9qX1BGYD69yItkSdOOSp6doGhKbEeTYvv9gA22XNEQPIX2KgOsRWhHqq1FyhK67uaWRJybUV+uAz471W6IDO5SGboR9Gqw8FrukjQpdMKPs6eo0TRdPLWZq+nn0mJgqzE4sbSNYQG4gYmuIViwHBPbOW9mMhlhbFPjOpnEIIc2+KDR8rYuu4qtySxxmByuf7HWVIZm5iu8eT7BusK+cWBbunGXNEY3ZGtr7Y6OZ2Eq6ZzQHNBTSA9mcdYSJUuhUPklxGC7hMNpSa1toactJy6M2IozvpRVx+y5Tq9E8ddHdmj5xL2RSGKFryuD3v2IvJO4Z+iMGM7n7IpDFBgLwCriERNh2XV1/ZmkhzgWVODYSIQ1bLkyXngjTpe1H+S5YFR8OCuhlYVzROQX+hBrz+U/87fN8Masd9fW4ZIqWk2nSOYZMY6ucTOYkv4RKrzgC/s+lI7kEwXlrpCR76VSQNhkFKRATadSBk9ga4uHEsqy2oE1/PO63NO6wEE5H8MEmm2iRNEWYc+SaM+TrdkEvvB/ElbClbsPffNdBXiBodSJYdRJv0ZKLa5gFr7RkTfxWcBTpHBpEgAoW2z3/4UWlBn69ni++/90c51P6eM5S8M3UsraeaGaT8BylI06uNtK+Jt9aRTan6aQ0K8dnReCKnBPMEEkr3iYtktsatE/kIV5dUZf4kLuE3o90rB4Am6xfEDWxMZPwSbBiPBHix3InzW1eWqV8PCp7LJHPcbKGf/efUIczS87n8SCh88RK84/y5HJPbnmip4pf5t9vfp/dfl98u6lILEvFL26+3v5UVuk54bIpqNFGzIMgT/B6SyTbMfc5+tOHNBDueCsnCr6bzq5n/U9GRhgSFodBPgHj3uGqVBiXRrtDN9uYkXkmJonWFLjOMlhqqEuWPEqb2rwtMzk9RIlEiC6XQIvSUIf7XAAbjuROmgLnxpfsYhL6QHDnlkouCFt9mb/roLXZDm8mEquW4RZTz3kwn95eHMw7pdiew/czhb22kwmIuy3exD7ztr4nNv8++jMadcQ/CpHaZmjEvm5dOA35NjPbQThcehGDrlCY3jKkVz59IHDo2g8+ufRWa8YD5IM4BxPC7tTNfbqGY1UQyKVOvIF5eVY+8wn/+tfnudtsaGINCV5mKRu6I3cMXHumt8wC17yQS/sF5GjvGuqCR+xDGhCQUKudNhWXKwHWLFy8lJE4Ys8clhdtffsZ5mw8cEc1zrSgzxSDvaZaaPglSgMIFENn6jeprIbnDMGC71R7mbdkVx13KUnTXx6A6hirlIE1o8JR1lcv2JaEPD2xV8RYurdvvUKYJ0vpBTDDgvzgfGhMJXdU3zvUQG8B31vUaIuv2fSYye2jOWpVzlyDGYXrxjw4n3rs+dBVQ4lVEF/Gddn5+3N1HauPJ+PhuDPp90Zdqzsei3PYGowH/UFnNBpPBuNeG/VHfQy/+2OrZ/UGo15voJ/O/JzxCeOZdjnNxcZE2AKOHci7m9VC+8x6bQkkMRGS5uHImoAV0sShNZxMBoMuWDTkxbnxCA874/54OIR0pGtZk3x1qVal67iqV0nZ64gS2NCs0uifl4pZIZsHRBcJO9OpZ0Y7vpxfz85vv1/fXM+K87zo4SGViZRNb67Oj3wanUMo+SRa0AV9fKZN2+UXR5GBpoTYx33tssPH32z5vPxe8coY6PYneNwdAPP7Q2x1B8D35M5wdApa7qnu8Ojy5qhecVOTceNQoet1tGaIo5sdCS+Twl+VxpFWmTYW2bd/eoVFIdzqTWCFB3gwVCl+boEz/MNftOwn+9b9V2T/6Tqla4TTvfBDxV5Yax809kCd5UaMmWGXoeEpfVlQ8Y8+GRZrcS4kPxOeJgJqPqWmJLPsgHB6MzGwp8NLT0aDmKWQy49KY1xif3FjOazzm8fWQmHzGI3pqGrVPNNO1WtTQpqzoNR/sMMrEsTNfyiljOcq79JcRa1ZA8a3UU7kwn/mZRkbOZAsNBRZQRi0O6zyBNbTEM27GrI1uNTnbs3lIsmlqBQIo3wKJB7QjsGiP9DVgFN8pduHKHmoQU/gp2STaKvA528TPKSPQ1usqtRCXfUwtw/91XNqwHEYs5esWtj056xDmNLq83GItCp7LUhGqb0SkyhM2q/AlHtEOgSp8JJUieiOsCRZyZUUa2MrqSQfwldaTq6DsSQs2sfHRWmtsQbmo2IiKULzuspRfk4qNnWcnJVtKnFcwQ0WEVGYqA3DLHscApKvfVRCUUeEujdLUEdiSi/39UBpN/y9GwXP+GDvipA6C/nOIU5D8IiNZnFIt0dtIGZ2UGcLKc0LSvFeUvqIXPoU8LST55Dkh71agbGM8LdrPuGroWpJxbGYC5mFLEf+UxYFtClCIuurRUTqsqTS0CsabjMc+cc4WZo51yK38KYhRZoVryDmMPZESJCftbLKrJXtWrmCd9phrGBabtPmrV1EK50eBOJA4SlTVNL/ctAiBaXMJtVVYlVWHtMV1q5CGaXC8vJzvgKeK6vPP82uF/PF3/YWp7u4siit1ux1dWnxesuzZaE8eSQB5k4VjevUU/PRIdN/VfOUS+FtbIjx50v7mYR5npaKgNq5bPgS0p3ngmLtgW/h+WSavVLnJVtwnX7TfvNeeOujBPkXb7OlQLw49JsYnzIC9vGxpw+x80gYdiKtkvqbxuw2+s2s+upXcUmEd4jTQKMW/4ukVUiBUScOf9jmr+g6z1Xj09pjJCPP+9ME8HvX2yHP/XD/JvdnfPdvgB12FEHPMvb9O+/f5P7Nx/enIG8M86k46/kWB/i4yLr78VI2Yozfn8LP4igmL0ggLjFlPdp6QK9IDtTPZBZT3lgxGGGWglPN6v//Ag). I activated the profiler right after I started the flight so that the averages here don't take into account the pre-flight idle time.

On Chrome running the "Fly in a city" option I get an average FPS of 57.9, with a min 28.7.

On Firefox it's an average of 34.24 fps with a min of 12.03. 

On the lowest FPS frames in Firefox, `createAndLinkProgram` seemed to take the majority of the time, at 42 ms. This function appears to be called more frequently in Firefox and take a longer time each time it's called, compared to Chrome (where it is called during frames with slightly lower FPS but takes only a few ms when it is called during the flight).

My conclusion is this issue is not specific to camera flights. Perhaps it is just more noticable that way, because moving the camera by hand is inherently more choppy. I can see similarly low FPS minimums in Firefox when moving the camera by hand with the profiler on.

**Comment by mramato** [comment]
It's possible that something in Firefox is causing CesiumJS to constantly rebuild it's shaders (like there's a bug in a rendering path that doesn't get executed on Chrome).

@lilleyse you're the first person I think of whenever I see `createAndLinkProgram` show up in a profile.  Any ideas?

**Comment by puckey** [comment]
Hmm looks like I had Firefox set up in a non standard way. I had been debugging Radio Garden for a user who complained it was no longer working with their firefox set-up. They had `privacy.resistFingerprinting` turned on in their `about:config`.

I thought I had turned it off again after fixing this bug, but it was still on. Looks like these frame-drops only happen when this setting is turned on in combination with camera flights. Zooms and other manual manipulations do not drop frames.

Since it seems this does not seem to be [a recommended setup](https://wiki.archlinux.org/index.php/Firefox/Privacy#Anti-fingerprinting), I propose to close this issue.
