### ISSUE TITLE
GeoJSON with vertical line crashes

### ISSUE THREAD

**Issue by silke-boehler** [CesiumGS/cesium#8764]
When loading the folling Sandcastle example, it will crash with following error:

> An error occurred while rendering.  Rendering has stopped.
> undefined
> DeveloperError: Expected right to be typeof object, actual typeof was undefined
> Error
>    at DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Workers/Check-c4f3a3fc.js:62:17)
>    at Check.typeOf.object (https://sandcastle.cesium.com/CesiumUnminified/Workers/Check-c4f3a3fc.js:238:17)
>    at Cartesian3.subtract (https://sandcastle.cesium.com/CesiumUnminified/Workers/Cartesian2-a4e73c05.js:530:13)
>    at PolylineGeometry.createGeometry (https://sandcastle.cesium.com/CesiumUnminified/Workers/createPolylineGeometry.js:389:21)
>    at createPolylineGeometry (https://sandcastle.cesium.com/CesiumUnminified/Workers/createPolylineGeometry.js:523:13)
>    at createGeometry (https://sandcastle.cesium.com/CesiumUnminified/Workers/createGeometry.js:60:21)
>    at callAndWrap (https://sandcastle.cesium.com/CesiumUnminified/Workers/createTaskProcessorWorker.js:61:17)
>    at Anonymous function (https://sandcastle.cesium.com/CesiumUnminified/Workers/createTaskProcessorWorker.js:106:17)

The example just loads one simple GeoJSON Feature of type LineString. If I change any of the three coordinates slighty, it works

 ```
geojson_produces_error = {"type":"Feature","geometry":{"type":"LineString","coordinates":[[7.970063350393387,47.59408093341338,773.65],[7.970063350393387,47.59408093341338,765.55]]}};
 geojson_this_works     = {"type":"Feature","geometry":{"type":"LineString","coordinates":[[7.970063350393387,47.59408093341338,773.650001],[7.970063350393387,47.59408093341338,765.55]]}};
```

[Sandcastle example:](https://sandcastle.cesium.com/#c=xVPBbuIwEP0VKxeCFDlBIaQsKaq21a60qrQHqr00CLnJ0Hrr2Mgeg2jFv3dCugW2Paz2Up88894b+3nGa2HZWsIGLDtnGjbsEpz0Df+1z4W9ah9eGo1CarC9/qTUpZ4JXVfCoQIu6voKlsIrvDFG3Qn71SMaHfZes8zhVkl934vY0usKJWF99txWYbQUILsH89sZvVhZU3s6cAHWmvY+z2WA2xWUwZcy+AYCvaV9VAYkaADtloBjyjXdcIaWDtuzKmNsLbVAcATf3uZ8nCfJKE2zJB2n6VkeDXOejYfJWULhcECpKM9TPsrm0b+RRxnPsvl8t5t0ZuL42A4+SLfYGPvoWuwT7SRJMvgfS4cO1QLFzHhbAdl4nZDvYH6Qzas3iCsj6vDjZvbfynXDxg8VXTtC4SHuT06IT8Y0N+YvfNfVC6KgaMcLpp3kQjYrY5F5q0LOY4Rmpdr3iu989QjIK+daYRH/ERW1XDNZn9Prns55GbBKCecIWXqlZvKJejItYuKfyFrL1KCfa7BKbFvKw2B63SU550VM4XsVdj/lqOIL)

Browsers:
  Google Chrome Version 80.0.3987.163
  Firefox 75.0 (64-Bit)
  Internet Explorer 11.719.18362.0

Operating System:
  Windows 10

**Comment by OmarShehata** [comment]
I initially thought this was related to this crash which happens when you have lines that are perfectly straight (sometimes): https://github.com/CesiumGS/cesium/issues/8464 but it looks like this issue is specific to vertical lines. [Here's a Sandcastle that loads the following GeoJSON](https://sandcastle.cesium.com/index.html#c=xVNNb+MgEP0ryJemUooBY4O7SbRSV1ppVW0PWe2l7oHaZINKIMI4UVr1v3fsJE2q/bguB6yZeTPvAc8bFdDG6K0OaIqc3qIb3ZpuhX8OudFFPYQ33kVlnA4Xl58ql6boq/bf5nff0dbEJdroEE2tLFobXWu09eGpRQuAV24D4xsV1dx3AUrT4/i+v/Xuy3sJW6+a0UuVxN1aV8l1ldzCgHkMxv2qknGV1N6HxjgVdQvle3RPMBmj/fYwPg8p6Vefo0Oc7zHo4fVP4r2zO6ROZ7BAi+qg2iUQAfo/nuCgeP88+CSixappRqf4DPTs/eqHHx0i7aKJRrc94B1Sq5UOCi/sDoAvlUOwGt3GXpnxDl2f2+BGBZBrlMtGRcEZlxIzyYUgXORjdMWyMqMclxmnjOdSCMjxrMhljmGTGaOZJMXleM/igwFFR5YD9UBvgq7/SX5FcFYKmYmSsqIUvJC8v6uCyCIviYTbKhinYsjJgsuM5iCMEl6yI3u/uvVfGQguqWAlkBBGC8ZY2Q9jQgAVzXKek5yKgZTJPCtLIqRghEE6PzK8Hr5NF46HpJWDN0zGyaSNO6tne8Bns1r7EFEX7AjjNOrV2va2SB+7+klHXLfDk03SY9OkMRtkmimY6OP/WCWotqptobLorJ2bZ7DebJIC/kNb703w4R3Y3KpdD1nS2e0+iTGepBD+3hW9t48qnE18Aw):

![image](https://user-images.githubusercontent.com/1711126/79575318-96637300-808f-11ea-8fb2-456b73e0507a.png)

The first two points are exactly vertical. If you remove the last point, it crashes.

**Comment by OmarShehata** [comment]
Also reported here with some additional debugging notes: https://github.com/CesiumGS/cesium/issues/8974

**Comment by TJKoury** [comment]
@OmarShehata This could be related to calculating the number of points in a rhumb line; if you have two points in a polyline that differ only in altitude, then the radians distance squared tends to be zero.

For this particular case making a change will fix the issue.
[Core/PolyLinePipeline.js#L28]:(https://github.com/CesiumGS/cesium/blob/master/Source/Core/PolylinePipeline.js#L28) 

```
return Math.max(
    1,
    Math.ceil(Math.sqrt(radiansDistanceSquared / (granularity * granularity))),
    1
  );
```
I have not tested this for other side effects.
