### ISSUE TITLE
The GeoJSONandTopoJSON doesn't work normal when use Webgl2.

### ISSUE THREAD

**Issue by zk8085454** [CesiumGS/cesium#8771]
Sandcastle example: GeoJSONandTopoJSON.

Browser: Chrome 78.0.3904.108 

Operating System: windows 10

code : var viewer = new Cesium.Viewer("cesiumContainer", {
        contextOptions: {
            webgl: {
                antialias: true,
                audioEngine: true,
                deterministicLockstep: false,
                lockstepMaxSteps: 4,
                preserveDrawingBuffer: true,
                stencil: true
            },
            requestWebgl2: true
        }
    });

**Comment by OmarShehata** [comment]
I can see significant artifacts when running the GeoJSON example here with WebGL 2: https://sandcastle.cesium.com/index.html?src=GeoJSON%20and%20TopoJSON.html but those same artifacts are presents without loading any GeoJSON either. So I'm not sure there's a specific GeoJSON WebGL 2 issue here.

I'm closing this since CesiumJS does not officially support WebGL 2, but it is on the roadmap. See: https://github.com/CesiumGS/cesium/issues/797#issuecomment-617189407
