### ISSUE TITLE
ArcGisMapServerImageryProvider can't show Arcgis Rest MapServer label  repeat

### ISSUE THREAD

**Issue by zhuxiangjian** [CesiumGS/cesium#8780]
arcgis rest services if has text label  , label well show in evevy tile ,actually,one text label should just in only one tile instead of current view every tiles has a same label

Sandcastle example:
https://sandcastle.cesium.com/#c=ZVBLSwMxEP4rYS/bgiR4rdui9CBCRaGgl71MN9PtYDZZJtmEVfzvpq2P2uY238z3SgQWkTAhi7mwmMQSPQ2dfDlgk7I5jEtnA5BFLqc3ta1tzKyenZifMO64uSf/CP0aOSI/dNAij8/sIums9FFbcfIGNmImyl0IvZ8plVKS2+Rl66JKGAxY7RVw05JXjD4on0Uph1Fr6HqDr46NXlKgjPxaln8Wn985Dy0kHbOsYET2ErQ+D5e7TIurovJhNLg4ytxS1zsO+6QTKVXA7Ash+22G5g2DbLzfm1Tqh1RpioL0vC7OPq0uRGPA+7zZDsas6R3rYlGpfP+PZhxosu1TrmJg3J/srherIyilrFQeL1nBObMBPlH8Ag
Browser:
Google
Operating System:
win 10

Sandcastle code:
var viewer = new Cesium.Viewer('cesiumContainer');

var pro =new Cesium.ArcGisMapServerImageryProvider({
            url : 'https://www.fws.gov/wetlands/arcgis/rest/services/SampleWorldCities/MapServer'
        });

viewer.imageryLayers.addImageryProvider(pro)

**Comment by GatorScott** [comment]
This is not considered a bug but an unfortunate consequence of using non-tiled imagery with Cesium.  Because Cesium is primarily a 3D visualization which can result in views that are from low elevation angles, the amount of map detail required in the foreground can be significantly higher than what is necessary in the background.  Requesting an image from the server for a high detail image for the entire visible area could be enormous.  To avoid requesting such an image, Cesium requests lots of images of varying resolution.  Because each image is requested separately, the map server ends up sending details with each tile that would not be necessary in a single image.

The solution from a Cesium point of view is to add tiled imagery support to the server.  Most servers are capable of this in one way or another.

Hope that helps.
Scott

**Comment by OmarShehata** [comment]
Closing since it sounds like there isn't anything actionable on the CesiumJS side.
