### ISSUE TITLE
how to comapre Date property in Cesium3DTileStyle?

### ISSUE THREAD

**Issue by xxbld** [CesiumGS/cesium#8833]
property : 2020-05-07T17:36:27.283

**Comment by mramato** [comment]
These are ISO 8601 dates, which can be parsed by all standard date libraries, including the standard JS Date object via `Date.parse`. However, since JS Dates are limited to millisecond precision, if you care about precision you should use Cesium's own [JulianDate.fromIso8601](https://cesium.com/docs/cesiumjs-ref-doc/JulianDate.html#.fromIso8601) and then you can use the comparison functions of JulianDate to do what you need: https://cesium.com/docs/cesiumjs-ref-doc/JulianDate.html.

If you don't care about sub-millisecond, just use `Date.parse`

Hope that helps.  In the future please ask questions like this on our community forum: https://community.cesium.com. We use GitHub exclusively for confirmed bugs and feature tracking.

**Comment by xxbld** [comment]
@mramato 

This seems to have no effect

```js
var style = {
    "defines": {
        "time": "Date.parse('2020-05-11T09:57:06.654')",
    },
    color: {
        conditions: [
            ["${time} < 1589162226655", "rgb(127, 59, 0)"]
        ]
    }
}
```

**Comment by OmarShehata** [comment]
@xxbld can you create a thread in the community forum (https://community.cesium.com/) for your question?
