### ISSUE TITLE
Add support for PolylineVolume to CZML

### ISSUE THREAD

**Issue by jrafidi** [CesiumGS/cesium#8840]
Looking at https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Packet, it seems like the majority of the Cesium geometries are supported. Would it be possible to add `PolylineVolumeGeometry` to that list?

**Comment by hpinkos** [comment]
Hi @jrafidi, we have an issue open for this here: https://github.com/CesiumGS/cesium/issues/3062

It's been a little tricky figuring out how to have full support for dynamic polyline volumes in CZML, which is why we haven't added it yet.  I'll add a comment to #3062 so we can notify you when we add support.  Otherwise, we would be happy to review a pull request if you are interested in trying to implement this!  Thanks
