### ISSUE TITLE
Sandcastle web editor breaks browser search

### ISSUE THREAD

**Issue by thw0rted** [CesiumGS/cesium#8844]
Sandcastle example: pick anything with more than one page of code in your browser.  I used "Polygon" for testing.

Reproduction: CTRL-F (CMD-F, etc) and search for a string.  You'll find hits in the currently visible portion of the code, but nothing that you'd have to scroll down to see.

It appears as though the later content is being dynamically added and removed by the editor plugin during scrolling.  If it's possible to disable this behavior, please do; if not, maybe the plugin provides its own search capability that you could hook to CTRL-F on the page?  (Of course, if you felt inclined to switch to [a better editor](https://github.com/microsoft/monaco-editor) I wouldn't complain...)

Browser: Any

Operating System: Any

**Comment by OmarShehata** [comment]
I've noticed this too and I always just instinctively copy the full text into my code editor to search..

If someone wants to look into if there's an easy fix for this I think we'd be happy to accept this contribution. I know a lot of the Sandcastle architecture is pretty old and we've talked about refactoring that a lot.

**Comment by hpinkos** [comment]
Sandcastle is definitely in need of a major overhaul, but I don't think we'll have the capacity to tackle it in the immediate future.

Instead of using the browser search function, use the Sandcastle search box instead: 
![image](https://user-images.githubusercontent.com/3451886/81821997-94f76000-9500-11ea-81b3-7e82239b1400.png)

This filters the demos in the gallery tab, but also highlights lines of code where that text is found in the editor.

**Comment by OmarShehata** [comment]
Looks like Ian has a PR here with a proposed fix: https://github.com/CesiumGS/cesium/pull/8847

**Comment by hpinkos** [comment]
Fixed in #8847
