### ISSUE TITLE
Resource Add subdomains attribute

### ISSUE THREAD

**Issue by myhnuhai** [CesiumGS/cesium#8882]
Due to the concurrent limitation of the same domain name in the browser, for example, the Chrome browser only supports 6 concurrent. It is recommended to add the subdomians attribute to support requesting data from multiple domain names.
`subdomains:['a','b','c','d']`
`http://{s}.tileset.com/Tileset/tileset.json`

**Comment by myhnuhai** [comment]
`http://a.tileset.com/Tileset/tileset.json
http://b.tileset.com/Tileset/tileset.json
http://c.tileset.com/Tileset/tileset.json
`

**Comment by OmarShehata** [comment]
@myhnuhai is the idea here that your server would have these multiple subdomains set up all serving the same tileset, as a way to get around this concurrency limit? 

I haven't seen this done before, and I wonder if that limit in the browser exists for a reason. Would this actually load the tileset faster? Have you benchmarked this to test that?

**Comment by mramato** [comment]
@myhnuhai I'm not exactly sure what you are asking because Cesium already does exactly this for servers that support it, such as Bing, Mapbox, etc...

In Cesium ion's case, the server is HTTP/2, which does not have a concurrent connection limit the way traditional HTTP/1 does so no round-robin-ing of subdomains is needed.

I'm going to close this, but if you want meant something else please feel free to include additional information.

If you are simply asking how to set this up in Cesium for your own servers, please post such questions to our [community forum](https://community.cesium.com).

**Comment by IKangXu** [comment]
@myhnuhai override method.
Cesium.Cesium3DTileset.loadJson and Cesium.Cesium3DTileset.prototype.loadTileset
