### ISSUE TITLE
Smokescreening TypeScript definitions

### ISSUE THREAD

**Issue by mramato** [CesiumGS/cesium#8905]
While we compile the generated TS type definitions to ensure they are not totally broken, this doesn't actually check that they work as expected in many situations.  For example that `ImageryProvider` instances actually conform to the correct interface.

We might be able to alleviate some of this via `@extends` and `@interface` in JSDoc, but we should probably add some high-level tests to make sure we catch regressions.  This would be no means be exhaustive, just give us a place to write some TS code when we fix an issue to prevent it from happening again.

I don't think we can actually use the `Cesium.d.ts` file in a standalone ts file without some scaffolding; so my current thinking is that we create a TypeScript folder under specs and put a single .ts file with any smokescreen tests and then we can `npm install` the generated Cesium package and typescript compiler to build/run it just like our users would.  This would happen as part of the build process, but also could be easily done locally as needed.

Is there a simpler approach I'm overlooking?

CC @kring @thw0rted

**Comment by thw0rted** [comment]
You shouldn't have to `npm install`, I don't think, because the only artifact it's actually using for `tsc` is the generated typings file `Cesium.d.ts`.  As long as you `run build-ts` first, I think you should be able to set up a `tsconfig.json` that includes your typings file, then builds the test code against it.  I think

````json
{
    "files": ["./smoketest.ts"],
    "include": [ "../Source/Cesium.d.ts" ],
}
````

should probably be enough.

**Comment by mramato** [comment]
@thw0rted byt how would `smoketest.ts` include Cesium?  If it uses a relative path to the source files, the TS compiler won't pick it up because they are not part of the module.

**Comment by thw0rted** [comment]
The thing that makes this work is that `tsc` does not actually look for or care about the source files.  You're describing the shape of the module that will be provided at runtime by `import` statements, but your smoke tests will never *see* runtime so it doesn't matter.  Your generated typings file declares that a module with the pathspec "cesium" exists and has all these exports, and that's good enough for `tsc` to do its job.

I actually just got this working.  I made a folder called `TSTests` in the project root, then ran `npx tsc --init` and edited the resulting file to include the above two lines.  Note that they're not inside the created `compilerOptions`, you have to add them as top-level siblings:

````json
{
  "compilerOptions": {
    // Generated stuff
  },
  "files": ["smoketest.ts"],
  "include": [".."]
}
````

Then in `smoketest.ts`, I just added

````ts
import { Entity } from "cesium";

const e = new Entity();
const s = e.rectangle?.show;
e.foo = 1;
````

The compiler flagged the last line, because `Property 'foo' does not exist on type 'Entity'.`.

Note that, by creating `tsconfig.json` inside the `TSTests` directory, VSCode will not see or use it, so `smoketests.ts` will show an error in the `import` line.  There are probably ways to fix it but I haven't spent any time on it yet.

**Comment by mramato** [comment]
That makes total sense. I forget just how much of TS definitions are "fiction" in that we're saying "we swear this thing is there and this is how it works" and it just takes our word for it.

I'll see if I can get a basic PR open ASAP.

**Comment by thw0rted** [comment]
I forgot a couple things:

* The ".." in `include` is a trick, by default it uses node-style module resolution, which means that when you give it the relative path to the base directory, it looks at `package.json` which has a `types`  property which points you to `./Source/Cesium.d.ts`.  You can decide for yourself whether this is clever or confusing. (I like it!)
* In practice, you probably want a `./Specs` or similar with multiple smoke-test files.  You could put that as an entry in `include`, which supports glob-style wildcards like `./Specs/*.ts`

If you want an actually useful smoke test, I just ran

````ts
import {
  BingMapsImageryProvider,
  ImageryProvider,
  WebMapServiceImageryProvider,
} from "cesium";

const ip1: ImageryProvider = new WebMapServiceImageryProvider({url: "", layers: "0"});
const ip2: ImageryProvider = new BingMapsImageryProvider({url: ""});
````

which flagged the `ip2` assignment, but not `ip1` on my local branch, because I was testing `@extends` tag on the WMS provider.

**Comment by mramato** [comment]
Only issue I've found is that VSCode doesn't pick up the intellisense itself with this approach.  The compiler does, which is good enough for now, but it would be nice to be able to "go to definition" and stuff to easily see the generated type.

I bet tweaking the config a little could make this happen.

On the other hand, adding a package.json and using `npm install` on it could actually be a more complete test, since it would be a true end-user application in every sense at that point.

**Comment by thw0rted** [comment]
You have a "-quick" version of other tasks, right?  If you wanted, you could have a "full test" that does an `install` and a "quick test" that just builds against the generated typings.  I'm not sure exactly how much time the install adds to the process.

**Comment by mramato** [comment]
These tests will only see occasional updates so it's not like it's a big deal either way.

**Comment by mramato** [comment]
Actually, that's VS Code suddenly started picking everything up.  So I think we're good.  There was just a lag for some reason.

**Comment by hpinkos** [comment]
fixed in https://github.com/CesiumGS/cesium/pull/8908
