### ISSUE TITLE
Switched from version 1.5x to 1.7.0 and now the project result blue screen.

### ISSUE THREAD

**Issue by YordanYanakiev** [CesiumGS/cesium#8950]
Sandcastle do not works anymore. ( Error, first part of bucket-requirejs.html must match first part of bucket.html exactly. )

**Comment by OmarShehata** [comment]
I assume you mean 1.70.0, not 1.7.0. A lot has changed since then - make sure you're following the build guide (see https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md#build-the-code). If you're still having issues please post the full error message you're getting on the forum and any other relevant information about your project: https://community.cesium.com/

**Comment by 123poorchinwe** [comment]
> 沙堡不再起作用。（ 错误，存储桶要求 js 的第一部分.html必须与存储桶的第一部分完全匹配.html。

Hello,I have encountered the same problem as you.Have you solved it?:)
