### ISSUE TITLE
Support glTF animations in 3D Tiles payloads

### ISSUE THREAD

**Issue by bertt** [CesiumGS/cesium#8962]
Hi, is there somewhere a sample/documention of playing glTF animation from b3dm tile(s) in Cesium? Is it supported? I see my tiles are rendered in Cesium but the animation is not playing :-(

**Comment by mramato** [comment]
This has come up before but I don't believe we have an issue so thanks for writing one up.  I'll update the issue title to make it clear this is a general feature request.

The 3D Tiles implementation does not currently activate and/or update animations contained within individual payloads. I'm not sure of how difficult this would be to expose as an option to the end-user API. I would imagine it would be similar to how Model works and then the tileset would have to cycle through all visible tiles each frame and updating the model animations. Depending on the number of animations, scalability could be an issue, both because of additional draw calls and also because of the time it takes to animate each tile.

When he has time, perhaps @lilleyse can chime in with his thoughts.

**Comment by lilleyse** [comment]
First thing I would check is if the glTF animates by itself. `b3dm` contains a `Model` instance which has a `ModelAnimationCollection` that uses `frameState.time`. I would expect animation to work out of the box. @bertt are you able to share your tileset ?

**Comment by bertt** [comment]
yes sure, 

live demo: https://bertt.github.io/cesium_3dtiles_samples/samples/animations/

code: https://github.com/bertt/cesium_3dtiles_samples/tree/master/samples/animations

I've unpacked the 1.b3dm to 1.glb and gltf: https://github.com/bertt/cesium_3dtiles_samples/blob/master/samples/animations/tiles/1.gltf

When inspecting the glb in Gesaltor it displays an animation with name 'track1':

![animation](https://user-images.githubusercontent.com/538812/84777704-3e3ee380-afe2-11ea-8678-1869c64163d1.png)

it also animates something when playing in Gestaltor.

**Comment by lilleyse** [comment]
Thanks @bertt, can confirm that animations don't play for the 3D Tiles on my end either.

Looks like the thing that's missing from the 3D Tiles code is a call to add the animations, like what `ModelVisualizer` does for glTF's in CZML:

```
model.activeAnimations.addAll({
    loop: ModelAnimationLoop.REPEAT
});
```

This could be added pretty easily to `Batched3DModel3DTileContent` and `Instanced3DModel3DTileContent`.
