### ISSUE TITLE
Polylines not displayed correctly at long zoom distance on iOS

### ISSUE THREAD

**Issue by sparsematrix** [CesiumGS/cesium#9035]
I have seen this in my app which uses WKWebView and also with the default Materials example when loaded in iOS Safari.

1. Navigate to the default sandcastle example (https://sandcastle.cesium.com/?src=Materials.html) in Safari on iOS 13.5.1 or 13.4 (perhaps others).
2. From the "Polyline materials" selection, choose "Polyline Outline".
3. Observe that the polyline is just a large blocky red line. It is not a while line with red outline as it should be.
4. Select any of the other 2 polyline types.
5. Observe that the lines cannot be seen at all.
6. Re-select "Polyline Outline".
7. Zoom in tightly on the giant red polyline. At sufficient zoom you will notice that it does correctly render as white with red outline.
8. Switch to either of the other 2 choices and notice that you can now see the polyline at this tighter zoom. If you zoom out the line will disappear.

Sandcastle example: https://sandcastle.cesium.com/?src=Materials.html

Browser: iOS Safari

Operating System: iOS 13.4 and 13.5.1

**Comment by OmarShehata** [comment]
Is this related to or the same as https://github.com/CesiumGS/cesium/issues/6735 @likangning93 ?

**Comment by sparsematrix** [comment]
I should probably add that I am using 1.67 currently as it does not present this issue. One of my colleagues reported to me that it was the latest he found that still worked.

**Comment by OmarShehata** [comment]
@sparsematrix that information helps a lot. If you're able to do a git bisect to determine exactly which commit caused this issue, that'd help narrowing it down. That's what I would do next.

**Comment by dzungpng** [comment]
Closing this issue as we have not heard from the original poster in a while and do not have sufficient information to move forward. Please feel free to re-open it to continue the discussion if necessary.

**Comment by sparsematrix** [comment]
You have sufficient information. I apologize that I have a greater than full time job and have not yet had time to perform a binary search on commits and determine which one broke it. Your sandcastle example is literally broken. You should need no more information than that.

**Comment by sparsematrix** [comment]
Re-opened as #9232

**Comment by dzungpng** [comment]
@sparsematrix  My apologies. I see that we have already confirmed that this is a bug. Re-opening issue to continue the discussion.

**Comment by sparsematrix** [comment]
Here is the result of my git bisect testing:
c5ac4558cd4b740f26ad22c7531b5c5c5c1c62f2 is the first bad commit
commit c5ac4558cd4b740f26ad22c7531b5c5c5c1c62f2
Author: Kevin Ring <kevin@kotachrome.com>
Date:   Tue Mar 31 15:12:03 2020 +1100

    Fix texture coordinates everywhere instead of in just the one place.

 Source/Shaders/Materials/PolylineArrowMaterial.glsl |  1 -
 Source/Shaders/PolylineFS.glsl                      | 10 ++++++----
 Source/Shaders/PolylineVS.glsl                      |  4 +++-

**Comment by hpinkos** [comment]
Thanks for taking the time to look further into this @sparsematrix 

@kring any ideas?

**Comment by kring** [comment]
Not much @sparsematrix and @hpinkos. That commit was part of a major rework of polyline rendering with the log depth buffer, which fixed a bunch of problems. Since it seems to be working on other platforms (certainly various desktop platforms and on the Android devices I've tried), it _could_ indicate an iOS bug, or it _could_ indicate we're doing something dodgy that other platforms just happen to let us get away with. But nothing jumps out at me as far as the latter, and I don't have an iOS device to debug it on.

One thing to try: disable the logarithmic depth buffer and see if that helps. [Here's a version of the Materials Sandcastle with log depth disabled](https://sandcastle.cesium.com/#c=7RuLbts48lcIAwfYd4kcp92266TF5dUiQNMGSTZd4LwoGIm2eaVEHUkl8R7y70tSL1KiElm2k8XeBWhtPubJ4Qw5Q99CBhjyBYxmBO1NolvZvqOMBBeVzpiSBcGRak6iaRL5AtMIwDgmiwMSz+EZjM+gQAxD0o8ZDrHAt2gLcB9FaAD+O4kAuIRR4EMuCPIC5BPIUN8JP9gDwyH4SBmY49mcyH8CRzOAIxODQljQ8SQeBBmMfOSFGRbwHkToDhwhjpPQK3jTnAAwhTcM+2OQNQHIwbjRBwBMWUuHrBEAxCJGYzDp5exPelvmcBLhKWUhr0ABgEM404CeN9Tf+TBl8vtnOqPfjyihzPt3PKvgA8CfwyhCRIGyyuCD0Sq/l998GsY0QpGw2QnwdJpwzcwt8l/1R97OwMKs5VfDliI83TIm5oTSz4eBNJKHup0cJmG8gplUwP9EVpKp8Qk7Oc5nrWIpN1IJIYy9OJq1MgEAbrTaHuUs0+xG2AKAC4aimZiPwY73bs1WW9G8l7UtHniM/ESakaK/MzIGIikd1NvJ1JGXdi9t3Udz5P9A7IZCFnQ1cReOtdl5xca9KaPhlbSAfirdpGdSn/RUb5OoykV1ltEEfgbheprgpNcoi7QxjgXqLk8FwYs4JudmdWxUSUbM1Y4Y/ajFmDlSvH7EiAQOILVHakDlXnV7xnRjxRvzO82ctfEvnCbMR+Ny0qTn/x5+L5ZANWZIFMo3B0+jOBHAaklDARNpYT3wDxOl9mQmWmOJMwrHaAoTUhKy0e41YZUx+7V0ktK8G6dMCYUiW9lrSBIkiQp0LxKGdo/7xopv2bJ4XAy8ZrSaqMdmNxJdiO/7+vSw4+1uSR/7Rv23O9gC+ZFCtX/KOw1WBk+ghxK5ggfbBst64Z3MDsDfJY23jyPNdQ7DEB5Rpo6+fT3QzExYCS4KRS7+00D6qFSAwKcB0vAjIbK9k3U8DZjHOQnKBYrlcowa1K3802U+O6RJJKD0ToLGvBn5HEfy9M+5xP7O27FRzSGLUVS6uyoWhuTiRQUypygPaWerUHtMRVdvbYA+R+yR5Bojz7F9dllaEhv8RaLOo0fbtiHpqctPu+PXSYg5l60VLhgOFP+bl4w219Gm6wYqlPgon4auV2DUN06szrsHQ3IxRA0VAPdjMNqqdi7GOlLZ3Q8vcGXJlajmVxXq5R063O0uvVG+KTxdt4gF3HJzbMrpaF6e8jd5UNSH0LYH4TTiapCMqZsEk+CMBglBvzDSNy1i0jvgHAk+vErPKHx4pxj7onHwFHc5f2CQmTL0nwRFvjS70Y78kyclI/MSSUbVqslAjYLa3RWGMcEiCaQmRgZcOxP4xHDnK6oJ+xwRVNFrDKGnai27SmIBv2j41Jy8WORUF1hpthwFmQWvchN2IlrCUahUs1/g0YqRG25PDeEp6Gs2PHljqtH6qPabuEzimDKBAmk5/JXwpeUMciXW0crlMtWp9Hj869XI+yHuJz1N8wEgIk/8y5JGwh8tTfrk6mgNpONb1kHs8+sLk/TmnPYypl7nfEnL/pL78a4WXUPw/6Rzu1OgEUGdbBWKXYGrlEabrPObP2fWuVBS15TzZXm46WrhDhQvGgoNfjYQEBtraC31LRiOO4dHG/o5zk4pxcbT0wUOP2d0u8rkQPF89QqD+KPlivOsdH3AGL3rKqkTSWtZ1bGm3ZpZdNKlM1VlICnSaY8K/YmsLrOJY4MiKzJyT5YHF7mBixtYup2PLk7PLr9+yXbrTAKc0zuknexu1ilgjFjR+7rc0Cup8Wsi1Meqmqyg2aAyM0qGPmna8w0HKiqWurhTHWAIdrN7ZCdl+QzJocNECBrxvqmSYoqgsxlBxbuSa8zxDZaX2EW/OKsWL1E8Pqd3qlTBErSXjtmvUvIJU3ksymfkT1TqY9mBtsLKNwujix83TYMptk5+8qVzcVLFtZRiHuEy48QwNxgEV5SSGxmDUZT0/5WiKAO1vHio6CmvIiEtc/q8krp3Qug6bBFzpaEgIjkbl3oo5dWAzQazZ2RC6hXpQt58cxrTDUmLPecsTLuPBg65qleadcplJzi6yVXJc7SWq7xsgk2K2Jx+6LqMjVkIt+i/Dfa6boJzRn0UJEz6xqxC2WYfWM8sNqNT11uUjup0PklpbUS6ALYRGc0iYDfRrFpga4nShOQ6RDK4tn14TVYrYdtNWDtv21ra/AqxkSWs3Ke6CVa9Vq19kx9CjpaJc/o9KLAvsOvUWu25bTe91V/dtjYK9W5ngwJW34l2k6/2XLS9z6qlc9bqtypl/46+q1r9by1dXnnd4AK6avHdxHSW5FuLmmYZNyhoPcHcTUxHnrm9h84f8mxOTFeesaOzdqUb1+6xzzD3l/HYFzgEZSZpWRU2XyOrenQl3OzIv5Qyncm31nZTLZ+vXVr7ocEKclYeHazdXE7uVTUdpYl/9ZJ3uVttDpSh2aRK64+VV1Cr4+Hy+i9IWdpiGY0WMFkKdFl1utIoVUU2pISz3qXU2JAYbr0PC3Gz9OcGpbVzwasIa2eEl5e1zE5uUNxaznYViWuZ2yf2SkD9JESRUGX7E4LU18PFqarQi3TfTHoDj4sFyROwqig/2vmbLsG7cqvneT7WTq8WcVg9+9XvBIrELVe7NKuWGLW4AlG/0O4M0RAJtjiNuFBlGD42AT5VRvvGquSQFkDhj3LIvlXNLVge1wB0JvsYzRiSYtoF3e3Rrv1CSv05urbf1Pteyy6zZ2CN3yImDTR9SlGwdEIIjjnFwWXCptBHB2WN6vrk4urk1+8fv16cHVyZxeQSrfG1LG5ZOmrGbyoL3tBb9InRJArGada2TuJhkNe+1KcdEP76RvHOYQE/1/tc837+K1sFACrXbw/blmL+qpc3GYppItncI0qUo5aeqT/ISkW5W39fItTQRfFCHjPkfD6u4jrHMdJljZmkzaSXO4JS6xzD6ID5pch1BMW8V6Z1yBgMF/lhJLWPkb3ur3et5va7n6z2qzf28KjyKnPXnr799q3VHpnYfys3aPblLi29GSxV16h8eaBW5xajO8TslxTXuk+GEV+3j6j+8QbKfuCmoPQ6SqAU2tNNOZQuL6EzyLCYh9g/RrGYHybTqSaRl4QmUUO42ctH7CKf7O5t9fZ1JPuQi/5PHKoHaSBhpO95Q4HkwVhCqpdE/g8kPJ/zPIDuD03Q/QDfAhy8d4gHfAI5lyPThJBL/Ls8PHzYH8r5NVBCYSDvRF/lDiZwoabNRx8+p52e5+0PZdMNWYRma/wP).

**Comment by kring** [comment]
Here's the PR that commit was part of:
https://github.com/CesiumGS/cesium/pull/8706

**Comment by sparsematrix** [comment]
> One thing to try: disable the logarithmic depth buffer and see if that helps. [Here's a version of the Materials Sandcastle with log depth disabled](https://sandcastle.cesium.com/#c=7RuLbts48lcIAwfYd4kcp92266TF5dUiQNMGSTZd4LwoGIm2eaVEHUkl8R7y70tSL1KiElm2k8XeBWhtPubJ4Qw5Q99CBhjyBYxmBO1NolvZvqOMBBeVzpiSBcGRak6iaRL5AtMIwDgmiwMSz+EZjM+gQAxD0o8ZDrHAt2gLcB9FaAD+O4kAuIRR4EMuCPIC5BPIUN8JP9gDwyH4SBmY49mcyH8CRzOAIxODQljQ8SQeBBmMfOSFGRbwHkToDhwhjpPQK3jTnAAwhTcM+2OQNQHIwbjRBwBMWUuHrBEAxCJGYzDp5exPelvmcBLhKWUhr0ABgEM404CeN9Tf+TBl8vtnOqPfjyihzPt3PKvgA8CfwyhCRIGyyuCD0Sq/l998GsY0QpGw2QnwdJpwzcwt8l/1R97OwMKs5VfDliI83TIm5oTSz4eBNJKHup0cJmG8gplUwP9EVpKp8Qk7Oc5nrWIpN1IJIYy9OJq1MgEAbrTaHuUs0+xG2AKAC4aimZiPwY73bs1WW9G8l7UtHniM/ESakaK/MzIGIikd1NvJ1JGXdi9t3Udz5P9A7IZCFnQ1cReOtdl5xca9KaPhlbSAfirdpGdSn/RUb5OoykV1ltEEfgbheprgpNcoi7QxjgXqLk8FwYs4JudmdWxUSUbM1Y4Y/ajFmDlSvH7EiAQOILVHakDlXnV7xnRjxRvzO82ctfEvnCbMR+Ny0qTn/x5+L5ZANWZIFMo3B0+jOBHAaklDARNpYT3wDxOl9mQmWmOJMwrHaAoTUhKy0e41YZUx+7V0ktK8G6dMCYUiW9lrSBIkiQp0LxKGdo/7xopv2bJ4XAy8ZrSaqMdmNxJdiO/7+vSw4+1uSR/7Rv23O9gC+ZFCtX/KOw1WBk+ghxK5ggfbBst64Z3MDsDfJY23jyPNdQ7DEB5Rpo6+fT3QzExYCS4KRS7+00D6qFSAwKcB0vAjIbK9k3U8DZjHOQnKBYrlcowa1K3802U+O6RJJKD0ToLGvBn5HEfy9M+5xP7O27FRzSGLUVS6uyoWhuTiRQUypygPaWerUHtMRVdvbYA+R+yR5Bojz7F9dllaEhv8RaLOo0fbtiHpqctPu+PXSYg5l60VLhgOFP+bl4w219Gm6wYqlPgon4auV2DUN06szrsHQ3IxRA0VAPdjMNqqdi7GOlLZ3Q8vcGXJlajmVxXq5R063O0uvVG+KTxdt4gF3HJzbMrpaF6e8jd5UNSH0LYH4TTiapCMqZsEk+CMBglBvzDSNy1i0jvgHAk+vErPKHx4pxj7onHwFHc5f2CQmTL0nwRFvjS70Y78kyclI/MSSUbVqslAjYLa3RWGMcEiCaQmRgZcOxP4xHDnK6oJ+xwRVNFrDKGnai27SmIBv2j41Jy8WORUF1hpthwFmQWvchN2IlrCUahUs1/g0YqRG25PDeEp6Gs2PHljqtH6qPabuEzimDKBAmk5/JXwpeUMciXW0crlMtWp9Hj869XI+yHuJz1N8wEgIk/8y5JGwh8tTfrk6mgNpONb1kHs8+sLk/TmnPYypl7nfEnL/pL78a4WXUPw/6Rzu1OgEUGdbBWKXYGrlEabrPObP2fWuVBS15TzZXm46WrhDhQvGgoNfjYQEBtraC31LRiOO4dHG/o5zk4pxcbT0wUOP2d0u8rkQPF89QqD+KPlivOsdH3AGL3rKqkTSWtZ1bGm3ZpZdNKlM1VlICnSaY8K/YmsLrOJY4MiKzJyT5YHF7mBixtYup2PLk7PLr9+yXbrTAKc0zuknexu1ilgjFjR+7rc0Cup8Wsi1Meqmqyg2aAyM0qGPmna8w0HKiqWurhTHWAIdrN7ZCdl+QzJocNECBrxvqmSYoqgsxlBxbuSa8zxDZaX2EW/OKsWL1E8Pqd3qlTBErSXjtmvUvIJU3ksymfkT1TqY9mBtsLKNwujix83TYMptk5+8qVzcVLFtZRiHuEy48QwNxgEV5SSGxmDUZT0/5WiKAO1vHio6CmvIiEtc/q8krp3Qug6bBFzpaEgIjkbl3oo5dWAzQazZ2RC6hXpQt58cxrTDUmLPecsTLuPBg65qleadcplJzi6yVXJc7SWq7xsgk2K2Jx+6LqMjVkIt+i/Dfa6boJzRn0UJEz6xqxC2WYfWM8sNqNT11uUjup0PklpbUS6ALYRGc0iYDfRrFpga4nShOQ6RDK4tn14TVYrYdtNWDtv21ra/AqxkSWs3Ke6CVa9Vq19kx9CjpaJc/o9KLAvsOvUWu25bTe91V/dtjYK9W5ngwJW34l2k6/2XLS9z6qlc9bqtypl/46+q1r9by1dXnnd4AK6avHdxHSW5FuLmmYZNyhoPcHcTUxHnrm9h84f8mxOTFeesaOzdqUb1+6xzzD3l/HYFzgEZSZpWRU2XyOrenQl3OzIv5Qyncm31nZTLZ+vXVr7ocEKclYeHazdXE7uVTUdpYl/9ZJ3uVttDpSh2aRK64+VV1Cr4+Hy+i9IWdpiGY0WMFkKdFl1utIoVUU2pISz3qXU2JAYbr0PC3Gz9OcGpbVzwasIa2eEl5e1zE5uUNxaznYViWuZ2yf2SkD9JESRUGX7E4LU18PFqarQi3TfTHoDj4sFyROwqig/2vmbLsG7cqvneT7WTq8WcVg9+9XvBIrELVe7NKuWGLW4AlG/0O4M0RAJtjiNuFBlGD42AT5VRvvGquSQFkDhj3LIvlXNLVge1wB0JvsYzRiSYtoF3e3Rrv1CSv05urbf1Pteyy6zZ2CN3yImDTR9SlGwdEIIjjnFwWXCptBHB2WN6vrk4urk1+8fv16cHVyZxeQSrfG1LG5ZOmrGbyoL3tBb9InRJArGada2TuJhkNe+1KcdEP76RvHOYQE/1/tc837+K1sFACrXbw/blmL+qpc3GYppItncI0qUo5aeqT/ISkW5W39fItTQRfFCHjPkfD6u4jrHMdJljZmkzaSXO4JS6xzD6ID5pch1BMW8V6Z1yBgMF/lhJLWPkb3ur3et5va7n6z2qzf28KjyKnPXnr799q3VHpnYfys3aPblLi29GSxV16h8eaBW5xajO8TslxTXuk+GEV+3j6j+8QbKfuCmoPQ6SqAU2tNNOZQuL6EzyLCYh9g/RrGYHybTqSaRl4QmUUO42ctH7CKf7O5t9fZ1JPuQi/5PHKoHaSBhpO95Q4HkwVhCqpdE/g8kPJ/zPIDuD03Q/QDfAhy8d4gHfAI5lyPThJBL/Ls8PHzYH8r5NVBCYSDvRF/lDiZwoabNRx8+p52e5+0PZdMNWYRma/wP).

@kring Thanks for taking a look. I've given that version a shot on an iPad and it shows the same issue as the regular Materials Sandcastle.

**Comment by sparsematrix** [comment]
@kring not sure if any of this helps...

Here's how it looks in 1.67 in my app. To get this display there is a PolylineOutline drawn and then a PolylineArrow drawn along the same path to get the appearance of both outline and arrows. The line color is magenta and the outline is black:
![cesium_1 67](https://user-images.githubusercontent.com/7504519/111659209-4672bc00-87ca-11eb-86aa-d01d5c0c8310.png)

Moving to commit d631c21, which is just before the breaking commit. The outline issue is not present but PolylineArrow no longer draws at all in iOS (still works in Chrome) regardless of zoom level:
![at_d631c21_arrows_broken](https://user-images.githubusercontent.com/7504519/111659737-b5e8ab80-87ca-11eb-89f3-7973fd322c57.png)

Moving to the breaking commit c5ac455. When zoomed out I only see the outline color. Zooming in tight at this commit results in the correct appearance of both the outline and arrow (seemingly fixing the arrow issue seen in d631c21):
![at_c5ac455](https://user-images.githubusercontent.com/7504519/111660403-47581d80-87cb-11eb-93b0-d6031f7b10eb.png)

![Screen Shot 2021-03-18 at 10 06 58 AM](https://user-images.githubusercontent.com/7504519/111667255-c2243700-87d1-11eb-94e5-390b67e11b43.png)

I have updated one of my iPads to the latest iOS (14.4.1) and confirmed that it is still an issue there with the Sandcastle example.

**Comment by sparsematrix** [comment]
I have confirmed that this issue remains in iOS 14.5.1

**Comment by sparsematrix** [comment]
Updated to iOS 15.4.1 and Cesium 1.92. 

Here's my latest results in Safari/WKWebView:
- Polyline Outline appears to work as expected now
- Polyline Arrow does not display
- Polyline Dash does not display (https://sandcastle.cesium.com/?src=Polyline%20Dash.html)

**Comment by sparsematrix** [comment]
Remaining issues appear to be covered by https://github.com/CesiumGS/cesium/issues/9827 and setting orderIndependentTranslucency to false does appear to resolve the issue.
