### ISSUE TITLE
Used in cesium gl.Lines And threejs gl.Lines What's the difference? Why is threejs used in gl.Lines The lines drawn are straight. What about the sawtooth in cesium?

### ISSUE THREAD

**Issue by weiyinggh** [CesiumGS/cesium#9045]
Used in cesium gl.Lines And threejs gl.Lines What's the difference? Why is threejs used in gl.Lines The lines drawn are straight. What about the sawtooth in cesium?
![image](https://user-images.githubusercontent.com/26948421/88046201-47434780-cb82-11ea-8459-f6f81e184141.png)

**Comment by OmarShehata** [comment]
The issue here is antialiasing, and will be seen on lines or any thin geometry, see: https://github.com/CesiumGS/cesium/issues/8228

The outlines on [Cesium OSM Buildings](https://sandcastle.cesium.com/index.html?src=Cesium%20OSM%20Buildings.html) are drawn with a different technique, you can read about it here: https://github.com/CesiumGS/cesium/pull/8776

If you have more questions please open a topic on the community forum: https://community.cesium.com/ !
