### ISSUE TITLE
ES6 syntax not caught by linter in Travis

### ISSUE THREAD

**Issue by ptrgags** [CesiumGS/cesium#9090]
Today when debugging a failed Travis build of an internal feature, @mramato and I tracked it down to a line where I had used `const` rather than `var`. This was not caught by the `npm run eslint` step of the Travis build.

We should check the eslint settings, maybe there's a default ECMAScript version that we're unintentionally using?

@mramato do you have any hunches of what the problem might be?

**Comment by mramato** [comment]
My best guess is that when we switched to ES6 modules, it was unintentionally toggled on.  I'll take a look later today.

**Comment by mramato** [comment]
The issue is that the parser options we enable for eslint are (reminder 2015 == 6):

```
  parserOptions: {
    ecmaVersion: 2015,
    sourceType: "module",
  },
```

This is because in order to use modules, we're required to set the ECMA version to at least 6. So this was introduced all the way back in the ES6 migration last October, but I guess no one has ran into it until now.

I can't find an eslint rule that diallows use of const/var either so I'm not sure what we can do about this yet, but definitely something I'd like to fix.

**Comment by ptrgags** [comment]
I'm closing this as no longer relevant since `const` and `let` are now supported as of #10026
