### ISSUE TITLE
request.requestFunction is always overridden 

### ISSUE THREAD

**Issue by danduk82** [CesiumGS/cesium#9123]
In the context of the swiss geological viewer development, we would like to access restricted tiles stored on AWS S3. 

In practice we are using the AWS-SDK to exchange an AWS-Cognito JWT with temporary AWS access keys, and we would like to use the AWS-SDK to implement a custom `Cesium.Request` parameter of the `Cesium.Resource` ( [see this branch](https://github.com/swissgeol/ngm/tree/cesium_custom_request) and in particular [this line](https://github.com/swissgeol/ngm/commit/cb1b9db3dd9d02a7d9bfd5c6264a310a552308e9#diff-149063e479ababf1e578b3f703c5ec7dR88) ).

Unfortunately, the requestFunction seems to be always overridden. I suppose that the problem is in this line:

https://github.com/CesiumGS/cesium/blob/74f650530bb96c19550d90d5d689488c8204b7d8/Source/Core/Resource.js#L1339

which do not consider the case where the `requesFunction` would be already set. I guess that something like this would be enough for what we want to do:

```javascript
request.requestFunction = request.requestFunction ? request.requestFunction : function () {
```

The cesium documentation says that this parameter is _for internal use only_ . Would you be interested in a PR that corrects this behaviour nonetheless? Or maybe is there a better way of doing what we want to do?

**Comment by OmarShehata** [comment]
So the reason you need to override the Resource's request function, instead of just making the request directly, is because you need to pass a `Resource` object to the `Cesium3DTileset` constructor, right?

Have you looked into how IonResource does it for handling authentication from Cesium ion? See: https://github.com/CesiumGS/cesium/blob/master/Source/Core/IonResource.js. It overrides the _makeRequest function: https://github.com/CesiumGS/cesium/blob/74f650530bb96c19550d90d5d689488c8204b7d8/Source/Core/IonResource.js#L185-L200. 

The entry point to it is typically the "fromAssetID" which handles the initial authentication to get the actual URL for where the tiles are after getting through the authentication request: https://github.com/CesiumGS/cesium/blob/master/Source/Core/IonResource.js#L101

**Comment by danduk82** [comment]
@OmarShehata thanks for your answer, yes indeed.

I will have a look at IonResource code next week and see if I can solve this issue overriding the `_makeRequest` function.

**Comment by dzungpng** [comment]
Closing this issue as the dicussion has been inactive for a while. Please free free to re-open if you would like to continue the discussion.
