### ISSUE TITLE
How to make a simple satellite trajectory with czml-writer

### ISSUE THREAD

**Issue by BaiH-ang** [CesiumGS/cesium#9158]
I use the. Net version of czml-writer.
I can run this, but I don't know how to create a simple satellite trajectory.

**Comment by BaiH-ang** [comment]
Can we get his trajectory by some formula instead of listing it？

**Comment by GatorScott** [comment]
You could try [satellite-js](https://github.com/shashwatak/satellite-js) (though I've never tried it).

**Comment by OmarShehata** [comment]
I have successfully used SatelliteJS + CesiumJS. You just give it the TLEs and you can produce one or more positions, which you can then add directly to your entity or produce a CZML and add it to your scene.

@BaiH-ang let's move this conversation to the Cesium community forum (https://community.cesium.com/) since it sounds like you're trying to generate a CZML not necessarily inside of CesiumJS.
