### ISSUE TITLE
When using camera.lookAt or camera.viewBoundingSphere, the camera can not be very close to the seted center.

### ISSUE THREAD

**Issue by Hang-Cheng-Zhang** [CesiumGS/cesium#9218]
var center = Cesium.Cartesian3.fromDegrees(100, 30, 200);
        var heading = Cesium.Math.toRadians(50.0);
        var pitch = Cesium.Math.toRadians(-20.0);
        var range = 0.1;
        viewer.camera.lookAt(center, new Cesium.HeadingPitchRange(heading, pitch, range));

When using the camera.lookAt, although the "range" is seted to a very small value "0.1", the position of the camera is very far away from the center. And using the mouse scroll, the camera can not be adjusted close to the center as well. It seems that there is a 
minimize distance between the camera and seted center during the lookAt or viewBoundingSphere mode. And this makes it impossible for us to get a close look at the details of the model. How can I solve this problem?

**Comment by dzungpng** [comment]
When you set the camera to lookAt a point, it will place the camera above that point. You cannot zoom closer because the camera will then no longer be above the point, which is not what lookAt is trying to achieve.

To get a closer zoomLevel, you can set the height in the center Cartesian point to be lower, something like 10. 

```js
 var center = Cesium.Cartesian3.fromDegrees(100, 30, 10);
```
