### ISSUE TITLE
GLTF Object disappear when i zoom/unzoom

### ISSUE THREAD

**Issue by popoleeMaster** [CesiumGS/cesium#9228]
Hello, 

I am unsure if I use Cesium wrong, or if there is a bug. I would still like to report and feel free to close if it's my issue.
In the forum the reply was that is might be related to this => https://github.com/CesiumGS/cesium/issues/2946 but I am using a GLTF not a polygon.

Anyway, I have an issue in Cesium IONS and Cesium when I load a models. I setup a GLTF model in Ions and imported as a 3d tile so that I could add a location to that model. The issue is, when zoom/unzoom in my map, the model appear and suddenly disappear.

![](https://aws1.discourse-cdn.com/business4/uploads/cesium/original/2X/d/d324275336fc64007691c506f4fa068d81e3c628.jpeg)

![](https://aws1.discourse-cdn.com/business4/uploads/cesium/original/2X/c/c61e555e9678f72b565e50dd54d3383410a437af.jpeg)

this doesn't look like the correct behavior. The exact same happen in my map (outside of Ions) even if I tried to setup many different setting like scale, clipping etc...

thank you.

**Comment by dzungpng** [comment]
Hi there,

Try decreasing the maximumScreenSpace error: [example](https://sandcastle.cesium.com/#c=lVNdb9owFP0rFg9TkCqnlMH6QatRWrGgUkYJrKC8hORCXBw7tR0+MvW/z04Ca7d12p6c2Odcn3PutW2jrvCZQh2QJI17I+QHAUiJFEc7ngpEOEO+lKCkxwoMdjjDISz8lKp2Dnb5Chi6RF4Fdr1o3g3IgPSccebU7okjHfbQCDpO01klj5NO7wxr0HPYXWmQ83H2rX8ydae7fue4Ps2uozt3WOu7QzXojrf3o+PGNHuIpu7kqf80iwfdPrnr9JKZLtbPhpt7dymdmEah+XfHjYE7rfezdmPweIzZLDqbBsPs9NZf9W9qbpONxmdut7FpDtkz+9KbbpvDbWfb27ZPvcqFxzy29gVaE9iA0E4YbMpE8CTfs7xKkP93OFM+YSC8yhH67jGEFAihd74KviYhiPPX5GJx3yKsnIZQKug5+pnpA0gdeAB4IXjcNpE7oVWrHhnwi1leqlpoIRHLABjgJeVz0L1IVOSCVO2lvkWq8jptQ4kUDuYUoaCL6u03NRJBYqLIGiT2w9Ayt/1moH7jFuT/kn5ar306KfQjFMI8XY4ivrnmKQsJW044TWM4zzWWmNjfkjiNR4EAYKPED+BWCK4TrRkPJgWPVXM/pRcswA93OteYSDAIrCJg1iJlgTKDa1VRKbi0nHEeu9wq6UUtc2zbqJ0kdIc0H5WzjaTaUUBkgYhCsCXSPIG8lg4Ttkr40kRcKsnfCC62LwqcZlrFF9pnpUvr2QmtAldFHz78FYC1iX8C7d/jyEiuFvCDd3QQWTi6fK/BOfvdqqWrl30ndNpcxyU2OvtXkYNp2eHugDPJKWDKl+XJRcHXS+Wo0soVXZmtzyROuFBmtCyMbQVxQn0F0p6nwUprD6Q0pJa9p7RCskYkvPzDy0QB1f3QJ4uU0hHJwKtctWyNf0Oj3DeDOFiDoP5OQ4yMVlS7uisOMMYtW/+aS3/lKs7p3Bev6v4A).

This is a known issue that we are tracking in our tiling pipeline. Small models disappear too early when zooming out because they produce too low of a geometric error.
