### ISSUE TITLE
Cesium hangs when zooming inside the boundaries of the globe.

### ISSUE THREAD

**Issue by iamscottcox** [CesiumGS/cesium#9230]
Hello!

We're trying to use Cesium to render pointclouds that are not projected into a co-ordinate system (they're derived from stereoscopic photogrammetry using localisation that doesn't involve GPS) and we've run into a snag.

We've removed the globe, moon, skybox, etc, and we're loading the asset and zooming to it via the following:
```
    const viewer = new Cesium.Viewer('cesium-container', {
      terrainProvider: Cesium.createWorldTerrain(),
      skyBox: new Cesium.SkyBox({
        show: false,
      }),
      navigationHelpButton: false,
      baseLayerPicker: false,
      homeButton: false,
      animation: false,
      scene3DOnly: true,
      timeline: false,
      geocoder: false,
    });

    viewer.scene.globe.show = false;
    viewer.scene.moon.show = false;
    viewer.scene.sun.show = false;

    const url = '/tilesets/test/tileset.json';

    const tileset = viewer.scene.primitives.add(
      new Cesium.Cesium3DTileset({
        url,
      }),
    );

    viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0.0, -1.0, 50.0));
```

Everything loads fine, and I'm able to rotate around the 3D Tileset. However, Cesium completely hangs if I try to zoom in or out. This isn't the case if `viewer.scene.globe.show` is not set to `false`, though. Instead, when I zoom in/out, I'm brought back to the closest position the camera can be to the globe. I'm going to have a dig around for a solution myself, but any pointers as to which direction I should head in would be brilliant.

Browser: Chrome (Version 86.0.4240.111 (Official Build) (x86_64))

Operating System: macOS Mojave v10.14.6

**Comment by OmarShehata** [comment]
Hey Scott, when you say completely hangs, does that mean you're unable to do anything else (including rotating the camera, or clicking on any buttons etc) ? Is there any error in the console?

If you are able to provide sample data to reproduce this that'd help us confirm whether this is a bug or not (either by uploading your 3D Tiles to Cesium ion https://cesium.com/docs/tutorials/ion-intro/ or by creating some geometry in that same location and sharing a [Sandcastle](https://cesium.com/docs/code-examples/)).

Otherwise, this may be a good question for the community forum (https://community.cesium.com/).I would try disabling the globe (by passing globe: false in the viewer constructor) instead of creating the terrain and hiding it. If we can reproduce/confirm this is a bug we can re-open this issue.

**Comment by iamscottcox** [comment]
Hi Omar,

It completely hangs as in you can't do anything else at all. Any interaction with Cesium stops entirely, but strangely there's no error in the console. I've tried disabling the globe like you mentioned, but unfortunately the result is the same.

However, I've made a Sandcastle for you this time around. Here you go! 

https://sandcastle.cesium.com/#c=jVPbctowEP0VDQ8dM5PKIdeSkEwTSKlpDE0gpcn4RcgLFsiSK8kE08m/V76QkPQyfZK9e85ezu66LuoqIgxqg2Zp3BsiQilojYxEmUwVYlIgojUYHYgSgz0pcAhTknJzUYBHcgECnaGgBlkvmnQpG7Ced7f2Gn3maU/cHtK2d+Qtku/f2r0mtqAfYXdhQd7qfnx/2I/70cNw9/BhTlfXo9vI73hm0Anng/Zu5nfuDvy53+iPe7G/d8Wu273kwQbz5/TAX+fB+/PJ/iWnmXc0tsnpvpdjxH3WC3Ps/fcbNphfNQaji5W/XmT+Ompi/ikZjtOefD8XX/rZbNaMb5r04Di685fH3Wh8Sz+RSdJsNsaXs6B2GohALIlCSwaPoGybAh4rufC3wuYENVr8t6UwhAlQQW0H/QwEQnqRXcrVyTZnWJicwm0BkXw8QVPCNezklqd68QiyZDNirPqfgSeXqTFSbMMmRMM1yUB9ZXQBatsVyRh+JxDB4iLetlFTELDfGQienSCj0tJqWAzcdrGNnIGkMnydaMblZAv0VC+lKiTBRWgcS7sreYtWtgJ3+gag09/8pdqGcbBbZ+2v8IliMTNsCRqTMHQKqV6kLZ/9zqgkbzROFT9BL8t7C9puNgU8VTK+yHfbC53Gh73mh+N6NYNAlM1UVWAFJMy+WjjTkCOwiUA401TQXFLk1FGVqip2LWU8kk5FL2PlbtdFF0nCM2T5qLohpE3GAbEpYgbBiun81IpYVgZYGUW0VWFTSXGLuDSfljjLdMovtOnShrYDDJ0SV0fv3v0TgG0T/wXa3P0wL7lewp97R89Flh2d/W00BfuvUauunjaTsGpLK5d6tNpvSQ5KSfWcm0qhJQfM5azynJZ8+9R2aq2iovPc9JHFiVQmXwoHY9dAnHBiQLuT1F6SwVTrnNRyN5RWyJaIhWd/OHJEuZ2H9UxTzodsDUHtvOVa/CsalyRkYjZYguIks5C8jFbUOL8uHRjjlmt/86RvuUZKPiFqK+4v
