### ISSUE TITLE
PixelFormat.R undefined in WebGL2

### ISSUE THREAD

**Issue by Mofangbao** [CesiumGS/cesium#9237]
PixelFormat.R is used in PixelFormat.toInternalFormat,but it's undefined.
When use float texture in WebGL1,alpha channel with pixelDatatype.FLOAT works, But,When use float texture in WebGL2,we can't get correct float value with alpha channal and console outputs "GL_INVALID_OPERATION: Invalid internal format".

Thanks a lot.

**Comment by lilleyse** [comment]
Here's a sandcastle example for testing this: [Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=jVVtb9owEP4rFl8atNQBukpbSqsxoBUSlKqwVtOYKpNcglXnZbYDpRP/fU6chATQti9O7u65587Hk8Oy0HwFSJDQdYiQDNAm4q8CUQ9x+JWAkM+w9FkHUYE8wgQsQstCMwDkRKGIFB44j7hAmxWExymSJypjTThaU9gAR9cohA3qg6BJgJ8yn3HmZGY/CiWhIfAzE/1ehCitIOFNTmNJVS1bO1G9iJ2XQGi3CHfNK11MOBCCqqWL4szMQzmpCmZenNsqquMBkcApYfVOJ7nXyHrwyJJTB5UdJSH1Ih6IvQehlDThYB8y4AF4JGFyFBAfRq6G70z9FFHCHUB2QbJoOO/BS9lSavggy2aqwVEYJxLVrKbqpoE+7MnSs0ZYuWzOnXdXlqgTXh3zrcH5qIbKovS3zS/dGRj5m1nvCIuTHAUGu9TzEpH+chkj5v7yb3DC4hUpweQElIPqIiwzDhC7RaOqHC2AmL4BeyJMaSzXwC2LiLzo9DgnW+NHC1+aqIXb6XGRHp9/6uSyrUIOOB9CXUpz7TSqEreLl0wHWQe3ioHIUj4Pex8ef5uM7nv3/eEePSCSyG0MdXzhxbfjaW+eobXCSp1uqCtXNurk+lsB9Vdyb5P0yl8TzwOefqt2dTgZRAtXkCBmwO3qNWfaZxSFOIln9sEMnpUT98e9ycPLfPoyHNwNzT16/t/ogKqBU4eka+KWMpl2Uk+dHCHw/bD3OJzNCwri/5PjGFIj2TWzh8do/N3Wu9KsCYuD+wiOJKHPYBQK9eIcSOMOogAk3xZRPTw/96LafEuqIsko12MeQPYRFns8CgbgcwBhnLfbLdwyUSc7zz9p4xK3mvo69a+C04BKuoZycZYegYnrGpXWHopIvf/iVumaPDWLbHwkjoHwbDT2qQXcK+PFfcsdZpev+/6bVw2z0RVyy+Cm+O6/0CCOuEQJZwbGlgQlVJUorGXivILEjhDpvVNo16qmdl26RtS9Vlu5/oeltorDiBAq4iWMzeg7LBo3XUvhj1LVLnFp6E/XwBnZprBV+2asnRjjrqXM05kyitiS8APmPw)

The two switch-case statements in `PixelFormat.toInternalFormat` are incorrectly using `PixelFormat.R` and `PixelFormat.RG` which don't exist, and should instead be checking `PixelFormat.LUMINANCE`, `PixelFormat.ALPHA`, and `PixelFormat.LUMINANCE_ALPHA`.

This is half the fix. The other half is in `Texture` and `CubeMap` which are using the correct `internalFormat` with the fix above but not the right `pixelFormat`. In WebGL2 the `pixelFormat` for floating point LUMINANCE_ALPHA, LUMINANCE, or ALPHA textures should be `RG`, `RED`, and `RED` respectively. Though I'm not sure if this is completely correct since it ignores the fact that luminance is really grayscale RGB and alpha is for the alpha channel not the red channel. May need more investigation.

See https://www.khronos.org/registry/webgl/specs/latest/2.0/#TEXTURE_TYPES_FORMATS_FROM_DOM_ELEMENTS_TABLE for a list of valid internal format, format, and type in WebGL 2.

**Comment by Mofangbao** [comment]
Thanks a lot.
