### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by yeshihua** [CesiumGS/cesium#9250]
![a](https://user-images.githubusercontent.com/30494071/100189348-15befc00-2f27-11eb-966f-afac5979cd1a.png)
cesium1.75

**Comment by OmarShehata** [comment]
You'll need to `git clone` this repo if you want to set up from source. Otherwise you can download a release zip from here: https://github.com/CesiumGS/cesium/releases

See also the Cesium quickstart guide: https://cesium.com/docs/tutorials/quick-start/.

For general questions please use the Cesium community forum: https://community.cesium.com/
