### ISSUE TITLE
3D Model stopped rendering after upgrading to v1.75

### ISSUE THREAD

**Issue by dzungpng** [CesiumGS/cesium#9270]
Sandcastle example: [link](https://sandcastle.cesium.com/#c=lVPvb9owEP1XLD5MQaqc0hZUWlqN0YkFNWWU0DUoX0JygItjp7bDj0z932cngbXbOm2fHJ/fu3v37mLbqC9CplAPJMmSwRiFUQRSIsXRjmcCEc5QKCUoGbASgx3OcAzzMKOqW4A9vgKGrlBQg91gOetHZEgGziR3GnfEkQ67b0Y9p+Ws0seH3qCNNeg57q80yDmbfnNPfM/fub3jUz//tLz1Rg3XG6lhf7K9Gx83/fx+6XsPT+7TNBn2XXLbG6RTnczNR5s7byGdhC5jc/cmzaHnn7p5tzl8PMZsumz70Sg//xyu3JuG12LjSdvrNzetEXtmXwb+tjXa9raDbfc8qF0GLGDrUKA1gQ0I3QmDTeUIfihiVlCLinuPMxUSBiKoHaHvAUNIgRA68lXwNYlBXLwml4f3FmEVNIQyQS/QT0/vQWrDI8BzwZOusdyJrUb9yIBfzPFS10JLiVhGwAAvKJ+BnkWqlh5I1V3oKlJV5XQbSmRwaE4RCjqpDr/JkQqSEEXWIHEYx5ap9lsDpzdeSf4f6SeNk/ZZa68/YPVCSaUCCwjjnXYkIRIMAqslMGuesUiZlbPqqCpVic05TzxuVfQyl3m2bdRNU7pDmo+qrURS7SggMkdEIdgSaZa3yKVtgK0SoTTmVEqK7cZl+LLEaaZVfqF9lzq1nnpslbg6+vDhrwCsm/gn0P5PGhvJ9RJ+6B0dRJYdXb03moL9btaqq5f9JLTbXNslNtr7V5brteHiUDviTHIKmPJF9XJZ8gvra0e1TqHp2gQ/kiTlQpm1sDC2FSQpDRVIe5ZFK60+ktLQOvae0onJGpH46g9/FYqonoh+mWeUjkkOQe26Y2v8GxrlYUzYYrgGQcOdhhgZnWXj+rZ8wBh3bH01RX/lKs7pLBSv8v4A).

Browser: Chrome

Operating System: Windows 10

What the model supposed to look like:
![image](https://user-images.githubusercontent.com/38567338/101404468-af31ca80-38a4-11eb-8441-8ac0afec6dd4.png)

What it looks like with v1.75:
![image](https://user-images.githubusercontent.com/38567338/101404493-b8229c00-38a4-11eb-8ad8-0ffe6d5ab971.png)

The breaking commit is https://github.com/CesiumGS/cesium/pull/9173 (@lilleyse).

This is a .glb model.

**Comment by lilleyse** [comment]
I think there's a bug in the glTF model itself that is being exposed by the change in https://github.com/CesiumGS/cesium/pull/9173.

This is one of the attribute accessors from the source .glb

```json
{
  "bufferView":7,
  "componentType":5125,
  "count":2145,
  "type":"SCALAR",
  "min":[4],
  "max":[4]
}
```

which isn't isn't valid according to the glTF spec:

> "gltf_detailedDescription": "The datatype of components in the attribute.  All valid values correspond to WebGL enums.  The corresponding typed arrays are `Int8Array`, `Uint8Array`, `Int16Array`, `Uint16Array`, `Uint32Array`, and `Float32Array`, respectively.  **5125 (UNSIGNED_INT) is only allowed when the accessor contains indices**, i.e., the accessor is only referenced by `primitive.indices`.",

The glTF validator doesn't seem to catch this and I may need to open a bug report.

One workaround is for the user is to delete the `_MaxHandle` vertex attribute from the `"attributes"` object in the glTF and then re-upload to ion.

The reason this breaks now is that https://github.com/CesiumGS/cesium/pull/9173 allowed unused attributes to be added to the vertex array because an unused attribute at time of vertex array creation might be used when a material is applied. But now a faulty attribute is slipping through and failing on the `gl.vertexAttribPointer` command because 5125 is not a valid `type`.

**Comment by emackey** [comment]
> The glTF validator doesn't seem to catch this and I may need to open a bug report.

Are there any glTF extensions in use here?  If not please [file an issue](https://github.com/KhronosGroup/glTF-Validator/issues), thanks!

**Comment by lilleyse** [comment]
@emackey no extensions. Just opened the issue: https://github.com/KhronosGroup/glTF-Validator/issues/154

**Comment by emackey** [comment]
Awesome thanks!

**Comment by emackey** [comment]
From my perspective, this is an invalid glTF file, not a bug in Cesium.  It should be corrected in the model itself.

**Comment by hpinkos** [comment]
Agreed. @dzungpng could you pass this information along to the person that reported the issue?
