### ISSUE TITLE
Default PerInstanceColorAppearance doesn't work with BoxOutlineGeometry

### ISSUE THREAD

**Issue by conradlempert** [CesiumGS/cesium#9290]
When using a `BoxOutlineGeometry` together with a `PerInstanceColorAppearance`, I have to set `flat: true` in the Appearance constructor, otherwise Cesium will throw an error while rendering. In the documentation there is no hint towards this, so I guess people will have to figure it out by trial and error like me.

Sandcastle example: https://sandcastle.cesium.com/#c=nZNRa9swEMe/isjLbMjklLGX1A3r0lEGg5a17Mkvin1JRGXJnE52s5LvPkmOUzftoNRg+3R3v//pTnYrkLUSOkB2wTR0bAlWupr/ib6kmJRxvTSahNSAxSQ9L3ShW8/VUsva1R48QEuB5C2hv/A1mvoKNghgk89nsymLj1mAIyoe34UGKNxfZ+EKdGm0JbYyTlfW40+FZseNzAdrGr2HGvPBKvQ+7r3fwso83jhSvqlrMDUQ7l5O4PureNJXHXrYPGP/RXiJIGiscJpxGGccN7claOANylqSbMFyUVXJaE+3QySJfQu70+UWjTbOztlaKAtTlmWsk7Q1jhhtpWV3QlelsKTAegeazjKhGSAaDBpDFz/9WIX2p+3nNap4fRLuCz9j86M17QOCCOXKURQ6JDNWGmXQO4bTDstT6cuBjF9ATEnG+fz3j6u0F9yH1z6NJX2/96HPzuCDjVNpGhAYFF+2cgs4lIp6l8e85GmtBM0JHezTsWZlwOpP1Ls+rBsPJgjv0/R8Mp3klnYKFsNsvsm6MUjMoUo4zwjqxlNgs5UrH4B4aeMnF1LzbIzmlWyZrC7e+ElZqYS1PrJ2St3Jv1BMFnnm81+hyohK6s1NC6jELqRtzxa/eifnPM/88m2SjFErgSfK/wA

Browser: Chrome 87.0.4280.88

Operating System: macOS Big Sur 11.1

**Comment by hpinkos** [comment]
@conradlempert this is expected.  `BoxOutlineGeometry` doesn't compute a `normal` attribute which is required by the `PerInstanceColorAppearance` unless it's using the flat format.

Unless you have a specific reason to do otherwise, I would recommend using entities to create your geometry: https://sandcastle.cesium.com/?src=Box.html&label=Geometries

Entities provide a friendlier API that uses geometry and appearances optimally and saves you from having to manage these lower level properties.
