### ISSUE TITLE
Polyline issue with per-vertex colors and duplicate position values

### ISSUE THREAD

**Issue by vividos** [CesiumGS/cesium#9379]
There's a problem when using per-vertex coloring of polylines when the polyline point values have duplicate position values.

Sandcastle example:
https://sandcastle.cesium.com/index.html#c=fVNhb9owEP0rFp9SiTllCE3LKBqiKavESsUQXdVUk0kOsObY0dkJY1X/++ykgZIhIlnyu3vvdHd+KRiSgsMWkFwRCVsyAs3zlC7KmBe14hKPlDSMS8CodfElkpEsrA5tZKm2x8J7JXbCMsegUjC4814iSUimNDdcSR3UvBFDY29MdukKVXoNawTQQ0S285yCkKcPn3pt8tEe3yfxhsk1ELPhmmwA7U2RMt/tuastZSpVHW3X8PMx7HQauNvAvRI/X5SRLU/MJiCdS3pZ4gJs139uFKbMBM2RR0ooHGYZMGQyBroIZ/Pw56+b6ez7cN521V2J2LH0PeCirBWQFRMa2odUQJ7qHTlMp7Ph3TisG6y+I8IsvD6TfQwnk+nDGcLocXh3Jv3w7XYePlf9CZZmczVGlcskIAZziOTrwRAZ8tQ+cwENS9ThygvrN2fcSm3cnuzA78jjRrbSHFRBbTsXfq1eie13HpyyYuNdvBfbOZNa5DFI87Z/W+owSul9qm0a6H4mTVmSeHvoqK12q6/NTsCgXt9XnmYKDclReJT6BtJMMGtOf5nHv8HQWGsndNS+/17aT3hBeHJ14odza9faZla5ED/4X4hag75v+f9JhWIJl+updalgO0fbdAaTKkgp7fsWnlYapcSSYaPyPw

The sandcastle demo shows the problem nicely. Per-vertex coloring can (I think, at least) only be specified when using `PolylineGeometry` and then adding a `Primitive`. The demo adds some polygon points, all different, and all segments with a specific color. For extra visibility, the first point is placed "below" the other points:

![grafik](https://user-images.githubusercontent.com/429902/107981326-2466fd80-6fc2-11eb-8eb6-f1d8287c70db.png)

When changing the first polygon point to be the same as the second, the second point is removed by CesiumJS and the colors "shift" a segment:

![grafik](https://user-images.githubusercontent.com/429902/107981485-6e4fe380-6fc2-11eb-818e-6cb56a033d6a.png)

The reason for this "shift" is the call to `arrayRemoveDuplicates()`, here:
https://github.com/CesiumGS/cesium/blob/f05522e405137591c591f73dd660bd1ba5d625a7/Source/Core/PolylineGeometry.js#L312

This removes duplicate positions, but doesn't handle removing the per-vertex color indices. A fix would be to pass additional arrays to `arrayRemoveDuplicates()` where entries would also be removed for every position entry removed.

A workaround would be to use `arrayRemoveDuplicates()` (which currently is an undocumented API call) before generating the per-vertex color values. In my case this would work, since I derive the color values from climb or sink values of the track.

Browser: Firefox current (85.0.2)

Operating System: Windows 10

**Comment by dzungpng** [comment]
The second workaround sounds like a good solution for this, as it does not require additional arrays to handle the removal and it seems to be relatively straightforward. @vividos would you be able to open a pull request with a fix?

**Comment by vividos** [comment]
Sorry, I'm not an experienced JavaScript developer and can't help with that.

**Comment by j9liu** [comment]
I'm not sure Dzung misunderstood the workaround or if I'm misunderstanding, but the workaround won't work for this Sandcastle because the color array is hardcoded. As a result, there is a relationship between the color and positions array that isn't accounted for when the duplicate positions are removed.

I also don't think we should modify `arrayRemoveDuplicates` to do more than what the function advertises. The actual fix may require a unique version of `arrayRemoveDuplicates` to be written for `PolylineGeometry` that removes duplicate positions, *and*  the corresponding color values. Would this be a good approach, @lilleyse ?

**Comment by lilleyse** [comment]
Maybe `arrayRemoveDuplicates` could take an optional fourth argument `removedIndices` where it pushes the indices that were removed so that the polyline code knows what colors to splice.

Also now that I'm looking at `arrayRemoveDuplicates` I get this sense that it can be simplified. Can't really put my finger on it though.

**Comment by j9liu** [comment]
@lilleyse - maybe `arrayRemoveDuplicates` could be consolidated into a single `for` loop? Or should it stay broken up the way it is?

**Comment by lilleyse** [comment]
Whatever is simplest and keeps the same functionality is good with me :+1:

**Comment by vividos** [comment]
For anyone interested, see my workaround here:
https://github.com/vividos/WhereToFly/blob/0d68915c0edfd97a77e0e2019cfdb55cfa51b131/src/App/Resources/Assets/map/mapView3D.js#L2260-L2302
Since I have some more arrays like `listOfTimePoints` and `groundProfile`, I had to find a way to get the indices of removed points in a way and also apply the changes there.

**Comment by vividos** [comment]
Thanks for fixing this!
