### ISSUE TITLE
Keep third-party code license under minification?

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium#9388]
Third-party code use to always have the license in a comment at the top of the file that was not removed during minification.

For example, see [Tween.js](https://github.com/CesiumGS/cesium/blob/master/Source/ThirdParty/Tween.js)

>/**
>@license
>tween.js - https://github.com/sole/tween.js
>Copyright (c) 2010-2012 Tween.js authors.

Looks like that is no longer always the case, e.g., see the Draco dependencies in [ThirdParty/Workers](https://github.com/CesiumGS/cesium/tree/master/Source/ThirdParty/Workers).

Draco is, however, mentioned in [LICENSE.md](https://github.com/CesiumGS/cesium/blob/master/LICENSE.md#draco).

What is the latest policy?  Why?  And is Cesium consistently following it?

**Comment by kring** [comment]
I don't think minified builds include license comments at all anymore, since I broke it in #8659. But even if they did, the Draco licenses wouldn't be included because they aren't marked with `@license`, so we wouldn't be able to tell them apart from other comments that we definitely do want removed in minified builds.

I think it's reasonably common practice to consider a minified build to be a compiled form of the code, which requires that the license information be _with_ it (i.e. in LICENSE.md), but not _in_ it. If you disagree I can work on bringing back the license comments, at the cost of a bigger Cesium.js. I didn't intentionally remove them before, it just happened as a result of a tooling change, but it may not be trivial to bring them back.

**Comment by kring** [comment]
Actually, if I'm not mistaken, my change in #8659 only removed the Cesium copyright header from the top, not the third-party licensing info. If we ever had the third-party info in minified builds, I'm not sure where it went to.
