### ISSUE TITLE
Label over 3d Tile problem

### ISSUE THREAD

**Issue by SergeyMashchenko** [CesiumGS/cesium#9411]
How can i attach label to polyline over 3d model
   const entity = this.viewer.entities.add({
            name : 'entitie-'+aoi.id,
             label:   new Cesium.LabelGraphics({
               disableDepthTestDistance:  Number.POSITIVE_INFINITY,
               heightReference: Cesium.HeightReference.RELATIVE_TO_GROUND,
                text: aoi.properties.Name + '',
                pixelOffset:  new Cesium.Cartesian2(0, - offset), // -25 for example
                showBackground : true,
                backgroundColor,
                clampToGround : false,
                fillColor,
                show: true
              }),
            polygon: {
              hierarchy: parsedCoords,
              material: Cesium.Color.RED.withAlpha(0.5),
                classificationType: Cesium.ClassificationType.CESIUM_3D_TILE,
            },
          })

i switched modes for polygon and know it is showing only 3d Model
 pixelOffset:  new Cesium.Cartesian2(0, - offset - highestPoitnOfPolyline),
 But result is inconsistanse for different zooms
 default behaviour
 
![image](https://user-images.githubusercontent.com/64319356/110211508-7ef7c900-7e9f-11eb-83cd-78ad9d208993.png)

with 
![image](https://user-images.githubusercontent.com/64319356/110211776-d6e2ff80-7ea0-11eb-914d-c6e172ce73c1.png)
![image](https://user-images.githubusercontent.com/64319356/110211789-e7937580-7ea0-11eb-9509-a535e0edc52d.png)
I think i dont understand labels...

**Comment by dzungpng** [comment]
You should set HeightReference to NONE (or not set it at all so it takes NONE as the default), then input the position of the polyline that you want to annotate into the `position` option of the `label`, with a slight height offset. That way the position will not be dependent on the ground, as you currently have with `HeightReference.RELATIVE_TO_GROUND`. 

You can also use `scene.pickPosition` if you want to precisely place the label instead of having it relative to something else. Here is an example: [Sandcastle](https://sandcastle.cesium.com/?src=3D%20Tiles%20Interactivity.html&label=All).

In the future for questions about how to use the Cesium API, please post on the [Community Forum](https://community.cesium.com/). We use Github for bug report, feature request, and roadmap questions. Thank you!
