### ISSUE TITLE
Can I provide business functionality ？

### ISSUE THREAD

**Issue by Anigod** [CesiumGS/cesium#9414]
Sorry, my English is not good, and there may be a lot of grammatical errors.
I come from a company that does custom development based on Cesium. We have a lot of business functions and improvements that we hope to provide to Cesium, but we are not sure which extensions other than bug fixes might be suitable for submission.
Should I post an issue for every content to be submitted?
The business function is similar to the mouse drawing graphics, the movement of the first view, the mouse picking and highlighting, etc. Maybe these should be provided as Sandcastle?

**Comment by hpinkos** [comment]
@Anigod since CesiumJS is a development library, we generally don't add things we could consider application level logic to the API.  However, we would consider adding sandcastle examples for some of the functionality you're suggesting.  And we're always happy to review pull requests for bug fixes.
Thank you for you interest in contributing to the project :smile:
