### ISSUE TITLE
Tracking Entity - Path Jitters on iOS & new M1 Macs

### ISSUE THREAD

**Issue by malaretv** [CesiumGS/cesium#9417]
On iPhone browswers in the past I've noticed when tracking an entity in Cesium the path appears jittery. With the recent release of the M1 Macbooks I've noticed it happening on them also. 

I've attached a video showing the phenomenon

https://user-images.githubusercontent.com/381932/110397444-dd5bad80-803f-11eb-85ca-0cc42184474b.mp4

Sandcastle example:
https://sandcastle.cesium.com/?src=Interpolation.html and Select "View Aircraft"

Browser:
iOS Chrome & Safari

Operating System:
iOS

**Comment by srothst1** [comment]
@ebogo1 this issue and #9907 seem to be the most prominent bugs that users have noticed when running CesiumJS on an M1 Apple device.

**Comment by srothst1** [comment]
@malaretv what version of iOS are you noticing this issue on?

**Comment by malaretv** [comment]
Testing on Browserstack seems to be present in every ios + device combo i try. For sure on iOS 15, 14, and 13.

**Comment by srothst1** [comment]
@malaretv thank you for this update. How about on iOS 11?

**Comment by malaretv** [comment]
Confirmed on iOS 11 and 12 also

**Comment by srothst1** [comment]
@malaretv interesting, thank you for the feedback. Errors related to [tileset highlighting on M1 devices](https://github.com/CesiumGS/cesium/issues/9907) do not occur on iOS 11 or iOS 12.

**Comment by chris-cooper** [comment]
We also see jagged/jumpy polylines on M1 devices (MacBook/iPad/iPhone) as shown in this [sandcastle example](https://sandcastle.cesium.com/#c=rZ1bbxvHFYD/CqEnB5DXM+fMOTNTX1DAAfpSoAES9CXyA00xCVGKNEjKhl34v3eGMleqbe6noiGQCBaX++ncz1x2uNhu9ofZ4tPNevZy9uvVZtZe/7770V9XF6vrq4u/tJ/X28XtzXJzuLq4fPj2Zn6zvLvg9W67389+Xi4Oq+3mq6veL3f742/7hXEIVxd3736+nCAu+g2f7u9u+PR6b5I9LIN/de932/XH9Wpz/Cse3Of05n7VP77/zrt3Vyzmu8Nyv5of/7hfv72iv56Ku5iVIYZ4eeaSpK41pSGonblES4hJ6xCsXhJHfJqjQ62EKY4Yi4hJJE6MCTmZxTmr2ZGThDhClGIojaNxRAw5EaWpaB1h62TPwJn4Y0dOzsiRRBxDL9CQiONFiVNQHlXUmyeyj0bmGOrNaiFOYk5BvZmRH2hGf0sR9WbRgZMCc7QQJ2WK04mbjBxH+7SfxMmIqZjcFN3AAoaPCboBSmOK4pgpYoQwnEQNfUAyVTj0NA9oGlGKHFfEKKosVnJoZ2lQmGiUpr1GxBTmRPKALMjJEct1cHKBjNkza0WMkA9kTDbZoSmQoRayTgkYN7kiRklphbNAoVogQynIQZcukhEjiMmJOUKcjMmzcN+eC6rNsMXJVTl2nDha45+QCzLaRxLlApfMqa0QJ2LL5sFYnkSc4JipucVxatliG7+Rv3lkP0AKlze2ThbCFExtnjiFpogcpeBxlsZRnIwx6o+IUaqj8RE5J8f6f6fqOBHpI4f73KIojycspI/I1WwfD4qVFO1TSiGOYUlQnJOoEVOBxYKVlDkcPSmjPJU5jmpLStmgCpqnViNO+x9xaFaituYP9aZGJe58a3fPSag3DZOtTgpDoJLQOFmJI9MlrnNorq1xakWOKHEycnAqNA6xROBMzNuOHEO9RSX7RGV5Muot1EwcR44E1Fsw8oNYmaOotxATcETQr8kNwlAzuZtwOhCqCo2jyKGRT59fRHlKJbVpLMhJipzp9NY5qSLHK3IwvWnOyKGyEFqD58BJATmJykKgSfHOUeYk9DcvZJ/kzMmoN5gU75yK/mZBiGOV/MCEOYL+ZoYcDFMzNA9Gj1VMblbQOimTNC6Y3TyidZJS8XHOoq5oHa0UpU5LPX3SNCPHiJMjRo/XhJxIxTQn9OrMWUcyZZ2cmZOw+mDvVjiJ5oxqi+TVRVGaElBrMSHHscYVwWQQA0UPUwyVFpx8oApzUJgglNqqIaaG6RA9jp4IUxijCTHQvrdGFbtdWOs7DqGdKNxNVagHx9noSBzoprxZOBTkhAScCHMtnQPV+riSI8SB+tY5CZ3N0T600cSnAvCeo4U4VpCT0T6WUR7IbJ3D/mbTc26dk9EPIlFSIq+OMLbqlKjEUdZaNeQIZgONpDUJGKUTDnniiFGUiqBXR0OvjiUTRyNyOHpiLMhhvWW0T8CsI4n9DbpD7bOZqDfH7EZTOp2D7sZBKrESpjiFjxQWR1FtJRhxKrqBJCNOxmStAdOBGOrNMe1oZHlghrdzIrm1ChYfKag3S+TWqshRaN8bJ2HaOT9Hf8+JGTmCfuAsj2KYaia/1sIcE+REKgspsN4c9cblJ0VMo5qREwtyBMuPFozTGGmokLjMJfZrLj9JsXlLMJWsuZUfaquSYV2AmeSOoeqTHL2AJkQbpmTkFJbGI3JQaRWLXILlnobJRuJYxCBNFa3j6ATGIyyLhhyKUeOWyhStY2gec1SbsbeZUK62jDFqjuZJjm5QWR4U5/wG7RPGA5Yeq5k4iq2Bs7d5RLWdX7AbOZxCXTBKRagk0Lx456REnOioN8cW0Q3liewH6AYOO8MaJiTyamevdupEfaiZzJN5msphT0PnRDJPjjhSyBE5BbNBVuYocyiJZmMMNaI+seAwcrg1yDRv4M1TUJ7M8lAj2jjsBjxPlSvqzYyKT66Y3QrN8vrEQywnTomY3UpE+5xvz+85aB/azd04mgpyML1N7JM/cQQHprRFsHMS2kdwQFK4yhVqQnxiTnrk8EChZEw7oaI8XH5KRftw+SkcpxVWZdUeMb9XuYevKsjBLqRG9INKqyQ2of2Ro+gH1ZkTKb9V9rda0D48xqpcfyqt/tnEvvCRQ4OFvl8OMewG8HBHx8ADhY1j0IzKEODBxc6h+VebGFWOHGEODX5sSDDf0jjqyMkYpjr9bFTnwIb7ziloH4UtaI1jyJlYvz1xBNJB41Bb1TgR04EE9DeaF+3bdDF+IpQFmdrefM9BeQLGD0ZphK06mrD4yMRg7wGnImf66e8jh+WhKE2tH7I/QR4aLKQhs9o4eBzVdn6A+7+IQzUuTTzJNXLiIzhoHjNFDupNiEJLPjK1/D5SaLaycQSdGiuPKFHUKVFH6nM6Bm0j7GvGWuNUIIIh6qw2R5+ORoUUd51MPe8yckJBDGY2OkelY7DPmYjzkQPW0aEihbtDpa5AJ4ZOJ47Q6mJf8I7IiYqcxJxEnKyCHNaboN7cmYNBqpQMdEDrROyl1NA6ppSoBSNUHY2TMiqNfYA2BCkuj8hUdhw5BTnKWjPsqM+fKzNyJEficKJOVEYbJ1KBE85siWMHjgE4clgexAQc8Jyf+bvHPIITMLVV5oB1BKeNOga9OtH0oQzFqfIoOwEFacMQBKsOHdrUIDkhJqEwRmNeacMDygTqmEBxvbxxlCJUM0aOUWsog2XUW2V5MspjQpzEwx2r6NP04FW7AtXm1Hy0m+DobWLHyshRdGtF86SChccZg70UbmqJvO4ruPzfOIqZLUf0NkkUPebYTWU2jwSqb8YFgY44UcGFnpYveHidabJAJk4HHTnc5xQOn4B9jnNfUBiDSSdHTG6F1kXiUHFolTnrFEpujYNunbkoVNrO0C4JlA7oxJbOoUYnTpzRNXK4OahUfCKuW/VWCLN1regHGUc98Gicy8RjfPcY7A9xWVHwhBONE2cLjhx4SLZz4KnSzsH5/ZqRQ4c9dw64tU49YTdyBPVGj7I3jjLHUG8G21qmBkb3nIJ6g/NdO6ciRwLqDU4i6kdZCvq1KKYdhWXfxnHEOIYpHER0PGc0Iqdgttbp46v7samCHDrhRCMuK+rUGdgjJ6HeBOb4lScnZOrJjxMnFnKDidnOkVMxTGkSpHESYeiAE424SadhMoqTEha5YJR1WJqMrQ6dQtQonAsS7RANE93DyDHkGJwx3zlCwZMK5lCjrZthKIVytUXm0NpI3wVHyc1oz0Rr8uGM+c4hSmYKzbb0PbEUOx6YQ2vlU4eXjBxlTkGteabowW3pfWyEGCUn8MoYGmb35yTIPFmwYmdHeSxR8GTD5JYLBo9hI5oLcnCY3Z+aAkyh4a/goc8doxSlRcq3F7z57199vvz662Bu5oflbjVfn/02mNOXyfw43/9x5qK7Cxfb9XY3ccXdVbvf384nvlfm9Dq/1DNecbZan17hEhnnL3jz/bc+X54T/7rp56f5oWnz+L05bqbfuf1nsseH1fXhqOf0zVuL9fzm3S/bv+22t5vjFwL9Nl/vl/dXfbl3+/Hm+dXmarM4fpHR+9Xyw3I3eznbLD/MXi/3q9ub4Z/H3z1ptzz++/V2c5g3Ezfr/fD89Lnr+WH+8/Z2t1j+tNverPbLdosvH3/96Wb94/j2sN7Or5/070vqH77DDfef3g/z6+sn39ztwbWfttubX7bfv+Ti8uLq4nkX7PTfbPZif/i4Xr46Cf7X1c277e4wu92tnwzDs8Py5t26OfX+2dvbxb+Wh2Gx3//w/Msnnz386Ivr1fvZ6vrld9Qwa7re79s7v92u1z+vPi2vLl69eNau/+ajXfjV5vd/vF/u1vOP/bI/4qu/3/1yGIYXz9o/v//Jw3a7fjvfPbjz3RX/AQ).  If it has been 1.5 years since this issue was reported with no update from Apple, is it possible to escalate a Cesium workaround @ggetz ?

![jenky](https://user-images.githubusercontent.com/484870/186076319-ce98629c-ed53-40d9-b196-e046f6156dae.gif)

Should be...

![image](https://user-images.githubusercontent.com/484870/186076668-053514cb-a8b0-4814-acd2-c3921c490de9.png)

**Comment by ggetz** [comment]
[Reported again on the forum](https://community.cesium.com/t/polyline-jittering/20495/4).

**Comment by informatter** [comment]
Hi @srothst1, @malaretv
I was the one that posted on the forum, and @ggetz kindly provided with the link to this discussion. I have also confirmed that the jittering is not present when I tested the sand castle example I provided on the forum post on Windows. Since this seems to be hardware related, what would be the best workaround for this? I have also tested the measurement tools in this [example](https://www.capturingreality.com/realitycapture-supports-upload-to-cesium)  in macOS and all the measurement polylines do not have any jitter, so I am curious how it was bypassed, I am aware Ion is not open source, but if you guys could perhaps point me to some papers, or any literature used for working around this problem it would be very helpful.

Thanks

Nicholas

**Comment by ggetz** [comment]
Also reported by @moxizhou in #10844.

**Comment by ggetz** [comment]
@moxizhou (or any others who can reproduce this issue), could you try using WebGL 2 and see if the issue persists?

````js
const viewer = new Cesium.Viewer("cesiumContainer", {
  contextOptions: {
    requestWebgl2: true,
  },
});
````

**Comment by informatter** [comment]
@ggetz still persists on my end. It looks like  the M1 chip is interfering with WebGL

**Comment by ggetz** [comment]
@informatter or anyone with a M1 machine who can reproduce, could you please post your results from visiting https://webglreport.com/?

Looking into potential precision issue with M1's, it looks like there is [a similar issue in webkit's bug tracker](https://bugs.webkit.org/show_bug.cgi?id=237434). I left a comment with the steps to reproduce the issue and will update this issue with any news.

**Comment by katSchmid** [comment]
Any progress or known workarounds?

**Comment by katSchmid** [comment]
Hopefully
[Dean Jackson](https://twitter.com/@grorgwork) [@grorgwork](https://twitter.com/@grorgwork)

WebGL 2 is enabled in yesterday's iOS/macOS/etc Safari releases. Also, everything is now running on top of Metal via ANGLE. Please test + measure your content and report bugs.

**Comment by ggetz** [comment]
Another manifestation was reported in https://github.com/CesiumGS/cesium/issues/10953.

**Comment by Williangalvani** [comment]
I can still replicate it with the sandcastle example, using Safari Version 16.3 (18614.4.6.1.6) on a M1 Mac

**Comment by katSchmid** [comment]
We are getting news that the canary workaround is no longer working

**Comment by vhive-jonathan-carse** [comment]
Workaround for development machines:

1. Download Chromium for Intel: https://www.chromium.org/getting-involved/download-chromium/ ( I used https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/1204193/ )
2. For some reason the Arm installer failed for me (claiming is corrupted) on the equivalent of Chrome 119 build . I will try other builds, but following Rosetta seemed to work for me.
3. Launch a Rosetta terminal (test that running "arch" produces i386)
4. I had to disable software protection because the "Open anyway" did nothing for me: sudo spctl --master-disable
5. Launch Chromium directly: ./Chromium.app/Contents/MacOS/Chromium

@ggetz Can someone from Cesium take a look at this workaround? Is it possible to find a workaround on Chrome/Safari based on this that is easier for edge clients to implement?

**Comment by over-ripe** [comment]
Started diving into this the other day and I tracked down the line causing the jitter, at least on polylines. This workaround prevents the compiler over-optimizing, but would be great to know if there's a better way, and if it helps with other entities besides polylines:
https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Shaders/Builtin/Functions/translateRelativeToEye.glsl
```diff
 vec4 czm_translateRelativeToEye(vec3 high, vec3 low)
 {
     vec3 highDifference = high - czm_encodedCameraPositionMCHigh;
-    vec3 lowDifference = low - czm_encodedCameraPositionMCLow;
+    vec3 lowDifference = (low - czm_encodedCameraPositionMCLow) * (1.0 + czm_epsilon7);
 
     return vec4(highDifference + lowDifference, 1.0);
 }
```

**Comment by ggetz** [comment]
Also reported in https://github.com/CesiumGS/cesium/issues/11671

**Comment by ggetz** [comment]
Also reported in https://github.com/CesiumGS/cesium/issues/11759

**Comment by ggetz** [comment]
Also reported with labels in https://github.com/CesiumGS/cesium/issues/11801.

**Comment by csciguy8** [comment]
Could not reproduce the issue on my M1 Macbook. The line looks steady, and is not jittering at all.

Macbook Pro
13-inch, M1, 2020
16GB Memory
macOS Sonoma 14.2.1

Tested on:
Safari (17.2.1)
Chrome (121.0.6167.139)
Firefox (122.0)

**Comment by malaretv** [comment]
Confirmed that I no longer see the issue in my original link when viewing from my M1 Macbook and iPhone 13

Macbook Pro
14-inch M1, 2021
MacOs Sonoma 14.2.1
Safari 17.2.1


iPhone 13
Safari 17.1

**Comment by malaretv** [comment]
Since upgrading to the latest cesium for my projects, this seems solved on all devices I saw this issue previously.

Closing this issue, though as it is an umbrella issue feel free to reopen it as needed
