### ISSUE TITLE
Path is used in cesium, but FPS is very low when there are many satellite tracks. How to improve performance? According to 24 hours, one data point per minute, will this affect

### ISSUE THREAD

**Issue by D-Plus-Plus** [CesiumGS/cesium#9475]
Path is used in cesium, but FPS is very low when there are many satellite tracks. How to improve performance? According to 24 hours, one data point per minute, will this affect。The CPU and GPU of my computer are occupied normally，so why？

![image](https://user-images.githubusercontent.com/21274723/113962821-06e44080-985b-11eb-8894-5f495bcd348f.png)

**Comment by ebogo1** [comment]
Thanks @D-Plus-Plus! Looking through the community forum this appears to be a known issue: 
- https://community.cesium.com/t/performance-issues-with-entity-path/11948
- https://community.cesium.com/t/low-frame-rate-with-dynamic-sampledpositionproperty/10379/6

Since this isn't necessarily a bug or a feature request, please continue the discussion on the forum.
