### ISSUE TITLE
When perPositionHeight and ImageMaterialProperty are used together to create a polygon texture, the texture is displayed abnormally

### ISSUE THREAD

**Issue by 322ne** [CesiumGS/cesium#9502]
When perPositionHeight and ImageMaterialProperty are used together to create a polygon texture, the texture is displayed abnormally, and it is strangely stretched and rotated. But if perPositionHeight is not used, the texture rendering is the result I want when it is attached to the ground and when it is not attached.

let polygonGraphic = self.viewer.entities.add({
      name: '2',
      polygon: {
        hierarchy: polygonCoords,
        perPositionHeight: true,
        material: new Cesium.ImageMaterialProperty({
          image: renderCanvas,
          repeat: Cesium.Cartesian2(1.0, 1.0), 
          transparent: true,
          color: Cesium.Color.WHITE.withAlpha(1),
        })
      }
    })

**Comment by ebogo1** [comment]
Thanks for posting! Since it's unclear whether this is a bug in Cesium, please open a thread in our [community forum](https://community.cesium.com/). More people keep up with new threads on our forum so you're more likely to get on there. If you include a full Sandcastle as well as your texture it might be easier to figure out the issue.
