### ISSUE TITLE
TileBoundingRegion.distanceToCamera is inaccurate when camera is on opposite side of the globe

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium#9534]
`TileBoundingRegion.distanceToCamera` is inaccurate when the camera is on the opposite side of the globe.

In this [sandcastle](https://sandcastle.cesium.com/#c=xVZtb9s2EP4rhD/JmEOLepfjBrOSbg2wtUNqDBiqfKAl2iZKkQZFOcmG/PedKNtxIyddiw37Ypu85+6ee8g7eks12nJ2xzR6gyS7Q5es5k2Ff7d7Tj4o7PpSSUO5ZDofjNBfuURI6ZLpa1myDYMPaeaaylo0BZPFwwQtqajZqMWNxyuhFmy3lcvH4Xkut5C1BiiDpF12bJc7k/UAk93DdgWWXPIlcnb8SrYEOqVjjcNhx8kucL1Wdz9r1chyZipVb9ZMt8Fs/vMnmDkijJmkC8FKgBndvIhaapDhJ1qwmdisKYBd7L6EXdDicx/62JZxXDEuaMU0xTUzreSOraNkteGSGq4kmhyfyiXVBn5R6TtnURQmaYDTgJDEjVNvhM5IGHpp5EbYTV0Sh25CYNNzIxIEBCdJ4PlpSJLhqDs/Dqd2Isc7RksuV79xU6xvlBBOhL3EJ0nouzGJ0zCJ2kw4jOI0hYApWAIvHCG3iwu3wV6FpdIVBN4F/ZUaze8DfH319v38ev7H7h50x63ZCljMQKRPbQQP+2FE/DBOCOSIfGLjgn4kjNw0TYIkiN0oJEFkDT4mnueGwAdECOPADXd48Ac5koS4qU/iILHbZ100ksvbZ/mzfX6oLfGCOPU9F77TOPBfJwB8gwSE8EgMCrnJAf8NBApD5UqwVoOdYjf7PdzIDdwlZ6fSvn0OPtlXfbInqQ0Hh7Y14IRvDrIfnf68B+iu5CHd5IitraTikldN9Y7x1dpM9of5KbjtrPT+lDW8/eIG9Gll308re5lW9iqt7AtaXZNCj3DDWY1pWfZS2jVChYJh2PYrq3vqILQ+LQx0yj3MmpKVfW3QWR9dQXjNqTi01KUSSuObt1f4jpu1HTOOi8OuCx9H/14h2clCsq8Vkh0Xkv2XhWxUzds5Njkek2ql6WbNC2zUYWo6vT6BEQxsnKdDG3ZpBV0wcdDFQIUTlA9m8Pr9D6SyV0llfVJdU5W8Bv/CDpUTfY/39jlwad8gp3uQlhpWH+FlYPtRswdmJwNl/yxQLgslawXlCbWC/xVXOydkFJq1daAfnhi3Di/Ds2dwmG+D0WBamwfBLjpxEPqRVxulDWq0cDAeG1ZtRHuxx4um+MwMLup6eN6Bp+Nj12nJt4iXb0789UGFoHUNlmUjxEf+J8sHF9Mx4HuuQtlH9MOWaUEfWtiaXPzSbWKMp2NYnvY0SokF1c8i/w0) rectangle A and B are on the opposite side of the globe. Rectangle A is clearly closer to the camera but the distance results say otherwise:

```
Distance to A: 18218478.748910885
Distance to B: 14805027.338562964
```

![image](https://user-images.githubusercontent.com/915398/117719155-0bc64800-b1ab-11eb-91c9-fb16ad33dfc2.png)

After stepping through [`TileBoundingRegion.distanceToCamera`](https://github.com/CesiumGS/cesium/blob/c47bc942c1f0c3fc0ddfa71d7ba1d5fc2cc9fb48/Source/Scene/TileBoundingRegion.js#L295-L402), the problem is that the distance from each plane (west, south, east, north) is computed using the dot product of the plane normal and a vector from one of the corners to the camera. In this specific view the distance from the east plane is much greater for rectangle A than rectangle B because the plane normal and the camera vector are more closely aligned, a situation that can only happen when the camera is on the opposite side of the globe.

This bug impacts screen space error calculations for 3D Tiles. It doesn't impact terrain because terrain uses [Horizon Culling](https://cesium.com/blog/2013/04/25/horizon-culling/), which is being added to 3D Tiles Next as well (see the tile metadata semantic [`TILE_HORIZON_OCCLUSION_POINT`](https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/specification/Metadata/Semantics#tile_horizon_occlusion_point))

I don't have any great suggestions for fixing this right now. One idea is to use an OBB distance check based on certain heuristics. But most likely the math can just be fixed.

**Comment by pjcozzi** [comment]
@lilleyse in practice, how significant of an issue is this right now for 3D Tiles refinement, e.g., as the user zooms in, are many tiles on the other side of the globe refined when they shouldn't be?  Or is this more of a minor problem just when the user is zoomed out at global scale?

If the former, perhaps @ebogo1 could take a look at the math?

**Comment by lilleyse** [comment]
> @lilleyse in practice, how significant of an issue is this right now for 3D Tiles refinement, e.g., as the user zooms in, are many tiles on the other side of the globe refined when they shouldn't be?

It's pretty significant. I created an implicit tileset - a double-headed quadtree with 8 levels - and recorded the number of tiles visited when the camera's near the surface. With the current math it visits `1437` tiles. When using an OBB approximation it visits only `253` tiles.

Given the numbers here we should definitely look at this soon.

Region|OBB approximation
--|--
![region](https://user-images.githubusercontent.com/915398/117734962-91092700-b1c2-11eb-81d4-c8b783c7a5f2.png)|![obb](https://user-images.githubusercontent.com/915398/117734965-923a5400-b1c2-11eb-9d1b-a37d30a26c0f.png)


#

@ebogo1 here's some resources for testing this

The OBB approximation looks like

```js
TileBoundingRegion.prototype.distanceToCamera = function (frameState) {
  return Math.sqrt(
    this._orientedBoundingBox.distanceSquaredTo(frameState.camera.positionWC)
  );
}
```
The tileset and a Node script for generating the tileset are here: [global-implicit.zip](https://github.com/CesiumGS/cesium/files/6455443/global-implicit.zip)

And finally a [local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=lVPBTtwwEP0VK6cgbe0UDq2WsKoKPSCV9rAUFRSp8jpDMsWxI9vJLkX999pxlizscqgPiT0z782b8bjnhvQIazDkjChYk3Ow2DX0ZrClRSKG87lWjqMCUyQz8lQoQiqpVzAn91xaKNTfo9NCFar3bA4lWHAv6eLv5OI6OtOBojNyToqkdq6dMya14LLW1s0/Ztkxs447FOwC7IPTLQvpuHyHTStRoGNjFvrbalUkk4BBNoWNA1WmY/JofCHhUtkWhNPmCjeoAjZIx601VH+lS5C+ipFSHIQP3EOkp9iH06kZ425QuRVfwqqrlrVef9adKlFVN1p2DYRo08HpFNjwDTZdsxQGQC1bLuCLMTpc2THNdgu3AhTQ1mCDDnuwlJdlOrLEDsVKBW/A8Km6iIvW55vUBitUry6SG+d3XJ2kH7JhzUhG42fbxhKNbwPqAN2DUQUVd5DuO358u7z+9XP2RrajwB4F0lZbHPmjxsm1m/t5P7m79qAmIbV6U9LdTmafrXb/T3EbKJJZklv3KGERhj+sT36ctXHhIaSUMgd+un1vLFt14sFfu7A2AENoznaheYk9wfLswPMkQnJrvee+k3KJf6BIFjnz8XtQqXmYue89GMkfQ1j9fvE1GimlOfPHw0intVxx84r5Hw).

**Comment by lilleyse** [comment]
![tiles](https://user-images.githubusercontent.com/915398/117735994-a3846000-b1c4-11eb-85ce-42ed6cdf1fc1.gif)

**Comment by pjcozzi** [comment]
@lilleyse is it correct that a worse case improvement is to runtime convert region to the (conservative) approximate OBB and then use the OBB for culling?  If so, maybe we should put that in a branch now for folks to move forward with while we work on the complete fix?

@ebogo1 I would suggest getting to go a good stopping point with KTX2 and then taking a look at this.

**Comment by donhatch** [comment]
Yes, this bug is a showstopper when trying to zoom in to a fully
populated (real or virtual) earth 3dtiles database that uses "region" boundingVolumes--
the viewer becomes useless (stuck showing too-coarse levels pretty much
forever) when zoomed in, since it's spending all its time refining the
far side of the planet.

Here is a monkeypatch that fixes it, for me.
(I think this does essentially what pjcozzi suggested in the previous comment.)
Run this any time after Cesium.js is loaded.

var FixCesiumFarSideBug = function() {
  // Unfortunately, TileBoundingRegion.prototype.distanceToCamera()
  // is nonsense.  But the region usually has a real bounding box
  // attached, whose distanceSquaredTo() has not been shown to be
  // nonsense, so use that instead if possible.
  // Incidentally, it also usually has a bounding sphere attached too, but
  // don't use that: BoundingSphere.distanceSquaredTo() is also nonsense
  // (distance squared to a sphere is not distance squared to its center
  // minus its radius squared).
  if (Cesium.TileBoundingRegion.prototype._nonsenseDistanceToCamera !== undefined) {
    return;  // already fixed, presumably
  }
  Cesium.TileBoundingRegion.prototype._nonsenseDistanceToCamera = Cesium.TileBoundingRegion.prototype.distanceToCamera;
  Cesium.TileBoundingRegion.prototype.distanceToCamera = function (frameState) {
    if (frameState.mode === Cesium.SceneMode.SCENE3D &&
        this.boundingVolume !== undefined) {
      return Math.sqrt(this.boundingVolume.distanceSquaredTo(frameState.camera.positionWC));
    }
    return this._nonsenseDistanceToCamera(frameState);
  };
};
console.log("  fixing cesium bounding region distance");
FixCesiumFarSideBug();
console.log("  fixed cesium bounding region distance");

**Comment by lilleyse** [comment]
Here's the branch with the patch (same idea as @donhatch): https://github.com/CesiumGS/cesium/compare/region-obb-distance

**Comment by donhatch** [comment]
Oh wait-- I don't think you need to kill the whole function-- it's only the SCENE3D case that was nonsense.
The SCENE2D logic looks fine, and works AFAIK.

**Comment by lilleyse** [comment]
Updated: https://github.com/CesiumGS/cesium/compare/region-obb-distance

**Comment by donhatch** [comment]
BTW, as I mentioned above in [my monkeypatch](https://github.com/CesiumGS/cesium/issues/9534#issuecomment-837636122),
TileBoundingSphere distance doesn't look right either.
So the only reliable boundingVolume type is "box", currently, if I'm not mistaken.
I was about to file an issue report on that, but the guidelines said post in the forum instead, [so I did](https://community.cesium.com/t/distance-to-bounding-sphere-function-looks-wrong/13567).

**Comment by kring** [comment]
As @donhatch observed, it's not just that the distance metric is inaccurate for tiles on the other side of the globe, it's actually complete nonsense. We measure the distance to tile edge planes, and those cut straight through the center of Earth and who knows what we get on the other side. And we use the cartographic height of the camera versus the top of the tile to measure the vertical distance, and that's nonsense too when the camera is on the other side of the world.

The terrain engine in CesiumJS doesn't have this problem because of horizon culling. Cesium for Unreal, however, doesn't use horizon culling and still doesn't have this problem (though it used to). The solution used in Cesium for Unreal is super simple: we compute the distance to the OBB, too (every bounding region already has an OBB), and then use the _max_ distance to either the OBB or the bounding region.
https://github.com/CesiumGS/cesium-native/blob/db684a63d080d266d7b3a6363857502d07025ff9/CesiumGeospatial/src/BoundingRegion.cpp#L211

So for nearby tiles we're using the more accurate distance-to-region measurement. For tiles on the other side of the globe we use the more conservative OBB distance.

I haven't "proven" that the region distance, when it goes wild, will always be smaller than the OBB distance, but I'm reasonably confident it's true.

**Comment by kring** [comment]
That's a good question, and I don't know the answer. Generally, small (high detail) quadtree tiles in a geographic projection are going to be tightly bounded by an OBB (assuming it's computed well), but larger (low detail) ones will be pretty poor because of Earth curvature and because tiles with a fixed width in longitude degrees are narrower at their side closest to the poles. So I suspect the biggest benefit from using distance-to-region will be at sort of medium zoom levels.

I just did some really quick and dirty inspection of this, and yeah, the above looks to be correct. The distance-to-region check is only being used in tiles at levels 1-4. It makes a pretty big difference in those tiles, though, estimating the distance to be 30%-ish greater in some cases. We should probably do some deeper analysis before removing the distance-to-region computation entirely, though, or even before restricting it to coarse tiles.
