### ISSUE TITLE
Npm install forked repo, no Build folder

### ISSUE THREAD

**Issue by Kennnyoung** [CesiumGS/cesium#9550]
When I fork cesium to my own repo and use it as my npm dependency, after npm install there is no Build folder in corresponding node modules. However if I npm install the official cesium package there will be a Build folder after installation, I am just wondering how do I create such Build folder with my own forked repo?

**Comment by ebogo1** [comment]
Hi @Kennnyoung, 

Hope you were able to resolve this one. Since this isn't a bug or feature request, the discussion would be better suited for our [community forum](https://community.cesium.com/c/cesiumjs/5).

Also, please see our [Build Guide](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/BuildGuide) if you haven't already. 

Thanks!
