### ISSUE TITLE
Missing positionToEyeEC and tangentToEyeMatrix for GLobe Material Input

### ISSUE THREAD

**Issue by xtassin** [CesiumGS/cesium#9557]
When adding a custom material using Fabric with source, positionToEyeEC and tangentToEyeMatrix material input properties appear not to be set.

Sandcastle example:
https://sandcastle.cesium.com/#c=dVLBbtswDP0VwrskQCJ3MLaD4wYFgh4KdN2AFe3FF0ViXKGy5FFS2mzIv492Ysxou5v0+Ei996i9JNgbfEGCS3D4AhsMJrXiYcBmdaaG+8a7KI1DqrMF/KkdQEQiRn6Q3xuNVI6NilBGfPRk9f2JMhv4AIS/Eob4gBTx9c5TK20oIVLCBeT5HaJGDdGznJCkNb8RgvUd9s3H+aJ2x/mqdietIih0KBrrtyjQya3FW9M8ReMattGPZGrf+AG9ZXlkpGXi1PC3Mzyq3cktGVXC+cqGDx2WUGeRPXAKI6x823mHLoYJF0Cb3S4FLP8hwL1ucM3WZqOKG9elKDofTDTe3fvrA15v5pP5x/PpeMphlS2yKsSDxfXIuDKsgCIksjMh8ohtZ3l6yLdJPWMUKoQ+uRNZaGz9Uo3rnEreSvXckE9Oc916Xumn4qIoiq+rCccTL3tJUpvEhr90r5NiJ7XmDbyFW0mNcQMKxaRy/J8m02cyVbbnL2OUtEvOruFJrdHa4rsnltF3JVy8faDKp3lV2uzB6MsPfjYoK0Pgyi5Z+5O3VGfrKmf+u1brZe/0Owuz8tDTnj6vb0+gEKLK+Trt/As

I would suggest the following modification to globeFS.glsl but I am not entirely confident so advice/suppervision would be welcome.

```
#ifdef APPLY_MATERIAL
    czm_materialInput materialInput;
    materialInput.st = v_textureCoordinates.st;
    materialInput.normalEC = normalize(v_normalEC);

     // adding the folowing two lines
    materialInput.positionToEyeEC = -v_positionEC;
    materialInput.tangentToEyeMatrix = czm_eastNorthUpToEyeCoordinates(v_positionMC, v_normalEC);

    materialInput.slope = v_slope;
    materialInput.height = v_height;
    materialInput.aspect = v_aspect;
    czm_material material = czm_getMaterial(materialInput);
    vec4 materialColor = vec4(material.diffuse, material.alpha);
    color = alphaBlend(materialColor, color);
#endif
```

**Comment by lilleyse** [comment]
@IanLilleyT does this look like the right fix?

**Comment by ebogo1** [comment]
The change looks like this in Sandcastle - 
![image](https://user-images.githubusercontent.com/31491650/119210953-5c785380-ba7d-11eb-82ac-8724a4ab5c2f.png)

**Comment by IanLilleyT** [comment]
@xtassin I tried out your change by applying the Water material (which uses `Water.glsl` under the hood, where both `positionToEyeEC` and `tangentToEyeMatrix` are used) to the globe, and after many hacks got some cool screenshots. My only suggestion is to do `czm_eastNorthUpToEyeCoordinates(v_positionMC, normalize(v_normalEC))` so that the normal is normalized after vertex interpolation. Feel free to open a PR and it should be an easy review.

![Screenshot from 2021-05-24 17-45-04](https://user-images.githubusercontent.com/1328450/119412278-a2b9f680-bcb9-11eb-81f9-77cc8c9bbe07.png)

Himalayas:

![Screenshot from 2021-05-24 17-54-22](https://user-images.githubusercontent.com/1328450/119412267-9f266f80-bcb9-11eb-894a-7d4ca4466064.png)
