### ISSUE TITLE
it is not effected when set gl_FragColor.alpha user PostProcessStage

### ISSUE THREAD

**Issue by hxboxy-xh** [CesiumGS/cesium#9587]
https://sandcastle.cesium.com/?src=Custom%20Per-Feature%20Post%20Process.html&label=Post%20Processing

i just change code from
  "        vec3 highlighted = highlight.a * highlight.rgb + (1.0 - highlight.a) * color.rgb;\n" +
  "        gl_FragColor = vec4(highlighted, 1.0);\n" +
to 
  "        gl_FragColor = vec4(highlight.rgb, 0.1);\n" +

but when mouse hover the ‘Man’， it  not transparent

**Comment by ebogo1** [comment]
@hxboxy-xh Due to how CesiumJS handles post process stages, it's not possible to use the post process shader to set the alpha of the final color (notice how `highlight.a` is being used to compute a color with alpha = 1.0). If you are trying to make a model translucent on mouseover, you could use [Scene.pick](https://cesium.com/docs/cesiumjs-ref-doc/Scene.html#pick) to set a model's color with a new alpha (see the [Model coloring Sandcastle](https://sandcastle.cesium.com/?src=3D%20Models%20Coloring.html).

For the future, for questions like this please use our [community forum](https://community.cesium.com/c/cesiumjs/5). More users are active there and you'll be likelier to receive help quickly. We like to reserve GitHub issues for bug tracking and feature requests.
