### ISSUE TITLE
`OrientedBoundingBox.distanceSquaredTo` fails when halfAxes have magnitude near 0

### ISSUE THREAD

**Issue by ebogo1** [CesiumGS/cesium#9658]
This was exposed in the [Particle System Sandcastle](https://sandcastle.cesium.com/?src=Particle%20System%20Fireworks.html) on Windows in Edge and Chrome after implementing the changes reverted in #9657. We considered adding epsilon checks to the OBB during creation, but this is inconsistent with the current behavior of defaulting the halfAxes matrix to the zero matrix.

The bug itself happens in `distanceSquaredTo` when we try to normalize a near-zero magnitude `w` axis. Maybe the math can be reworked in this function to handle this edge case.

**Comment by lilleyse** [comment]
@j9liu some background on getting started with this...

Oriented bounding boxes were added a while back to improve frustum culling for terrain tiles, as written about in this blog: https://cesium.com/blog/2015/06/24/oriented-bounding-boxes/. They are also used in 3D Tiles when a tileset has the `box` bounding volume type. The distance check is used to determine screen space error for tile, which determines when it refines to its children.

The crux of the problem is that `OrientedBoundingBox.distanceSquaredTo` crashes when an oriented bounding box has an axis of zero length, but this type of OBB is completely valid and it should work.

One mental model for this is:

* No degenerate axes: treat as distance to box
* 1 degenerate axis: treat as distance to rectangle
* 2 degeneate axes: treat as distance to line segment
* 3 degenerate axes treat as distance to point

I'm not sure if this requires if/else's or if it can cleanly fit into a single algorithm.

You should be able to work on this with unit tests alone rather than looking at the fireworks sandcastle.
