### ISSUE TITLE
Why Cesium3DTileFeature.getExactClassName() is private ?

### ISSUE THREAD

**Issue by puxiao** [CesiumGS/cesium#9831]
In this demo: [3D Tiles Batch Table Hierarchy](https://sandcastle.cesium.com/?src=3D%20Tiles%20Batch%20Table%20Hierarchy.html&label=All)

![](https://puxiao.com/temp/getExactClassName.jpg)

`getExactClassName()` is defined as private.

![](https://puxiao.com/temp/getExactClassName2.jpg)

If you use typescript...

![](https://puxiao.com/temp/getExactClassName3.jpg)

<br>

???
<br>
Please tell me why.
Is it possible to delete private tags in JSDoc.

```diff
     /**
      * Returns the feature's class name.
      * <p>
      * This function returns <code>undefined</code> if no batch table hierarchy is present.
      * </p>
      *
      * @returns {String} The feature's class name.
      *
-     * @private
     */
     Cesium3DTileFeature.prototype.getExactClassName = function () {
       return this._content.batchTable.getExactClassName(this._batchId);
     };
```

<br>

`isClass()`, `isExactClass()`, `getPropertyInherited()`, `getPropertyInherited()`, `content`, `pickId` 

They also have the same situation.

**Comment by ggetz** [comment]
These classes are marked as private since they are designed to only be used internally. It should most likely be removed from the Sandcastle demo. 

Is there a reason you're looking for these to public?

> Is it possible to delete private tags in JSDoc.

Not as far as I know. JSDoc comments are used for internal documentation as well as public API documentation, and we need a way to distinguish between these cases.

**Comment by puxiao** [comment]
Thank you for your answer.
