### ISSUE TITLE
Cesium rendering issue at level 6 and 7

### ISSUE THREAD

**Issue by kkuk628** [CesiumGS/cesium#9910]
I noticed cesium latest version has an error.
When I zoom to level 6 and 7 at north US.
It is rendering prior level images for all imagery layers like follow image.
![image](https://aws1.discourse-cdn.com/business4/uploads/cesium/original/2X/b/b06f4efa6736f03ea6653bd43b724e5bbb170473.jpeg)
As you can see inspector says all area are level 6 but above labels are different to below labels in size.
I found this in hello world sample of cesium sandcastle.
I checked this in several recent versions.
Here are my code.
[Cesium Rendering Error](https://sandcastle.cesium.com/#c=bVLvT9swEP1XrHwqUnGaMSiDUq0KjKVr0hXSiqBIU+ocxI1jF9vpj0z873OSboNpn07v7r27d2fbNrqVCdfIBUXLYnyPEkJAKaQF2otSIio4SpQCrWLecrAnOE7hKSmZHjXkUOTA0RWKLdiPs+UtoVM69uaV5wTUUx6/OyWud+bl64eFO/6EDeklvc1rEotWueOvsiygDguKqJqEs5OoIjpazR3/vrd9DFkRfVjkfvG4CqoZnbjj9aNpFlzPTqfhXHkFy1KD/TDaBdeR41ejnf/Qw9FeuTeLl2gmz8qv/XlvXHpfPl67ExFQeU6OjxfZrv9t/iPd3PRi6zLmMd8kEm0obEGaTThsDxfBiybXiS3SYFdwnVAOMra66GfMEdIgpcl8l2JDU5AXb8VtCN8zOo0MoVKyC/T3pnegzMEJ4CcpilF9ci/tnJ73nfOTo26teK3D69Fl61UR4GCstp5xA02pifiZiSWYR1rrLASlR89mvNIHH0akZQnN1rY9StODCeRxtQaihTQT2q6w08DTzsFkm2zBH65Pd5TXpqyuNVB6z2BYm/1Mi7WQul6yg7GtoVizRIOylyXJQWOiVC0a2L8lg5RuEE2v/nNoRJj5gqbyVDJ2TyuIreHANvx3MiaSlPLn6QYkS/aGUtsYZM5w0hYwxgPbwHrov1otBFsm8k3fXw)

```
// Grant CesiumJS access to your ion assets
Cesium.Ion.defaultAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYjk1MjhhNi1lNmYzLTQ3YzctYjU1MS0wZTlmY2VkMmZjNzQiLCJpZCI6NDQ5OTUsImlhdCI6MTYxNDY1MzAxMX0.YysCEVqYQr6uH7U0JuIF4DCLoNir8c--Vhx7KU_dvE0";

var viewer = new Cesium.Viewer("cesiumContainer", {
  terrainProvider: new Cesium.CesiumTerrainProvider({
    url: Cesium.IonResource.fromAssetId(587183),
  }),
});
var scene = viewer.scene;
scene.globe.depthTestAgainstTerrain = true;

//Add Cesium Inspector
viewer.extend(Cesium.viewerCesiumInspectorMixin);
```

**Comment by lilleyse** [comment]
Hm... this happens for Bing Maps, ESRI, and Open Street Map... but not for Sentinel 2, which if I remember correctly is geographic instead of Web Mercator like the others. @kring is this expected?

**Comment by kring** [comment]
Yes, it's intentional. CesiumJS automatically adjusts web mercator imagery level by latitude. The code that does it is here:
https://github.com/CesiumGS/cesium/blob/3831cb9ff1c5f63a2e656223e798eb0a4d52575e/Source/Scene/ImageryLayer.js#L1526

The reason is that Web Mercator tiles mapped to the globe become smaller as latitude increases, so the latitude factor attempts to account for that by reducing the resolution as we move toward the poles. But we can only select imagery resolution in the discrete steps supported by the imagery provider, so there is necessarily going to be a discontinuity at some point.

I don't have a huge amount of confidence in the specific adjustment we're using here (`cos(latitude)`), though. In cesium-native we have a new system (https://github.com/CesiumGS/cesium-native/pull/327, not merged yet as of this writing) that does this in a much more principled way. It estimates the on-screen size of a terrain (or other geometry) tile at the switch distance, measured along axes aligned with the imagery projection. And then uses that plus the geospatial rectangle coverd by the geometry tile to more accurately select an imagery level. I think we should implement this in CesiumJS too.

Even that won't avoid a discontinuity where the imagery switches level, though.

By the way, the reason the "tile coordinates" don't show the different levels is because they're showing the terrain tile coordinates, not the imagery tile coordinates. Terrain uses a geographic projection which is not adjusted by latitude because geographic tiles only get smaller along one axis as we move toward the poles, so we can't reduce the resolution without creating noticeable blurriness.

**Comment by kkuk628** [comment]
Thank you for your explanations, @kring 
Is there any way to show imagery tile coordinates using inspector or something else?

**Comment by kring** [comment]
You can add a Web Mercator tile coordinates layer with this code:

```
scene.globe.imageryLayers.addImageryProvider(new Cesium.TileCoordinatesImageryProvider({
  tilingScheme: new Cesium.WebMercatorTilingScheme()
}));
``

**Comment by kkuk628** [comment]
Thank you @kring

**Comment by kkuk628** [comment]
Hello guys,
So there isn't a solution for this issue?

**Comment by kring** [comment]
No, sorry. It's inherent to rendering 2D images on a round planet.
